# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: tags/RELEASE_10_3_0/net-p2p/p5-Net-BitTorrent-PeerPacket/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Net-BitTorrent-PeerPacket
PORTVERSION=	1.2
PORTREVISION=	1
CATEGORIES=	net-p2p perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Parse/Build Peer Packets from BitTorrent

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
