# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/archivers/rubygem-rubyzip/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	rubyzip
PORTVERSION=	1.1.7
CATEGORIES=	archivers rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby module for reading and writing zip files

LICENSE=	BSD2CLAUSE RUBY
LICENSE_COMB=	dual

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
