# Created by: Donald Burr <dburr@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/no-login/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	nologin
PORTVERSION=	1.0
PORTREVISION=	1
CATEGORIES=	sysutils
MASTER_SITES=	LOCAL/wes

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Refuse a login to a user, and make a note of it in syslog

PLIST_FILES=	bin/nologin man/man8/${PORTNAME}.8.gz

.include <bsd.port.mk>
