# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: tags/RELEASE_10_3_0/security/p5-Crypt-RC4/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Crypt-RC4
PORTVERSION=	2.02
PORTREVISION=	1
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Perl implementation of the RC4 encryption algorithm

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
