# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/science/py-pydicom/Makefile 388642 2015-06-05 21:10:18Z amdmi3 $

PORTNAME=	pydicom
PORTVERSION=	0.9.8
PORTREVISION=	1
CATEGORIES=	science python
MASTER_SITES=	GOOGLE_CODE
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Read, modify, and write DICOM files with Python code

LICENSE=	MIT

USES=		python shebangfix
SHEBANG_FILES=	dicom/test/shell_all
USE_PYTHON=	distutils autoplist
NO_ARCH=	yes

.include <bsd.port.mk>
