# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Log-Simple/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Log-Simple
PORTVERSION=	1.8
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Basic runtime logger

LICENSE=	GPLv2

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
