# Created by: shanee@augusta.de
# $FreeBSD: tags/RELEASE_10_3_0/misc/unclutter/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	unclutter
PORTVERSION=	8
PORTREVISION=	3
CATEGORIES=	misc
MASTER_SITES=	XCONTRIB/utilities

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Remove idle cursor image from screen

WRKSRC=		${WRKDIR}/unclutter
USES=		imake tar:Z
USE_XORG=	x11 xext

PLIST_FILES=	bin/unclutter \
		man/man1/unclutter.1.gz

.include <bsd.port.mk>
