# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/misc/R-cran-mime/Makefile 396158 2015-09-05 07:48:12Z tota $

PORTNAME=	mime
PORTVERSION=	0.4
CATEGORIES=	misc
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Map Filenames to MIME Types

LICENSE=	GPLv2

USES=	cran:auto-plist

.include <bsd.port.mk>
