# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/pear-Services_Yahoo/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Services_Yahoo
PORTVERSION=	0.2.0
CATEGORIES=	www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Provides access to the Yahoo! Web Services

USES=	pear

.include <bsd.port.mk>
