# Created by: Daichi GOTO <daichi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/japanese/mozc-tool/Makefile 358651 2014-06-20 22:53:29Z sanpei $

PKGNAMESUFFIX=	-tool

COMMENT=	Mozc tool for IBus, SCIM, and others
DATADIR=	${PREFIX}/share/${PORTNAME}${PKGNAMESUFFIX}

MASTERDIR=	${.CURDIR}/../../japanese/mozc-server
BUILD_MOZC_LIST=	mozc_tool

.include "${MASTERDIR}/Makefile"
