# Created by: Igor Vinokurov <igor@zynaps.ru>
# $FreeBSD: tags/RELEASE_10_3_0/net/p5-Net-ext/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Net-ext
PORTVERSION=	1.011
PORTREVISION=	2
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl modules for using sockets

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
