# Created by: Michael Frey <frey@raum3.de>
# $FreeBSD: tags/RELEASE_10_3_0/net/pear-Net_IDNA/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Net_IDNA
PORTVERSION=	0.8.1
CATEGORIES=	net pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Pear Punycode encoding and decoding package

USES=	pear

.include <bsd.port.mk>
