# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/x11/libXau/Makefile 384234 2015-04-18 15:34:36Z kwm $

PORTNAME=	libXau
PORTVERSION=	1.0.8
PORTREVISION=	3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Authentication Protocol library for X11

XORG_CAT=	lib
USE_XORG=	xproto:both

.include <bsd.port.mk>
