# $FreeBSD: tags/RELEASE_10_3_0/misc/rubygem-mimemagic/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	mimemagic
PORTVERSION=	0.3.0
CATEGORIES=	misc rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@michael-fausten.de
COMMENT=	MIME detection by extension or content in pure ruby
COMMENT=	Detects the mime type of a file by extension or by content

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
