# Created by: will
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Ioctl/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	Ioctl
PORTVERSION=	0.81
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN/Ioctl/JPRIT
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module that provides a way to get the value of C ioctl constants

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
