# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Sys-RunAlone/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	Sys-RunAlone
PORTVERSION=	0.12
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Make sure only one invocation of a script is active at a time

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
