# Created by: Lars Thegler <lth@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-PerlIO-via-MD5/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	PerlIO-via-MD5
PORTVERSION=	0.07
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	PerlIO layer for creating an MD5 digest of a file

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
