# Created by: Qian Jin <eric.siroh@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/finance/py-vatnumber/Makefile 397120 2015-09-17 15:49:47Z wen $

PORTNAME=	vatnumber
PORTVERSION=	1.2
PORTREVISION=	1
CATEGORIES=	finance python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	chian.jin@gmail.com
COMMENT=	Python module to validate VAT numbers

LICENSE=	GPLv3

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}stdnum>=1.1:${PORTSDIR}/devel/py-stdnum

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
