# $FreeBSD: tags/RELEASE_10_3_0/devel/py-ZopeUndo/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	ZopeUndo
PORTVERSION=	2.12.0
PORTREVISION=	1
CATEGORIES=	devel python zope
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=	zope

MAINTAINER=	zope@FreeBSD.org
COMMENT=	ZODB undo support for Zope2

LICENSE=	ZPL21

USES=		python zip
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
