# Created by: Andrew Pantyukhin <infofarmer@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/xpi-menueditor/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	menueditor
PORTVERSION=	1.2.7
DISTVERSIONSUFFIX=	-fx+tb
CATEGORIES=	www

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Customize application menus

XPI_DISTNAME=	menu_editor
XPI_ID=		{EDA7B1D7-F793-4e03-B074-E6F303317FB0}
XPI_NUM=	710

.include "${.CURDIR}/../xpi-adblock/Makefile.xpi"
.include <bsd.port.mk>
