# Created by: Brent J. Nordquist <bjn@visi.com>
# $FreeBSD: tags/RELEASE_10_3_0/converters/btoa/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	btoa
PORTVERSION=	5.2
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	converters
MASTER_SITES=	LOCAL/pgollucci

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Encode/decode binary to printable ASCII

DESTDIRNAME=	IGNOREME
MAKE_ARGS=	DESTDIR=${STAGEDIR}${PREFIX}
MAKEFILE=	Makefile.sun

.include <bsd.port.mk>
