# Created by: Rich Neswold <rneswold@mcs.net>
# $FreeBSD: tags/RELEASE_10_3_0/net/wmnet/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	wmnet
PORTVERSION=	1.2
PORTREVISION=	3
CATEGORIES=	net windowmaker
MASTER_SITES=	ftp://ftp.enteract.com/users/rneswold/ \
		LOCAL/novel

MAINTAINER=	novel@FreeBSD.org
COMMENT=	Network bandwidth monitor intended for the WindowMaker dock

USE_XORG=	xpm

.include <bsd.port.mk>
