# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/p5-Proc-PidUtil/Makefile 398843 2015-10-08 18:42:57Z sunpoet $

PORTNAME=	Proc-PidUtil
PORTVERSION=	0.09
PORTREVISION=	1
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	PID file management utilities

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

NO_ARCH=	yes
USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
