# Created by: Wen heping <wenheping@gmail.com>)
# $FreeBSD: tags/RELEASE_10_3_0/www/pear-Services_Google/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Services_Google
PORTVERSION=	0.2.0
CATEGORIES=	www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PHP interface to access the Google SOAP Web APIs

USES=	pear
USE_PHP=	soap

.include <bsd.port.mk>
