# Created by: Jordi Haarman
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-simpletal/Makefile 375249 2014-12-22 17:12:26Z feld $

PORTNAME=	simpletal
PORTVERSION=	4.3
PORTREVISION=	1
CATEGORIES=	devel textproc www python
MASTER_SITES=	http://www.owlfish.com/software/simpleTAL/downloads/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	SimpleTAL-${PORTVERSION}

MAINTAINER=	ayu@commun.jp
COMMENT=	Stand alone TAL Python implementation to power HTML & XML templates

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
