# Created by: David Le Brun <david@dyn-ns.net>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/p5-Filesys-DiskFree/Makefile 386075 2015-05-11 12:04:18Z mat $

PORTNAME=	Filesys-DiskFree
PORTVERSION=	0.06
PORTREVISION=	2
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl equivalent of df(2)

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
