# Created by: Shell Hung <shell@shellhung.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Test-Simple/Makefile 390489 2015-06-24 15:49:37Z adamw $

PORTNAME=	Test-Simple
PORTVERSION=	1.001.014
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-${PORTVERSION:R}${PORTVERSION:E}

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Basic utilities for writing tests in perl

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

CONFLICTS=	p5-Test-Tester-[0-9]* p5-Test-use-ok-[0-9]*

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
