# Created by: wen@FreeBSD.org
# $FreeBSD: tags/RELEASE_10_3_0/security/pecl-pam/Makefile 402450 2015-11-26 14:39:58Z miwi $

PORTNAME=	pam
PORTVERSION=	1.0.3
CATEGORIES=	security pear
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PECL classes for PAM integration

LICENSE= 	PHP202

USES=		tar:tgz
USE_PHP=	yes
USE_PHPIZE=	yes
USE_PHPEXT=	yes

.include <bsd.port.mk>
