# Created by: Muhammad Moinur Rahman <5u623l20@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-Structure_LinkedList/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	Structures_LinkedList
PORTVERSION=	0.2.2
CATEGORIES=	devel pear

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Implements singly and doubly-linked lists

USES=	pear

.include <bsd.port.mk>
