# Created by: ijliao
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-XML-Parser-Lite-Tree/Makefile 389434 2015-06-13 13:57:21Z sunpoet $

PORTNAME=	XML-Parser-Lite-Tree
PORTVERSION=	0.14
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Lightweight XML tree builder

LICENSE=	ART20

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
