# $FreeBSD: tags/RELEASE_10_3_0/devel/py-epdb/Makefile 403255 2015-12-08 09:05:15Z mat $

PORTNAME=	epdb
PORTVERSION=	0.14
DISTVERSIONPREFIX=	${PORTNAME}-
CATEGORIES=	devel python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	swills@FreeBSD.org
COMMENT=	Enhanced Python Debugger

USES=		python
USE_GITHUB=	yes
USE_PYTHON=	autoplist distutils

GH_ACCOUNT=	sassoftware

.include <bsd.port.mk>
