# Created by: roam@orbitel.bg
# $FreeBSD: tags/RELEASE_10_3_0/net/tcpcat/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	tcpcat
PORTVERSION=	1.2.0
CATEGORIES=	net
MASTER_SITES=	http://ess4.engr.uvic.ca/proj/tcpcat/ \
		LOCAL/roam/net

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Simple utility for sending/receiving data over a TCP or a Unix-domain socket

GNU_CONFIGURE=	yes
PLIST_FILES=	bin/tcpcat

.include <bsd.port.mk>
