# Created by: Gabor Kovesdan
# $FreeBSD: tags/RELEASE_10_3_0/security/p5-Crypt-TEA/Makefile 384666 2015-04-24 16:20:31Z mat $

PORTNAME=	Crypt-TEA
PORTVERSION=	1.25
PORTREVISION=	1
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Perl extension to Tiny Encryption Algorithm

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
