# Created by: Parv <parv@pair.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Data-Swap/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Data-Swap
PORTVERSION=	0.08
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	parv@pair.com
COMMENT=	XS module to swap the contents and types of referenced variables

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
