# $FreeBSD: tags/RELEASE_10_3_0/www/twiki-TagMePlugin/Makefile 362252 2014-07-19 11:09:51Z ohauer $

PORTNAME=	TagMePlugin
SVNREV=		17472

COMMENT=	Collaborative content tagging

.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
