# Created by: Valery Komarov <komarov@valerka.net>
# $FreeBSD: tags/RELEASE_10_3_0/devel/php5-blitz-devel/Makefile 344683 2014-02-17 06:59:44Z miwi $

PORTNAME=	blitz-devel
PORTVERSION=	0.7.2
CATEGORIES=	devel
MASTER_SITES=	http://alexeyrybak.com/blitz/
PKGNAMEPREFIX=	php5-
DISTNAME=	blitz-${PORTVERSION}-devel

MAINTAINER=	komarov@valerka.net
COMMENT=	PHP templating engine

CONFLICTS=	php5-blitz-0.6*

USE_PHP=	yes
USE_PHP_BUILD=	yes
USE_PHPEXT=	yes
PHP_MODNAME=	blitz

.include <bsd.port.mk>
