# Created by: Gerrit Beine <gerrit.beine@gmx.de>
# $FreeBSD: tags/RELEASE_10_3_0/mail/squirrelmail-multilogin-plugin/Makefile 366415 2014-08-28 15:16:49Z adamw $

PORTNAME=	multilogin
PORTVERSION=	2.4
PORTREVISION=	3
CATEGORIES=	mail www
DISTNAME=	${PORTNAME}-${PORTVERSION}-1.2.9

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Allows manual selection of login server on login page

USE_SM_COMPAT=	yes
USE_GENERIC_PKGMESSAGE=	yes

.include "${.CURDIR}/../squirrelmail/bsd.squirrelmail.mk"
.include <bsd.port.mk>
