# Created by: snowchyld
# $FreeBSD: tags/RELEASE_10_3_0/mail/p5-Mail-Alias/Makefile 386075 2015-05-11 12:04:18Z mat $

PORTNAME=	Mail-Alias
PORTVERSION=	1.12
PORTREVISION=	1
CATEGORIES=	mail perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Mail::Alias

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
