# Created by: Vladimir Chukharev
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-robotframework/Makefile 399262 2015-10-14 13:54:33Z mat $

PORTNAME=	robotframework
PORTVERSION=	2.9.2
CATEGORIES=	devel www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	Vladimir.Chukharev@gmail.com
COMMENT=	Generic test automation framework

LICENSE=	APACHE20

NO_ARCH=	yes
USES=		python:2
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
