# Created by: Tom Hukins <tom@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/ports-mgmt/p5-FreeBSD-Ports/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	FreeBSD-Ports
PORTVERSION=	0.04
PORTREVISION=	1
CATEGORIES=	ports-mgmt perl5
MASTER_SITES=	LOCAL/tom
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl modules for parsing FreeBSD's Ports INDEX file


USES=		perl5 tar:bzip2
USE_PERL5=	configure

.include <bsd.port.mk>
