# Created by: clsung
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Text-Affixes/Makefile 400290 2015-10-27 15:52:38Z sunpoet $

PORTNAME=	Text-Affixes
PORTVERSION=	0.09
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module for prefixes and suffixes analisys of text

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
