# Created by: will
# $FreeBSD: tags/RELEASE_10_3_0/audio/shout/Makefile 363157 2014-07-28 14:12:36Z adamw $

PORTNAME=	shout
PORTVERSION=	0.8.0
PORTREVISION=	1
CATEGORIES=	audio net
MASTER_SITES=	http://downloads.xiph.org/releases/libshout/ \
		http://downloads.us.xiph.org/releases/libshout/ \
		http://public.planetmirror.com/pub/xiph/releases/libshout/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Send mp3 streams to an icecast/shoutcast server

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
