# $FreeBSD: tags/RELEASE_10_3_0/devel/elixir-estree/Makefile 399293 2015-10-14 20:38:11Z olgeni $

PORTNAME=	elixir-estree
PORTVERSION=	2.1.1
DISTVERSIONPREFIX=	v
CATEGORIES=	devel

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	JavaScript AST to JavaScript code generator in Elixir

LICENSE=	MIT

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	bryanjos

ELIXIR_APP_NAME=estree

.include <bsd.port.mk>
