# $FreeBSD: tags/RELEASE_10_3_0/net/py-paho-mqtt/Makefile 391296 2015-07-04 09:09:32Z ohauer $

PORTNAME=	paho-mqtt
PORTVERSION=	1.1
CATEGORIES=	net python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	joe@thrallingpenguin.com
COMMENT=	MQTT version 3.1/3.1.1 client class

LICENSE=	EPL

USES=		shebangfix python
USE_PYTHON=	distutils autoplist
SHEBANG_FILES=	examples/*.py

.include <bsd.port.mk>
