# Created by: will
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-String-Random/Makefile 377656 2015-01-22 14:23:39Z tobez $

PORTNAME=	String-Random
PORTVERSION=	0.28
PORTEPOCH=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl interface to generate "random" strings

USES=		perl5
USE_PERL5=	modbuild

PORTSCOUT=	limit:^0\.(\d\.){,2}

.include <bsd.port.mk>
