# Created by: Sheldon Hearn <sheldonh@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Config-General/Makefile 400540 2015-10-30 14:01:55Z jadawin $

PORTNAME=	Config-General
PORTVERSION=	2.60
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	jadawin@FreeBSD.org
COMMENT=	Perl5 module for handling Apache-style configuration files

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
