# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/archivers/rubygem-archive-zip/Makefile 367753 2014-09-09 17:22:10Z tota $

PORTNAME=	archive-zip
PORTVERSION=	0.7.0
CATEGORIES=	archivers rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Provides interface to working with ZIP archives

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

RUN_DEPENDS=	rubygem-io-like>=0.3.0:${PORTSDIR}/devel/rubygem-io-like

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
