# Created by: William Grzybowski <william88@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-mccabe/Makefile 400986 2015-11-07 12:47:17Z wg $

PORTNAME=	mccabe
PORTVERSION=	0.3.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Ned's script to check McCabe complexity

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
