# Created by: James FitzGibbon <jfitz@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Religion/Makefile 386075 2015-05-11 12:04:18Z mat $

PORTNAME=	Religion
PORTVERSION=	1.04
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:KJALB
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 module to install die() and warn() handlers

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
