# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/multimedia/rubygem-flvtool2/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	flvtool2
PORTVERSION=	1.0.6
CATEGORIES=	multimedia rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Flash video (FLV) manipulation tool

LICENSE=	BSD3CLAUSE

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/flvtool2

.include <bsd.port.mk>
