# Created by: joerg
# $FreeBSD: tags/RELEASE_10_3_0/deskutils/xpostit/Makefile 363374 2014-07-29 19:11:51Z adamw $

PORTNAME=	xpostit
PORTVERSION=	3.3.1
PORTREVISION=	2
CATEGORIES=	deskutils
MASTER_SITES=	ftp://ftp.x.org/R5contrib/
DISTNAME=	${PORTNAME}${PORTVERSION}

MAINTAINER=	joerg@FreeBSD.org
COMMENT=	PostIt (R) messages onto your X11 screen

USES=		imake tar:Z
USE_XORG=	ice sm x11 xaw xext xmu xpm xt
WRKSRC=		${WRKDIR}/xpostit

.include <bsd.port.mk>
