# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/math/R-cran-minqa/Makefile 385917 2015-05-10 03:08:17Z tota $

PORTNAME=	minqa
PORTVERSION=	1.2.4
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Derivative-free optimization algorithms by quadratic approximation

LICENSE=	GPLv2

RUN_DEPENDS=	R-cran-Rcpp>=0.9.10:${PORTSDIR}/devel/R-cran-Rcpp

USES=	cran:auto-plist

.include <bsd.port.mk>
