# Created by: Lars Balker Rasmussen <lbr@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Class-C3-XS/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Class-C3-XS
PORTVERSION=	0.13
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	XS speedups for Class::C3

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
