# Created by: Steven Kreuzer <skreuzer@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/R-cran-microbenchmark/Makefile 371160 2014-10-18 21:36:33Z antoine $

PORTNAME=	microbenchmark
DISTVERSION=	1.4-2
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Infrastructure to measure the execution time of R expressions

LICENSE=	BSD3CLAUSE

RUN_DEPENDS=	R-cran-ggplot2>0:${PORTSDIR}/graphics/R-cran-ggplot2

USES=	cran:auto-plist

.include <bsd.port.mk>
