# Created by: René Ladan <rene@freebsd.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/py-django-overextends/Makefile 404403 2015-12-25 07:04:07Z sunpoet $

PORTNAME=	django-overextends
PORTVERSION=	0.4.1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	rene@FreeBSD.org
COMMENT=	Django reusable app enabling circular template inheritance

LICENSE=	BSD2CLAUSE

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}django>=1.7:${PORTSDIR}/www/py-django

NO_ARCH=	yes

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
