# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/x11/libXcomposite/Makefile 384234 2015-04-18 15:34:36Z kwm $

PORTNAME=	libXcomposite
PORTVERSION=	0.4.4
PORTREVISION=	3
PORTEPOCH=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Composite extension library

XORG_CAT=	lib
USE_XORG=	compositeproto:both x11 xfixes xext fixesproto xproto:both

.include <bsd.port.mk>
