# Created by: MIHIRA Yoshiro <sanpei@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/rubygem-unf/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	unf
PORTVERSION=	0.1.4
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Wrapper library to bring Unicode Normalization Form support

LICENSE=	BSD2CLAUSE

RUN_DEPENDS=	rubygem-unf_ext>=0:${PORTSDIR}/textproc/rubygem-unf_ext

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
