# $FreeBSD: tags/RELEASE_10_3_0/x11-fonts/font-bitstream-speedo/Makefile 381876 2015-03-21 23:05:19Z bapt $

PORTNAME=	font-bitstream-speedo
PORTVERSION=	1.0.2
PORTREVISION=	3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org Bitstream Vera Speedo font

XORG_CAT=	font

.include <bsd.port.mk>
