# Created by: Ying-Chieh Liao <ijliao@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Perl-Tidy/Makefile 394303 2015-08-15 12:09:47Z sunpoet $

PORTNAME=	Perl-Tidy
PORTVERSION=	20150815
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Indents and reformats Perl scripts to make them easier to read

LICENSE=	GPLv2

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
