# $FreeBSD: tags/RELEASE_10_3_0/www/py-plone.synchronize/Makefile 405764 2016-01-11 05:23:46Z rm $

PORTNAME=	plone.synchronize
PORTVERSION=	1.0.1
PORTREVISION=	1
CATEGORIES=	www python zope
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=	zope

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Simple decorators to support synchronized methods

LICENSE=	BSD3CLAUSE

NO_ARCH=	yes
USES=		python zip
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
