# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/databases/R-cran-DBI/Makefile 369449 2014-09-28 11:57:52Z tota $

PORTNAME=	DBI
PORTVERSION=	0.3.1
CATEGORIES=	databases
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	R Database Interface

LICENSE=	LGPL20 LGPL21 LGPL3
LICENSE_COMB=	dual

USES=	cran:auto-plist

.include <bsd.port.mk>
