# Created by: Shinsuke Matsui <smatsui@karashi.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-File-chmod/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	File-chmod
PORTVERSION=	0.32
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	smatsui@karashi.org
COMMENT=	File::chmod - Implements symbolic and ls chmod modes

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
