# Created by: Rui Lopes (rgl ruilopes com)
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-tzinfo/Makefile 398612 2015-10-04 18:01:39Z sunpoet $

PORTNAME=	tzinfo
PORTVERSION=	1.2.2
PORTREVISION=	1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Daylight-savings aware timezone support for Ruby

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

RUN_DEPENDS=	rubygem-thread_safe1>=0.1:${PORTSDIR}/devel/rubygem-thread_safe1

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
