# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Text-Lorem/Makefile 383844 2015-04-12 08:45:54Z mat $

PORTNAME=	Text-Lorem
PORTVERSION=	0.3
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Generate random Latin looking text

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
