# Created by: Phil Phillips
# $FreeBSD: tags/RELEASE_10_3_0/www/p5-CGI-Thin/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	CGI-Thin
PORTVERSION=	0.52
PORTREVISION=	1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	pphillips@experts-exchange.com
COMMENT=	Lightweight Parser for CGI Forms

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
