# $FreeBSD: tags/RELEASE_10_3_0/audio/festvox-cmu_us_awb_arctic/Makefile 402849 2015-12-02 19:41:44Z pi $

VOICE=	cmu_us_awb_arctic

COMMENT=	CMU US English Scottish male voice for festival

MASTERDIR=	${.CURDIR}/../festvox-cmu_us_slt_arctic

.include "${MASTERDIR}/Makefile"
