# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-ToscaWidgets/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	ToscaWidgets
PORTVERSION=	0.9.12
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	robak@FreeBSD.org
COMMENT=	Python framework for building reusable web components

LICENSE=	MIT

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}webob>=0:${PORTSDIR}/www/py-webob

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
