# Created by: ache
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-String-CRC32/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	String-CRC32
PORTVERSION=	1.5
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl interface for cyclic redundancy check generation

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
