# Created by: Maxim Maximov (mcsi@agava.com)
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-enum/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	enum
PORTVERSION=	1.090
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:NEILB
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-${PORTVERSION:C/0$//}

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Defines symbolic constants with ordered numeric values, like C enums

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
