# Created by: Mathieu Arnold <mat@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Script-isAperlScript/Makefile 381151 2015-03-12 23:00:02Z adamw $

PORTNAME=	Script-isAperlScript
PORTVERSION=	1.0.0
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Basic check for if something is a perl script or not

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=	perl5
USE_PERL5=	configure

.include <bsd.port.mk>
