# Created by: wenheping@gmail.com
# $FreeBSD: tags/RELEASE_10_3_0/print/rubygem-prawn-layout/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	prawn-layout
PORTVERSION=	0.8.4
CATEGORIES=	print rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Prawn Extension to Provides Table Support and Other Layout

LICENSE=	GPLv2 RUBY
LICENSE_COMB=	dual

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
