# Created by: Tomoyuki Sakurai <cherry@trombik.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-File-Stream/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	File-Stream
PORTVERSION=	2.30
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Regular expression delimited records from streams

RUN_DEPENDS=	p5-YAPE-Regex>=4.00:${PORTSDIR}/textproc/p5-YAPE-Regex

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
