# Makefile for games/cre (Corewars Redcode Evolver).
#
# $FreeBSD: tags/RELEASE_10_3_0/games/cre/files/Makefile 340722 2014-01-22 17:00:46Z mat $
#

PROG=	cre
SRCS!=	ls *.[ch]
NO_MAN=	yes

.include <bsd.prog.mk>
