# $FreeBSD: tags/RELEASE_10_3_0/graphics/gstreamer1-plugins-png/Makefile 397984 2015-09-26 14:36:23Z kwm $

PORTREVISION=	0
CATEGORIES=	graphics
PKGNAMESUFFIX=	1-plugins-png

COMMENT=	Gstreamer png plugin

GST_PLUGIN=	libpng
DIST=		good

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
