# $FreeBSD: tags/RELEASE_10_3_0/net/rubygem-connection_pool/Makefile 404872 2015-12-30 17:37:05Z sunpoet $

PORTNAME=	connection_pool
PORTVERSION=	2.2.0
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Generic connection pool for Ruby

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
