# Created by: Palle Girgensohn <girgen@partitur.se>
# $FreeBSD: tags/RELEASE_10_3_0/databases/postgresql91-plperl/Makefile 366114 2014-08-25 17:53:26Z crees $

WANT_PGSQL_VER=	9.1
COMPONENT=	-plperl

.include "${.CURDIR}/../postgresql90-plperl/Makefile"
