# Created by: David Chaplin-Loebell <direct@klatha.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Tie-CPHash/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Tie-CPHash
PORTVERSION=	1.04
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	direct@klatha.com
COMMENT=	Perl module implementing a case preserving hash table

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
