# Created by: Joseph Benden <joe@thrallingpenguin.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-rb-fsevent/Makefile 404805 2015-12-30 08:06:02Z sunpoet $

PORTNAME=	rb-fsevent
PORTVERSION=	0.9.7
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	FSEvents API with Signals catching (without RubyCocoa)

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
