# Created by: MIHIRA Yoshiro <sanpei@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/net/rubygem-domain_name/Makefile 398859 2015-10-08 18:44:10Z sunpoet $

PORTNAME=	domain_name
PORTVERSION=	0.5.25
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Domain Name manipulation library for ruby

LICENSE=	BSD2CLAUSE

RUN_DEPENDS=	rubygem-unf>=0.0.5:${PORTSDIR}/textproc/rubygem-unf

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
