# $FreeBSD: tags/RELEASE_10_3_0/devel/erlang-syslog/Makefile 391483 2015-07-06 22:27:17Z olgeni $

PORTNAME=	syslog
PORTVERSION=	1.0.3
CATEGORIES=	devel
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Erlang port driver for interacting with syslog

USES=		erlang:rebar
USE_GITHUB=	yes
GH_ACCOUNT=	Vagabond
GH_PROJECT=	${PKGNAMEPREFIX}${PORTNAME}

.include <bsd.port.mk>
