# Created by: Marc Fonvieille <blackend@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/misc/freebsd-doc-sr/Makefile 354559 2014-05-19 16:43:45Z blackend $

CATEGORIES=	misc docs
PKGNAMEPREFIX=	sr-

MAINTAINER=	doceng@FreeBSD.org
COMMENT=	Serbian translation of the FreeBSD Documentation Project

MASTERDIR=	${.CURDIR}/../freebsd-doc-en
PLIST=		${.CURDIR}/pkg-plist

DOCLANG=	sr_YU.ISO8859-2

.include "${MASTERDIR}/Makefile"
