# Created by: clsung@dragon2.net
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Text-ExtractWords/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Text-ExtractWords
PORTVERSION=	0.08
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl extension for extract words from strings

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
