# Created by: Mark Felder <feld@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-channel-htmlpurifier/Makefile 351812 2014-04-22 12:09:51Z antoine $

PORTNAME=	htmlpurifier
PORTVERSION=	20140120
PORTREVISION=	1
CATEGORIES=	devel www pear
MASTER_SITES=	#

MAINTAINER=	feld@FreeBSD.org
COMMENT=	PEAR channel ${PEAR_CHANNEL_HOST}

PEAR_CHANNEL_HOST=	htmlpurifier.org
PEAR_CHANNEL_ALIAS=	hp

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear/bsd.pear.channel.mk"
.include <bsd.port.post.mk>
