# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/misc/kde4-l10n-es/Makefile 371193 2014-10-19 15:57:27Z makc $

PORTNAME=	kde-l10n
PORTVERSION=	${KDE4_VERSION}
CATEGORIES=	misc kde spanish

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Spanish messages and documentation for KDE SC 4

KDE4_L10N=	es

.include "${.CURDIR}/../kde4-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
