# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/hs-MissingH/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	MissingH
PORTVERSION=	1.3.0.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Large utility library

LICENSE=	BSD3CLAUSE

USE_CABAL=	hslogger HUnit mtl network old-time parsec random regex-compat

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
