# Created by: ports@c0decafe.net <ports@c0decafe.net>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-notify/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	notify
PORTVERSION=	0.5.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	meta+ports@vmeta.jp
COMMENT=	Desktop notify for many platform

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/notify

.include <bsd.port.mk>
