# Created by: Alonso Cardenas Marquez <acm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/converters/fpc-iconvenc/Makefile 403082 2015-12-05 23:29:36Z marino $

CATEGORIES=	converters lang
PKGNAMESUFFIX=	-iconvenc

MAINTAINER=	freebsd-fpc@FreeBSD.org
COMMENT=	Free Pascal unit to iconv library

USE_FPC=	yes

MASTERDIR=	${.CURDIR}/../../lang/fpc
WRKUNITDIR=	${FPCSRCDIR}/packages/${PKGNAMESUFFIX:S/-//}
EXTRACTUNITDIR=	${WRKUNITDIR}

.include "${MASTERDIR}/Makefile"
