# Created by: Mario S F Ferreira <lioux@linf.unb.br> et al.
# $FreeBSD: tags/RELEASE_10_3_0/math/p5-Math-Expr/Makefile 402575 2015-11-29 07:00:19Z sunpoet $

PORTNAME=	Math-Expr
PORTVERSION=	0.4
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:HAKANARDO
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module for parsing mathematical expressions into a tree structure

LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/COPYING

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
