# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/audio/gstreamer-plugins-lame/Makefile 352119 2014-04-25 12:46:45Z bapt $
#   $MCom: ports/audio/gstreamer-plugins-lame/Makefile,v 1.5 2008/03/19 14:05:30 ahze Exp $

PORTREVISION=	1
CATEGORIES=	audio

COMMENT=	Gstreamer mp3 encode plugin

GST_PLUGIN=	lame

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
