# Created by: rpsfa@rit.edu
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-devise-rails4/Makefile 394132 2015-08-13 17:35:53Z sunpoet $

PKGNAMESUFFIX=	-rails4

RAILS4=		yes
MASTERDIR=	${.CURDIR}/../rubygem-devise

.include "${MASTERDIR}/Makefile"
