# Created by: John Chen <johnpupu@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pecl-ev/Makefile 404164 2015-12-21 18:35:04Z sunpoet $

PORTNAME=	ev
PORTVERSION=	0.2.15
PORTREVISION=	2
CATEGORIES=	devel
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-
DIST_SUBDIR=	PECL

MAINTAINER=	johnpupu@gmail.com
COMMENT=	Libev extension for PHP

LICENSE=	PHP301
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		tar:tgz
USE_PHP=	yes
USE_PHP_BUILD=	yes
USE_PHPIZE=	yes
USE_PHPEXT=	yes

.include <bsd.port.mk>
