# $FreeBSD: tags/RELEASE_10_3_0/textproc/rubygem-shell2html/Makefile 403353 2015-12-09 03:03:02Z araujo $

PORTNAME=	shell2html
PORTVERSION=	0.0.6
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	mose@mose.com
COMMENT=	Ruby lib for transforming bash colors into html

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
PLIST_FILES=	bin/shell2css bin/shell2html

.include <bsd.port.mk>
