# Created by: joerg
# $FreeBSD: tags/RELEASE_10_3_0/deskutils/sliderule/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	sliderule
PORTVERSION=	1.0
PORTREVISION=	2
CATEGORIES=	deskutils
MASTER_SITES=	LOCAL/joerg
DISTNAME=	${PORTNAME}

MAINTAINER=	joerg@FreeBSD.org
COMMENT=	The part of X11R3's xcalc featuring a slide rule

USES=		imake
USE_XORG=	x11 xext
USE_GCC=	any
PLIST_FILES=	bin/sliderule man/man1/sliderule.1.gz

.include <bsd.port.mk>
