# $FreeBSD: tags/RELEASE_10_3_0/databases/erlang-eredis/Makefile 391484 2015-07-06 22:34:11Z olgeni $

PORTNAME=	eredis
PORTVERSION=	1.0.8
DISTVERSIONPREFIX=	v
PORTREVISION=	2
CATEGORIES=	databases
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Non-blocking Redis client for Erlang

LICENSE=	MIT

USES=		erlang:rebar
USE_GITHUB=	yes
GH_ACCOUNT=	wooga

.include <bsd.port.mk>
