# $FreeBSD: tags/RELEASE_10_3_0/net/py-ntplib/Makefile 398958 2015-10-09 20:57:26Z pawel $

PORTNAME=	ntplib
PORTVERSION=	0.3.3
CATEGORIES=	net python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	uros@gruber.si
COMMENT=	Python NTP library

LICENSE=	MIT

USES=		python
USE_PYTHON=	autoplist distutils

NO_ARCH=	yes

.include <bsd.port.mk>
