# Created by: "Choe, Cheng-Dae" whitekid
# $FreeBSD: tags/RELEASE_10_3_0/textproc/py-rss2gen/Makefile 377822 2015-01-24 20:39:38Z jbeich $

PORTNAME=	rss2gen
PORTVERSION=	1.1
CATEGORIES=	textproc python
MASTER_SITES=	http://www.dalkescientific.com/Python/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	PyRSS2Gen-${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Python library for generating RSS 2.0 feeds

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
