# Created by: never@nevermind.kiev.ua
# $FreeBSD: tags/RELEASE_10_3_0/devel/publib/Makefile 387927 2015-05-30 11:42:58Z pawel $

PORTNAME=	publib
PORTVERSION=	0.40
CATEGORIES=	devel
MASTER_SITES=	http://ftp.debian.org/debian/pool/main/p/publib/
DISTNAME=	publib_${PORTVERSION}.orig

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Library of C functions for various purposes

LICENSE=	BSD2CLAUSE

USES=		gmake
GNU_CONFIGURE=	yes

WRKSRC=		${WRKDIR}/${PORTNAME}-${PORTVERSION}

.include <bsd.port.mk>
