# Created by: Tim Bishop <tim@bishnet.net>
# $FreeBSD: tags/RELEASE_10_3_0/net/onenetd/Makefile 361440 2014-07-10 12:13:11Z olgeni $

PORTNAME=	onenetd
PORTVERSION=	12
CATEGORIES=	net
MASTER_SITES=	http://offog.org/files/ \
		http://ftp.i-scream.org/pub/offog.org/files/

MAINTAINER=	tdb@FreeBSD.org
COMMENT=	Single-server inetd

GNU_CONFIGURE=	yes
PLIST_FILES=	bin/onenetd \
		man/man1/onenetd.1.gz

.include <bsd.port.mk>
