# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/lang/p5-Scalar-List-Utils/Makefile 392438 2015-07-18 17:06:45Z sunpoet $

PORTNAME=	Scalar-List-Utils
PORTVERSION=	1.42
PORTEPOCH=	1
CATEGORIES=	lang perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl subroutines that would be nice to have in the perl core

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
