# Created by: Vivek Khera <vivek@khera.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Text-Format+NWrap/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Text-Format+NWrap
PORTVERSION=	0.52
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	Text-Format0.52+NWrap0.11

MAINTAINER=	vivek@khera.org
COMMENT=	Various subroutines to format and wrap text

CONFLICTS=	p5-Text-Format-[0-9]*

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
