# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-setuptools32/Makefile 352367 2014-04-26 19:31:10Z sunpoet $

PKGNAMESUFFIX=	${PYTHON_SUFFIX}

PYTHON_VERSION=	python3.2

MASTERDIR=	${.CURDIR}/../py-setuptools

.include "${MASTERDIR}/Makefile"
