# $FreeBSD: tags/RELEASE_10_3_0/graphics/graphos/Makefile 397315 2015-09-19 10:33:34Z theraven $

PORTNAME=	graphos
PORTVERSION=	0.5
PORTREVISION=	3
CATEGORIES=	graphics gnustep
MASTER_SITES=	SAVANNAH/gap
DISTNAME=	Graphos-${PORTVERSION}

MAINTAINER=	theraven@FreeBSD.org
COMMENT=	Vector drawing application centered around bezier paths

LICENSE=	GPLv2

USES=		gnustep
USE_GNUSTEP=	back build
USE_LDCONFIG=	${GNUSTEP_LOCAL_LIBRARIES}

.include <bsd.port.mk>
