# Created by: Dorit Rottner (<rottner@punkt.de>)
# $FreeBSD: tags/RELEASE_10_3_0/finance/pear_Payment_DTA/Makefile 369668 2014-09-30 21:25:37Z bapt $

PORTNAME=	Payment_DTA
PORTVERSION=	1.2.1
CATEGORIES=	finance pear

MAINTAINER=	rottner@punkt.de
COMMENT=	PEAR class to create and handle DTA files used in Germany

USES=	pear

.include <bsd.port.mk>
