# Created by: Jean-Yves Lefort <jylefort@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/astro/celestia-gtk/Makefile 352516 2014-04-28 15:55:51Z bapt $

CELESTIA_UI=	gtk
MASTERDIR=	${.CURDIR}/../celestia

.include "${MASTERDIR}/Makefile"
