# $FreeBSD: tags/RELEASE_10_3_0/www/rubygem-heroku-api/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	heroku-api
PORTVERSION=	0.3.18
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	rpaulo@FreeBSD.org
COMMENT=	Heroku API

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST= yes

.include <bsd.port.mk>
