# Created by: Denis Pokataev <catone@cpan.org>
# $FreeBSD: tags/RELEASE_10_3_0/converters/p5-JSON-XS-VersionOneAndTwo/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	JSON-XS-VersionOneAndTwo
PORTVERSION=	0.31
PORTREVISION=	1
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Support versions 1 and 2 of JSON::XS

RUN_DEPENDS=	p5-JSON-XS>=0:${PORTSDIR}/converters/p5-JSON-XS
BUILD_DEPENDS:=	${RUN_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
