# Created by: Cristiano Deana <cris@gufi.org>
# $FreeBSD: tags/RELEASE_10_3_0/security/expiretable/Makefile 349352 2014-03-27 18:37:25Z garga $

PORTNAME=	expiretable
PORTVERSION=	0.6
PORTREVISION=	1
CATEGORIES=	security
MASTER_SITES=	http://expiretable.fnord.se/

MAINTAINER=	cris@gufi.org
COMMENT=	Utility to remove entries from the pf(4) table based on their age

USE_RC_SUBR=	expiretable

.include <bsd.port.mk>
