# $FreeBSD: tags/RELEASE_10_3_0/games/fortunate/Makefile 397315 2015-09-19 10:33:34Z theraven $

PORTNAME=	fortunate
PORTVERSION=	3.1
PORTREVISION=	5
CATEGORIES=	games gnustep
MASTER_SITES=	GNUSTEP_CH

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Graphical front-end to the command-line BSD fortune

USES=		gnustep
USE_GNUSTEP=	back build

.include <bsd.port.mk>
