# Created by: Jeremy Shaffner <jeremy@external.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-File-Tail/Makefile 394927 2015-08-21 06:56:57Z kuriyama $

PORTNAME=	File-Tail
PORTVERSION=	1.3
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl Module to read the end of a file as it's appended to

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	YES

.include <bsd.port.mk>
