# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: tags/RELEASE_10_3_0/www/twiki-BugzillaLinkPlugin/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	BugzillaLinkPlugin
SVNREV=		15560
MASTER_SITES=	http://protey.ru/freebsd/distfiles/ \
		LOCAL/skv

COMMENT=	Link to Bugzilla bugs using shorthand references

.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
