# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/mail/rubygem-email_reply_parser-discourse/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	email_reply_parser-discourse
PORTVERSION=	0.6
CATEGORIES=	mail rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Email Reply Parser

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
