# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/graphics/p5-Google-Chart/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Google-Chart
PORTVERSION=	0.05014
PORTREVISION=	4
CATEGORIES=	graphics perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Perl Interface to Google Charts API

RUN_DEPENDS=	p5-libwww>0:${PORTSDIR}/www/p5-libwww \
		p5-Moose>=2:${PORTSDIR}/devel/p5-Moose \
		p5-URI>0:${PORTSDIR}/net/p5-URI

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
