# Created by: Thomas Gellekum <tg@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/graphics/xbmbrowser/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	xbmbrowser
PORTVERSION=	5.1
PORTREVISION=	3
CATEGORIES=	graphics
MASTER_SITES=	XCONTRIB/utilities
DISTNAME=	${PORTNAME}${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	View complete directories of X bitmaps and X pixmaps

USES=		gmake imake
USE_XORG=	xaw xmu

.include <bsd.port.mk>
