# Created by: Wen Heping<wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-deprecated/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	deprecated
PORTVERSION=	3.0.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Library intended to aid developers working with deprecated code

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
