# Created by: Michael Moll <kvedulv@kvedulv.de>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/rubygem-chef-api/Makefile 405015 2016-01-01 17:05:54Z mmoll $

PORTNAME=	chef-api
PORTVERSION=	0.5.0
CATEGORIES=	sysutils ruby
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Leightweight Chef API client

LICENSE=	APACHE20

RUN_DEPENDS=	rubygem-logify>=0.1:${PORTSDIR}/sysutils/rubygem-logify

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
