# Created by: Andrej Zverev <andrey.zverev@electro-com.ru>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Regexp-Copy/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Regexp-Copy
PORTVERSION=	0.06
PORTREVISION=	2
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:JDUNCAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Copy the contents of one Regexp object to another

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
