# $FreeBSD: tags/RELEASE_10_3_0/devel/py-zope.datetime/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	zope.datetime
PORTVERSION=	3.4.1
PORTREVISION=	1
CATEGORIES=	devel python zope
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=	zope

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Commonly used date and time related utility functions

LICENSE=	ZPL21

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
