# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/net-mgmt/p5-NSNMP/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	NSNMP
PORTVERSION=	0.5
PORTREVISION=	1
CATEGORIES=	net-mgmt perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:KRAGEN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	NSNMP - fast, flexible, low-level, pure-Perl SNMP library

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
