# Created by: Gabor Kovesdan
# $FreeBSD: tags/RELEASE_10_3_0/security/p5-Digest-Perl-MD5/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Digest-Perl-MD5
PORTVERSION=	1.9
PORTREVISION=	1
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ashish@FreeBSD.org
COMMENT=	Perl extension for MD5 hash algorithm in pure Perl

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
