# Created by: jaharkes
# $FreeBSD: tags/RELEASE_10_3_0/devel/lwp/Makefile 362736 2014-07-23 21:56:25Z amdmi3 $

PORTNAME=	lwp
PORTVERSION=	2.6
PORTREVISION=	1
CATEGORIES=	devel
MASTER_SITES=	http://ftp.coda.cs.cmu.edu/pub/lwp/src/ \
		http://ftp.wu-wien.ac.at/pub/systems/coda/src/ \
		ftp://ftp.coda.cs.cmu.edu/pub/lwp/src/ \
		ftp://ftp.wu-wien.ac.at/pub/systems/coda/src/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Userspace thread library

LICENSE=	LGPL20

USES=		gmake libtool pathfix
GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes
INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
