# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Proc-Wait3/Makefile 400735 2015-11-04 11:19:30Z tobez $

PORTNAME=	Proc-Wait3
PORTVERSION=	0.05
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl extension for wait3 system call

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
