# Created by: Jui-Nan Lin <jnlin@csie.nctu.edu.tw>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py_static_check/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	py_static_check
PORTVERSION=	1.2
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP

MAINTAINER=	jnlin@csie.nctu.edu.tw
COMMENT=	Statically check your python code

LICENSE=	MIT

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}pyflakes>=0.5:${PORTSDIR}/devel/py-pyflakes

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
