# $FreeBSD: tags/RELEASE_10_3_0/www/p5-I18N-AcceptLanguage/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	I18N-AcceptLanguage
PORTVERSION=	1.04
PORTREVISION=	1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension to matches language preference (HTTP Accept-Language)

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
