# $FreeBSD: tags/RELEASE_10_3_0/net/gstreamer1-plugins-libmms/Makefile 351947 2014-04-23 14:22:47Z tijl $

PORTREVISION=	0
CATEGORIES=	net

COMMENT=	Gstreamer mms:// and mmsh:// plugin

GST_PLUGIN=	libmms
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
