# $FreeBSD: tags/RELEASE_10_3_0/devel/erlang-bbmustache/Makefile 391483 2015-07-06 22:27:17Z olgeni $

PORTNAME=	bbmustache
PORTVERSION=	1.0.3
DISTVERSIONPREFIX=	v
CATEGORIES=	devel
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Mustache template engine for Erlang

LICENSE=	MIT

USES=		erlang:rebar3
USE_GITHUB=	yes
GH_ACCOUNT=	soranoba

.include <bsd.port.mk>
