# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-File-ShareDir-Install/Makefile 375969 2015-01-01 16:22:24Z sunpoet $

PORTNAME=	File-ShareDir-Install
PORTVERSION=	0.10
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Install read-only data files from a distribution

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
