# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Commands-Guarded/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Commands-Guarded
PORTVERSION=	1.01
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Deterministic guarded commands for Perl

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
