# Created by: Zach Thompson <hideo@lastamericanempire.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Tie-Hash-Indexed/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Tie-Hash-Indexed
PORTVERSION=	0.05
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Ordered hashes for Perl in XS

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
