# Created by: Edwin Groothuis <edwin@mavetju.org>
# $FreeBSD: tags/RELEASE_10_3_0/math/ploticus-nox11/Makefile 361015 2014-07-06 23:57:55Z linimon $

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Generates plots and graphs from data (no X11 required)

WITHOUT_X11=	yes

MASTERDIR=	${.CURDIR}/../../math/ploticus

.include "${MASTERDIR}/Makefile"
