# Created by: Aaron Dalton <aaron@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Class-STL-Containers/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	Class-STL-Containers
PORTVERSION=	0.35
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Perl extension for STL-like object management

LICENSE=	GPLv2

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
