# Created by: Michael Moll <kvedulv at kvedulv.de>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-bindata/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	bindata
PORTVERSION=	2.1.0
CATEGORIES=	devel ruby
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby library to read and write binary file formats

LICENSE=	BSD2CLAUSE

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
