# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/science/R-cran-som/Makefile 367888 2014-09-10 20:50:31Z gerald $

PORTNAME=	som
DISTVERSION=	0.3-5
PORTREVISION=	9
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Self-Organizing Map

LICENSE=	GPLv3

USES=	cran:auto-plist

.include <bsd.port.mk>
