# Created by: fernandotcl
# $FreeBSD: tags/RELEASE_10_3_0/net/opendpi/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	opendpi
PORTVERSION=	1.2.0
PORTREVISION=	1
CATEGORIES=	net
MASTER_SITES=	GOOGLE_CODE

MAINTAINER=	fernando@netfilter.com.br
COMMENT=	Open source deep packet inspection engine

GNU_CONFIGURE=	yes
INSTALL_TARGET=	install-strip
USES=		libtool

.include <bsd.port.mk>
