# Created by: Marc Fonvieille <blackend@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/misc/freebsd-doc-pt/Makefile 354559 2014-05-19 16:43:45Z blackend $

CATEGORIES=	misc docs
PKGNAMEPREFIX=	pt-

MAINTAINER=	doceng@FreeBSD.org
COMMENT=	Portuguese translation of the FreeBSD Documentation Project

MASTERDIR=	${.CURDIR}/../freebsd-doc-en
PLIST=		${.CURDIR}/pkg-plist

DOCLANG=	pt_BR.ISO8859-1
DOCLANG_PREFIX=	pt_BR

.include "${MASTERDIR}/Makefile"
