# Created by: will
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Algorithm-Diff/Makefile 379117 2015-02-16 21:26:34Z adamw $

PORTNAME=	Algorithm-Diff
PORTVERSION=	1.1903
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl interface to compute differences between two objects

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
