# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-highline/Makefile 399038 2015-10-10 23:11:58Z sunpoet $

PORTNAME=	highline
PORTVERSION=	1.7.8
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	High-level IO library for command-line interfaces

LICENSE=	GPLv2 RUBY
LICENSE_COMB=	dual
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
