# Created by: Kirill Ponomarew <ponomarew@oberon.net>
# $FreeBSD: tags/RELEASE_10_3_0/www/ffproxy/Makefile 381078 2015-03-12 10:40:36Z amdmi3 $

PORTNAME=	ffproxy
PORTVERSION=	1.6
CATEGORIES=	www
MASTER_SITES=	http://${PORTNAME}.sourceforge.net/${PORTNAME}/ \
		http://www.sourcefiles.org/System/Daemons/Proxy/ \
		http://www.nevm.de/${PORTNAME}/ \
		http://faith.eu.org/${PORTNAME}/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Filtering HTTP proxy server

LICENSE=	GPLv2 # or later
LICENSE_FILE=	${WRKSRC}/COPYING

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
