# $FreeBSD: tags/RELEASE_10_3_0/www/p5-Plack-Middleware-CrossOrigin/Makefile 403529 2015-12-11 13:42:20Z miwi $

PORTNAME=	Plack-Middleware-CrossOrigin
PORTVERSION=	0.012
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	jeremybbaggs@gmail.com
COMMENT=	Plack Middleware headers to allow Cross-Origin Resource Sharing

LICENSE=	GPLv1
LICENSE_FILE=	${WRKSRC}/LICENSE

BUILD_DEPENDS=	p5-Plack>=0:${PORTSDIR}/www/p5-Plack
RUN_DEPENDS=	p5-Plack>=0:${PORTSDIR}/www/p5-Plack

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
