# Created by: SimaMoto,RyoTa <liangtai.s4@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/misc/gimp-help-sv/Makefile 342129 2014-02-01 12:49:26Z makc $

CATEGORIES=	misc graphics

MAINTAINER=	liangtai.s16@gmail.com
COMMENT=	The GIMP User Manual in Swedish

LICENSE=	GFDL

MASTERDIR=	${.CURDIR}/../gimp-help-en

DOCLANG=	sv

.include "${MASTERDIR}/Makefile"
