# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: tags/RELEASE_10_3_0/www/twiki-NewUserPlugin/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	NewUserPlugin
SVNREV=		17515
MASTER_SITES=	http://protey.ru/freebsd/distfiles/ \
		LOCAL/skv

COMMENT=	Create user's topic for externally authenticated users

.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
