# $FreeBSD: tags/RELEASE_10_3_0/www/py-plone.intelligenttext/Makefile 405764 2016-01-11 05:23:46Z rm $

PORTNAME=	plone.intelligenttext
PORTVERSION=	2.1.0
CATEGORIES=	www python zope
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=	zope

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Transforms from text/x-web-intelligent to text/html

LICENSE=	GPLv2

NO_ARCH=	yes
USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
