# Created by: Joseph Benden <joe@thrallingpenguin.com>
# $FreeBSD: tags/RELEASE_10_3_0/www/rubygem-wasabi/Makefile 402051 2015-11-20 09:16:35Z sunpoet $

PORTNAME=	wasabi
PORTVERSION=	1.0.0
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	joe@thrallingpenguin.com
COMMENT=	Library for simple WSDL parsing

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

RUN_DEPENDS=	rubygem-nokogiri>=1.6.1:${PORTSDIR}/textproc/rubygem-nokogiri

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
