# Created by: John Merryweather Cooper et al
# $FreeBSD: tags/RELEASE_10_3_0/devel/fpc-gdbint/Makefile 403082 2015-12-05 23:29:36Z marino $

CATEGORIES=	devel
PKGNAMESUFFIX=	-gdbint

MAINTAINER=	freebsd-fpc@FreeBSD.org
COMMENT=	Free Pascal unit providing interface to gdb

USE_FPC=	yes

MASTERDIR=	${.CURDIR}/../../lang/fpc
WRKUNITDIR=	${FPCSRCDIR}/packages/${PKGNAMESUFFIX:S/-//}
EXTRACTUNITDIR=	${WRKUNITDIR}

.include "${MASTERDIR}/Makefile"
