# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/multimedia/gstreamer-plugins-mpeg2enc/Makefile 367888 2014-09-10 20:50:31Z gerald $
#   $MCom: ports/multimedia/gstreamer-plugins-mpeg2enc/Makefile,v 1.5 2008/03/19 14:05:37 ahze Exp $

PORTREVISION=	2
CATEGORIES=	multimedia

COMMENT=	Gstreamer mpeg encoder plugin

GST_PLUGIN=	mpeg2enc

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
