# Created by: Lars Thegler <lars@thegler.dk>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-File-Path-Expand/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	File-Path-Expand
PORTVERSION=	1.02
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Expand filenames

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
