# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Filesys-Notify-Simple/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Filesys-Notify-Simple
PORTVERSION=	0.12
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:MIYAGAWA
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension for simple and dumb file system watcher

USES=	perl5
USE_PERL5=	configure

.include <bsd.port.mk>
