# Created by: Dmitry Sivachenko <demon@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Tree-Simple/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Tree-Simple
PORTVERSION=	1.23
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	demon@FreeBSD.org
COMMENT=	Simple tree object

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-Test-Exception>=0.15:${PORTSDIR}/devel/p5-Test-Exception

USES=		perl5 tar:tgz
USE_PERL5=	configure

.include <bsd.port.mk>
