# Created by: Dryice Liu <dryice@dryice.name>
# $FreeBSD: tags/RELEASE_10_3_0/www/py-routes/Makefile 376109 2015-01-03 08:41:20Z mva $

PORTNAME=	routes
PORTVERSION=	2.0
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP/source/R/Routes
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	Routes-${PORTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Routing package for Python that matches URLs to dicts and vice versa

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
