# Created by: Mike Heffner <mikeh@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/net-p2p/napshare/Makefile 368108 2014-09-13 15:11:27Z tijl $

PORTNAME=	napshare
PORTVERSION=	1.3
PORTREVISION=	2
CATEGORIES=	net-p2p
MASTER_SITES=	SF/${PORTNAME}/NapShare%20V${PORTVERSION}/Linux

MAINTAINER=	ports@FreeBSD.org
COMMENT=	GTK based Gnutella client

USES=		gmake
USE_GNOME=	gtk12
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
