# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Stream-Buffered/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Stream-Buffered
PORTVERSION=	0.03
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension for temporary buffer to save bytes

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	YES

.include <bsd.port.mk>
