# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-EnthoughtBase/Makefile 401096 2015-11-09 12:59:03Z antoine $

PORTNAME=	EnthoughtBase
PORTVERSION=	3.1.0
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	http://enthought.com/repo/ets/ \
		CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Core Packages for the Enthought Tool Suite

BROKEN=		unfetchable

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
