# $FreeBSD: tags/RELEASE_10_3_0/net/p5-POSIX-Socket/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	POSIX-Socket
PORTVERSION=	0.09
PORTREVISION=	1
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension for POSIX socket low-level interface

USES=	perl5
USE_PERL5=	configure

.include <bsd.port.mk>
