# Created by: Felippe de Meirelles Motta <lippemail@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-ExtUtils-Manifest/Makefile 399249 2015-10-14 11:04:10Z culot $

PORTNAME=	ExtUtils-Manifest
PORTVERSION=	1.70
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:ETHER
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Utilities to write and check a MANIFEST file

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
