# Created by: Pete Fritchman <petef@databits.net>
# $FreeBSD: tags/RELEASE_10_3_0/misc/p5-Geo-Weather/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Geo-Weather
PORTVERSION=	1.41
PORTREVISION=	1
CATEGORIES=	misc perl5 geography
MASTER_SITES=	CPAN \
		ftp://ftp.innercite.com/pub/perl/
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module to retrieve weather information from weather.com

RUN_DEPENDS=	p5-libwww>=0:${PORTSDIR}/www/p5-libwww

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
