# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/pear-Horde_Service_UrlShortener/Makefile 369674 2014-09-30 22:14:59Z bapt $

PORTNAME=	Horde_Service_UrlShortener
PORTVERSION=	2.0.1
CATEGORIES=	www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde URL shortening services interface

USES=	horde
USE_HORDE_RUN=	Horde_Exception \
		Horde_Http \
		Horde_Url

.include <bsd.port.mk>
