# Created by: Lars Thegler <lth@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Devel-TraceCalls/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Devel-TraceCalls
PORTVERSION=	0.04
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Track calls to subs, classes, and object instances

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
