# $FreeBSD: tags/RELEASE_10_3_0/x11/xlsatoms/Makefile 399842 2015-10-20 13:48:10Z kwm $

PORTNAME=	xlsatoms
PORTVERSION=	1.1.2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	List interned atoms defined on a server

LICENSE=	MIT

XORG_CAT=	app
USE_XORG=	x11 xmuu

PLIST_FILES=	bin/xlsatoms man/man1/xlsatoms.1.gz

.include <bsd.port.mk>
