# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/tk-aspell/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	${DICT}-aspell
DISTVERSION=	5-tk-0.01-0
PORTREVISION=	1
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Turkmen dictionary

DICT=	 	tk

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
