# Created by: Holger Lamm <holger@e-gitt.net> and Mario S F Ferreira <lioux@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/net-p2p/mldonkey-core/Makefile 362404 2014-07-21 08:07:26Z leeym $

OPTIONS_EXCLUDE=GUI

COMMENT=	Client 'core' for the MLDonkey peer-to-peer network

MASTERDIR=	${.CURDIR}/../mldonkey

.include "${MASTERDIR}/Makefile"
