# Created by: Andrew Pantyukhin <infofarmer@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/deskutils/py-vobject/Makefile 371173 2014-10-19 08:50:17Z mva $

PORTNAME=	vobject
PORTVERSION=	0.8.1c
PORTREVISION=	2
CATEGORIES=	deskutils python
MASTER_SITES=	http://vobject.skyhouseconsulting.com/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jun-g@daemonfreaks.com
COMMENT=	ICalendar library

RUN_DEPENDS=	py*-dateutil>=1.1:${PORTSDIR}/devel/py-dateutil

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
