# Created by: Andrew Pantyukhin <infofarmer@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/xpi-quickproxy/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	quickproxy
PORTVERSION=	2009.07.19
DISTVERSIONSUFFIX=	-fx
CATEGORIES=	www

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Statusbar button to quickly turn the proxy on and off

XPI_ID=		{d5ea4520-61a1-11da-8cd6-0800200c9a66}
XPI_NUM=	1557
XPI_FILES=	chrome/quickproxy.jar chrome.manifest install.rdf
XPI_DIRS=	chrome

.include "${.CURDIR}/../xpi-adblock/Makefile.xpi"
.include <bsd.port.mk>
