# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Test-Identity/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Test-Identity
PORTVERSION=	0.01
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Assert the referential identity of a reference

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
