# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/math/fftw3-long/Makefile 347093 2014-03-05 03:17:04Z bf $
#    $MCom: ports-experimental/math/fftw3-long/Makefile,v 1.1 2006/03/28 00:08:58 ahze Exp $

COMMENT=	Fast Discrete Fourier Transform (Long Double Precision C Routines)

FFTW3_FLAVOR=	long
MASTERDIR=	${.CURDIR}/../../math/fftw3

.include "${MASTERDIR}/Makefile"
