# Created by: Zane C, Bowers <vvelox@vvelox.net>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Dir-Watch/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Dir-Watch
PORTVERSION=	0.0.0
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:VVELOX
PKGNAMEPREFIX=	p5-

MAINTAINER=	vvelox@vvelox.net
COMMENT=	Watches the current directory for file/dir additions or removals

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
