# $FreeBSD: tags/RELEASE_10_3_0/www/rubygem-jquery-atwho-rails/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	jquery-atwho-rails
PORTVERSION=	1.1.0
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	jQuery plugin that implement GitHub-like mentions

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
