# Created by: "Waitman Gobble" <uzimac@da3m0n8t3r.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/libfortuna/Makefile 384908 2015-04-28 15:16:09Z bdrewery $

PORTNAME=	libfortuna
PORTVERSION=	0.1.1
CATEGORIES=	devel

MAINTAINER=	waitman@waitman.net
COMMENT=	Fortuna PRNG Library

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYRIGHT

USE_GITHUB=	yes
USE_LDCONFIG=	yes
GH_ACCOUNT=	waitman
GH_TAGNAME=	11cbd88

.include <bsd.port.mk>
