# Created by: will
# $FreeBSD: tags/RELEASE_10_3_0/archivers/p5-Mac-Macbinary/Makefile 395329 2015-08-26 02:00:19Z amdmi3 $

PORTNAME=	Mac-Macbinary
PORTVERSION=	0.06
PORTREVISION=	1
CATEGORIES=	archivers perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module that can extract info from Macbinary files

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
