# Created by: kevit
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Template-Plugin-XML-Escape/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Template-Plugin-XML-Escape
PORTVERSION=	0.02
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	simarg@gmail.com
COMMENT=	Escape variables to suit being placed into XML

BUILD_DEPENDS=	p5-Template-Toolkit>=2.20:${PORTSDIR}/www/p5-Template-Toolkit
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
