# Created by: joerg
# $FreeBSD: tags/RELEASE_10_3_0/games/xonix/Makefile 403659 2015-12-13 09:41:22Z bapt $

PORTNAME=	xonix
PORTVERSION=	1.4
PORTREVISION=	3
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.interface-business.de/pub/outgoing/

MAINTAINER=	joerg@FreeBSD.org
COMMENT=	Try to win land without colliding with `flyers' and `eaters'

BROKEN=		unfetchable
USES=		imake
USE_XORG=	xaw

.include <bsd.port.mk>
