# Created by: Will Andrews <will@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-LockFile-Simple/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	LockFile-Simple
PORTVERSION=	0.2.8
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-${PORTVERSION:R}0${PORTVERSION:E}

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module implementing simple file locking

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
