# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-pkg-config/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	pkg-config
PORTVERSION=	1.1.6
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	pkg-config implementation for Ruby

LICENSE=	LGPL21 LGPL3
LICENSE_COMB=	dual

USES=		pkgconfig
NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
USE_RAKE=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
