# Created by: TAKAHASHI Kaoru <kaoru@kaisei.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-FreeBSD-i386-Ptrace/Makefile 377180 2015-01-16 15:35:05Z sunpoet $

PORTNAME=	FreeBSD-i386-Ptrace
PORTVERSION=	0.05
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module for ptrace on FreeBSD-i386

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
ONLY_FOR_ARCHS=	i386

.include <bsd.port.mk>
