# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-File-LibMagic/Makefile 378162 2015-01-30 16:35:51Z tj $

PORTNAME=	File-LibMagic
PORTVERSION=	1.09
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tj@FreeBSD.org
COMMENT=	Nice wrapper for libmagic

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5 gmake
USE_PERL5=	configure
MAKE_JOBS_UNSAFE=yes

.include <bsd.port.mk>
