# BSD Makefile for librs232
#
# $FreeBSD: tags/RELEASE_10_3_0/comms/librs232/files/Makefile 373861 2014-12-04 06:49:58Z kevlo $
#

SRCS=	rs232.c

# Includes
INCS=	rs232.h
INCSDIR=${PREFIX}/include

# Libraries
LIB=	rs232
SHLIB_MAJOR=	1
LIBDIR=	${PREFIX}/lib
NO_PROFILE=	YES

.include <bsd.lib.mk>
