# $FreeBSD: tags/RELEASE_10_3_0/games/rubygem-fortune_gem/Makefile 402257 2015-11-23 03:24:01Z araujo $

PORTNAME=	fortune_gem
PORTVERSION=	0.0.8
CATEGORIES=	games rubygems
MASTER_SITES=	RG

MAINTAINER=	mose@mose.com
COMMENT=	Unix fortune program, implemented as a ruby gem

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
PLIST_FILES=	bin/fortune_gem

.include <bsd.port.mk>
