# $FreeBSD: tags/RELEASE_10_3_0/misc/raspbsd-led/Makefile 400970 2015-11-07 03:05:33Z brd $

PORTNAME=	raspbsd-led
PORTVERSION=	0.1
DISTVERSIONPREFIX=	v
CATEGORIES=	misc

MAINTAINER=	brd@FreeBSD.org
COMMENT=	Misc LED programs for ARM boards

USE_GITHUB=	yes
GH_ACCOUNT=	raspbsd
ONLY_FOR_ARCHS=	armv6
PLIST_FILES=	sbin/flash-heartbeat-led

.include <bsd.port.mk>
