# Created by: Xavier Beaudouin <kiwi@oav.net>
# $FreeBSD: tags/RELEASE_10_3_0/misc/p5-Test-Dir/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Test-Dir
PORTVERSION=	1.014
PORTREVISION=	1
CATEGORIES=	misc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kiwi@oav.net
COMMENT=	Test directory attributes

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
