# Created by: thinker <thinker@branda.to>
# $FreeBSD: tags/RELEASE_10_3_0/www/clearsilver-python/Makefile 341701 2014-01-29 09:02:29Z miwi $

WITH_PYTHON=	yes

MASTERDIR=	${.CURDIR}/../clearsilver

.include "${MASTERDIR}/Makefile"
