# Created by: alexander smishlajev
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-decoratortools/Makefile 364929 2014-08-15 03:43:54Z sunpoet $

PORTNAME=	DecoratorTools
PORTVERSION=	1.8
PORTREVISION=	2
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Class, function, and metaclass decorators

LICENSE=	PSFL ZPL21
LICENSE_COMB=	dual

USE_PYTHON=	autoplist distutils
USES=		python:2 zip

.include <bsd.port.mk>
