# Created by: ijliao
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Sort-Maker/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Sort-Maker
DISTVERSION=	0.06
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Simple way to make efficient sort subs

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
