# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-Console_Color/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Console_Color
PORTVERSION=	1.0.3
CATEGORIES=	devel www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PEAR use ANSI console colors

USES=	pear

.include <bsd.port.mk>
