# Created by: mm@FreeBSD.org
# $FreeBSD: tags/RELEASE_10_3_0/graphics/libwmf-nox11/Makefile 351973 2014-04-23 20:44:14Z antoine $

PKGNAMESUFFIX=	-nox11
PORTSCOUT=	ignore:1

CONFLICTS=	libwmf-[0-9]*
MASTERDIR=	${.CURDIR}/../libwmf
OPTIONS_EXCLUDE=	X11
OPTIONS_FILE_UNSET=	X11

.include        "${MASTERDIR}/Makefile"
