# $FreeBSD: tags/RELEASE_10_3_0/net/p5-POSIX-getpeername/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	POSIX-getpeername
PORTVERSION=	0.01
PORTREVISION=	1
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension to provide getpeername(2)

USES=	perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
