# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/pear-Horde_Text_Diff/Makefile 376829 2015-01-12 14:54:44Z mm $

PORTNAME=	Horde_Text_Diff
PORTVERSION=	2.1.1
CATEGORIES=	textproc www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde engine for performing and rendering text diffs

USES=	horde
USE_HORDE_RUN=	Horde_Exception \
		Horde_Util

.include <bsd.port.mk>
