# Created by: Bill Brinzer <bill.brinzer@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Capture-Tiny/Makefile 402431 2015-11-26 01:01:06Z sunpoet $

PORTNAME=	Capture-Tiny
PORTVERSION=	0.28
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:DAGOLDEN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bill.brinzer@gmail.com
COMMENT=	Capture STDOUT and STDERR from Perl, XS, or external programs

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

TEST_DEPENDS=	p5-Inline>=0.50:${PORTSDIR}/devel/p5-Inline

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
