# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/math/p5-Math-VectorReal/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Math-VectorReal
PORTVERSION=	1.02
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl Module to handle 3D Vector Mathematics

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
