# Created by: Alexander Logvinov <ports@logvinov.com>
# $FreeBSD: tags/RELEASE_10_3_0/russian/rubygem-rutils/Makefile 388760 2015-06-07 20:41:18Z sunpoet $

PORTNAME=	rutils
PORTVERSION=	2.0.0
CATEGORIES=	russian devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Simple processing of Russian strings

LICENSE=	MIT

DEPRECATED=	Deprecated by upstream

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
