# Created by: Yuri Victorovich <yuri@rawbw.com>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/py-hexdump/Makefile 386176 2015-05-12 22:49:50Z vanilla $

PORTNAME=	hexdump
PORTVERSION=	3.2
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	yuri@rawbw.com
COMMENT=	Print binary in hex format

LICENSE=	unknown
LICENSE_NAME=	Public Domain
LICENSE_TEXT=	This software us in the public domain
LICENSE_PERMS=	dist-mirror dist-sell pkg-mirror pkg-sell auto-accept

WRKSRC=		${WRKDIR}
USES=		python zip
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
