# Created by: Antonio Carlos Venancio Junior (<antonio@php.net>)
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-Validate/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Validate
PORTVERSION=	0.8.5
CATEGORIES=	devel www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PEAR Validation class

USES=	pear

.include <bsd.port.mk>
