# Created by: Alexander Yerenkow <yerenkow@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/vietnamese/x-unikey/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	x-unikey
PORTVERSION=	1.0.4
CATEGORIES=	vietnamese textproc
MASTER_SITES=	SF/unikey/${PORTNAME}/${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Vietnamese input method for X

USES=		tar:bzip2
USE_XORG=	x11
GNU_CONFIGURE=	yes

PLIST_FILES=	bin/unikey bin/ukxim

.include <bsd.port.mk>
