# Created by: Kubilay Kocak <koobs@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/security/py-cpe/Makefile 365172 2014-08-17 11:18:54Z koobs $

PORTNAME=	cpe
PORTVERSION=	1.1.0
CATEGORIES=	security python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	koobs@FreeBSD.org
COMMENT=	Common Platform Enumeration (CPE) for Python

LICENSE=	GPLv3
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python:-2.7
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
