# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Parallel-Fork-BossWorker/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Parallel-Fork-BossWorker
PORTVERSION=	0.05
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Easily create forking queue processing applications

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
