# Created by: Neil Blakey-Milner <nbm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/py-scgi/Makefile 376109 2015-01-03 08:41:20Z mva $

PORTNAME=	scgi
PORTVERSION=	1.14
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	http://python.ca/scgi/releases/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jlaffaye@FreeBSD.org
COMMENT=	Python server implementation of the Simple Common Gateway Protocol

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
