# Created by: Vladimir Kondratiev <wulf@mail.mipt.ru>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-debugger-linecache/Makefile 396012 2015-09-03 16:25:18Z sunpoet $

PORTNAME=	debugger-linecache
PORTVERSION=	1.2.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby module for reading and caching lines

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
