# Created by: Dima Panov <fluffy@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/net/cagibi/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	cagibi
PORTVERSION=	0.2.0
CATEGORIES=	net devel
MASTER_SITES=	KDE/stable/${PORTNAME}

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KDE SSDP/uPNP proxy

USES=		cmake tar:bzip2
USE_KDE4=	automoc4
USE_QT4=	corelib network xml dbus \
		qmake_build moc_build rcc_build uic_build

.include <bsd.port.mk>
