# $FreeBSD: tags/RELEASE_10_3_0/devel/R-cran-gbm/Makefile 367888 2014-09-10 20:50:31Z gerald $

PORTNAME=	gbm
DISTVERSION=	2.0-8
PORTREVISION=	6
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Extensions to AdaBoost algorithm

LICENSE=	GPLv2

USES=	cran:auto-plist

.include <bsd.port.mk>
