# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Text-Brew/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Text-Brew
PORTVERSION=	0.02
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension for the Brew edit distance

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
