# Created by: Andrew Pantyukhin <infofarmer@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Unicode-CheckUTF8/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Unicode-CheckUTF8
DISTVERSION=	1.03
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Check if scalar is valid UTF-8

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
