# Created by: Gabor Kovesdan
# $FreeBSD: tags/RELEASE_10_3_0/security/p5-Crypt-HCE_MD5/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Crypt-HCE_MD5
PORTVERSION=	0.70
PORTREVISION=	1
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ashish@FreeBSD.org
COMMENT=	Perl extension implementing one way hash chaining encryption using MD5

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
