# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/graphics/rubygem-emoji/Makefile 391760 2015-07-11 15:28:47Z sunpoet $

PORTNAME=	emoji
PORTVERSION=	1.0.5
CATEGORIES=	graphics rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby gem for emoji

LICENSE=	MIT

RUN_DEPENDS=	rubygem-json>=0:${PORTSDIR}/devel/rubygem-json

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
