# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-prefork/Makefile 381151 2015-03-12 23:00:02Z adamw $

PORTNAME=	prefork
PORTVERSION=	1.04
PORTREVISION=	2
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:ADAMK
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Optimize module loading across forking and non-forking scenarios

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
