# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Set-NestedGroups/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Set-NestedGroups
PORTVERSION=	0.01
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl module for grouped data eg ACL's, city/state/country etc

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
