# $FreeBSD: releng/10.3/usr.sbin/bsdconfig/networking/Makefile 279611 2015-03-05 00:34:33Z dteske $

NO_OBJ=

SUBDIR= include share

FILESDIR=	${LIBEXECDIR}/bsdconfig/120.networking
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	defaultrouter devices hostname nameservers networking

.include <bsd.prog.mk>
