# Created by: Alexander Wittig <alexander@wittig.name>
# $FreeBSD: tags/RELEASE_10_3_0/mail/squirrelmail-change_ldappass-plugin/Makefile 366415 2014-08-28 15:16:49Z adamw $

PORTNAME=	change_ldappass
PORTVERSION=	2.2
PORTREVISION=	6
CATEGORIES=	mail www
DISTNAME=	${PORTNAME}-${PORTVERSION}-1.4.0

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Allows users to change their passwords stored in LDAP Tree

LICENSE=	GPLv2

USE_PHP+=	ldap
USES=		gettext

USE_GENERIC_PKGMESSAGE=	yes

.include "${.CURDIR}/../squirrelmail/bsd.squirrelmail.mk"
.include <bsd.port.mk>
