# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-Horde_Injector/Makefile 376829 2015-01-12 14:54:44Z mm $

PORTNAME=	Horde_Injector
PORTVERSION=	2.0.4
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde dependency injection container

USES=	horde
USE_HORDE_RUN=	Horde_Exception

.include <bsd.port.mk>
