# Created by: Murilo Opsfelder <mopsfelder@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-ipaddr/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	ipaddr
PORTVERSION=	2.1.10
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	GOOGLE_CODE
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	mopsfelder@gmail.com
COMMENT=	Google open source IPv4/IPv6 manipulation library in Python

PROJECTHOST=	ipaddr-py
USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
