# Created by: Mathieu Arnold <m@absolight.net>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Pod-Escapes/Makefile 376759 2015-01-11 13:29:52Z sunpoet $

PORTNAME=	Pod-Escapes
PORTVERSION=	1.07
CATEGORIES=	textproc devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	For resolving Pod E<...> sequences

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
