# Created by: nork@FreeBSD.org
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-DB_File-Lock/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	DB_File-Lock
PORTVERSION=	0.05
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module to use the DB_File with Lock

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
