# Created by: James FitzGibbon <jfitz@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-File-BasicFlock/Makefile 386075 2015-05-11 12:04:18Z mat $

PORTNAME=	File-BasicFlock
PORTVERSION=	98.1202
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 module for file locking with flock

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
