# Created by: vanilla
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-ExtUtils-XSBuilder/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	ExtUtils-XSBuilder
PORTVERSION=	0.28
PORTREVISION=	2
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Autogenerating XS-glue Code

RUN_DEPENDS=	p5-Tie-IxHash>=0:${PORTSDIR}/devel/p5-Tie-IxHash
BUILD_DEPENDS=	${RUN_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
