# Created by: clutton mbsd@isgroup.com.ua
# $FreeBSD: tags/RELEASE_10_3_0/www/xpi-pentadactyl/Makefile 380854 2015-03-09 14:53:39Z robak $

PORTNAME=	pentadactyl
PORTVERSION=	20131128
CATEGORIES=	www
MASTER_SITES=	GOOGLE_CODE
PROJECTHOST=	dactyl

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Firefox for Vim and Links addicts

XPI_NUM=	235854
XPI_ID=		pentadactyl@dactyl.googlecode.com

.include "${.CURDIR}/../xpi-adblock/Makefile.xpi"
.include <bsd.port.mk>
