# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/graphics/R-cran-colorspace/Makefile 389333 2015-06-13 08:34:12Z tota $

PORTNAME=	colorspace
DISTVERSION=	1.2-6
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Color Space Manipulation

LICENSE=	BSD3CLAUSE

USES=	cran:auto-plist

.include <bsd.port.mk>
