# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/x11/xproto/Makefile 399835 2015-10-20 13:43:07Z kwm $

PORTNAME=	xproto
PORTVERSION=	7.0.28
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X11 protocol headers

XORG_CAT=	proto

CONFIGURE_ARGS+=--disable-specs --without-fop --without-xmlto --without-xsltproc

.include <bsd.port.mk>
