# Created by: Mons Anderson <mons@cpan.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-ex-lib/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	ex-lib
PORTVERSION=	0.90
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	mons@cpan.org
COMMENT=	Relative use lib in absolute way

RUN_DEPENDS=	p5-lib-abs>=0.90:${PORTSDIR}/devel/p5-lib-abs

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
