# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/converters/p5-Encoding-FixLatin/Makefile 400843 2015-11-05 11:03:12Z tobez $

PORTNAME=	Encoding-FixLatin
PORTVERSION=	1.04
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:GRANTM
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Takes mixed encoding input and produces UTF-8 output

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
