# Created by: James Bailie <jimmy@mammothcheese.ca>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pty/Makefile 344859 2014-02-18 10:26:43Z ehaupt $

PORTNAME=	pty
PORTVERSION=	1.2
CATEGORIES=	devel
MASTER_SITES=	http://www.mammothcheese.ca/

MAINTAINER=	jimmy@mammothcheese.ca
COMMENT=	Helps debug programs which fiddle with their tty settings

PLIST_FILES=	bin/pty man/man1/pty.1.gz

.include <bsd.port.mk>
