# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/security/pear-Horde_Oauth/Makefile 369674 2014-09-30 22:14:59Z bapt $

PORTNAME=	Horde_Oauth
PORTVERSION=	1.0.2
CATEGORIES=	security www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde OAuth client/server

USES=	horde
USE_HORDE_RUN=	Horde_Exception Horde_Http
USE_PHP=	hash openssl

.include <bsd.port.mk>
