# Created by: Ruben van Staveren
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-threads-shared/Makefile 389670 2015-06-15 05:43:31Z culot $

PORTNAME=	threads-shared
PORTVERSION=	1.48
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:JDHEDDEN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Share data structures between threads

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
