# Created by: Eugene Grosbein <ports@grosbein.net>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-application/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	application
PORTVERSION=	1.2.9
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	python-${PORTNAME}-${PORTVERSION}

MAINTAINER=	ports@grosbein.net
COMMENT=	Basic building blocks for python applications

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
