# Created by: rokaz
# $FreeBSD: tags/RELEASE_10_3_0/security/belier/Makefile 371453 2014-10-24 16:50:42Z mva $

PORTNAME=	belier
PORTVERSION=	1.2
PORTREVISION=	1
CATEGORIES=	security net
MASTER_SITES=	http://www.ohmytux.com/belier/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	romain.garbage@gmail.com
COMMENT=	easily cross several machines with ssh

RUN_DEPENDS=	expect>=5.42.1:${PORTSDIR}/lang/expect

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
