# $FreeBSD: tags/RELEASE_10_3_0/devel/R-cran-Hmisc/Makefile 367888 2014-09-10 20:50:31Z gerald $

PORTNAME=	Hmisc
DISTVERSION=	3.10-1
PORTREVISION=	7
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Harrell Miscellaneous functions useful for data analysis

LICENSE=	GPLv2

USES=	cran:auto-plist

.include <bsd.port.mk>
