# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/R-cran-yaml/Makefile 393711 2015-08-08 05:23:28Z tota $

PORTNAME=	yaml
PORTVERSION=	2.1.13
CATEGORIES=	textproc
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Methods to convert R data to YAML and back

LICENSE=	BSD3CLAUSE

USES=	cran:auto-plist

.include <bsd.port.mk>
