# $FreeBSD: tags/RELEASE_10_3_0/converters/p5-JSON/Makefile 402114 2015-11-21 02:09:18Z sunpoet $

PORTNAME=	JSON
PORTVERSION=	2.90
PORTREVISION=	1
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension to convert to JSON (JavaScript Object Notation)

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

CONFLICTS=	p5-JSON-1.* p5-JSON1-*
NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
