# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: tags/RELEASE_10_3_0/multimedia/libdc1394/Makefile 393429 2015-08-02 15:03:19Z tijl $

PORTNAME=	libdc1394
PORTVERSION=	2.2.3
PORTREVISION=	1
CATEGORIES=	multimedia
MASTER_SITES=	SF/${PORTNAME}/${PORTNAME}-2/${PORTVERSION}/

MAINTAINER=	multimedia@FreeBSD.org
COMMENT=	1394-based DC Control Library

LICENSE=	LGPL21

GNU_CONFIGURE=	yes
USES=	libtool pathfix
USE_LDCONFIG=	yes
INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
