# $FreeBSD: tags/RELEASE_10_3_0/textproc/rubygem-zmq/Makefile 387236 2015-05-24 00:11:05Z sunpoet $

PORTNAME=	zmq
PORTVERSION=	2.1.4
PORTREVISION=	1
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby ZeroMQ gem

LICENSE=	LGPL3

LIB_DEPENDS=	libzmq.so:${PORTSDIR}/net/libzmq2

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
