# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/graphics/gstreamer-plugins-opencv/Makefile 384092 2015-04-16 08:05:47Z kwm $

PORTREVISION=	3
CATEGORIES=	graphics

COMMENT=	Gstreamer opencv real time computer vision plugin

GST_PLUGIN=	opencv

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
