# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/audio/gstreamer-plugins-soundtouch/Makefile 403855 2015-12-16 09:39:40Z jbeich $
#   $MCom: ports/audio/gstreamer-plugins-soundtouch/Makefile,v 1.3 2008/03/19 14:05:32 ahze Exp $

PORTREVISION=	2
CATEGORIES=	audio

COMMENT=	GStreamer soundtouch plugin

GST_PLUGIN=	soundtouch

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
