# $FreeBSD: releng/10.3/usr.sbin/bsdconfig/ttys/Makefile 279611 2015-03-05 00:34:33Z dteske $

NO_OBJ=

SUBDIR= include

FILESDIR=	${LIBEXECDIR}/bsdconfig/150.ttys
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	ttys

.include <bsd.prog.mk>
