# Created by: Simun Mikecin <numisemis@yahoo.com>
# $FreeBSD: tags/RELEASE_10_3_0/graphics/pear-Image_Canvas/Makefile 369089 2014-09-23 16:37:41Z bapt $

PORTNAME=	Image_Canvas
PORTVERSION=	0.3.2
PORTREVISION=	1
CATEGORIES=	graphics www pear

MAINTAINER=	numisemis@yahoo.com
COMMENT=	OO PEAR common interface to image drawing

RUN_DEPENDS=	${PEARDIR}/Image/Color.php:${PORTSDIR}/graphics/pear-Image_Color

USE_PHP=	gd
USES=		dos2unix pear

.include <bsd.port.mk>
