# Created by: Satoshi Asami <asami@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/print/pkfonts118/Makefile 357252 2014-06-10 03:40:19Z vanilla $

RESOLUTION=	118
MASTERDIR=	${.CURDIR}/../pkfonts300

.include	"${MASTERDIR}/Makefile"
