# Created by: roam@FreeBSD.org
# $FreeBSD: tags/RELEASE_10_3_0/misc/rname/Makefile 395483 2015-08-28 13:39:56Z amdmi3 $

PORTNAME=	rname
PORTVERSION=	1.0
PORTREVISION=	1
CATEGORIES=	misc
MASTER_SITES=	http://devel.ringlet.net/sysutils/rname/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Execute a program with a fake name

WRKSRC=		${WRKDIR}/${PORTNAME}
USES=		gmake

OPTIONS_DEFINE=	DOCS

DOCS_INSTALL_TARGET=	install install-doc

.include <bsd.port.mk>
