# Created by: Lev Serebryakov <lev@serebryakov.spb.ru>
# $FreeBSD: tags/RELEASE_10_3_0/devel/mingw32-binutils/Makefile 377619 2015-01-21 17:27:54Z bapt $

PORTEPOCH=	1
PKGNAMEPREFIX=	mingw32-

MAINTAINER=	cyberbotx@cyberbotx.com
COMMENT=	GNU Binutils for Windows cross-development

MASTERDIR=	${.CURDIR}/../binutils
PLIST=		${.CURDIR}/pkg-plist

BUTARGET=	${PKGNAMEPREFIX:S/-$//}

INFO=		as bfd binutils gprof ld
INFO_PATH=	${BUTARGET}/info

.include "${MASTERDIR}/Makefile"
