# $FreeBSD: tags/RELEASE_10_3_0/lang/gcc-aux/Makefile.version 402635 2015-11-30 00:15:39Z marino $

GCC_BRANCH=		4.9
GCC_POINT=		3
GCC_VERSION=		${GCC_BRANCH}.${GCC_POINT}
SNAPSHOT=		20150626
MAIN_PR=		0
UTIL_PR=		0
ARMV7_PR=		1
X86_PR=			0

# Snapshot naming pattern
#IDENTIFICATION=	gcc-${GCC_BRANCH}-${SNAPSHOT}
#MS_SUBDIR=		snapshots/${GCC_BRANCH}-${SNAPSHOT}

# Release naming pattern
IDENTIFICATION=		gcc-${GCC_VERSION}
MS_SUBDIR=		releases/gcc-${GCC_VERSION}
