# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-get_process_mem/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	get_process_mem
PORTVERSION=	0.2.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@michael-fausten.de
COMMENT=	Get memory usage of a process in Ruby

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
