# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-curses/Makefile 392681 2015-07-22 13:55:49Z swills $

PORTNAME=	curses
PORTVERSION=	1.0.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	freebsd@jonathanprice.org
COMMENT=	Ruby binding for curses, ncurses and PDCurses

LICENSE=	RUBY BSD2CLAUSE
LICENSE_COMB=	dual

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
