# $FreeBSD: tags/RELEASE_10_3_0/net-p2p/namecoin-daemon/Makefile 389159 2015-06-11 05:42:58Z pi $

PKGNAMESUFFIX=	-daemon

COMMENT=	A decentralized, open DNS system and general purpose key/value store.

MASTERDIR=	${.CURDIR}/../namecoin

DESCR=		${MASTERDIR}/pkg-descr

SLAVE_PORT=	yes

OPTIONS_EXCLUDE=	X11 DBUS QRCODES

.include "${MASTERDIR}/Makefile"
