# $FreeBSD: tags/RELEASE_10_3_0/devel/py-versiontools/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	versiontools
PORTVERSION=	1.9.1
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	rm@FreeBSD.org
COMMENT=	Smart replacement for plain tuple used in __version__

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
