# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/multimedia/gstreamer-plugins-bz2/Makefile 352119 2014-04-25 12:46:45Z bapt $
#    $MCom: ports/multimedia/gstreamer-plugins-bz2/Makefile,v 1.6 2008/03/19 14:05:35 ahze Exp $

PORTREVISION=	1
CATEGORIES=	multimedia

COMMENT=	Gstreamer bz2 plugin

GST_PLUGIN=	bz2

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
