# Created by: Anders Nordby <anders@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/audio/resid/Makefile 376388 2015-01-06 09:36:21Z ehaupt $

PORTNAME=	resid
PORTVERSION=	0.16
PORTREVISION=	2
CATEGORIES=	audio emulators
MASTER_SITES=	LOCAL/ehaupt

MAINTAINER=	ehaupt@FreeBSD.org
COMMENT=	Cycle-based SID emulator engine

LICENSE=	GPLv2

USES=		libtool
GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes

CONFIGURE_ARGS=		--enable-shared

.include <bsd.port.mk>
