# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/archivers/pear-PHP_Archive/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	PHP_Archive
PORTVERSION=	0.12.0
CATEGORIES=	archivers pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Create and Use PHP Archive files

LICENSE=	PHP301

NO_ARCH=	yes
USES=		pear

.include <bsd.port.mk>
