# Created by: Shell Hung <shell@shellhung.org>
# $FreeBSD: tags/RELEASE_10_3_0/chinese/p5-Date-Chinese/Makefile 390487 2015-06-24 15:16:23Z adamw $

PORTNAME=	Date-Chinese
PORTVERSION=	1.12
PORTREVISION=	1
CATEGORIES=	chinese perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module to calculate dates in the Chinese calendar

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
