# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-IPC-MM/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	IPC-MM
PORTVERSION=	0.03
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl interface to Ralf Engelschall's mm library

LIB_DEPENDS=	libmm.so:${PORTSDIR}/devel/mm

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
