# Created by: will
# $FreeBSD: tags/RELEASE_10_3_0/math/p5-Math-FixedPrecision/Makefile 388088 2015-05-31 13:37:20Z amdmi3 $

PORTNAME=	Math-FixedPrecision
PORTVERSION=	0.21
PORTREVISION=	2
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module that provides decimal math without floating point errors

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
