# Created by: Ade Lovett <ade@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-DateConvert/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	DateConvert
PORTVERSION=	0.16
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN/Date
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Perl5 module to convert dates between any two calendar formats

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
