# Created by: Mike Meyer <mwm@mired.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/py-beautifulsoup32/Makefile 371112 2014-10-18 10:52:53Z rm $

PORTNAME=	beautifulsoup
PORTVERSION=	3.2.1
CATEGORIES=	www python
MASTER_SITES=	http://www.crummy.com/software/BeautifulSoup/bs3/download//3.x/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
PKGNAMESUFFIX=	32
DISTNAME=	BeautifulSoup-${PORTVERSION}

MAINTAINER=	mwm@mired.org
COMMENT=	HTML/XML Parser for Python

USES=		python:2
USE_PYTHON=	autoplist distutils

CONFLICTS=	py[0-9]*-beautifulsoup-3.0.*

.include <bsd.port.mk>
