# Created by: Anish Mistry <amistry@am-productions.biz>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-List-Permutor/Makefile 386075 2015-05-11 12:04:18Z mat $

PORTNAME=	List-Permutor
PORTVERSION=	0.022
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Allow you to process all possible permutations of a list

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
