# $FreeBSD: tags/RELEASE_10_3_0/emulators/mess/Makefile 400117 2015-10-24 11:13:16Z madpilot $

PORTNAME=	mess
MTARGET=	mame
MSUBTARGET=	mess
COMMENT=	Multiple Emulator Super System

MASTERDIR=	${.CURDIR}/../mame
DESCR=		${.CURDIR}/pkg-descr
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
