# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-Horde_Cli/Makefile 376829 2015-01-12 14:54:44Z mm $

PORTNAME=	Horde_Cli
PORTVERSION=	2.0.6
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Command Line Interface API

USES=	horde
USE_HORDE_RUN=	Horde_Support Horde_Translation

.include <bsd.port.mk>
