# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/net/php55-ldap/Makefile 364015 2014-08-04 15:04:08Z ale $

CATEGORIES=	net

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-ldap

.include "${MASTERDIR}/Makefile"
