# $FreeBSD: tags/RELEASE_10_3_0/x11/xlogo/Makefile 351411 2014-04-16 18:28:47Z zeising $

PORTNAME=	xlogo
PORTVERSION=	1.0.4
PORTREVISION=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Displays the X Window System logo

LICENSE=	MIT

XORG_CAT=	app
USE_XORG=	xrender xft xext xt xaw xp xprintutil

.include <bsd.port.mk>
