# $FreeBSD: tags/RELEASE_10_3_0/x11-themes/qtcurve-utils/Makefile 386718 2015-05-18 21:26:50Z makc $

PORTNAME=	qtcurve
PORTREVISION=	0

COMMENT=	QtCurve common files and libraries

QTCURVE_SLAVE=	utils

MASTERDIR=	${.CURDIR}/../qtcurve

.include "${MASTERDIR}/Makefile"
