# Created by: Thomas Gellekum <tg@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/games/xdemineur/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	xdemineur
PORTVERSION=	2.1.1
PORTREVISION=	1
CATEGORIES=	games
MASTER_SITES=	XCONTRIB/games \
		http://www.babafou.eu.org/xdemineur/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Another minesweeper game for the X Window System

USES=		imake
USE_XORG=	xpm
PLIST_FILES=	bin/xdemineur \
		man/man1/xdemineur.1.gz

.include <bsd.port.mk>
