# Created by: Alexey Dokuchaev <danfe@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/math/R-cran-outliers/Makefile 367888 2014-09-10 20:50:31Z gerald $

PORTNAME=	outliers
PORTVERSION=	0.14
PORTREVISION=	5
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Collection of some tests commonly used for identifying outliers

USES=	cran:auto-plist

.include <bsd.port.mk>
