# Created by: Anatoliy Dmytriyev
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Heap/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Heap
PORTVERSION=	0.80
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tolid@tolid.eu.org
COMMENT=	Perl extensions for keeping data partially sorted

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
