# Created by: Jim Pirzyk <pirzyk@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/security/pam_per_user/Makefile 364047 2014-08-04 20:09:10Z amdmi3 $

PORTNAME=	pam_per_user
PORTVERSION=	0.4
PORTREVISION=	1
CATEGORIES=	security
MASTER_SITES=	ftp://ftp.feep.net/pub/software/PAM/pam_per_user/

MAINTAINER=	pirzyk@FreeBSD.org
COMMENT=	PAM module for per-user authentication

USES=		libtool
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
