# $FreeBSD: tags/RELEASE_10_3_0/converters/p5-Convert-Moji/Makefile 392648 2015-07-21 22:24:10Z kuriyama $

PORTNAME=	Convert-Moji
PORTVERSION=	0.07
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension to convert objects to alphabets

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	YES

.include <bsd.port.mk>
