# $FreeBSD: releng/10.3/tests/sys/netinet/Makefile 276486 2014-12-31 23:25:37Z ngie $

TESTSDIR=	${TESTSBASE}/sys/netinet
BINDIR=		${TESTSDIR}

ATF_TESTS_SH=	fibs_test
PROGS=	udp_dontroute
MAN=
WARNS?=	6

.include <bsd.test.mk>
