# Created by: Daniel Harris <dannyboy@subdimension.com>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/fortunelock/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	fortunelock
PORTVERSION=	0.1.2
CATEGORIES=	sysutils
MASTER_SITES=	LOCAL/dannyboy

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Locks a terminal while showing fortunes

USES=		tar:bzip2

PLIST_FILES=	bin/fortunelock man/man1/${PORTNAME}.1.gz

.include <bsd.port.mk>
