# Created by: Geoffroy Desvernay <dgeo@centrale-marseille.fr>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Time-timegm/Makefile 380893 2015-03-10 06:08:19Z vanilla $

PORTNAME=	Time-timegm
PORTVERSION=	0.01
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:PEVANS
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Efficiently compute time from local and GMT time

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
