# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Sub-Prototype/Makefile 381151 2015-03-12 23:00:02Z adamw $

PORTNAME=	Sub-Prototype
PORTVERSION=	0.02
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Set a sub's prototype

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
