# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-Validate_US/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Validate_US
PORTVERSION=	0.5.5
CATEGORIES=	devel www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PEAR data validation class for US

BUILD_DEPENDS=	pear-Validate>=0.5.0:${PORTSDIR}/devel/pear-Validate
RUN_DEPENDS=	pear-Validate>=0.5.0:${PORTSDIR}/devel/pear-Validate

USES=	pear

.include <bsd.port.mk>
