# $FreeBSD: tags/RELEASE_10_3_0/x11/xgc/Makefile 399844 2015-10-20 13:49:18Z kwm $

PORTNAME=	xgc
PORTVERSION=	1.0.5
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X graphics demo

LICENSE=	MIT

XORG_CAT=	app
USE_XORG=	xt xaw

.include <bsd.port.mk>
