# $FreeBSD: tags/RELEASE_10_3_0/sysutils/py-pkginfo/Makefile 398444 2015-10-02 17:49:56Z pawel $

PORTNAME=	pkginfo
PORTVERSION=	1.2.1
CATEGORIES=	sysutils python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	che@bein.link
COMMENT=	Query metadatdata from sdists / bdists / installed packages

LICENSE=	MIT

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
