# Created by: Tim Bishop <tim@bishnet.net>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/freedt/Makefile 367259 2014-09-04 11:12:08Z tdb $

PORTNAME=	freedt
PORTVERSION=	23
CATEGORIES=	sysutils
MASTER_SITES=	http://offog.org/files/ \
		http://ftp.i-scream.org/pub/offog.org/files/

MAINTAINER=	tdb@FreeBSD.org
COMMENT=	Experimental reimplementation of Dan Bernstein's daemontools

CONFLICTS=	daemontools-[0-9]*

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
