# $FreeBSD: tags/RELEASE_10_3_0/www/twiki-PreferencesPlugin/Makefile 362252 2014-07-19 11:09:51Z ohauer $

PORTNAME=	PreferencesPlugin
SVNREV=		17568

COMMENT=	Edit preferences in-place

.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
