# Created by: will
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-File-Cache/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	File-Cache
PORTVERSION=	0.16
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Perl module implementing a persistent object store

LICENSE=	GPLv1 GPLv2 GPLv3
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
