# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: tags/RELEASE_10_3_0/security/pear-Crypt_CHAP/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Crypt_CHAP
PORTVERSION=	1.5.0
CATEGORIES=	security www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PEAR class for generating CHAP packets

USES=	pear
USE_PHP=	mcrypt mhash

.include <bsd.port.mk>
