# Created by: renchap@cocoa-x.com
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-mixlib-authentication/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	mixlib-authentication
PORTVERSION=	1.3.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	renchap@cocoa-x.com
COMMENT=	Mixes in simple per-request authentication

RUN_DEPENDS=	rubygem-mixlib-log>=0:${PORTSDIR}/devel/rubygem-mixlib-log

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
