# $FreeBSD: tags/RELEASE_10_3_0/databases/py-MySQLdb56/Makefile 375803 2014-12-29 21:18:45Z rm $

PKGNAMESUFFIX=	56

COMMENT=	Access a MySQL database through Python (Using MySQL 5.6 Client)

WANT_MYSQL_VER=	56
MASTERDIR=	${.CURDIR}/../py-MySQLdb

.include "${MASTERDIR}/Makefile"
