# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Text-MicroTemplate/Makefile 389593 2015-06-14 05:35:17Z kuriyama $

PORTNAME=	Text-MicroTemplate
PORTVERSION=	0.23
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension for standalone, fast and intelligent template engine

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-IO-stringy>0:${PORTSDIR}/devel/p5-IO-stringy

USES=	perl5
USE_PERL5=	configure
NO_ARCH=	YES

.include <bsd.port.mk>
