# $FreeBSD: tags/RELEASE_10_3_0/databases/rubygem-arel3/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	arel
PORTVERSION=	3.0.3
PORTEPOCH=	1
CATEGORIES=	databases rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	3

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Relational Algebra for Ruby

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PORTSCOUT=	ignore

.include <bsd.port.mk>
