# $FreeBSD: tags/RELEASE_10_3_0/net/py-pybeanstalk/Makefile 371449 2014-10-24 16:21:26Z mva $

PORTNAME=	pybeanstalk
PORTVERSION=	0.11.1
CATEGORIES=	net python
MASTER_SITES=	GOOGLE_CODE

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Pure python client library for beanstalkd queue

LICENSE=	GPLv2

USES=		python
USE_PYTHON=	distutils autoplist

WRKSRC=	${WRKDIR}/${PORTVERSION}

.include <bsd.port.mk>
