# Created by: Mikhail Teterin
# $FreeBSD: tags/RELEASE_10_3_0/devel/insight/Makefile 394508 2015-08-17 14:20:40Z mat $

PORTREVISION=	2

MAINTAINER=	mi@aldan.algebra.com
COMMENT=	Gnu debugger with the Insight GUI front-end

MASTERDIR=	${.CURDIR:H}/gdb66
OPTIONS_SLAVE=	INSIGHT
CONFLICTS=	gdb-[6-9]*

MAKE_JOBS_UNSAFE=	yes

.include "${MASTERDIR}/Makefile"
