# Created by: Aaron Dalton <aaron@daltons.ca>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Tree-Node/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	Tree-Node
PORTVERSION=	0.08
PORTREVISION=	2
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Memory-efficient tree nodes in Perl

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
