# Created by: gahr
# $FreeBSD: tags/RELEASE_10_3_0/x11/ooxcb/Makefile 403738 2015-12-14 21:10:13Z amdmi3 $

PORTNAME=	ooxcb
PORTVERSION=	1.2
CATEGORIES=	x11
MASTER_SITES=	CHEESESHOP

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Python binding to the X server using xcb

LICENSE=	BSD3CLAUSE

NO_ARCH=	yes

USES=		python
USE_PYTHON=	distutils autoplist
USE_XORG=	xcb

.include <bsd.port.mk>
