# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Badger/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	Badger
PORTVERSION=	0.09
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl Application Programming Toolkit

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
