# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/rubygem-rack-ssl/Makefile 389524 2015-06-13 20:14:20Z sunpoet $

PORTNAME=	rack-ssl
PORTVERSION=	1.4.1
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Rack middleware to force SSL/TLS

LICENSE=	MIT

RUN_DEPENDS=	rubygem-rack16>=0:${PORTSDIR}/www/rubygem-rack16

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
