# Created by: Ashish Shukla <wahjava@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/multimedia/msdl/Makefile 346429 2014-02-28 03:50:59Z miwi $

PORTNAME=	msdl
PORTVERSION=	1.2.7
CATEGORIES=	multimedia
MASTER_SITES=	SF/${PORTNAME}/${PORTNAME}/${PORTNAME}-${PORTVERSION}

MAINTAINER=	ashish@FreeBSD.org
COMMENT=	Streaming multimedia files downloader

GNU_CONFIGURE=	yes
PLIST_FILES=	bin/msdl \
		man/man1/msdl.1.gz

.include <bsd.port.mk>
