# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: tags/RELEASE_10_3_0/www/rubygem-sinatra-respond_to/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	sinatra-respond_to
PORTVERSION=	0.9.0
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Respond_to style Rails block for Sinatra

LICENSE=	MIT

RUN_DEPENDS=	rubygem-sinatra>=1.3:${PORTSDIR}/www/rubygem-sinatra

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
