# Created by: Dmitry Marakasov <amdmi3@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/rubygem-net-http-pipeline/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	net-http-pipeline
PORTVERSION=	1.0.1
CATEGORIES=	www net rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	HTTP/1.1 pipelining implementation atop Net::HTTP

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
