# Created by: James Bailie <jimmy@mammothcheese.ca>
# $FreeBSD: tags/RELEASE_10_3_0/x11-wm/nickleby/Makefile 395938 2015-09-03 09:52:06Z amdmi3 $

PORTNAME=	nickleby
PORTVERSION=	2.2.2
CATEGORIES=	x11-wm
MASTER_SITES=	http://www.mammothcheese.ca/

MAINTAINER=	jimmy@mammothcheese.ca
COMMENT=	Simple window manager

USE_XORG=	x11
DESTDIRNAME=	STAGEDIR

PLIST_FILES=	bin/nickleby \
		man/man1/nickleby.1.gz

.include <bsd.port.mk>
