# Created by: Li-Wen Hsu <lwhsu@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/databases/py-pgxnclient/Makefile 371173 2014-10-19 08:50:17Z mva $

PORTNAME=	pgxnclient
PORTVERSION=	1.2.1
PORTREVISION=	1
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP

MAINTAINER=	lwhsu@FreeBSD.org
COMMENT=	Command line tool to interact with the PostgreSQL Extension Network

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
