# $FreeBSD: tags/RELEASE_10_3_0/devel/erlang-meck/Makefile 404734 2015-12-29 10:55:58Z olgeni $

PORTNAME=	meck
PORTVERSION=	0.8.4
CATEGORIES=	devel
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Erlang library for building mock modules

LICENSE=	APACHE20

USES=		erlang:rebar
USE_GITHUB=	yes
GH_ACCOUNT=	eproxus

.include <bsd.port.mk>
