# Created by: Oleg Pudeyev <oleg@bsdpower.com>
# $FreeBSD: tags/RELEASE_10_3_0/www/py-frozen-flask/Makefile 376109 2015-01-03 08:41:20Z mva $

PORTNAME=	Frozen-Flask
PORTVERSION=	0.11
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	oleg@bsdpower.com
COMMENT=	Freezes a Flask application into a set of static files

LICENSE=	BSD3CLAUSE

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}Flask>=0:${PORTSDIR}/www/py-flask

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
