# Created by: Andrey Kostenko <andrey@kostenko.name>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-IO-Interactive/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	IO-Interactive
PORTVERSION=	0.0.6
PORTREVISION=	2
PORTEPOCH=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Utilities for interactive I/O

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

PORTSCOUT=	skipv:0.01

.include <bsd.port.mk>
