# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/archivers/php56-zip/Makefile 398632 2015-10-05 09:37:54Z ale $

CATEGORIES=	archivers

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-zip

.include "${MASTERDIR}/Makefile"
