# Created by: chinsan
# $FreeBSD: tags/RELEASE_10_3_0/finance/p5-Business-TW-Invoice-U420/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Business-TW-Invoice-U420
PORTVERSION=	0.01
PORTREVISION=	1
CATEGORIES=	finance perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Print Taiwan Unified Invoice with U420 printer

BUILD_DEPENDS=	p5-Class-Accessor>=0:${PORTSDIR}/devel/p5-Class-Accessor
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
