# $FreeBSD: tags/RELEASE_10_3_0/misc/p5-Business-ISMN/Makefile 392544 2015-07-20 01:16:56Z hrs $

PORTNAME=	Business-ISMN
PORTVERSION=	1.13
CATEGORIES=	misc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	hrs@FreeBSD.org
COMMENT=	Work with International Standard Music Numbers

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
