# Created by: nork@cityfujisawa.ne.jp
# $FreeBSD: tags/RELEASE_10_3_0/security/p5-Digest-HMAC/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Digest-HMAC
PORTVERSION=	1.03
PORTREVISION=	1
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 interface to HMAC Message-Digest Algorithms

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
