# Created by: janos.mohacsi@bsd.hu
# $FreeBSD: tags/RELEASE_10_3_0/hungarian/jdictionary-eng-hun-expr/Makefile 358062 2014-06-17 00:57:08Z vanilla $

PORTNAME=	jdictionary-eng-hun-expr
PORTVERSION=	1.4
PORTREVISION=	4
CATEGORIES=	hungarian textproc
MASTER_SITES=	SF/jdictionary/Plugins%20for%20jDictionary/Smart%20English-Hungarian%20expression
DISTNAME=	SmartEngHunExp-1_4.jar

COMMENT=	JDictionary plugin: English-Hungarian expression dictionary

MASTERDIR=	${.CURDIR}/../../textproc/jdictionary

.include "${MASTERDIR}/Makefile.plugin"
