# $FreeBSD: tags/RELEASE_10_3_0/x11-drivers/xf86-video-savage/Makefile 399179 2015-10-13 07:45:08Z kwm $

PORTNAME=	xf86-video-savage
PORTVERSION=	2.3.8
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org savage display driver

USE_GL=		gl

XORG_CAT=	driver
USE_XORG=	xf86driproto glproto

.include <bsd.port.mk>
