# Created by: dds
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/fileprune/Makefile 359395 2014-06-26 16:43:38Z vanilla $

PORTNAME=	fileprune
PORTVERSION=	1.9
CATEGORIES=	sysutils
MASTER_SITES=	http://www.spinellis.gr/sw/unix/fileprune/ \
		http://www.dmst.aueb.gr/dds/sw/unix/fileprune/

MAINTAINER=	dds@FreeBSD.org
COMMENT=	Prune a file set according to a given age distribution

PLIST_FILES=	bin/fileprune man/man1/fileprune.1.gz

.include <bsd.port.mk>
