# Created by: Aaron Dalton <aaron@daltons.ca>
# $FreeBSD: tags/RELEASE_10_3_0/games/p5-Games-AlphaBeta/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	Games-AlphaBeta
PORTVERSION=	0.4.7
PORTREVISION=	1
CATEGORIES=	games perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-v${PORTVERSION}

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Game-tree search with object oriented interface

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
