# Created by: ports@c0decafe.net <ports@c0decafe.net>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-File-Path-Tiny/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	File-Path-Tiny
PORTVERSION=	0.7
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Lightweight File::Path alternative

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
