# $FreeBSD: releng/10.3/etc/autofs/Makefile 283242 2015-05-21 13:42:37Z trasz $

FILES=		include_ldap special_hosts special_media special_noauto special_null

NO_OBJ=
FILESDIR=	/etc/autofs
FILESMODE=	755

.include <bsd.prog.mk>
