# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/x11-wm/xcompmgr/Makefile 399830 2015-10-20 13:37:49Z kwm $

PORTNAME=	xcompmgr
PORTVERSION=	1.1.7
CATEGORIES=	x11-wm

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Sample X compositing manager

XORG_CAT=	app
USE_XORG=	x11 xcomposite xfixes xdamage xrender

PLIST_FILES=	bin/${PORTNAME} man/man1/${PORTNAME}.1.gz

.include <bsd.port.mk>
