# Created by: ijliao
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Module-Pluggable-Fast/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Module-Pluggable-Fast
PORTVERSION=	0.19
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:MRAMBERG
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Fast plugins with instantiation

BUILD_DEPENDS=	p5-UNIVERSAL-require>=0:${PORTSDIR}/devel/p5-UNIVERSAL-require
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
