# Created by: Martin Jackson (mhjacks@swbell.net)
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Shell-EnvImporter/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Shell-EnvImporter
PORTVERSION=	1.07
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	mhjacks@swbell.net
COMMENT=	Inherit different shell environments and restore previous

RUN_DEPENDS=	p5-Class-MethodMaker>=0:${PORTSDIR}/devel/p5-Class-MethodMaker

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
