# Created by: D'Arcy J.M. Cain <darcy@druid.net>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-generate/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	generate
PORTVERSION=	2.6
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	ftp://ftp.druid.net/pub/distrib/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	generate-${PORTVERSION}

MAINTAINER=	darcy@druid.net
COMMENT=	Python module to implement generate

USES=		gmake python tar:tgz
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
