# Created by: Christer Edwards <christer.edwards@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/net/py-raet/Makefile 403456 2015-12-10 14:14:44Z miwi $

PORTNAME=	raet
PORTVERSION=	0.6.5
CATEGORIES=	net python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	christer.edwards@gmail.com
COMMENT=	Reliable Asynchronous Event Transport protocol library

LICENSE=	APACHE20

USES=		python:2
USE_PYTHON=	autoplist distutils
NO_ARCH=	yes

.include <bsd.port.mk>
