# Created by: dcf@aracnet.com
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-IO-Tee/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	IO-Tee
PORTVERSION=	0.64
PORTREVISION=	3
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Multiplex output to multiple output handles

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
