# Created by: Piotr Rybicki <meritus@innervision.pl>
# $FreeBSD: tags/RELEASE_10_3_0/math/pear-Math_BigInteger/Makefile 369092 2014-09-23 16:45:35Z bapt $

PORTNAME=	Math_BigInteger
PORTVERSION=	1.0.2
CATEGORIES=	math pear

MAINTAINER=	meritus@innervision.pl
COMMENT=	Pure-PHP arbitrary precision integer arithmetic library

USE_PHP=	pcre
USES=	pear

.include <bsd.port.mk>
