# Created by: bf <bf@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/math/libR/Makefile 375097 2014-12-20 19:15:31Z bapt $

PORTNAME=	libR

COMMENT=	The static libR library from R

DESCR=	${.CURDIR}/pkg-descr
LIBR_SLAVEPORT=	yes
MASTERDIR=	${.CURDIR}/../R
PLIST=	${.CURDIR}/pkg-plist
PLIST_FILES=	lib/R/lib/libR.a

.include "${MASTERDIR}/Makefile"
