# $FreeBSD: tags/RELEASE_10_3_0/graphics/qt5-graphicaleffects/Makefile 346930 2014-03-03 16:50:32Z makc $

PORTNAME=	graphicaleffects
DISTVERSION=	${QT5_VERSION}
CATEGORIES=	graphics
PKGNAMEPREFIX=	qt5-

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Qt Quick graphical effects

USE_QT5=	# empty
QT_DIST=	${PORTNAME}
USES=		qmake
NO_BUILD=	yes

.include <bsd.port.mk>
