# Created by: Antonio Carlos Venancio Junior (<antonio@php.net>)
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-HTML_Form/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	HTML_Form
PORTVERSION=	1.3.0
PORTREVSION=	1
CATEGORIES=	devel pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PEAR simple HTML form package

USES=	pear

.include <bsd.port.mk>
