# $FreeBSD: tags/RELEASE_10_3_0/dns/erlang-idna/Makefile 391483 2015-07-06 22:27:17Z olgeni $

PORTNAME=	idna
PORTVERSION=	1.0.2
CATEGORIES=	dns
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	IDNA implementation in pure Erlang

LICENSE=	MIT

USES=		erlang:rebar
USE_GITHUB=	yes
GH_ACCOUNT=	benoitc
GH_PROJECT=	${PKGNAMEPREFIX}${PORTNAME}

.include <bsd.port.mk>
