# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/net/p5-Socket-Class/Makefile 377064 2015-01-15 09:05:37Z tijl $

PORTNAME=	Socket-Class
PORTVERSION=	2.258
PORTREVISION=	2
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl class to communicate with sockets

USES=		perl5
USE_OPENSSL=	yes
USE_PERL5=	configure

.include <bsd.port.mk>
