# Created by: chinsan <chinsan.tw@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/net/pecl-cvsclient/Makefile 402450 2015-11-26 14:39:58Z miwi $

PORTNAME=	cvsclient
PORTVERSION=	0.2
CATEGORIES=	net pear
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-
DIST_SUBDIR=	PECL

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PHP extension for CVS pserver client

LICENSE=	PHP202

USES=		tar:tgz
USE_PHP=	yes
USE_PHPEXT=	yes
IGNORE_WITH_PHP=5 56

.include <bsd.port.mk>
