# Created by: Mario Sergio Fujikawa Ferreira <lioux@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/x11-themes/kde-icons-graphite-rade8/Makefile 377647 2015-01-22 06:00:41Z vanilla $

PORTNAME=	graphite-rade8
PORTVERSION=	3.1
MASTER_SITES=	SF/graphitekde/graphitekde/Graphite-RAD.E8-${PORTVERSION}
DISTNAME=	Graphite-RAD.E8-${PORTVERSION}

MAINTAINER=	portmaster@bsdforge.com
COMMENT=	KDE Mac OS X like iconset, most from rad-e8 design

USES=		tar:bzip2
WRKSRC=		${WRKDIR}/Graphite-RAD.E8-${PORTVERSION}

.include "${.CURDIR}/../kde-icons-noia/Makefile.icons"
