# $FreeBSD: tags/RELEASE_10_3_0/www/twiki-JSCalendarContrib/Makefile 362252 2014-07-19 11:09:51Z ohauer $

PORTNAME=	JSCalendarContrib
SVNREV=		17493

COMMENT=	Mishoo JSCalendar repackaged

.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
