# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Data-Inherited/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Data-Inherited
PORTVERSION=	1.100860
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension for hierarchy-wide accumulation of list/hash results

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
