# Created by: Veniamin Gvozdikov <vg@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/databases/p5-DR-Tarantool/Makefile 391554 2015-07-08 09:17:44Z vg $

PORTNAME=	DR-Tarantool
PORTVERSION=	0.44
CATEGORIES=	databases perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:UNERA
PKGNAMEPREFIX=	p5-

MAINTAINER=	vg@FreeBSD.org
COMMENT=	Perl driver for Tarantool

LICENSE=	ART10

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
