# Created by: Chris S.J. Peron <maneo@bsdpro.com>
# $FreeBSD: tags/RELEASE_10_3_0/net-mgmt/subcalc/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	subcalc
PORTVERSION=	1.1
CATEGORIES=	net-mgmt ipv6
MASTER_SITES=	http://www.seccuris.com/documents/downloads/

MAINTAINER=	csjp@FreeBSD.org
COMMENT=	Advanced IP/IPv6 subnet calculation and discovery

PLIST_FILES=	bin/subcalc man/man1/subcalc.1.gz

.include <bsd.port.mk>
