# $FreeBSD: tags/RELEASE_10_3_0/devel/erlang-sbroker/Makefile 392029 2015-07-14 15:33:24Z olgeni $

PORTNAME=	sbroker
PORTVERSION=	0.6.2
DISTVERSIONPREFIX=	v
CATEGORIES=	devel
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Sojourn-time based active queue management library

LICENSE=	APACHE20

USES=		erlang:rebar
USE_GITHUB=	yes
GH_ACCOUNT=	fishcakez

.include <bsd.port.mk>
