# Created by: Philip M. Gollucci <philip@p6m7g8.com>
# $FreeBSD: tags/RELEASE_10_3_0/databases/p5-DBIx-Browse/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	DBIx-Browse
PORTVERSION=	2.09
PORTREVISION=	1
CATEGORIES=	databases perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	DBIx::Browse - Perl extension to browse tables

BUILD_DEPENDS=	p5-DBI>=0:${PORTSDIR}/databases/p5-DBI
RUN_DEPENDS=	p5-DBI>=0:${PORTSDIR}/databases/p5-DBI

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
