# Created by: Nicola Vitale	<nivit@email.it>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-testgears/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	TestGears
PORTVERSION=	0.2
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	http://nivi.interfree.it/distfiles/${PORTNAME}/ \
		http://www.turbogears.org/download/eggs/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Python module to run tests written as simple functions

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
