# Created by: Kubilay Kocak <koobs@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/databases/py-umemcache/Makefile 371173 2014-10-19 08:50:17Z mva $

PORTNAME=	umemcache
PORTVERSION=	1.6.3
PORTREVISION=	1
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	koobs@FreeBSD.org
COMMENT=	Memcache client written in highly optimized C++ with Python bindings

LICENSE=	BSD4CLAUSE

USES=		dos2unix python:2 zip
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
