# Created by: Byung-Hee HWANG <bh@izb.knu.ac.kr>
# $FreeBSD: tags/RELEASE_10_3_0/audio/py-mutagen/Makefile 396574 2015-09-10 15:02:33Z olivierd $

PORTNAME=	mutagen
PORTVERSION=	1.31
CATEGORIES=	audio python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	python@FreeBSD.org
COMMENT=	Python-based audio metadata tag reader and writer

LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		python
USE_PYTHON=	autoplist distutils
NO_ARCH=	yes

.include <bsd.port.mk>
