# Created by: Thierry Thomas (<thierry@pompo.net>)
# $FreeBSD: tags/RELEASE_10_3_0/net/pear-Net_Socket/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Net_Socket
PORTVERSION=	1.0.14
CATEGORIES=	net www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PEAR Network Socket Interface

USES=	pear

.include <bsd.port.mk>
