# $FreeBSD: tags/RELEASE_10_3_0/converters/py-rencode/Makefile 389158 2015-06-11 04:40:14Z jkim $

PORTNAME=	rencode
PORTVERSION=	1.0.3
CATEGORIES=	converters devel python
MASTER_SITES=	https://www.xpra.org/src/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	python@FreeBSD.org
COMMENT=	R-encoding and r-decoding implementation

LICENSE=	GPLv3

BUILD_DEPENDS=	cython:${PORTSDIR}/lang/cython

USE_PYTHON=	autoplist distutils
USES=		python tar:xz

.include <bsd.port.mk>
