# Created by: Alex Miller (<asm@asm.kiev.ua>)
# $FreeBSD: tags/RELEASE_10_3_0/www/pear-HTTP_Upload/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	HTTP_Upload
PORTVERSION=	0.9.1
CATEGORIES=	www devel pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Easy and secure management of files submitted via HTML Forms

USES=	pear

.include <bsd.port.mk>
