# $FreeBSD: tags/RELEASE_10_3_0/print/rubygem-prawn-flexible-table/Makefile 392374 2015-07-17 12:25:37Z sunpoet $

PORTNAME=	prawn-flexible-table
PORTVERSION=	0.1.2
PORTREVISION=	1
CATEGORIES=	print rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Create tables with *span attributes for each cell with Prawn

LICENSE=	GPLv2 RUBY
LICENSE_COMB=	dual

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
