# Created by: alexander smishlajev
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-extremes/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	Extremes
PORTVERSION=	1.1.1
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Production-quality 'Min' and 'Max' objects (adapted from PEP 326)

USES=		python zip
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
