# $FreeBSD: tags/RELEASE_10_3_0/devel/elixir-lager_logger/Makefile 398110 2015-09-28 12:24:33Z olgeni $

PORTNAME=	lager_logger
PORTVERSION=	1.0.1
DISTVERSIONPREFIX=	v
CATEGORIES=	devel
PKGNAMEPREFIX=	elixir-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Lager backend for Elixir's Logger

LICENSE=	APACHE20

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	PSPDFKit-labs

.include <bsd.port.mk>
