# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/net/pear-Services_Pingback/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Services_Pingback
PORTVERSION=	0.2.2
CATEGORIES=	net www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Pingback user-agent class

USES=	pear

.include <bsd.port.mk>
