# Created by: Mathieu Arnold <mat@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/databases/p5-Class-DBI-Oracle/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Class-DBI-Oracle
PORTVERSION=	0.51
PORTREVISION=	1
CATEGORIES=	databases perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Extensions to Class::DBI for Oracle

BUILD_DEPENDS=	p5-Class-DBI>=0:${PORTSDIR}/databases/p5-Class-DBI
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
