# Created by: Jose Alonso Cardenas Marquez <acardenas@bsd.org.pe>
# $FreeBSD: tags/RELEASE_10_3_0/security/py-cerealizer/Makefile 371453 2014-10-24 16:50:42Z mva $

PORTNAME=	cerealizer
PORTVERSION=	0.7
PORTREVISION=	1
CATEGORIES=	security python
MASTER_SITES=	http://download.gna.org/soya/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	Cerealizer-${PORTVERSION}
DIST_SUBDIR=	python

MAINTAINER=	acm@FreeBSD.org
COMMENT=	Secure pickle-like module

USES=		python tar:bzip2
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
