# Created by: clsung@dragon2.net
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-RTF-Tokenizer/Makefile 376761 2015-01-11 13:30:04Z sunpoet $

PORTNAME=	RTF-Tokenizer
PORTVERSION=	1.19
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module for reading RTF files

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
