# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/rubygem-redmine_acts_as_taggable_on/Makefile 389463 2015-06-13 15:35:18Z sunpoet $

PORTNAME=	redmine_acts_as_taggable_on
PORTVERSION=	1.0.0
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Allows multiple Redmine plugins to use tags safely

LICENSE=	GPLv2

RUN_DEPENDS=	rubygem-acts-as-taggable-on>=2.3:${PORTSDIR}/www/rubygem-acts-as-taggable-on

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
