# Created by: Andrey Zakhvatov
# $FreeBSD: tags/RELEASE_10_3_0/games/xoj/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	xoj
PORTVERSION=	1.0
PORTREVISION=	2
CATEGORIES=	games
MASTER_SITES=	SUNSITE/X11/demos

MAINTAINER=	ports@FreeBSD.org
COMMENT=	O. J. Simpson Simulator root window demo

USES=		imake:noman tar:tgz
USE_XORG=	xaw
PLIST_FILES=	bin/xoj

.include <bsd.port.mk>
