# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Text-Filter/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Text-Filter
PORTVERSION=	1.10
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Base class for objects that can read and write text lines

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
