# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Test-RequiresInternet/Makefile 387561 2015-05-27 10:52:36Z pi $

PORTNAME=	Test-RequiresInternet
PORTVERSION=	0.05
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	pi@FreeBSD.org
COMMENT=	Test network connectivity before functional tests

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=	perl5
USE_PERL5=	configure
NO_ARCH=	YES

.include <bsd.port.mk>
