# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/converters/pear-Services_JSON/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Services_JSON
PORTVERSION=	1.0.3
CATEGORIES=	converters www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PHP implementation of json_encode/decode

USES=		pear

.include <bsd.port.mk>
