# Created by: Peter Pentchev <roam@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/dns/p5-Stanford-DNSserver/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	Stanford-DNSserver
PORTVERSION=	1.2.0
PORTREVISION=	1
CATEGORIES=	dns perl5
MASTER_SITES=	http://www.stanford.edu/~riepel/lbnamed/Stanford-DNSserver/
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	DNS name server framework with a Perl backend

LICENSE=	BSD3CLAUSE

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
