# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/graphics/R-cran-RColorBrewer/Makefile 389330 2015-06-13 08:20:32Z tota $

PORTNAME=	RColorBrewer
DISTVERSION=	1.1-2
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	ColorBrewer palettes

LICENSE=	APACHE20

USES=	cran:auto-plist

.include <bsd.port.mk>
