# $FreeBSD: tags/RELEASE_10_3_0/www/p5-HTML-Perlinfo/Makefile 389323 2015-06-13 06:47:22Z pi $

PORTNAME=	HTML-Perlinfo
PORTVERSION=	1.68
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	pi@FreeBSD.org
COMMENT=	Display a lot of Perl information in HTML format

LICENSE_COMB=	dual
LICENSE=	ART10 GPLv1

PERL5=		yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
