# Created by: antoine@FreeBSD.org
# $FreeBSD: tags/RELEASE_10_3_0/textproc/py-acora/Makefile 400594 2015-10-31 22:36:15Z antoine $

PORTNAME=	acora
PORTVERSION=	1.9
CATEGORIES=	textproc devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	antoine@FreeBSD.org
COMMENT=	Fast multi-keyword search engine for text strings

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
