# Created by: olgeni@FreeBSD.org
# $FreeBSD: tags/RELEASE_10_3_0/x11-themes/gtk-xfce-engine/Makefile 384919 2015-04-28 17:01:46Z bdrewery $

PORTNAME=	gtk-xfce-engine
PORTVERSION=	3.2.0
CATEGORIES=	x11-themes xfce
MASTER_SITES=	XFCE/src/xfce/${PORTNAME}/${PORTVERSION:R}
DIST_SUBDIR=	xfce4

MAINTAINER=	xfce@FreeBSD.org
COMMENT=	Xfce GTK2 theme engine

LICENSE=	GPLv2

GNU_CONFIGURE=	yes
USES=		gmake libtool pkgconfig xfce tar:bzip2
USE_GNOME=	glib20 gtk20

.include <bsd.port.mk>
