# Created by: Daniel Roethlisberger <daniel@roe.ch>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/rubygem-rdiscount/Makefile 387226 2015-05-24 00:07:01Z sunpoet $

PORTNAME=	rdiscount
PORTVERSION=	2.1.8
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Fast Markdown converter for ruby based on discount

LICENSE=	BSD3CLAUSE

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/rdiscount

.include <bsd.port.mk>
