# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/php56-dom/Makefile 367268 2014-09-04 14:24:25Z ale $

CATEGORIES=	textproc

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-dom

.include "${MASTERDIR}/Makefile"
