# Created by: chinsan <chinsan.tw@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-CSS/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	CSS
PORTVERSION=	1.09
PORTREVISION=	1
CATEGORIES=	textproc www perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:IAMCAL
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Object oriented access to Cascading Style Sheets (CSS)

BUILD_DEPENDS=	p5-Parse-RecDescent>=1.94:${PORTSDIR}/devel/p5-Parse-RecDescent

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
