# Created by: Steve Wills <steve@stevenwills.com>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/fist/Makefile 363904 2014-08-03 14:15:08Z olgeni $

PORTNAME=	fist
PORTVERSION=	4.0
CATEGORIES=	textproc
MASTER_SITES=	ftp://ftp.fourmilab.ch/pub/fist/

MAINTAINER=	swills@FreeBSD.org
COMMENT=	Emphatic message generator

GNU_CONFIGURE=	yes
PLIST_FILES=	bin/fist man/man1/fist.1.gz

.include <bsd.port.mk>
