# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Sub-Installer/Makefile 381151 2015-03-12 23:00:02Z adamw $

PORTNAME=	Sub-Installer
PORTVERSION=	0.0.3
PORTREVISION=	2
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-v${PORTVERSION}

MAINTAINER=	perl@FreeBSD.org
COMMENT=	A clean way to (re)install package subroutines

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
