# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Devel-Gladiator/Makefile 373894 2014-12-04 13:25:47Z jadawin $

PORTNAME=	Devel-Gladiator
PORTVERSION=	0.07
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl 5 module to walk Perls arena

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
