# Created by: Joe Horn <joehorn@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-channel-twig/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	twig
PORTVERSION=	20140108
CATEGORIES=	devel www pear
MASTER_SITES=	#

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PEAR channel ${PEAR_CHANNEL_HOST}

PEAR_CHANNEL_HOST=	pear.twig-project.org

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/devel/pear/bsd.pear.channel.mk"
.include <bsd.port.post.mk>
