# Created by: Li-Wen Hsu <lwhsu@lwhsu.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-ezpyinline/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	ezpyinline
PORTVERSION=	0.1
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
DIST_SUBDIR=	python

MAINTAINER=	lwhsu@FreeBSD.org
COMMENT=	Easy embedded Inline C for Python

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
