# Created by: vanilla
# $FreeBSD: tags/RELEASE_10_3_0/x11-toolkits/p5-Tk-Autoscroll/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Tk-Autoscroll
PORTVERSION=	1.14
PORTREVISION=	4
CATEGORIES=	x11-toolkits perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Tk::Autoscroll - space invaders-like scrolling

BUILD_DEPENDS=	p5-Tk>=0:${PORTSDIR}/x11-toolkits/p5-Tk
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
