# Created by: Fukang Chen <loader@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-File-Copy-Link/Makefile 396502 2015-09-09 14:14:40Z loader $

PORTNAME=	File-Copy-Link
PORTVERSION=	0.140
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	loader@FreeBSD.org
COMMENT=	Extension for replacing a link with a copy of linked file

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
