# $FreeBSD: tags/RELEASE_10_3_0/comms/gstreamer1-plugins-spandsp/Makefile 375225 2014-12-22 10:22:38Z kwm $

PORTREVISION=	0
CATEGORIES=	comms

COMMENT=	Gstreamer DSP library and software FAX machine plugin

GST_PLUGIN=	spandsp
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
