# Created by: Gabor Kovesdan
# $FreeBSD: tags/RELEASE_10_3_0/security/p5-Crypt-MySQL/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Crypt-MySQL
PORTVERSION=	0.04
PORTREVISION=	1
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ashish@FreeBSD.org
COMMENT=	Perl extension to compare MySQL passwords without libmysqlclient

RUN_DEPENDS=	p5-Digest-SHA1>=0:${PORTSDIR}/security/p5-Digest-SHA1

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
