# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/math/p5-GIS-Distance-Lite/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	GIS-Distance-Lite
PORTVERSION=	1.0
PORTREVISION=	2
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:JOBERO
PKGNAMEPREFIX=	p5-

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Calculate geographic distances in geodetic WGS84 format

RUN_DEPENDS=	p5-Math-Complex>1.0.3:${PORTSDIR}/math/p5-Math-Complex

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
