# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-chronic/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	chronic
PORTVERSION=	0.10.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Natural language date/time parser written in pure Ruby

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
