# Created by: Alex Miller <asm@asm.kiev.ua>
# $FreeBSD: tags/RELEASE_10_3_0/net/ilbc/Makefile 361810 2014-07-14 18:37:54Z tijl $

PORTNAME=	ilbc
DISTVERSION=	rfc3951
PORTREVISION=	1
CATEGORIES=	net
MASTER_SITES=	http://simon.morlat.free.fr/download/1.2.x/source/

MAINTAINER=	asm@asm.kiev.ua
COMMENT=	Internet Low Bit Rate codec (RFC3951)

CONFLICTS=	libilbc-[0-9]*

GNU_CONFIGURE=	yes
INSTALL_TARGET=	install-strip
USES=		libtool
USE_LDCONFIG=	yes

.include <bsd.port.mk>
