# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/audio/gstreamer-plugins-flite/Makefile 352119 2014-04-25 12:46:45Z bapt $

PORTREVISION=	2
CATEGORIES=	audio

COMMENT=	Gstreamer flite run-time speech synthesis engine plugin

GST_PLUGIN=	flite

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
