# Created by: swhetzel@gmail.com
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/b43-fwcutter/Makefile 363371 2014-07-29 18:41:15Z adamw $

PORTNAME=	b43-fwcutter
PORTVERSION=	015
CATEGORIES=	sysutils
MASTER_SITES=	http://bu3sch.de/b43/fwcutter/

MAINTAINER=	swhetzel@gmail.com
COMMENT=	Extracts firmware for Broadcom Wireless adapters

USES=		gmake tar:bzip2

PLIST_FILES=	bin/b43-fwcutter \
		man/man1/b43-fwcutter.1.gz

.include <bsd.port.mk>
