# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/mail/claws-mail-tnef/Makefile 329440 2013-10-05 11:25:29Z pawel $

PORTNAME=	tnef
PORTREVISION=	0

COMMENT=	TNEF attachment format parser plugin for Claws Mail

CLAWS_PLUGINS_BUILD=	tnef_parse

.include "../claws-mail/Makefile.claws"
.include <bsd.port.mk>
