# Created by: roam@FreeBSD.org
# $FreeBSD: tags/RELEASE_10_3_0/dns/ares/Makefile 357277 2014-06-10 07:39:01Z olgeni $

PORTNAME=	ares
PORTVERSION=	1.1.1
PORTREVISION=	1
CATEGORIES=	dns
MASTER_SITES=	http://mirrors.rit.edu/zi/ \
		ftp://athena-dist.mit.edu/pub/ATHENA/ares/

MAINTAINER=	zi@FreeBSD.org
COMMENT=	Asynchronous DNS resolver library

CONFLICTS=	c-ares-1.* c-ares-config-1.*

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
