# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/graphics/gstreamer-plugins-libcaca/Makefile 367888 2014-09-10 20:50:31Z gerald $
#   $MCom: ports/graphics/gstreamer-plugins-libcaca/Makefile,v 1.5 2008/03/19 14:05:34 ahze Exp $

PORTREVISION=	2
CATEGORIES=	graphics

COMMENT=	Gstreamer color ASCII art plugin

GST_PLUGIN=	libcaca

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
