# Created by: Gabor Kovesdan
# $FreeBSD: tags/RELEASE_10_3_0/security/p5-Crypt-Salt/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Crypt-Salt
PORTVERSION=	0.01
PORTREVISION=	1
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ashish@FreeBSD.org
COMMENT=	Perl extension to generate a salt to be fed into crypt

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
