# $FreeBSD: tags/RELEASE_10_3_0/lang/fpc-rtl-extra/Makefile 403082 2015-12-05 23:29:36Z marino $

CATEGORIES=	lang
PKGNAMESUFFIX=	-rtl-extra

MAINTAINER=	freebsd-fpc@FreeBSD.org
COMMENT=	Free Pascal rtl-extra unit

USE_FPC=	yes

MASTERDIR=	${.CURDIR}/../../lang/fpc
WRKUNITDIR=	${FPCSRCDIR}/packages/${PKGNAMESUFFIX:S/-//}
EXTRACTUNITDIR=	${WRKUNITDIR}

.include "${MASTERDIR}/Makefile"
