# $FreeBSD: releng/10.3/share/i18n/Makefile 291792 2015-12-04 18:14:31Z bdrewery $
# $NetBSD: Makefile,v 1.1 2003/06/27 08:39:59 tshiozak Exp $

.include <bsd.own.mk>

SUBDIR=	csmapper esdb
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
