# Created by: Pawel Worach
# $FreeBSD: tags/RELEASE_10_3_0/x11-fonts/font-schumacher-misc/Makefile 381876 2015-03-21 23:05:19Z bapt $

PORTNAME=	font-schumacher-misc
PORTVERSION=	1.1.2
PORTREVISION=	3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org miscellaneous Schumacher fonts

XORG_CAT=	font
USE_XORG=	fontutil

.include <bsd.port.mk>
