# Created by: Wen Heping<wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-sequel3/Makefile 399585 2015-10-17 18:09:59Z sunpoet $

# legacy for rubygem-larch

PORTNAME=	sequel
PORTVERSION=	3.48.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	3

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	The Database Toolkit for Ruby

LICENSE=	MIT

PORTSCOUT=	limit:^3

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/sequel

.include <bsd.port.mk>
