# Created by: Wei-chun Chao
# $FreeBSD: tags/RELEASE_10_3_0/net-mgmt/p5-Net-Netmask/Makefile 388695 2015-06-07 13:09:28Z lth $

PORTNAME=	Net-Netmask
PORTVERSION=	1.9022
CATEGORIES=	net-mgmt perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Perl module to parse, manipulate, and lookup IP network blocks

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
