# $FreeBSD: tags/RELEASE_10_3_0/textproc/py-trans/Makefile 402388 2015-11-25 02:28:59Z wen $

PORTNAME=	trans
PORTVERSION=	2.0.1
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	d.pryadko@rambler-co.ru
COMMENT=	Module for performing transliteration

LICENSE=	BSD

USES=		python tar:bzip2
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
