# Created by: jkh
# $FreeBSD: tags/RELEASE_10_3_0/editors/jove/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	jove
PORTVERSION=	4.16
PORTREVISION=	1
CATEGORIES=	editors
MASTER_SITES=	ftp://ftp.cs.toronto.edu/pub/moraes/jove/ \
		LOCAL/simon

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Jonathan's Own Version of Emacs

WRKSRC=		${WRKDIR}/${PORTNAME}

.include <bsd.port.mk>
