# Created by: Carlo Strub
# $FreeBSD: tags/RELEASE_10_3_0/security/py-pyptlib/Makefile 371453 2014-10-24 16:50:42Z mva $

PORTNAME=	pyptlib
PORTVERSION=	0.0.6
CATEGORIES=	security net python
MASTER_SITES=	http://www.c-s.li/ports/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	cs@FreeBSD.org
COMMENT=	Pluggable transport library

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
