# $FreeBSD: tags/RELEASE_10_3_0/devel/py-pyee/Makefile 392729 2015-07-23 15:22:03Z jpaetzel $

PORTNAME=	pyee
PORTVERSION=	0.0.9
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jpaetzel@FreeBSD.org
COMMENT=	Python EventEmitter implementation

LICENSE=	MIT

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
