# $FreeBSD: tags/RELEASE_10_3_0/graphics/rubygem-cairo/Makefile 396773 2015-09-12 17:09:37Z sunpoet $

PORTNAME=	cairo
PORTVERSION=	1.14.3
CATEGORIES=	graphics rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby binding for GLib2

LICENSE=	GPLv2 RUBY
LICENSE_COMB=	dual

RUN_DEPENDS=	rubygem-pkg-config>=1.1.5:${PORTSDIR}/devel/rubygem-pkg-config

USE_GNOME=	cairo
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
