
# $FreeBSD: releng/10.3/kerberos5/lib/Makefile 289252 2015-10-13 18:56:50Z bdrewery $

SUBDIR=	libasn1 libgssapi_krb5 libgssapi_ntlm libgssapi_spnego libhdb \
	libheimntlm libhx509 libkadm5clnt libkadm5srv libkafs5 libkrb5 \
	libroken libsl libvers libkdc libwind libheimsqlite libheimbase libheimipcc libheimipcs

SUBDIR_DEPEND_libkafs5=	libkrb5

.include <bsd.subdir.mk>
