# Created by: Gerrit Beine (<tux@pinguru.net>)
# $FreeBSD: tags/RELEASE_10_3_0/net/pear-Net_POP3/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Net_POP3
PORTVERSION=	1.3.8
CATEGORIES=	net pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Provides a POP3 class to access POP3 server

BUILD_DEPENDS=	${PEARDIR}/Net/Socket.php:${PORTSDIR}/net/pear-Net_Socket
RUN_DEPENDS=	${PEARDIR}/Net/Socket.php:${PORTSDIR}/net/pear-Net_Socket

USES=	pear

.include <bsd.port.mk>
