# Created by: Archie Cobbs
# $FreeBSD: tags/RELEASE_10_3_0/net/suckblow/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	suckblow
PORTVERSION=	1.1
CATEGORIES=	net
MASTER_SITES=	LOCAL/archie

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Two companion utilities for transferring data over a TCP socket

USES=		uidfix
CONFLICTS=	suck-4.* suck-cnews-4.*

.include <bsd.port.mk>
