# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Term-Sk/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Term-Sk
PORTVERSION=	0.14
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:KEICHNER
PKGNAMEPREFIX=	p5-

MAINTAINER=	milki@FreeBSD.org
COMMENT=	Perl extension to display a progress indicator on a terminal

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
