# Created by: janos.mohacsi@bsd.hu
# $FreeBSD: tags/RELEASE_10_3_0/french/jdictionary-fre-hun/Makefile 360248 2014-07-02 19:26:05Z antoine $

PORTNAME=	jdictionary-fre-hun
PORTVERSION=	1.0
PORTREVISION=	4
CATEGORIES=	french hungarian textproc
MASTER_SITES=	SF/jdictionary/Plugins%20for%20jDictionary/Smart%20French-Hungarian
DISTNAME=	Smart_French_Hungarian-1_0.jar

COMMENT=	JDictionary plugin: French-Hungarian dictionary

MASTERDIR=	${.CURDIR}/../../textproc/jdictionary

.include "${MASTERDIR}/Makefile.plugin"
