# Created by: ports@c0decafe.net
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Template-Tiny/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	Template-Tiny
PORTVERSION=	1.12
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Template Toolkit reimplemented in as little code as possible

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
