# $FreeBSD: tags/RELEASE_10_3_0/textproc/rubygem-github-markdown/Makefile 394158 2015-08-13 17:38:00Z sunpoet $

PORTNAME=	github-markdown
PORTVERSION=	0.6.9
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Self-contained Markdown parser for GitHub

DEPRECATED=	This gem is not maintained and not supported by upstream

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
