# Created by: gebhart@secnetix.de
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Scalar-Util-Numeric/Makefile 380740 2015-03-08 03:15:09Z vanilla $

PORTNAME=	Scalar-Util-Numeric
PORTVERSION=	0.40
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	gebhart@secnetix.de
COMMENT=	Numeric tests for perl scalars

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
