# Created by: chuck@pkix.net
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/clean/Makefile 363399 2014-07-29 21:43:17Z adamw $

PORTNAME=	clean
PORTVERSION=	3.4
CATEGORIES=	sysutils
MASTER_SITES=	SF

MAINTAINER=	chuck@pkix.net
COMMENT=	Automatically remove unwanted files

USES=	tar:bzip2

PLIST_FILES=	bin/clean man/man1/clean.1.gz

.include <bsd.port.mk>
