# $FreeBSD: tags/RELEASE_10_3_0/russian/py-pytils/Makefile 394192 2015-08-13 21:20:00Z rm $

PORTNAME=	pytils
PORTVERSION=	0.3
CATEGORIES=	russian python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	rm@FreeBSD.org
COMMENT=	Russian-specific string utils

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
