# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Test-CheckManifest/Makefile 376516 2015-01-08 09:54:22Z culot $

PORTNAME=	Test-CheckManifest
PORTVERSION=	1.29
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Check if your Manifest matches your distro

LICENSE=	ART20

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
