# Created by: Murilo Opsfelder <mopsfelder@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Config-IniRegEx/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Config-IniRegEx
PORTVERSION=	0.01
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	mopsfelder@gmail.com
COMMENT=	Ini workaround, regex search for parameters and sections

RUN_DEPENDS=	p5-Config-IniFiles>=0:${PORTSDIR}/devel/p5-Config-IniFiles

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
