# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-streetaddress/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	StreetAddress
PORTVERSION=	1.0.6
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Parses one line street addresses into normalized address object

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
