# Created by: Johann Visagie <johann@egenetics.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-File-Temp/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	File-Temp
PORTVERSION=	0.23.04
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-${PORTVERSION:R}${PORTVERSION:E}

MAINTAINER=	leeym@FreeBSD.org
COMMENT=	Perl5 module to generate temporary files or directories safely

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
