# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/print/gutenprint-foomatic/Makefile 362853 2014-07-24 21:15:46Z danilo $
#    $MCom: ports/print/gutenprint-foomatic/Makefile,v 1.1 2007/03/30 16:42:47 ahze Exp $

PORTEPOCH=	0
PKGNAMESUFFIX=	-foomatic

MAINTAINER=	cmt@burggraben.net
COMMENT=	GutenPrint Foomatic Drivers

LICENSE=	GPLv2

MASTERDIR=	${.CURDIR}/../../print/gutenprint-base

GUT_SLAVE=	foomatic
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
