# Created by: Murilo Opsfelder <mopsfelder@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Template-Provider-Encode/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Template-Provider-Encode
PORTVERSION=	0.02
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	mopsfelder@gmail.com
COMMENT=	Encode templates for Template Toolkit

RUN_DEPENDS=	p5-Template-Toolkit>=0:${PORTSDIR}/www/p5-Template-Toolkit

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
