# Created by: Brian Gaeke <brg@dgate.org>
# $FreeBSD: tags/RELEASE_10_3_0/emulators/vmips/Makefile 375264 2014-12-22 20:26:16Z pawel $

PORTNAME=	vmips
PORTVERSION=	1.5
CATEGORIES=	emulators
MASTER_SITES=	SF \
		http://www.dgate.org/vmips/releases/${DISTNAME}/

MAINTAINER=	brg@dgate.org
COMMENT=	MIPS R3000 simulator

LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		gmake
GNU_CONFIGURE=	yes

INFO=		vmips

.include <bsd.port.mk>
