# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/graphics/php56-exif/Makefile 367268 2014-09-04 14:24:25Z ale $

CATEGORIES=	graphics

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-exif

.include "${MASTERDIR}/Makefile"
