# $FreeBSD: tags/RELEASE_10_3_0/www/rubygem-fcgi/Makefile 387141 2015-05-23 15:29:56Z sunpoet $

PORTNAME=	fcgi
PORTVERSION=	0.9.2.1
CATEGORIES=	www ruby
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	FastCGI library for Ruby

LICENSE=	MIT

LIB_DEPENDS=	libfcgi.so:${PORTSDIR}/www/fcgi

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
