# Created by: Bill Fenner <fenner@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/net/p5-Net-NBName/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	Net-NBName
PORTVERSION=	0.26
PORTREVISION=	1
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Performs simple NetBIOS Name Service Requests

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
