# $FreeBSD: tags/RELEASE_10_3_0/sysutils/py-power/Makefile 371454 2014-10-24 16:56:10Z mva $

PORTNAME=	power
PORTVERSION=	1.3
CATEGORIES=	sysutils python
MASTER_SITES=	https://github.com/Kentzo/Power/releases/download/v${PORTVERSION}/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	cederom@tlen.pl
COMMENT=	Cross-platform system power status information for Python

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
