# Created by: rhay
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/mtxorbd/Makefile 357429 2014-06-11 08:19:36Z vanilla $

PORTNAME=	mtxorbd
PORTVERSION=	1.0.2
CATEGORIES=	sysutils
MASTER_SITES=	SF/mtxorb/${PORTNAME}/${PORTNAME}-${PORTVERSION}
EXTRACT_SUFX=	.tgz

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Control Daemon for Matrix Orbital LCD screens

.include <bsd.port.mk>
