# $FreeBSD: releng/10.3/lib/clang/liblldbPluginPlatformFreeBSD/Makefile 255722 2013-09-20 01:52:02Z emaste $

.include <bsd.own.mk>

LIB=	lldbPluginPlatformFreeBSD

SRCDIR=	tools/lldb/source/Plugins/Platform/FreeBSD
SRCS=	PlatformFreeBSD.cpp

TGHDRS=	DiagnosticCommonKinds \
	DeclNodes \
	StmtNodes \
	CommentCommandList

.include "../lldb.lib.mk"
