# $FreeBSD: releng/10.3/usr.bin/svn/Makefile 289252 2015-10-13 18:56:50Z bdrewery $

SUBDIR = lib .WAIT \
	 svn svnadmin svndumpfilter svnlook svnserve svnsync svnversion \
	 svnmucc svnrdump
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
