# Created by: Ju Pengfei <jupengfei@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/ftp/py-tftpy/Makefile 373284 2014-11-24 18:28:34Z sunpoet $

PORTNAME=	tftpy
PORTVERSION=	0.6.2
CATEGORIES=	ftp python
MASTER_SITES=	CHEESESHOP \
		SF/${PORTNAME}
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Pure Python TFTP Implementation

LICENSE=	MIT

USE_PYTHON=	autoplist distutils
USES=		python:2

.include <bsd.port.mk>
