# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/databases/php5-pdo_sqlite/Makefile 389655 2015-06-14 20:23:09Z ale $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-pdo_sqlite

.include "${MASTERDIR}/Makefile"
