# Created by: Thierry Thomas (<thierry@pompo.net>)
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-I18N/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	I18N
PORTVERSION=	1.0.0
CATEGORIES=	devel www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PEAR internationalization package

BUILD_DEPENDS=	${PEARDIR}/PEAR.php:${PORTSDIR}/devel/pear
RUN_DEPENDS=	${PEARDIR}/PEAR.php:${PORTSDIR}/devel/pear

USES=	pear

.include <bsd.port.mk>
