# $FreeBSD: tags/RELEASE_10_3_0/graphics/poppler-qt5/Makefile 373403 2014-11-25 12:55:00Z makc $

PORTREVISION=	0
PKGNAMESUFFIX=	-qt5

MAINTAINER=	gnome@FreeBSD.org
COMMENT=	Qt 5 bindings to poppler

MASTERDIR=	${.CURDIR}/../../graphics/poppler
SLAVEPORT=	qt5
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
