# $FreeBSD: tags/RELEASE_10_3_0/security/qtkeychain-qt4/Makefile 387341 2015-05-24 21:03:19Z madpilot $

PKGNAMESUFFIX=	-qt4

MASTERDIR=	${.CURDIR}/../qtkeychain-qt5

.include "${MASTERDIR}/Makefile"
