# $FreeBSD: tags/RELEASE_10_3_0/french/libreoffice/Makefile 397662 2015-09-23 21:06:12Z jkim $

CATEGORIES=	french
LO_I18N=	fr
LO_HAS_HELPPACK=	yes

.include "${.CURDIR}/../../editors/libreoffice/Makefile.i18n"

.include <bsd.port.mk>
