# Created by: Alex Kapranoff <alex@kapranoff.ru>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Test-LectroTest/Makefile 399249 2015-10-14 11:04:10Z culot $

PORTNAME=	Test-LectroTest
PORTVERSION=	0.5001
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Easy, automatic, specification-based tests

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
