# Created by: Pawel Worach
# $FreeBSD: tags/RELEASE_10_3_0/x11-fonts/font-bh-75dpi/Makefile 381876 2015-03-21 23:05:19Z bapt $

PORTNAME=	font-bh-75dpi
PORTVERSION=	1.0.3
PORTREVISION=	3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org Bigelow Holmes 75dpi font

XORG_CAT=	font
USE_XORG=	fontutil

.include <bsd.port.mk>
