# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: tags/RELEASE_10_3_0/net/py-iplib/Makefile 371449 2014-10-24 16:21:26Z mva $

PORTNAME=	iplib
PORTVERSION=	1.1
PORTREVISION=	1
CATEGORIES=	net python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Convert amongst many different IPv4 notations

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
