# Created by: Stefan Walter <swalter@lettermax.de>
# $FreeBSD: tags/RELEASE_10_3_0/misc/vifm/Makefile 392306 2015-07-16 18:35:10Z pgollucci $

PORTNAME=	vifm
PORTVERSION=	0.8
DISTVERSIONPREFIX=	v
CATEGORIES=	misc

MAINTAINER=	mp39590@gmail.com
COMMENT=	Ncurses based file manager with vi like keybindings

LICENSE=	GPLv2

USES=		desktop-file-utils gmake ncurses tar:bzip2
GNU_CONFIGURE=	yes
CONFIGURE_ARGS=	--without-gtk

USE_GITHUB=	yes

.include <bsd.port.mk>
