# $FreeBSD: releng/10.3/gnu/usr.bin/groff/src/preproc/html/Makefile 276486 2014-12-31 23:25:37Z ngie $

PROG_CXX=	pre-grohtml
SRCS=		pre-html.cpp pushback.cpp
DPADD=		${LIBGROFF}
LDADD=		${LIBGROFF}
MAN=

.include <bsd.prog.mk>
