# $FreeBSD: tags/RELEASE_10_3_0/www/mod_reproxy/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	mod_reproxy
PORTVERSION=	0.02.20110826
CATEGORIES=	www
MASTER_SITES=	LOCAL/kuriyama

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Apache module to support x-reproxy-url header

LICENSE=	APACHE20

WRKSRC=		${WRKDIR}/lestrrat-mod_reproxy-0f945ff

USE_APACHE=	22+
AP_FAST_BUILD=	yes
AP_GENPLIST=	yes

.include <bsd.port.mk>
