# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Set-Scalar/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Set-Scalar
PORTVERSION=	1.26
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl module containing a set of scalars, including references

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
