# $FreeBSD: tags/RELEASE_10_3_0/textproc/nunnimcax/files/Makefile 365579 2014-08-21 18:41:16Z antoine $

LIB = 	NunniMCAX
SRCS=	NunniCXMLParser.c NunniCXMLParserFSM.c NunniHashtable.c NunniStack.c
INCS=	NunniMCAX.h

LIBDIR=		${PREFIX}/lib
INCLUDEDIR=	${PREFIX}/include

.include <bsd.lib.mk>
