# Created by: James FitzGibbon <jfitz@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Devel-Symdump/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Devel-Symdump
PORTVERSION=	2.1000
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-2.10

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 module that dumps symbol names or the symbol table

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
