# Created by: arved
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-XML-Parser-Style-Elemental/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	XML-Parser-Style-Elemental
PORTVERSION=	0.50
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:TIMA
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	More advanced and flexible object tree style for XML::Parser

LICENSE=	ART10

BUILD_DEPENDS=	p5-XML-Parser>=0:${PORTSDIR}/textproc/p5-XML-Parser

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
