# Created by: Corey Smith
# $FreeBSD: tags/RELEASE_10_3_0/www/py-slimmer/Makefile 376109 2015-01-03 08:41:20Z mva $

PORTNAME=	slimmer
PORTVERSION=	0.1.30
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	corsmith@gmail.com
COMMENT=	Whitespace optimizer for CSS, HTML and XHTML output

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
