# Created by: Maxim Sobolev <sobomax@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/libsoup-gnome/Makefile 393607 2015-08-05 19:13:24Z kwm $

PORTREVISION=	0
CATEGORIES=	devel gnome
PKGNAMESUFFIX=	-gnome

MAINTAINER=	gnome@FreeBSD.org
COMMENT=	GNOME wrapper for libsoup

MASTERDIR=	${.CURDIR}/../libsoup
DESCR=		${.CURDIR}/pkg-descr
PLIST=		${.CURDIR}/pkg-plist

SOUP_SLAVE=	yes

.include "${MASTERDIR}/Makefile"
