# Created by: Torsten Zuhlsdorff <ports@toco-domains.de>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-sprockets-rails-rails41/Makefile 402315 2015-11-23 19:01:10Z sunpoet $

PKGNAMESUFFIX=	-rails41

RUN_DEPENDS=	rubygem-actionpack41>=4.1.12:${PORTSDIR}/www/rubygem-actionpack41 \
		rubygem-activesupport41>=4.1.12:${PORTSDIR}/devel/rubygem-activesupport41 \
		rubygem-sprockets3>=3.0.3:${PORTSDIR}/devel/rubygem-sprockets3

MASTERDIR=	${.CURDIR}/../rubygem-sprockets-rails

.include "${MASTERDIR}/Makefile"
