# Created by: Frederic Culot <frederic@culot.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Parallel-Iterator/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Parallel-Iterator
PORTVERSION=	1.00
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Simple parallel execution

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
