# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-notiffany/Makefile 397149 2015-09-17 17:10:40Z sunpoet $

PORTNAME=	notiffany
PORTVERSION=	0.0.8
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Single wrapper for most popular notification libraries

LICENSE=	MIT

RUN_DEPENDS=	rubygem-nenv>=0.1:${PORTSDIR}/devel/rubygem-nenv \
		rubygem-shellany>=0:${PORTSDIR}/sysutils/rubygem-shellany

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
