# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Lingua-StopWords/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Lingua-StopWords
PORTVERSION=	0.09
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Stop words for several languages

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
