# $FreeBSD: tags/RELEASE_10_3_0/audio/gstreamer1-plugins-mpg123/Makefile 397984 2015-09-26 14:36:23Z kwm $

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	GStreamer MPEG Layer 1, 2, and 3 plugin

GST_PLUGIN=	mpg123
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
