# Created by: Vladimir Perepelitsa <mons@cpan.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-ToolSet/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	ToolSet
PORTVERSION=	1.00
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:DAGOLDEN
PKGNAMEPREFIX=	p5-

MAINTAINER=	mons@cpan.org
COMMENT=	Load your commonly-used modules in a single import

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
