# Created by: Alfred Perlstein <alfred@freebsd.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-fake-factory/Makefile 373187 2014-11-23 22:48:43Z alfred $

PORTNAME=	fake-factory
PORTVERSION=	0.4.2
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	alfred@FreeBSD.org
COMMENT=	Generate fake data using python

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
