# $FreeBSD: tags/RELEASE_10_3_0/devel/geany-plugins-l10n/Makefile 395656 2015-08-31 08:57:38Z makc $

PORTNAME=	geany-plugins-l10n
PORTVERSION=	${GEANY_VER}
CATEGORIES=	devel

MAINTAINER=	makc@FreeBSD.org
COMMENT=	Localization messages for Geany plugins

NO_ARCH=	yes

.include "${.CURDIR}/../geany-plugins/files/Makefile.common"
.include <bsd.port.mk>
