# $FreeBSD: tags/RELEASE_10_3_0/x11/xkbcomp/Makefile 401221 2015-11-10 23:25:33Z kwm $

PORTNAME=	xkbcomp
PORTVERSION=	1.3.1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Compile XKB keyboard description

LICENSE=	MIT

XORG_CAT=	app
USE_XORG=	x11 xkbfile
USES=		pathfix

PLIST_FILES=	bin/xkbcomp \
		libdata/pkgconfig/xkbcomp.pc \
		man/man1/xkbcomp.1.gz

.include <bsd.port.mk>
