# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Tie-LLHash/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Tie-LLHash
PORTVERSION=	1.003
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:KWILLIAMS
PKGNAMEPREFIX=	p5-

MAINTAINER=	swills@FreeBSD.org
COMMENT=	Perl module which implements an ordered hash-like object

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
