# Created by: Lars Thegler <lth@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Log-Trace/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	Log-Trace
PORTVERSION=	1.070
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Provides a unified approach to tracing

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
