# Created by: fjoe@FreeBSD.org
# $FreeBSD: tags/RELEASE_10_3_0/x11-toolkits/wxgtk28-contrib-common/Makefile 347864 2014-03-11 07:13:06Z miwi $

MAINTAINER=	fjoe@FreeBSD.org
COMMENT=	The wxWidgets GUI toolkit contributed libraries (common files)

WXGTK_FLAVOR=	gtk2-contrib-common
MASTERDIR=	${.CURDIR}/../wxgtk28

.include "${MASTERDIR}/Makefile"
