# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/ssid/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	ssid
PORTVERSION=	0.1
CATEGORIES=	sysutils
MASTER_SITES=	http://dl.suckless.org/tools/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Simple setsid replacement

LICENSE=	MIT

PLIST_FILES=	bin/ssid

.include <bsd.port.mk>
