# Created by: Dmitry Sivachenko <demon@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/memcheck/Makefile 403636 2015-12-12 23:02:03Z bapt $

PORTNAME=	memcheck
PORTVERSION=	0.2.4
PORTREVISION=	1
CATEGORIES=	devel
MASTER_SITES=	http://hald.dnsalias.net/projects/memcheck/

MAINTAINER=	demon@FreeBSD.org
COMMENT=	Memory Allocation Checker

BROKEN=		unfetchable
USES=		libtool
GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes

MAKE_JOBS_UNSAFE=	yes

.include <bsd.port.mk>
