# $FreeBSD: tags/RELEASE_10_3_0/ftp/gstreamer1-plugins-curl/Makefile 375225 2014-12-22 10:22:38Z kwm $

PORTREVISION=	0
CATEGORIES=	ftp

COMMENT=	Gstreamer curl plugin

GST_PLUGIN=	curl
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
