# Created by: Wei-chun Chao
# $FreeBSD: tags/RELEASE_10_3_0/misc/p5-File-CounterFile/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	File-CounterFile
PORTVERSION=	1.04
PORTREVISION=	1
CATEGORIES=	misc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Perl module for persistent counter class

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
