# Created by: Pawel Pekala <pawel@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/mail/claws-mail-spamassassin/Makefile 347936 2014-03-11 21:49:40Z adamw $

PORTNAME=	spamassassin
PORTREVISION=	0

COMMENT=	SpamAssassin plugin for Claws Mail

RUN_DEPENDS=	spamd:${PORTSDIR}/mail/spamassassin

CLAWS_PLUGINS_BUILD=	spamassassin

.include "../claws-mail/Makefile.claws"
.include <bsd.port.mk>
