# Created by: Aaron Dalton <aaron@daltons.ca>
# $FreeBSD: tags/RELEASE_10_3_0/games/p5-Games-Dice/Makefile 385205 2015-05-02 19:00:51Z danilo $

PORTNAME=	Games-Dice
PORTVERSION=	0.045
CATEGORIES=	games perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	danilo@FreeBSD.org
COMMENT=	Perl module to simulate die rolls

LICENSE=	MIT

TEST_DEPENDS=	p5-Capture-Tiny>=0:${PORTSDIR}/devel/p5-Capture-Tiny \
		p5-Test-Script>=1.06:${PORTSDIR}/devel/p5-Test-Script \
		p5-Test-Simple>=0.96:${PORTSDIR}/devel/p5-Test-Simple

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
