# $FreeBSD: tags/RELEASE_10_3_0/audio/festvox-cmu_us_clb_arctic/Makefile 402853 2015-12-02 21:09:41Z pi $

VOICE=	cmu_us_clb_arctic

COMMENT=	CMU US English female voice for festival

MASTERDIR=	${.CURDIR}/../festvox-cmu_us_slt_arctic

PORTDATA=       *

.include "${MASTERDIR}/Makefile"
