# Created by: vanilla
# $FreeBSD: tags/RELEASE_10_3_0/x11-toolkits/p5-Tk-HistEntry/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Tk-HistEntry
PORTVERSION=	0.43
PORTREVISION=	5
CATEGORIES=	x11-toolkits perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Tk::HistEntry - Entry widget with history capability

BUILD_DEPENDS=	p5-Tk>=0:${PORTSDIR}/x11-toolkits/p5-Tk
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
