# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/rubygem-SyslogLogger/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	SyslogLogger
PORTVERSION=	2.0
CATEGORIES=	sysutils rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Logger replacement that logs to syslog

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
