# $FreeBSD: tags/RELEASE_10_3_0/devel/geany-plugin-extrasel/Makefile 380787 2015-03-08 18:43:08Z makc $

PORTNAME=	geany-plugin-extrasel
PORTVERSION=	${GEANY_VER}
CATEGORIES=	devel

MAINTAINER=	makc@FreeBSD.org
COMMENT=	Geany plugin: ${${GEANY_PLUGIN}_DESC}

.include "${.CURDIR}/../geany-plugins/files/Makefile.common"
.include <bsd.port.mk>
