# $FreeBSD: releng/10.3/usr.sbin/bsdconfig/startup/Makefile 279611 2015-03-05 00:34:33Z dteske $

NO_OBJ=

SUBDIR= include share

FILESDIR=	${LIBEXECDIR}/bsdconfig/140.startup
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	misc rcadd rcconf rcdelete rcedit rcvar startup

.include <bsd.prog.mk>
