# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-XML-Quote/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	XML-Quote
PORTVERSION=	1.02
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	XML quote/dequote functions

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
