# Created by: rpsfa@rit.edu
# $FreeBSD: tags/RELEASE_10_3_0/dns/rubygem-net-dns/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	net-dns
PORTVERSION=	0.8.0
PORTREVISION=	1
CATEGORIES=	dns rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Pure Ruby DNS library

LICENSE=	BSD2CLAUSE RUBY
LICENSE_COMB=	dual

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
