# Created by: Alexander Botero-Lowry <alexbl@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/net/py-netstring/Makefile 371449 2014-10-24 16:21:26Z mva $

PORTNAME=	netstring
PORTVERSION=	1.14
CATEGORIES=	net devel python
MASTER_SITES=	ftp://ftp.tummy.com/pub/tummy/Python/netstring/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	python-${PORTNAME}-${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Python module implementing the netstring protocol

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
