# $FreeBSD: tags/RELEASE_10_3_0/security/p5-Digest-MurmurHash/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Digest-MurmurHash
PORTVERSION=	0.11
PORTREVISION=	1
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension for XS interface to the MurmurHash algorithm

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
