# Created by: Joe Marcus Clarke <marcus@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py3-gobject3/Makefile 376731 2015-01-10 23:15:27Z demon $
#   $MCom: ports/trunk/devel/py3-gobject3/Makefile 19696 2014-05-26 11:20:01Z gusi $

PORTREVISION=	1
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
PKGNAMESUFFIX=	3

COMMENT=	Python 3 bindings for GObject

SLAVE_PORT=	python3

MASTERDIR=	${.CURDIR}/../../devel/pygobject3-common
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
