# $FreeBSD: tags/RELEASE_10_3_0/misc/rubygem-dotenv/Makefile 390193 2015-06-21 10:40:48Z sunpoet $

PORTNAME=	dotenv
PORTVERSION=	2.0.2
CATEGORIES=	misc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Loads environment variables from `.env`

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/dotenv

.include <bsd.port.mk>
