# Created by: Anes Mukhametov <anes@anes.su>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Text-Hyphen/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Text-Hyphen
PORTVERSION=	0.11
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	anes@anes.su
COMMENT=	Determine positions for hyphens inside words

LICENSE=	BSD

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
