# Created by: Olivier Duchateau
# $FreeBSD: tags/RELEASE_10_3_0/www/py-waitress/Makefile 396518 2015-09-09 15:43:51Z olivierd $

PORTNAME=	waitress
PORTVERSION=	0.8.10
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	olivierd@FreeBSD.org
COMMENT=	Python WSGI server

LICENSE=	ZPL21

USES=	python
USE_PYTHON=	distutils autoplist
NO_ARCH=	yes

.include <bsd.port.mk>
