# Created by: Roman Bogorodskiy
# $FreeBSD: tags/RELEASE_10_3_0/audio/p5-MP3-Tag/Makefile 388088 2015-05-31 13:37:20Z amdmi3 $

PORTNAME=	MP3-Tag
PORTVERSION=	1.13
PORTREVISION=	1
CATEGORIES=	audio perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	novel@FreeBSD.org
COMMENT=	Module for reading tags of MP3 audio files

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

CONFLICTS=	p5-tagged-0.*

.include <bsd.port.mk>
