# Created by: Shinsuke Matsui <smatsui@karashi.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/p5-HTML-Selector-XPath/Makefile 379665 2015-02-23 10:08:52Z sunpoet $

PORTNAME=	HTML-Selector-XPath
PORTVERSION=	0.14
PORTREVISION=	1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	smatsui@karashi.org
COMMENT=	HTML::Selector::XPath - CSS Selector to XPath compiler

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-Test-Base>=0:${PORTSDIR}/devel/p5-Test-Base

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
