# Created by: Adam Weinberger <adamw@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-List-Flatten/Makefile 382549 2015-03-28 20:00:43Z adamw $

PORTNAME=	List-Flatten
PORTVERSION=	0.01
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:OBRADOVIC
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Interpolate array references in a list

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
