# Created by: Kurt Lidl <kurt.lidl@cello.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Data-Grouper/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Data-Grouper
PORTVERSION=	0.06
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:FERRANCE
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Data aggregator for perl objects

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
