# $FreeBSD: tags/RELEASE_10_3_0/www/twiki-TinyMCEPlugin/Makefile 362252 2014-07-19 11:09:51Z ohauer $

PORTNAME=	TinyMCEPlugin
SVNREV=		17303

COMMENT=	TinyMCE WYSIWYG editor integration

TWDEP=		BehaviourContrib>=15357 WysiwygPlugin>=16650

.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
