# Created by: Stephen Montgomery-Smith <stephen@math.missouri.edu>
# $FreeBSD: tags/RELEASE_10_3_0/math/octave-forge-tcl-octave/Makefile 367888 2014-09-10 20:50:31Z gerald $

PORTNAME=	octave-forge-tcl-octave
PORTVERSION=	0.1.8
PORTREVISION=	11
CATEGORIES=	math

MAINTAINER=	stephen@FreeBSD.org
COMMENT=	Octave-forge package ${OCTAVE_PKGNAME}

GNU_CONFIGURE=	yes

USES+=		tcl:wrapper

.include "${.CURDIR}/../../Mk/bsd.octave.mk"
.include <bsd.port.mk>
