# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/graphics/R-cran-shape/Makefile 372351 2014-11-09 10:14:04Z tota $

PORTNAME=	shape
PORTVERSION=	1.4.2
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Functions for plotting graphical shapes, colors

LICENSE=	GPLv3

USES=	cran:auto-plist

.include <bsd.port.mk>
