# Created by: chinsan <chinsan.tw@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/www/xpi-web_developer/Makefile 364158 2014-08-06 09:11:57Z olgeni $

PORTNAME=	web_developer
PORTVERSION=	1.2.2
DISTVERSIONSUFFIX=	-fx+sm
CATEGORIES=	www

MAINTAINER=	gecko@FreeBSD.org
COMMENT=	Extension to add various web developer tools

XPI_NUM=	60
XPI_ID=		{c45c406e-ab73-11d8-be73-000a95be3b12}

.include "../xpi-adblock/Makefile.xpi"
.include <bsd.port.mk>
