# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Time-Out/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	Time-Out
PORTVERSION=	0.11
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Easily timeout long running operations

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
