# $FreeBSD: releng/10.3/usr.sbin/bsdconfig/startup/share/Makefile 279611 2015-03-05 00:34:33Z dteske $

NO_OBJ=

FILESDIR=	${SHAREDIR}/bsdconfig/startup
FILES=		rcconf.subr rcedit.subr rcvar.subr

.include <bsd.prog.mk>
