# Created by: chinsan
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Scalar-Listify/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Scalar-Listify
PORTVERSION=	0.03
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Poduces an array(ref)? from a scalar value or array ref

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
