# Created by: David Naylor <naylor.b.david@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/math/R-cran-quadprog/Makefile 367888 2014-09-10 20:50:31Z gerald $

PORTNAME=	quadprog
DISTVERSION=	1.5-5
PORTREVISION=	5
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	dbn@FreeBSD.org
COMMENT=	Functions to solve Quadratic Programming Problems

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USES=	cran:auto-plist

.include <bsd.port.mk>
