# Created by: Wen heping <wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/www/pear-HTML_TagCloud/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	HTML_TagCloud
PORTVERSION=	1.0.0
CATEGORIES=	www devel pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Generate TagCloud in HTML And Visualize Tags

USES=	pear

.include <bsd.port.mk>
