# Created by: Chris St Denis <chris@smartt.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-HTML_QuickForm_Renderer_Tableless/Makefile 369068 2014-09-23 15:15:04Z bapt $

PORTNAME=	HTML_QuickForm_Renderer_Tableless
PORTVERSION=	0.6.1
CATEGORIES=	devel www pear

MAINTAINER=	chris@smartt.com
COMMENT=	Implementation of Tableless Renderer for HTML_QuickForm

BUILD_DEPENDS=	${PEARDIR}/HTML/QuickForm.php:${PORTSDIR}/devel/pear-HTML_QuickForm
RUN_DEPENDS=	${PEARDIR}/HTML/QuickForm.php:${PORTSDIR}/devel/pear-HTML_QuickForm

USES=	pear

.include <bsd.port.mk>
