# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: tags/RELEASE_10_3_0/www/pear-Text_Wiki/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Text_Wiki
PORTVERSION=	1.2.1
CATEGORIES=	www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Abstracts parsing and rendering rules for Wiki markup

USES=	pear

.include <bsd.port.mk>
