# Created by: Valerio Daelli <valerio.daelli@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/security/ossec-hids-local/Makefile 389271 2015-06-12 14:13:29Z brd $

PORTREVISION=	0
COMMENT=	The client and server (local) port of ossec-hids

LOCAL_ONLY=	yes

MASTERDIR=	${.CURDIR}/../ossec-hids-server

.include "${MASTERDIR}/Makefile"
