# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Carp-Always/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Carp-Always
PORTVERSION=	0.13
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension to warn and die noisily with stack backtraces

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-Test-Base>0:${PORTSDIR}/devel/p5-Test-Base

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
