# $FreeBSD: tags/RELEASE_10_3_0/textproc/elixir-earmark/Makefile 404716 2015-12-29 06:28:03Z olgeni $

PORTNAME=	earmark
PORTVERSION=	0.2.0
DISTVERSIONPREFIX=	v
CATEGORIES=	textproc
PKGNAMEPREFIX=	elixir-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Markdown parser for Elixir

LICENSE=	APACHE20

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	pragdave

MIX_REWRITE=	yes

.include <bsd.port.mk>
