# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Class-Multimethods-Pure/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Class-Multimethods-Pure
PORTVERSION=	0.13
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Method-ordered multimethod dispatch

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
