# Created by: Mario S F Ferreira <lioux@linf.unb.br> et al.
# $FreeBSD: tags/RELEASE_10_3_0/math/p5-Math-Logic/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	Math-Logic
PORTVERSION=	1.19
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Perl module providing pure 2, 3, or multi-value logic

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
