# $FreeBSD: tags/RELEASE_10_3_0/x11-toolkits/py32-tkinter/Makefile 401909 2015-11-19 01:28:38Z lwhsu $

MASTERDIR=	${.CURDIR}/../py-tkinter

PYTHON_VERSION=	python3.2

.include "${MASTERDIR}/Makefile"
