# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/converters/p5-Number-RecordLocator/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Number-RecordLocator
PORTVERSION=	0.005
PORTREVISION=	1
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Encodes integers into a short locator string

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
