# $FreeBSD: tags/RELEASE_10_3_0/databases/py-python-sql/Makefile 403824 2015-12-16 00:27:27Z wen $

PORTNAME=	python-sql
PORTVERSION=	0.8
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Library to write SQL queries

#LICENSE=	BSD

USES=		pkgconfig python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
