# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: tags/RELEASE_10_3_0/security/pear-File_HtAccess/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	File_HtAccess
PORTVERSION=	1.2.1
CATEGORIES=	security www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PEAR class to manipulate .htaccess files

USES=	pear

.include <bsd.port.mk>
