# Created by: Thomas Gellekum <tg@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/gnustep/Makefile 383626 2015-04-09 07:44:41Z bapt $

PORTNAME=	gnustep
PORTVERSION=	1.28.0
PORTREVISION=	2
CATEGORIES=	devel lang gnustep

MAINTAINER=	theraven@FreeBSD.org
COMMENT=	Objective-C libraries based on the OpenStep standard

USES=		metaport gnustep
USE_GNUSTEP=	back gui base

.include <bsd.port.mk>
