# $FreeBSD: tags/RELEASE_10_3_0/x11/xhost/Makefile 399844 2015-10-20 13:49:18Z kwm $

PORTNAME=	xhost
PORTVERSION=	1.0.7
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Server access control program for X

XORG_CAT=	app
USE_XORG=	x11 xmuu xau

PLIST_FILES=	bin/xhost man/man1/xhost.1.gz

.include <bsd.port.mk>
