# Created by: Steve Wills <steve@mouf.net>
# $FreeBSD: tags/RELEASE_10_3_0/math/p5-Statistics-Frequency/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Statistics-Frequency
PORTVERSION=	0.03
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	Statistics
PKGNAMEPREFIX=	p5-

MAINTAINER=	swills@FreeBSD.org
COMMENT=	Simple counting of elements

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
