# Created by: will
# $FreeBSD: tags/RELEASE_10_3_0/math/p5-AI-NeuralNet-BackProp/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	AI-NeuralNet-BackProp
PORTVERSION=	0.89
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Perl module implementing back-propagation feed-forward neural network

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

NO_WRKSUBDIR=	yes
USES=		perl5 zip
USE_PERL5=	configure

.include <bsd.port.mk>
