# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/R-cran-RgoogleMaps/Makefile 389318 2015-06-13 05:18:36Z tota $

PORTNAME=	RgoogleMaps
PORTVERSION=	1.2.0.7
CATEGORIES=	www
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Overlays on Google map tiles in R

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

RUN_DEPENDS=	R-cran-png>0:${PORTSDIR}/graphics/R-cran-png \
		R-cran-RJSONIO>0:${PORTSDIR}/converters/R-cran-RJSONIO

USES=	cran:auto-plist

.include <bsd.port.mk>
