# Created by: Neil Booth <kyuupichan@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/security/py-pbkdf2/Makefile 376026 2015-01-01 19:29:33Z pawel $

PORTNAME=	pbkdf2
PORTVERSION=	1.3
CATEGORIES=	security python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	kyuupichan@gmail.com
COMMENT=	PKCS5 v2.0 PBKDF2 Module

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
