# Created by: markm
# $FreeBSD: tags/RELEASE_10_3_0/misc/dejagnu/Makefile 346487 2014-02-28 10:30:08Z gahr $

PORTNAME=	dejagnu
PORTVERSION=	1.5.1
PORTREVISION=	1
CATEGORIES=	misc tcl tk
MASTER_SITES=	GNU

MAINTAINER=	tcltk@FreeBSD.org
COMMENT=	Automated program/system tester

LICENSE=	GPLv3

LIB_DEPENDS=	libexpect.so:${PORTSDIR}/lang/expect

USES+=		gmake tcl
GNU_CONFIGURE=	yes

INFO=		${PORTNAME}

.include <bsd.port.mk>
