# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: tags/RELEASE_10_3_0/misc/p5-Array-IntSpan/Makefile 376248 2015-01-04 17:11:43Z sunpoet $

PORTNAME=	Array-IntSpan
PORTVERSION=	2.003
CATEGORIES=	misc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Module for handling arrays using IntSpan techniques

LICENSE=	ART10

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
