# $FreeBSD: tags/RELEASE_10_3_0/devel/py-blessings/Makefile 403277 2015-12-08 15:01:06Z skreuzer $

PORTNAME=	blessings
PORTVERSION=	1.6
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Thin wrapper around terminal coloring, styling, and positioning

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
