# Created by: Holger Lamm <holger@e-gitt.net>
# $FreeBSD: tags/RELEASE_10_3_0/net-p2p/mldonkey-gui/Makefile 362404 2014-07-21 08:07:26Z leeym $

OPTIONS_EXCLUDE=CORE

COMMENT=	OCAML/GTK GUI for the MLdonkey peer-to-peer network client

MASTERDIR=	${.CURDIR}/../mldonkey

.include "${MASTERDIR}/Makefile"
