# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/audio/gstreamer-plugins-nas/Makefile 352119 2014-04-25 12:46:45Z bapt $
#   $MCom: ports/audio/gstreamer-plugins-nas/Makefile,v 1.5 2008/03/19 14:05:31 ahze Exp $

PORTREVISION=	1
CATEGORIES=	audio

COMMENT=	GStreamer NAS (Network Audio System) plugin

GST_PLUGIN=	nas

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
