# $FreeBSD: tags/RELEASE_10_3_0/russian/calligra-l10n/Makefile 404140 2015-12-21 18:10:32Z rakuco $

PORTNAME=	calligra-l10n
PORTVERSION=	${CALLIGRA_VERSION}
CATEGORIES=	russian editors kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Russian messages and documentation for Calligra

CALLIGRA_L10N=	ru

.include "${.CURDIR}/../../editors/calligra-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
