# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: tags/RELEASE_10_3_0/finance/p5-Finance-Currency-Convert/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Finance-Currency-Convert
PORTVERSION=	1.08
PORTREVISION=	1
CATEGORIES=	finance perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Convert currencies and fetch their exchange rates

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5 tar:tgz
USE_PERL5=	configure

.include <bsd.port.mk>
