# Created by: Alexander Wittig <alexander@wittig.name>
# $FreeBSD: tags/RELEASE_10_3_0/mail/squirrelmail-compatibility-plugin/Makefile 366415 2014-08-28 15:16:49Z adamw $

PORTNAME=	compatibility
PORTVERSION=	2.0.16
PORTREVISION=	1
CATEGORIES=	mail www
DISTNAME=	${PORTNAME}-${PORTVERSION}-1.0

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Required by many plugins for compatibility with SquirrelMail

.include "${.CURDIR}/../squirrelmail/bsd.squirrelmail.mk"
.include <bsd.port.mk>
