#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: releng/10.3/usr.bin/vgrind/RETEST/Makefile 276486 2014-12-31 23:25:37Z ngie $

PROG=	retest
SRCS=	regexp.c retest.c
.PATH:	${.CURDIR}/..
MAN=

install:

.include <bsd.prog.mk>
