# Created by: Sahil Tandon <sahil@tandon.net>
# $FreeBSD: tags/RELEASE_10_3_0/www/p5-HTML-Field/Makefile 386075 2015-05-11 12:04:18Z mat $

PORTNAME=	HTML-Field
PORTVERSION=	1.19
PORTREVISION=	1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module to generate HTML form elements

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
