# Created by: Pierre David <pdagog@gmail.com>, Jean Benoit <jean@unistra.fr>
# $FreeBSD: tags/RELEASE_10_3_0/net-mgmt/netmagis-utils/Makefile 400427 2015-10-29 01:34:21Z junovitch $

PORTNAME=	netmagis
PKGNAMESUFFIX=	-utils

COMMENT=	Netmagis command-line utilities

RUN_DEPENDS=	netmagis-config:${PORTSDIR}/net-mgmt/netmagis-common

MASTERDIR=	${.CURDIR}/../netmagis-common

PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
