# Created by: Steve Wills <swills@freebsd.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/py-bugzillatools/Makefile 382892 2015-04-01 07:33:41Z antoine $

PORTNAME=	bugzillatools
PORTVERSION=	0.5.3.1
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	swills@FreeBSD.org
COMMENT=	Tool for interacting with the Bugzilla bug tracking system

LICENSE=	GPLv3

USES=		python:2
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
