# Created by: Sergey A. Osokin <osa@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/math/p5-Statistics-Lite/Makefile 401225 2015-11-11 04:04:22Z osa $

PORTNAME=	Statistics-Lite
PORTVERSION=	3.62
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	osa@FreeBSD.org
COMMENT=	The lightweight and functional object-oriented statistics

USES=		dos2unix perl5
USE_PERL5=	configure

.include <bsd.port.mk>
