# $FreeBSD: tags/RELEASE_10_3_0/archivers/pear-Horde_Pack/Makefile 372167 2014-11-04 19:46:21Z mm $

PORTNAME=	Horde_Pack
PORTVERSION=	1.0.5
CATEGORIES=	archivers www pear
PKGNAMEPREFIX=	pear-

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Pack Utility

USES=		horde
USE_HORDE_RUN=	Horde_Compress_Fast \
		Horde_Exception

.include <bsd.port.mk>
