# Created by: Matthew Seaman <matthew@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/math/p5-Math-Fleximal/Makefile 397550 2015-09-22 16:18:31Z matthew $

PORTNAME=	Math-Fleximal
PORTVERSION=	0.06
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	matthew@FreeBSD.org
COMMENT=	Integers with flexible representations

NO_ARCH=	yes

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
