# Created by: Patrick Li <pat@databits.net>
# $FreeBSD: tags/RELEASE_10_3_0/lang/slisp/Makefile 345787 2014-02-24 09:04:30Z gahr $

PORTNAME=	slisp
PORTVERSION=	1.2
CATEGORIES=	lang lisp
MASTER_SITES=	http://www.sigala.it/sandro/files/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Simple Lisp interpreter

LICENSE=	BSD2CLAUSE

GNU_CONFIGURE=	yes

INFO=		slisp
PLIST_FILES=	bin/slisp \
		man/man1/slisp.1.gz

.include <bsd.port.mk>
