# Created by: Gabor Kovesdan
# $FreeBSD: tags/RELEASE_10_3_0/security/p5-Crypt-Imail/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Crypt-Imail
PORTVERSION=	0.01
PORTREVISION=	1
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Perl extension to encrypt and decrypt Imail passwords

USES=		perl5
USE_PERL5=	configure

WRKSRC=		${WRKDIR}/Imail

.include <bsd.port.mk>
