# Created by: chinsan
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Perl6-Builtins/Makefile 381151 2015-03-12 23:00:02Z adamw $

PORTNAME=	Perl6-Builtins
PORTVERSION=	0.0.3
PORTREVISION=	2
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Provide Perl 5 versions of the new Perl 6 builtins

BUILD_DEPENDS=	p5-Contextual-Return>=0:${PORTSDIR}/devel/p5-Contextual-Return
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
