# Created by: Hye-Shik Chang
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-repl/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	repl
PORTVERSION=	0.8.4
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	pyrepl-${PORTVERSION}
DIST_SUBDIR=	python

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Replacement for readline and interactive environment for Python

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
