# Created by: Kimura Fuyuki <fuyuki@hadaly.org>
# $FreeBSD: tags/RELEASE_10_3_0/net/p5-Net-Finger/Makefile 386075 2015-05-11 12:04:18Z mat $

PORTNAME=	Net-Finger
PORTVERSION=	1.06
PORTREVISION=	1
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl implementation of a finger client

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
