# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/math/R-cran-labeling/Makefile 367888 2014-09-10 20:50:31Z gerald $

PORTNAME=	labeling
PORTVERSION=	0.3
PORTREVISION=	1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Provides a range of axis labeling algorithms

LICENSE=	MIT

USES=	cran:auto-plist

.include <bsd.port.mk>
