# $FreeBSD: tags/RELEASE_10_3_0/news/husky-huskylib/Makefile 397523 2015-09-21 22:09:08Z bdrewery $

PORTNAME=	husky-huskylib

COMMENT=	Husky generic FTN library

INSTALL_TARGET= install install-man
USE_LDCONFIG=	yes

MASTERDIR=	${.CURDIR}/../husky
COMPONENT_SUBDIR=	huskylib

.include "${MASTERDIR}/Makefile"
