# Created by: Aaron Dalton <aaron@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/x11-fonts/p5-Font-TTFMetrics/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	Font-TTFMetrics
PORTVERSION=	0.1
PORTREVISION=	1
CATEGORIES=	x11-fonts perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Parser for the TTF file

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
