# Created by: James Bailie <jimmy@mammothcheese.ca>
# $FreeBSD: tags/RELEASE_10_3_0/net-im/chattahoochie/Makefile 367236 2014-09-03 21:07:17Z antoine $

PORTNAME=	chattahoochie
PORTVERSION=	1.9
CATEGORIES=	net-im
MASTER_SITES=	http://www.mammothcheese.ca/

MAINTAINER=	jimmy@mammothcheese.ca
COMMENT=	Small group plain-text chat server

MAKE_ENV=	INSTALL_MAN="${INSTALL_MAN}" INSTALL_PROGRAM="${INSTALL_PROGRAM}" \
		INSTALL_SCRIPT="${INSTALL_SCRIPT}"

.include <bsd.port.mk>
