# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Module-Pluggable/Makefile 396667 2015-09-11 14:15:10Z lth $

PORTNAME=	Module-Pluggable
PORTVERSION=	5.2
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Automatically give your module the ability to have plugins

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
