# Created by: Murilo Opsfelder <mopsfelder@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Unix-Uptime/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Unix-Uptime
PORTVERSION=	0.3701
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	mopsfelder@gmail.com
COMMENT=	Determine the current uptime in seconds

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
