# Created by: Tim Robbins <tim@robbins.dropbear.id.au>
# $FreeBSD: tags/RELEASE_10_3_0/net/coda6_client/Makefile 362028 2014-07-16 04:01:36Z vanilla $

PORTREVISION=	3

COMMENT=	Client programs for a replicated high-performance network file system

MASTERDIR=	${.CURDIR}/../coda6_server
PKGDIR=		${.CURDIR}

CODA_SUITE=	client

.include "${MASTERDIR}/Makefile"
