# Created by: mharo@FreeBSD.org
# $FreeBSD: tags/RELEASE_10_3_0/net/p5-Net-CIDR-Lite/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Net-CIDR-Lite
PORTVERSION=	0.21
PORTREVISION=	1
CATEGORIES=	net perl5 ipv6
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl extension for merging IPv4 or IPv6 CIDR addresses

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
