# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-List-UtilsBy/Makefile 394930 2015-08-21 08:05:45Z kuriyama $

PORTNAME=	List-UtilsBy
PORTVERSION=	0.10
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension for higher-order list utility functions

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	YES

.include <bsd.port.mk>
