# Created by: UMENO Takashi
# $FreeBSD: tags/RELEASE_10_3_0/games/gbottler/Makefile 390159 2015-06-20 10:26:46Z rm $

PORTNAME=	gbottler
PORTVERSION=	0.1.7
PORTREVISION=	2
CATEGORIES=	games
MASTER_SITES=	SFJP/gbottler/45155

MAINTAINER=	ports@FreeBSD.org
COMMENT=	SSTP Bottle client

NO_ARCH=	yes
USES=		gettext-tools gmake python:2
USE_GNOME=	pygtk2
PLIST_SUB=	VERSION=${PORTVERSION}

.include <bsd.port.mk>
