# Created by: Zane C, Bowers <vvelox@vvelox.net>
# $FreeBSD: tags/RELEASE_10_3_0/net/p5-Net-LDAP-AutoDNs/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Net-LDAP-AutoDNs
PORTVERSION=	0.2.2
PORTREVISION=	1
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:VVELOX
PKGNAMEPREFIX=	p5-

MAINTAINER=	vvelox@vvelox.net
COMMENT=	Automatically make some default decisions some LDAP DNs and scopes

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
