# Created by: Dmitry Liakh <dliakh@ukr.net>
# $FreeBSD: tags/RELEASE_10_3_0/databases/p5-Text-xSV/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Text-xSV
PORTVERSION=	0.21
PORTREVISION=	1
CATEGORIES=	databases
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	dliakh@ukr.net
COMMENT=	Read character separated files

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
