# Created by: Timur I. Bakeyev <bat@cpan.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Shell-Source/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	Shell-Source
PORTVERSION=	0.01
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Run programs and inherit environment changes

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
