# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/x11/libXxf86vm/Makefile 389656 2015-06-14 20:57:23Z avilla $

PORTNAME=	libXxf86vm
PORTVERSION=	1.1.4
PORTREVISION=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Vidmode Extension

LICENSE=	MIT

XORG_CAT=	lib
USE_XORG=	xproto x11 xextproto xext xf86vidmodeproto:both
USES+=	cpe
CPE_PRODUCT=	libxxf86vm
CPE_VENDOR=	x

.include <bsd.port.mk>
