# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/multimedia/gstreamer-plugins-schroedinger/Makefile 352119 2014-04-25 12:46:45Z bapt $

PORTREVISION=	1
CATEGORIES=	multimedia

COMMENT=	Gstreamer Dirac high-speed codec plugin

GST_PLUGIN=	schroedinger

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
