# $FreeBSD: releng/10.3/gnu/lib/tests/Makefile 264741 2014-04-21 21:39:25Z jmmv $

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/gnu/lib

.PATH:		${.CURDIR:H:H:H}/tests
KYUAFILE=	yes

.include <bsd.test.mk>
