# Created by: Pav Lucistnik <pav@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/pear-Spreadsheet_Excel_Writer/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	Spreadsheet_Excel_Writer
PORTVERSION=	0.9.3
CATEGORIES=	textproc www pear

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	PEAR class for writing Microsoft Excel files

LICENSE=	LGPL3

BUILD_DEPENDS=	${PEARDIR}/OLE.php:${PORTSDIR}/devel/pear-OLE
RUN_DEPENDS=	${PEARDIR}/OLE.php:${PORTSDIR}/devel/pear-OLE

USES=	pear

.include <bsd.port.mk>
