# Created by: Don Croyle <croyle@gelemna.org>
# $FreeBSD: tags/RELEASE_10_3_0/math/p5-Set-IntSpan/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Set-IntSpan
PORTVERSION=	1.19
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	danilo@FreeBSD.org
COMMENT=	Manages sets of integers

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
