# Created by: Michael Moll <kvedulv at kvedulv.de>
# $FreeBSD: tags/RELEASE_10_3_0/www/rubygem-rack-cors/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	rack-cors
PORTVERSION=	0.4.0
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Middleware that will make Rack-based apps CORS compatible

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
