# Created by: Andreas Fehlner <fehlner@gmx.de>
# $FreeBSD: tags/RELEASE_10_3_0/ftp/cmdftp/Makefile 343335 2014-02-08 14:20:51Z danilo $

PORTNAME=	cmdftp
PORTVERSION=	0.9.8
CATEGORIES=	ftp
MASTER_SITES=	SAVANNAH

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Command line shell-like ftp client

LICENSE=	GPLv3

GNU_CONFIGURE=	yes

PLIST_FILES=	bin/cmdftp man/man1/${PORTNAME}.1.gz

.include <bsd.port.mk>
