# $FreeBSD: tags/RELEASE_10_3_0/german/Makefile 402562 2015-11-28 23:08:03Z rene $
#

    COMMENT = German support

    SUBDIR += BBBike
    SUBDIR += alt-aspell
    SUBDIR += aspell
    SUBDIR += bugzilla44
    SUBDIR += calligra-l10n
    SUBDIR += dict
    SUBDIR += ding
    SUBDIR += dtaus
    SUBDIR += eric4
    SUBDIR += eric6
    SUBDIR += geonext
    SUBDIR += gimp-help
    SUBDIR += hunspell
    SUBDIR += hyphen
    SUBDIR += jdictionary-eng-ger
    SUBDIR += jdictionary-ger-hun
    SUBDIR += kde4-l10n
    SUBDIR += libreoffice
    SUBDIR += mediathek
    SUBDIR += mythes
    SUBDIR += phone
    SUBDIR += php_doc
    SUBDIR += schwobifyer
    SUBDIR += selfhtml
    SUBDIR += steak
    SUBDIR += tipp10
    SUBDIR += trytond28_account_de_skr03
    SUBDIR += unix-connect
    SUBDIR += webalizer2
    SUBDIR += wordpress

.include <bsd.port.subdir.mk>
