# Created by: Jonathan Anderson <jonathan@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/git-cola/Makefile 397625 2015-09-23 16:56:05Z antoine $

PORTNAME=	git-cola
PORTVERSION=	2.2.1
DISTVERSIONPREFIX=	v
CATEGORIES=	devel

MAINTAINER=	jonathan@FreeBSD.org
COMMENT=	Sleek and powerful Git GUI

LICENSE=	GPLv2

USE_GITHUB=	yes

USES=		desktop-file-utils gettext gmake python
INSTALLS_ICONS=	YES

MAKE_ARGS=	prefix=${PREFIX} PYTHON=${PYTHON_CMD}

.include <bsd.port.mk>
