# $FreeBSD: tags/RELEASE_10_3_0/java/openjdk6-jre/Makefile 394508 2015-08-17 14:20:40Z mat $

CATEGORIES=	java devel
PKGNAMESUFFIX=	-jre

COMMENT=	Oracle's Java 6 Runtime Environment under the GPL v2

BUILD_JRE=	yes
MASTERDIR=	${.CURDIR}/../openjdk6

.include "${MASTERDIR}/Makefile"
