# $FreeBSD: tags/RELEASE_10_3_0/x11-drivers/xf86-input-void/Makefile 399179 2015-10-13 07:45:08Z kwm $

PORTNAME=	xf86-input-void
PORTVERSION=	1.4.1
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org void input driver

XORG_CAT=	driver

.include <bsd.port.mk>
