# Created by: hq@FreeBSD.org
# $FreeBSD: tags/RELEASE_10_3_0/german/jdictionary-eng-ger/Makefile 358525 2014-06-20 07:48:40Z vanilla $

PORTNAME=	jdictionary-eng-ger
PORTVERSION=	1.4
PORTREVISION=	2
CATEGORIES=	german textproc
MASTER_SITES=	SF/jdictionary/Plugins%20for%20jDictionary/Smart%20English-German
DISTNAME=	SmartEngGer-1_4.jar

COMMENT=	JDictionary plugin: English-German dictionary

MASTERDIR=	${.CURDIR}/../../textproc/jdictionary

.include "${MASTERDIR}/Makefile.plugin"
