# Created by: Aaron Dalton <aaron@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/math/p5-Math-Units/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Math-Units
PORTVERSION=	1.3
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Unit conversion

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
