# $FreeBSD: tags/RELEASE_10_3_0/textproc/rubygem-syntax/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	syntax
PORTVERSION=	1.2.0
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Module for using Systax highlighting in Ruby

LICENSE=	BSD3CLAUSE

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
