# $FreeBSD: tags/RELEASE_10_3_0/x11-drivers/xf86-video-cirrus/Makefile 399179 2015-10-13 07:45:08Z kwm $

PORTNAME=	xf86-video-cirrus
PORTVERSION=	1.5.3
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org cirrus display driver

XORG_CAT=	driver

.include <bsd.port.mk>
