# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/math/R-cran-geepack/Makefile 403949 2015-12-18 02:03:44Z wen $

PORTNAME=	geepack
DISTVERSION=	1.2-0
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Generalized Estimating Equation Package

LICENSE=	GPLv3

USES=		cran:auto-plist

.include <bsd.port.mk>
