# Created by: chinsan
# $FreeBSD: tags/RELEASE_10_3_0/games/p5-Acme-GuessNumber/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	Acme-GuessNumber
PORTVERSION=	0.04
PORTREVISION=	1
CATEGORIES=	games perl5
MASTER_SITES=	CPAN/Locale/IMACAT
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Automatic number guessing game robot

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
