# Created by: Ben Kibbey <bjk@arbornet.org>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/userinfo/Makefile 380264 2015-03-02 14:22:28Z zi $

PORTNAME=	userinfo
PORTVERSION=	2.5
CATEGORIES=	sysutils
MASTER_SITES=	SF/${PORTNAME}/${PORTVERSION}

MAINTAINER=	zi@FreeBSD.org
COMMENT=	Show information about local users

LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		libtool tar:bzip2
GNU_CONFIGURE=	yes
INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
