# Created by: renchap@cocoa-x.com
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-mixlib-config/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	mixlib-config
PORTVERSION=	2.1.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	renchap@cocoa-x.com
COMMENT=	Class based config mixin, similar to the one found in Chef

LICENSE=	APACHE20

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
