# Created by: Zane C, Bowers <vvelox@vvelox.net>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/p5-Sys-Group-GIDhelper/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Sys-Group-GIDhelper
PORTVERSION=	0.0.2
PORTREVISION=	1
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:VVELOX
PKGNAMEPREFIX=	p5-

MAINTAINER=	vvelox@vvelox.net
COMMENT=	Helps for locating free GIDs

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
