# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Lingua-EN-Gender/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Lingua-EN-Gender
PORTVERSION=	0.02
PORTREVISION=	2
PORTEPOCH=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Inflect pronouns for gender

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
