# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/math/p5-Geo-Coordinates-UTM/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	Geo-Coordinates-UTM
PORTVERSION=	0.11
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl extension for converting latitude/longitude to UTM

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
