# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/multimedia/gstreamer-plugins-theora/Makefile 352119 2014-04-25 12:46:45Z bapt $
#   $MCom: ports/multimedia/gstreamer-plugins-theora/Makefile,v 1.4 2008/03/21 04:01:32 ahze Exp $

PORTREVISION=	1
CATEGORIES=	multimedia

COMMENT=	Gstreamer theora plugin

GST_PLUGIN=	theora

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
