# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Class-ErrorHandler/Makefile 396668 2015-09-11 14:22:20Z lth $

PORTNAME=	Class-ErrorHandler
PORTVERSION=	0.04
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Base class for error handling

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
