# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/R-cran-scrapeR/Makefile 367888 2014-09-10 20:50:31Z gerald $

PORTNAME=	scrapeR
PORTVERSION=	0.1.6
PORTREVISION=	13
CATEGORIES=	www
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Tools for Scraping Data from HTML and XML Documents

RUN_DEPENDS=	R-cran-XML>0:${PORTSDIR}/textproc/R-cran-XML \
		R-cran-RCurl>0:${PORTSDIR}/ftp/R-cran-RCurl

USES=	cran:auto-plist

.include <bsd.port.mk>
