# Created by: Terry Sposato <terry@sucked-in.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Sys-MemInfo/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Sys-MemInfo
PORTVERSION=	0.91
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	terry@sucked-in.com
COMMENT=	Sys::MemInfo - Perl extension for getting Memory information

WRKSRC=	${WRKDIR}/${PORTNAME}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
