# $FreeBSD: tags/RELEASE_10_3_0/sysutils/cfengine-masterfiles/Makefile 403174 2015-12-07 03:10:43Z cy $

VERSIONS=		36 37
CFENGINE_VERSION?=	37

MASTERDIR=		${.CURDIR}/../cfengine-masterfiles${CFENGINE_VERSION}

.include "${MASTERDIR}/Makefile"
