# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: tags/RELEASE_10_3_0/net/pear-Net_IPv6/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Net_IPv6
DISTVERSION=	1.2.1
CATEGORIES=	net pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Check and validate IPv6 addresses

USES=	pear

PORTSCOUT=		skipv:1.2.2b,1.2.2b2

.include <bsd.port.mk>
