# $FreeBSD: tags/RELEASE_10_3_0/x11-servers/Makefile 343824 2014-02-11 21:56:02Z swills $
#

    COMMENT = X11 servers

    SUBDIR += Xfstt
    SUBDIR += mga_hal
    SUBDIR += x11rdp
    SUBDIR += x2vnc
    SUBDIR += x2x
    SUBDIR += xephyr
    SUBDIR += xorg-dmx
    SUBDIR += xorg-nestserver
    SUBDIR += xorg-server
    SUBDIR += xorg-vfbserver

.include <bsd.port.subdir.mk>
