# Created by: ports@c0decafe.net
# $FreeBSD: tags/RELEASE_10_3_0/security/p5-Data-Password/Makefile 377615 2015-01-21 15:03:22Z culot $

PORTNAME=	Data-Password
PORTVERSION=	1.12
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Assess password quality

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
