# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-YAML-Shell/Makefile 390988 2015-06-30 19:40:04Z swills $

PORTNAME=	YAML-Shell
PORTVERSION=	0.69
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:INGY
PKGNAMEPREFIX=	p5-

MAINTAINER=	swills@FreeBSD.org
COMMENT=	YAML Test Shell

BUILD_DEPENDS=	p5-YAML>=0.67:${PORTSDIR}/textproc/p5-YAML
RUN_DEPENDS=	p5-YAML>=0.67:${PORTSDIR}/textproc/p5-YAML

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
