# Created by: Konstantin Chuguev <Konstantin.Chuguev@dante.org.uk>
# $FreeBSD: tags/RELEASE_10_3_0/converters/iconv-rfc1345/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	iconv-rfc1345
PORTVERSION=	2.0
CATEGORIES=	converters
MASTER_SITES=	LOCAL/bland

MAINTAINER=	bland@FreeBSD.org
COMMENT=	Additional charset modules for the iconv library (from RFC1345)

LIB_DEPENDS=	libbiconv.so:${PORTSDIR}/converters/iconv

USES=		perl5 uidfix

.include <bsd.port.mk>
