# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/R-cran-markdown/Makefile 393713 2015-08-08 06:19:03Z tota $

PORTNAME=	markdown
PORTVERSION=	0.7.7
CATEGORIES=	textproc
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Markdown Rendering for R

LICENSE=	GPLv2

RUN_DEPENDS=	R-cran-mime>=0.3:${PORTSDIR}/misc/R-cran-mime

USES=	cran:auto-plist

.include <bsd.port.mk>
