# $FreeBSD: tags/RELEASE_10_3_0/www/sws/Makefile 380221 2015-03-01 18:11:26Z rpaulo $

PORTNAME=	sws
PORTVERSION=	1.0
CATEGORIES=	www
MASTER_SITES=	http://prd4.wynn.com:8080/src/

MAINTAINER=	wynkoop@wynn.com
COMMENT=	Simple, safe, secure, web server written in /bin/sh

LICENSE=	BSD2CLAUSE

NO_ARCH=	yes

.include <bsd.port.mk>
