# Created by: Torsten Zuhlsdorff <ports@toco-domains.de>
# $FreeBSD: tags/RELEASE_10_3_0/www/rubygem-turbolinks-rails41/Makefile 402315 2015-11-23 19:01:10Z sunpoet $

PKGNAMESUFFIX=	-rails41

RUN_DEPENDS=	rubygem-coffee-rails41>=4.1.0:${PORTSDIR}/devel/rubygem-coffee-rails41

MASTERDIR=	${.CURDIR}/../rubygem-turbolinks

.include "${MASTERDIR}/Makefile"
