# Created by: clsung@dragon2.net
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Sort-Tree/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Sort-Tree
PORTVERSION=	1.09
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module for sorting a objects into a tree structure

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
