# Created by: Mark Felder <feld@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-bluelet/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	bluelet
PORTVERSION=	0.2.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	feld@FreeBSD.org
COMMENT=	Pure-Python asynchronous I/O using coroutines

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils

PLIST_FILES=	%%PYTHON_SITELIBDIR%%/bluelet.py \
		%%PYTHON_SITELIBDIR%%/bluelet.pyc \
		%%PYTHON_SITELIBDIR%%/bluelet.pyo

.include <bsd.port.mk>
