# $FreeBSD: tags/RELEASE_10_3_0/archivers/pear-Horde_Compress_Fast/Makefile 376829 2015-01-12 14:54:44Z mm $

PORTNAME=	Horde_Compress_Fast
PORTVERSION=	1.1.0
CATEGORIES=	archivers www pear
PKGNAMEPREFIX=	pear-

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Fast Compression Library

USES=	horde
USE_HORDE_RUN=	Horde_Exception

.include <bsd.port.mk>
