# Created by: Tatsumi Hosokawa
# $FreeBSD: tags/RELEASE_10_3_0/x11/kb2mb2/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	kb2mb2
PORTVERSION=	1.0
PORTREVISION=	3
CATEGORIES=	x11
MASTER_SITES=	PORTS_JP

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Redirect any key to second mouse button

PLIST_FILES=	bin/kb2mb2
USES=		imake
USE_XORG=	x11 xext xtst

.include <bsd.port.mk>
