# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-Math_Fraction/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Math_Fraction
PORTVERSION=	0.4.1
CATEGORIES=	devel www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Classes that represent and manipulate fractions

USES=	pear

.include <bsd.port.mk>
