# Created by: Nobutaka Mantani <nobutaka@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/net/py-pygeoip/Makefile 385640 2015-05-07 17:26:05Z mat $

PORTNAME=	pygeoip
PORTVERSION=	0.3.2
DISTVERSIONPREFIX=	v
CATEGORIES=	net python geography
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nobutaka@FreeBSD.org
COMMENT=	Pure Python GeoIP API

LICENSE=	LGPL3
LICENSE_FILE=	${WRKSRC}/LICENSE.md

USES=		python
USE_PYTHON=	distutils autoplist

USE_GITHUB=	yes
GH_ACCOUNT=	appliedsec

.include <bsd.port.mk>
