# Created by: will
# $FreeBSD: tags/RELEASE_10_3_0/security/p5-Crypt-ECB/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Crypt-ECB
PORTVERSION=	1.45
PORTREVISION=	1
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl module implementing the ECB encryption algorithm

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
