# Created by: Dmitry Sivachenko <demon@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/py-tinycss/Makefile 373452 2014-11-26 15:16:33Z demon $

PORTNAME=	tinycss
PORTVERSION=	0.3
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	demon@FreeBSD.org
COMMENT=	A complete yet simple CSS parser for Python

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
