# Created by: Kelly Yancey <kbyanc@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/net/p5-Net-Radius/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Net-Radius
PORTVERSION=	2.103
PORTREVISION=	1
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module to manipulate RADIUS packets

TEST_DEPENDS=	p5-Test-Warn>=0:${PORTSDIR}/devel/p5-Test-Warn

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
