# Created by: Jacob Myers
# $FreeBSD: tags/RELEASE_10_3_0/games/bsdrain/Makefile 367512 2014-09-07 11:04:57Z antoine $

PORTNAME=	bsdrain
PORTVERSION=	5.0
CATEGORIES=	games
MASTER_SITES=	http://freebsd.unixfreunde.de/sources/ \
		http://whotookspaz.org/misc/freebsd/rain/
DISTNAME=	rain-${PORTVERSION}

MAINTAINER=	jacob@whotookspaz.org
COMMENT=	The original BSD rain program, ported from NetBSD

PLIST_FILES=	bin/rain \
		man/man6/rain.6.gz

USES=		tar:bzip2 uidfix

.include <bsd.port.mk>
