# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/math/p5-Statistics-Benford/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Statistics-Benford
PORTVERSION=	0.08
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Calculate the deviation from Benford's Law

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
