# $FreeBSD: tags/RELEASE_10_3_0/x11-drivers/xf86-video-neomagic/Makefile 399179 2015-10-13 07:45:08Z kwm $

PORTNAME=	xf86-video-neomagic
PORTVERSION=	1.2.9
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org neomagic display driver

XORG_CAT=	driver
USE_XORG=	xf86dgaproto

.include <bsd.port.mk>
