# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-HTML_TreeMenu/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	HTML_TreeMenu
PORTVERSION=	1.2.2
CATEGORIES=	devel www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Provides an API to create a HTML tree

USES=	pear

.include <bsd.port.mk>
