# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-Horde_Itip/Makefile 384516 2015-04-22 19:58:46Z mm $

PORTNAME=	Horde_Itip
PORTVERSION=	2.1.0
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde iTip invitation response handling

USES=		horde
USE_HORDE_RUN=	Horde_Icalendar \
		Horde_Mime

.include <bsd.port.mk>
