# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/pear-XML_Feed_Parser/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	XML_Feed_Parser
PORTVERSION=	1.0.5
CATEGORIES=	textproc devel pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Providing a unified API for handling Atom/RSS

USES=		pear
USE_PHP=	tidy dom

.include <bsd.port.mk>
