# Created by: Autrijus Tang <autrijus@autrijus.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-IPC-Run3/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	IPC-Run3
PORTVERSION=	0.048
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Run a subprocess in batch mode

# Any version of the following licenses are acceptable
LICENSE=	ART10 GPLv1 BSD2CLAUSE
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
