# $FreeBSD: tags/RELEASE_10_3_0/net/py-dugong/Makefile 404243 2015-12-22 15:31:05Z miwi $

PORTNAME=	dugong
PORTVERSION=	3.5
CATEGORIES=	net python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	niklaas@kulturflatrate.net
COMMENT=	HTTP 1.1 client module designed for RESTful protocols

LICENSE=	PSFL
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python:3.3+ tar:bzip2
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
