# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/rubygem-loggability/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	loggability
PORTVERSION=	0.11.0
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Composable logging system built on the standard Logger library

LICENSE=	BSD3CLAUSE

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
