# Created by: Vanilla I. Shu <vanilla@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/net/p5-Net-Daemon/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Net-Daemon
PORTVERSION=	0.48
PORTREVISION=	1
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:MNOONING
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 extension for portable daemons

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
