# Created by: Alex Miller (<asm@asm.kiev.ua>)
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-HTML_Template_IT/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	HTML_Template_IT
PORTVERSION=	1.3.0
PORTEPOCH=	1
CATEGORIES=	devel www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PEAR Integrated template API

USES=	pear

.include <bsd.port.mk>
