# Created by: will
# $FreeBSD: tags/RELEASE_10_3_0/security/p5-Crypt-Twofish/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Crypt-Twofish
PORTVERSION=	2.17
PORTREVISION=	1
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module implementing the Twofish cipher

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
