# Created by: Mario Sergio Fujikawa Ferreira <lioux@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/libebml/Makefile 403052 2015-12-05 10:05:17Z bapt $

PORTNAME=	libebml
PORTVERSION=	1.3.3
CATEGORIES=	textproc
MASTER_SITES=	http://dl.matroska.org/downloads/libebml/ \
		http://www.bunkus.org/videotools/mkvtoolnix/sources/

MAINTAINER=	multimedia@FreeBSD.org
COMMENT=	EBML (Extensible Binary Meta Language), sort of binary version of XML

LICENSE=	LGPL21

USES=		gmake libtool pathfix tar:bzip2
USE_LDCONFIG=	yes
GNU_CONFIGURE=	yes

INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
