# Created by: Martin Matuska <martin@matuska.org>
# $FreeBSD: tags/RELEASE_10_3_0/databases/luasql-sqlite3/Makefile 357266 2014-06-10 05:49:41Z bapt $

PORTNAME=	luasql

LUASQL_DRIVER=	sqlite3

MASTERDIR=	${.CURDIR}/../luasql-mysql

.include "${MASTERDIR}/Makefile"
