# Created by: Peter Wemm <peter@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/editors/hexpert/Makefile 367527 2014-09-07 11:59:25Z antoine $

PORTNAME=	hexpert
PORTVERSION=	2.4.1
CATEGORIES=	editors
MASTER_SITES=	LOCAL/peter

MAINTAINER=	peter@FreeBSD.org
COMMENT=	Hexpert - a simple but flexible binary file editor

USES=		uidfix
MAKE_ENV=	NO_MAN=yes NO_OBJ=yes

PLIST_FILES=	bin/hex

.include <bsd.port.mk>
