# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Set-CrossProduct/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Set-CrossProduct
PORTVERSION=	1.95
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:BDFOY
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Work with the cross product of two or more sets

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
