# Created by: arved
# $FreeBSD: tags/RELEASE_10_3_0/audio/xmms-scrobbler/Makefile 352968 2014-05-04 18:48:54Z tijl $

PORTNAME=	xmms-scrobbler
PORTREVISION=	7

MAINTAINER=	novel@FreeBSD.org
COMMENT=	XMMS plugin for Audioscrobbler.com

CONFLICTS=	scrobbler-*

MASTERDIR=	${.CURDIR}/../scrobbler

OPTIONS_SLAVE=	XMMS

.include "${MASTERDIR}/Makefile"
