# Created by: Dan Rench <citric@cubicone.tmetic.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Regexp-Grammars/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Regexp-Grammars
PORTVERSION=	1.026
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	citric@cubicone.tmetic.com
COMMENT=	Add grammatical parsing features to Perl 5.10 regexes

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
