# Created by: Marcin Cieslak <saper@saper.info>
# $FreeBSD: tags/RELEASE_10_3_0/deskutils/x026/Makefile 363374 2014-07-29 19:11:51Z adamw $

PORTNAME=	x026
PORTVERSION=	1.2
CATEGORIES=	deskutils
MASTER_SITES=	SF/x3270/${PORTNAME}/${PORTVERSION}

MAINTAINER=	saper@saper.info
COMMENT=	IBM 026 Keypunch Emulator for the X Window System

USES=		imake tar:tgz
USE_XORG=	xaw7 xpm xt

PLIST_FILES=	bin/${PORTNAME} \
		man/man1/x026.1.gz

.include <bsd.port.mk>
