# $FreeBSD: tags/RELEASE_10_3_0/x11/xkbevd/Makefile 399844 2015-10-20 13:49:18Z kwm $

PORTNAME=	xkbevd
PORTVERSION=	1.1.4
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	XKB event daemon

LICENSE=	MIT

XORG_CAT=	app
USE_XORG=	xkbfile x11

PLIST_FILES=	bin/xkbevd man/man1/xkbevd.1.gz

.include <bsd.port.mk>
