# Created by: Mark Pulford <mark@kyne.com.au>
# $FreeBSD: tags/RELEASE_10_3_0/audio/id3tool/Makefile 357139 2014-06-09 11:21:52Z olgeni $

PORTNAME=	id3tool
PORTVERSION=	1.2a
CATEGORIES=	audio
MASTER_SITES=	http://nekohako.xware.cx/id3tool/

MAINTAINER=	gavin@FreeBSD.org
COMMENT=	Utility for manipulating mp3 ID3 Tags

GNU_CONFIGURE=	yes

PLIST_FILES=	bin/id3tool man/man1/id3tool.1.gz

.include <bsd.port.mk>
