# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Text-Format/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Text-Format
PORTVERSION=	0.58
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Various subroutines to format text

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
