# Created by: Marc Fonvieille <blackend@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/misc/freebsd-doc-bn/Makefile 354559 2014-05-19 16:43:45Z blackend $

CATEGORIES=	misc docs
PKGNAMEPREFIX=	bn-

MAINTAINER=	doceng@FreeBSD.org
COMMENT=	Bengali translation of the FreeBSD Documentation Project

MASTERDIR=	${.CURDIR}/../freebsd-doc-en
PLIST=		${.CURDIR}/pkg-plist

DOCLANG=	bn_BD.UTF-8

.include "${MASTERDIR}/Makefile"
