# Created by: Alonso Cardenas Marquez <acm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/emulators/mupen64plus-ui-console/Makefile 389666 2015-06-15 03:27:50Z acm $

PORTREVISION=	0
PKGNAMESUFFIX=	-ui-console

COMMENT=	UI for Mupen64plus

MASTERDIR=	${.CURDIR}/../mupen64plus-core

OPTIONS_DEFINE=	#

.include "${MASTERDIR}/Makefile"
