# Created by: Kouki Hashimoto <hsmtkk@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-unittestplus/Makefile 370613 2014-10-10 22:30:56Z antoine $

PORTNAME=	unittestplus
PORTVERSION=	1.1.1
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	hsmtkk@gmail.com
COMMENT=	Test utilities built on unittest

USES=		python zip
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
