# Created by: Maksym Sobolyev <sobomax@pbxpress.it>
# $FreeBSD: tags/RELEASE_10_3_0/net/p5-Net-Syslog/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Net-Syslog
PORTVERSION=	0.04
PORTREVISION=	1
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sobomax@FreeBSD.org
COMMENT=	Perl extension for sending syslog messages to a remote syslogd

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
