# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/graphics/gstreamer-plugins-aalib/Makefile 352119 2014-04-25 12:46:45Z bapt $
#   $MCom: ports/graphics/gstreamer-plugins-aalib/Makefile,v 1.5 2008/03/19 14:05:33 ahze Exp $

PORTREVISION=	1
CATEGORIES=	graphics

COMMENT=	Gstreamer ASCII art plugin

GST_PLUGIN=	aalib

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
