# Created by: James Bailie <jimmy@mammothcheese.ca>
# $FreeBSD: tags/RELEASE_10_3_0/devel/libdombey/Makefile 403995 2015-12-19 01:05:46Z junovitch $

PORTNAME=	libdombey
PORTVERSION=	5.25
CATEGORIES=	devel
MASTER_SITES=	http://www.mammothcheese.ca/

MAINTAINER=	jimmy@mammothcheese.ca
COMMENT=	SCGI application server in a library

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_LDCONFIG=	yes

DESTDIRNAME=	STAGEDIR

PLIST_SUB=	PORTVERSION=${PORTVERSION}

.include <bsd.port.mk>
