# Created by: James Bailie <jimmy@mammothcheese.ca>
# $FreeBSD: tags/RELEASE_10_3_0/www/ephemera/Makefile 404908 2015-12-31 06:04:45Z miwi $

PORTNAME=	ephemera
PORTVERSION=	5.9
CATEGORIES=	www
MASTER_SITES=	http://www.mammothcheese.ca/

MAINTAINER=	jimmy@mammothcheese.ca
COMMENT=	Blog server

LICENSE=	BSD3CLAUSE

RUN_DEPENDS=	munger:${PORTSDIR}/lang/munger

DATADIR=	${PREFIX}/share/ephemera

USE_SQLITE=	3

.include <bsd.port.mk>
