# Created by: kirk@daycos.com
# $FreeBSD: tags/RELEASE_10_3_0/databases/pgdbf/Makefile 396220 2015-09-06 14:15:14Z danfe $

PORTNAME=	pgdbf
PORTVERSION=	0.6.2
CATEGORIES=	databases
MASTER_SITES=	SF

MAINTAINER=	kirk@strauser.com
COMMENT=	Convert XBase / FoxPro tables to PostgreSQL

LICENSE=	GPLv3

USES=		gmake tar:xz
GNU_CONFIGURE=	yes

PLIST_FILES=	bin/pgdbf \
		%%DOCSDIR%%/README \
		man/man1/pgdbf.1.gz

.include <bsd.port.mk>
