# Created by: Steven Kreuzer <skreuzer@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-jedi/Makefile 369655 2014-09-30 19:08:43Z skreuzer $

PORTNAME=	jedi
PORTVERSION=	0.8.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTVERSION=	${PORTVERSION}-final0

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Autocompletion tool for Python

USES=		python:2
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
