# $FreeBSD: tags/RELEASE_10_3_0/www/twiki-SmiliesPlugin/Makefile 362252 2014-07-19 11:09:51Z ohauer $

PORTNAME=	SmiliesPlugin
SVNREV=		16417

COMMENT=	Converts smilies into icons automatically

.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
