# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Module-Install-Repository/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Module-Install-Repository
PORTVERSION=	0.06
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension to set repository URL from svn/svk/Git checkout

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
