# $FreeBSD: tags/RELEASE_10_3_0/www/twiki-PatternSkin/Makefile 362252 2014-07-19 11:09:51Z ohauer $

PORTNAME=	PatternSkin
SVNREV=		17425

COMMENT=	CSS-based skin

TWDEP=		TwistyPlugin>=0 TablePlugin>=0

.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
