# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/p5-Apache-Admin-Config/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Apache-Admin-Config
PORTVERSION=	0.95
PORTREVISION=	1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module to manipulate Apache configuration files

USES=		perl5
USE_PERL5=	configure patch

.include <bsd.port.mk>
