# Created by: Timur Bakeyev <bat@cpan.org>
# $FreeBSD: tags/RELEASE_10_3_0/converters/p5-URI-UTF8-Punycode/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	URI-UTF8-Punycode
PORTVERSION=	1.00
PORTREVISION=	1
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Punycode conversion of UTF-8 string

LICENSE=	GPLv3

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
