# Created by: Alexey Dokuchaev <danfe@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/x11-themes/metacity-digital-harmony-theme/Makefile 356282 2014-06-03 04:49:02Z danfe $

TYPE=		metacity
MASTERDIR=	${.CURDIR}/../gtk-digital-harmony-theme

.include "${MASTERDIR}/Makefile"
