# $FreeBSD: tags/RELEASE_10_3_0/textproc/py-zope.structuredtext/Makefile 374183 2014-12-07 10:01:36Z mva $

PORTNAME=	zope.structuredtext
PORTVERSION=	3.5.1
PORTREVISION=	1
CATEGORIES=	textproc python zope
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=	zope

MAINTAINER=	zope@FreeBSD.org
COMMENT=	StructuredText parser

LICENSE=	ZPL21

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
