# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-HTML_Javascript/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	HTML_Javascript
PORTVERSION=	1.1.2
CATEGORIES=	devel www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Provides an interface for creating simple JS scripts

USES=	pear

.include <bsd.port.mk>
