# Created by: Jim Pirzyk pirzyk@FreeBSD.org
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/p5-File-Stat-Bits/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	File-Stat-Bits
PORTVERSION=	1.01
PORTREVISION=	1
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	pirzyk@FreeBSD.org
COMMENT=	Perl5 module interface to the major()/minor() C routines

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
