# Created by: Mario Sergio Fujikawa Ferreira <lioux@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/x11-themes/kde-icons-lush/Makefile 386097 2015-05-11 18:34:57Z mat $

PORTNAME=	lush
PORTVERSION=	0.1.0
MASTER_SITES=	LOCAL/lioux
DISTNAME=	${PORTNAME}-${PORTVERSION}dave

COMMENT=	KDE Lush complete iconset

WRKSRC=		"${WRKDIR}/${PORTNAME}"

.include "${.CURDIR}/../kde-icons-noia/Makefile.icons"
