# $FreeBSD: tags/RELEASE_10_3_0/devel/py-ExtensionClass/Makefile 391330 2015-07-04 21:07:29Z rm $

PORTNAME=	ExtensionClass
PORTVERSION=	4.1.2
CATEGORIES=	devel python zope
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=	zope

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Metaclass for subclassable extension types

LICENSE=	ZPL21
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
