# $FreeBSD: tags/RELEASE_10_3_0/mail/squirrelmail-secure_login-plugin/Makefile 366415 2014-08-28 15:16:49Z adamw $

PORTNAME=	secure_login
PORTVERSION=	1.4
PORTREVISION=	3
CATEGORIES=	mail www
DISTNAME=	${PORTNAME}-${PORTVERSION}-1.2.8

MAINTAINER=	ports@FreeBSD.org
COMMENT=	This plugin will automatically turn on SSL security during login

LICENSE=	GPLv2

USE_GENERIC_PKGMESSAGE=	yes

.include "${.CURDIR}/../squirrelmail/bsd.squirrelmail.mk"
.include <bsd.port.mk>
