# Created by: Palle Girgensohn <girgen@partitur.se>
# $FreeBSD: tags/RELEASE_10_3_0/databases/postgresql94-pltcl/Makefile 366197 2014-08-26 10:17:30Z crees $

WANT_PGSQL_VER=	9.4

.include "${.CURDIR}/../postgresql91-pltcl/Makefile"
