# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-ansi/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	ansi
PORTVERSION=	1.5.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Gem enabling ANSI code based colorization and stylization of output

LICENSE=	BSD2CLAUSE

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
