# Created by: Rong-En Fan <rafan@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/print/pkipplib/Makefile 393303 2015-07-31 12:58:49Z amdmi3 $

PORTNAME=	pkipplib
PORTVERSION=	0.07
CATEGORIES=	print python
MASTER_SITES=	http://www.pykota.com/software/pkipplib/download/tarballs/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Create and parse IPP requests

LICENSE=	GPLv2 # or later
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		python
USE_PYTHON=	distutils
NO_ARCH=	yes

.include <bsd.port.mk>
