# Created by: Johannes Meixner <xmj@chaot.net>
# $FreeBSD: tags/RELEASE_10_3_0/www/rubygem-ace-rails-ap/Makefile 401677 2015-11-15 03:05:04Z sunpoet $

PORTNAME=	ace-rails-ap
PORTVERSION=	4.0.1
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ajax.org Cloud9 Editor (Ace) for the Rails 3.1 asset pipeline

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
USES=		shebangfix

SHEBANG_FILES=	update.sh

.include <bsd.port.mk>
