# Created by: ports@c0decafe.net <ports@c0decafe.net>
# $FreeBSD: tags/RELEASE_10_3_0/www/p5-URI-Encode/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	URI-Encode
PORTVERSION=	0.09
PORTREVISION=	1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:MITHUN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Simple URI Encoding/Decoding

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
