# Created by: Hsin-Han You <hhyou@cs.nctu.edu.tw>
# $FreeBSD: tags/RELEASE_10_3_0/archivers/rubygem-rubyzip2/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	rubyzip2
PORTVERSION=	2.0.2
CATEGORIES=	archivers rubygems
MASTER_SITES=	RG

MAINTAINER=	hhyou@cs.nctu.edu.tw
COMMENT=	Ruby compatible Zip library

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
