# Created by: rpsfa@rit.edu
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-sugar-high/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	sugar-high
PORTVERSION=	0.7.3
PORTREVISION=	1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	More Ruby sugar

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
