# $FreeBSD: tags/RELEASE_10_3_0/shells/Makefile 394918 2015-08-20 23:02:14Z pgj $
#

    COMMENT = Shells

    SUBDIR += 44bsd-csh
    SUBDIR += ambit
    SUBDIR += bash
    SUBDIR += bash-completion
    SUBDIR += bash-static
    SUBDIR += bashc
    SUBDIR += ch
    SUBDIR += dash
    SUBDIR += es
    SUBDIR += esh
    SUBDIR += fd
    SUBDIR += fish
    SUBDIR += flash
    SUBDIR += heirloom-sh
    SUBDIR += hs-shelly
    SUBDIR += ibsh
    SUBDIR += jailkit
    SUBDIR += ksh93
    SUBDIR += lshell
    SUBDIR += mksh
    SUBDIR += nologinmsg
    SUBDIR += osh
    SUBDIR += p5-Bash-Completion
    SUBDIR += p5-Shell-Perl
    SUBDIR += p5-Term-Bash-Completion-Generator
    SUBDIR += p5-Term-ShellUI
    SUBDIR += pdksh
    SUBDIR += pear-PHP_Shell
    SUBDIR += psh
    SUBDIR += rc
    SUBDIR += rssh
    SUBDIR += sash
    SUBDIR += scponly
    SUBDIR += shell-include
    SUBDIR += tcsh_nls
    SUBDIR += tcshrc
    SUBDIR += v7sh
    SUBDIR += viewglob
    SUBDIR += vshnu
    SUBDIR += wcd
    SUBDIR += zsh

.include <bsd.port.subdir.mk>
