# $FreeBSD: releng/10.3/gnu/usr.bin/rcs/Makefile 291792 2015-12-04 18:14:31Z bdrewery $

SUBDIR= lib .WAIT \
	ci co ident merge rcs rcsclean rcsdiff rcsmerge rlog rcsfreeze
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
