# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Pod-Stripper/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Pod-Stripper
PORTVERSION=	0.22
PORTREVISION=	5
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Strip all pod, and output what's left

USES=		perl5 dos2unix
USE_PERL5=	configure

.include <bsd.port.mk>
