# Created by: Palle Girgensohn <girgen@pingpong.net>
# $FreeBSD: tags/RELEASE_10_3_0/databases/postgresql90-docs/Makefile 366114 2014-08-25 17:53:26Z crees $

WANT_PGSQL_VER=	9.0
COMPONENT=	-docs

.include "${.CURDIR}/../postgresql91-docs/Makefile"
