# Created by: Jim Riggs <ports@christianserving.org>
# $FreeBSD: tags/RELEASE_10_3_0/net-mgmt/zabbix2-proxy/Makefile 351868 2014-04-22 18:14:34Z rene $

PORTNAME=	zabbix2
PKGNAMESUFFIX=	-proxy

MASTERDIR=	${.CURDIR}/../zabbix2-server

.include "${MASTERDIR}/Makefile"
