# Created by: Marc Fonvieille <blackend@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/misc/freebsd-doc-zh_tw/Makefile 357873 2014-06-15 12:32:26Z blackend $

CATEGORIES=	misc docs
PKGNAMEPREFIX=	zh_tw-

MAINTAINER=	doceng@FreeBSD.org
COMMENT=	Traditional Chinese translation of the FreeBSD Documentation Project

MASTERDIR=	${.CURDIR}/../freebsd-doc-en
PLIST=		${.CURDIR}/pkg-plist

DOCLANG=	zh_TW.UTF-8
DOCLANG_PREFIX=	zh_TW

.include "${MASTERDIR}/Makefile"
