# Created by: will
# $FreeBSD: tags/RELEASE_10_3_0/astro/p5-Geo-METAR/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	Geo-METAR
PORTVERSION=	1.15
PORTREVISION=	1
CATEGORIES=	astro geography perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module that processes METAR information from NOAA sources

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
