# Created by: Stanislav Sedov <stas@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/x11/emprint/Makefile 384128 2015-04-16 21:55:10Z bapt $

PORTNAME=	emprint
PORTVERSION=	20130520
PORTREVISION=	2
CATEGORIES=	x11 enlightenment
MASTER_SITES=	LOCAL/gblach/e17/extra/

MAINTAINER=	enlightenment@FreeBSD.org
COMMENT=	Utility for taking screenshots for E17

LIB_DEPENDS=	libefl.so:${PORTSDIR}/devel/efl

DIST_SUBDIR=	e17
GNU_CONFIGURE=	yes
USES=		pkgconfig tar:bzip2

.include <bsd.port.mk>
