# $FreeBSD: tags/RELEASE_10_3_0/net/go-amqp/Makefile 385640 2015-05-07 17:26:05Z mat $

PORTNAME=	amqp
PORTVERSION=	0.0.0.20140916
CATEGORIES=	net
PKGNAMEPREFIX=	go-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Go library for AMQP client with RabbitMQ extensions

LICENSE=	BSD2CLAUSE

USE_GITHUB=	yes
GH_ACCOUNT=	streadway
GH_TAGNAME=	7d6d180

GO_PKGNAME=	github.com/${GH_ACCOUNT}/${PORTNAME}

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/lang/go/files/bsd.go.mk"
.include <bsd.port.post.mk>
