# $FreeBSD: tags/RELEASE_10_3_0/textproc/rubygem-cssmin/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	cssmin
PORTVERSION=	1.0.3
PORTREVISION=	1
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby library for minifying CSS. Inspired by cssmin.js and YUI Compressor

LICENSE=	BSD3CLAUSE

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
