# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-Horde_Notification/Makefile 399990 2015-10-22 16:00:30Z mm $

PORTNAME=	Horde_Notification
PORTVERSION=	2.0.3
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Notification System

USES=	horde
USE_HORDE_RUN=	Horde_Exception \
		Horde_Util
USE_PHP=	gettext

.include <bsd.port.mk>
