# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-XML-Atom-SimpleFeed/Makefile 396484 2015-09-09 13:52:46Z tobez $

PORTNAME=	XML-Atom-SimpleFeed
PORTVERSION=	0.862
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	XML::Atom::SimpleFeed - Generate simple Atom syndication feeds

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
