# Created by: Cy Schubert <cy@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/hdrecover/Makefile 362126 2014-07-17 08:57:51Z olgeni $

PORTNAME=	hdrecover
PORTVERSION=	0.5
CATEGORIES=	sysutils
MASTER_SITES=	SF/${PORTNAME}/${PORTNAME}/${PORTNAME}-${PORTVERSION}

MAINTAINER=	cy@FreeBSD.org
COMMENT=	Attempts to recover a hard disk that has bad blocks on it

GNU_CONFIGURE=	yes
LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/COPYING

PLIST_FILES=	bin/hdrecover

.include <bsd.port.mk>
