# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-PDF-Writer/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	PDF-Writer
PORTVERSION=	0.06
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	PDF writer abstraction layer

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USE_PERL5=	modbuild
USES=		perl5

.include <bsd.port.mk>
