# Created by: dliakh
# $FreeBSD: tags/RELEASE_10_3_0/mail/p5-Email-AddressParser/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Email-AddressParser
PORTVERSION=	0.04
PORTREVISION=	1
CATEGORIES=	mail perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	dliakh@ukr.net
COMMENT=	RFC 2822 Address Parsing and Creation

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
