# Created by: Aaron Dalton <aaron@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Stream/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	Stream
PORTVERSION=	1.00
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Generic stream classes for Perl

LICENSE=	BSD3CLAUSE

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
