# $FreeBSD: tags/RELEASE_10_3_0/x11-toolkits/py-wxPython-common/Makefile 360826 2014-07-05 21:54:02Z wg $

PORTREVISION=		1
WITH_WXVERSION_ONLY=	yes

MASTERDIR=	${.CURDIR}/../py-wxPython30

PLIST=	${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
