# $FreeBSD: releng/10.3/tools/tools/ath/ath_ee_v14_print/Makefile 276486 2014-12-31 23:25:37Z ngie $

.PATH:  ${.CURDIR}/../../../../sys/dev/ath/ath_hal

PROG=	ath_ee_v14_print
NOMAN=	yes
MAN=

.include <../Makefile.inc>

.include <bsd.prog.mk>
