# Created by: Yarema <yds@CoolRat.org>
# $FreeBSD: tags/RELEASE_10_3_0/mail/courier-authlib-vchkpw/Makefile 396348 2015-09-07 21:29:19Z madpilot $

PORTREVISION=	2
PKGNAMESUFFIX=	-vchkpw

COMMENT=	Vpopmail/vchkpw support for the Courier authentication library
CATEGORIES=	mail

MASTERDIR=	${.CURDIR}/../../security/courier-authlib

.include "${MASTERDIR}/Makefile"
