# Created by: Sheldon Hearn <sheldonh@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/mail/exim-postgresql/Makefile 362543 2014-07-22 14:05:43Z vsevolod $

PKGNAMESUFFIX=	-postgresql
MASTERDIR=	${.CURDIR}/../exim

OPTIONS_SLAVE=	PGSQL

.include "${MASTERDIR}/Makefile"
