# Created by: Gerrit Beine (<tux@pinguru.net>)
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-HTML_Table/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	HTML_Table
PORTVERSION=	1.8.3
CATEGORIES=	devel www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Makes the design of HTML tables easy, flexible, reusable, and efficient

BUILD_DEPENDS=	${PEARDIR}/HTML/Common.php:${PORTSDIR}/devel/pear-HTML_Common
RUN_DEPENDS=	${PEARDIR}/HTML/Common.php:${PORTSDIR}/devel/pear-HTML_Common

USES=	pear

.include <bsd.port.mk>
