# Created by: Dmitry Sivachenko <dima@Chg.RU>
# $FreeBSD: tags/RELEASE_10_3_0/misc/p5-I18N-LangTags/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	I18N-LangTags
PORTVERSION=	0.35
PORTREVISION=	1
CATEGORIES=	misc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	demon@FreeBSD.org
COMMENT=	Functions for dealing with RFC-1766-style language tags

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
