# Created by: Mons Anderson <mons@cpan.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-constant-def/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	constant-def
PORTVERSION=	0.01
PORTREVISION=	2
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	mons@cpan.org
COMMENT=	Declare only undeclared constants

BUILD_DEPENDS=	p5-ex-lib>=0.06:${PORTSDIR}/devel/p5-ex-lib
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
