# Created by: Scott Sanders <scott@jssjr.com>
# $FreeBSD: tags/RELEASE_10_3_0/www/rubygem-merb-haml/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	merb-haml
PORTVERSION=	1.1.3
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Merb plugin for HAML support

LICENSE=	MIT

RUN_DEPENDS=	rubygem-haml>=2.0.3:${PORTSDIR}/www/rubygem-haml \
		rubygem-merb-core>=1.1.3:${PORTSDIR}/www/rubygem-merb-core

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
