# Created by: b.f. <bf@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/math/fftw3-quad/Makefile 347093 2014-03-05 03:17:04Z bf $

COMMENT=	Fast Discrete Fourier Transform (Quad Precision C Routines)

FFTW3_FLAVOR=	quad
MASTERDIR=	${.CURDIR}/../../math/fftw3

.include "${MASTERDIR}/Makefile"
