# Created by: Anish Mistry <amistry@am-productions.biz>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-List-PowerSet/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	List-PowerSet
PORTVERSION=	0.01
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Perl module that allows you to generate the power set of a list

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
