# Created by: Shinsuke Matsui (<smatsui@karashi.org>)
# $FreeBSD: tags/RELEASE_10_3_0/net/pear-Net_UserAgent_Mobile/Makefile 369094 2014-09-23 16:57:57Z bapt $

PORTNAME=	Net_UserAgent_Mobile
PORTVERSION=	1.0.0
CATEGORIES=	net www pear
DISTNAME=	${PORTNAME}-${PORTVERSION}RC1

MAINTAINER=	smatsui@karashi.org
COMMENT=	PEAR class that parses HTTP mobile user agent string

USE_PHP=	pcre
USES=	pear

.include <bsd.port.mk>
