# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/mergelog/Makefile 364158 2014-08-06 09:11:57Z olgeni $

PORTNAME=	mergelog
PORTVERSION=	4.5
PORTREVISION=	2
CATEGORIES=	www textproc
MASTER_SITES=	SF

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Tool to merge and sort by date http log files

USES=	gmake
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
