# Created by: Kelly Yancey <kbyanc@posi.net>
# $FreeBSD: tags/RELEASE_10_3_0/www/p5-FCGI/Makefile 378671 2015-02-08 18:53:58Z adamw $

PORTNAME=	FCGI
PORTVERSION=	0.77
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:ETHER
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Modules for perl5, for enabling FastCGI support in CGI scripts

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
