# Created by: Kozlov Sergey <kozlov.sergey.404@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/www/py-django-registration-defaults/Makefile 376109 2015-01-03 08:41:20Z mva $

PORTNAME=	django-registration-defaults
PORTVERSION=	0.4.4
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	kozlov.sergey.404@gmail.com
COMMENT=	Default templates and settings for django-registration

LICENSE=	MIT

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}django-registration>=0:${PORTSDIR}/www/py-django-registration

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
