# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Sort-Fields/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Sort-Fields
PORTVERSION=	0.90
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl module to sort lines containing delimited fields

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
