# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/converters/R-cran-jsonlite/Makefile 403116 2015-12-06 14:52:27Z tota $

PORTNAME=	jsonlite
PORTVERSION=	0.9.19
CATEGORIES=	converters
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Robust, High Performance JSON Parser and Generator for R

LICENSE=	MIT

USES=	cran:auto-plist

.include <bsd.port.mk>
