# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/multimedia/gstreamer-plugins-vp8/Makefile 401587 2015-11-14 19:34:12Z jbeich $

PORTREVISION=	3
CATEGORIES=	multimedia

COMMENT=	Gstreamer vp8 codec plugin

GST_PLUGIN=	vp8

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
