# Created by: Kurt Jaeger <fbsd-ports@opsec.eu>
# $FreeBSD: tags/RELEASE_10_3_0/devel/dragon/Makefile 357068 2014-06-08 19:05:27Z pi $

PORTNAME=	dragon
PORTVERSION=	1.3.10
CATEGORIES=	devel
MASTER_SITES=	http://www.lemke-it.com/

MAINTAINER=	pi@FreeBSD.org
COMMENT=	Combined C++ scanner/parser generator for LR compliant grammars

LIB_DEPENDS=	liblfcbase.so:${PORTSDIR}/devel/lfcbase

LICENSE=	GPLv3
GNU_CONFIGURE=	yes
PLIST_FILES=	bin/dragon

MAKE_JOBS_UNSAFE=yes

.include <bsd.port.mk>
