# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-App-cpanminus/Makefile 394923 2015-08-21 06:36:41Z kuriyama $

PORTNAME=	App-cpanminus
PORTVERSION=	1.7039
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:MIYAGAWA
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension to get, unpack, build, and install modules from CPAN

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=	perl5
USE_PERL5=	configure
NO_ARCH=	YES

.include <bsd.port.mk>
