# Created by: tobez
# $FreeBSD: tags/RELEASE_10_3_0/print/p5-PostScript-Simple/Makefile 376255 2015-01-04 17:12:26Z sunpoet $

PORTNAME=	PostScript-Simple
PORTVERSION=	0.09
CATEGORIES=	print perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Produce PostScript files from Perl

LICENSE=	GPLv2

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
