# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/lang/p5-JavaScript-Squish/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	JavaScript-Squish
PORTVERSION=	0.07
PORTREVISION=	1
CATEGORIES=	lang perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Reduce/Compact JavaScript code to as few characters as possible

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
