# Created by: philip@p6m7g8.com
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Filter-Simple/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Filter-Simple
PORTVERSION=	0.91
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Simplified source filtering

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
