# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-Horde_Icalendar/Makefile 403603 2015-12-12 14:29:08Z mm $

PORTNAME=	Horde_Icalendar
PORTVERSION=	2.1.2
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde iCalendar API

USES=	horde
USE_HORDE_RUN=	Horde_Date \
		Horde_Exception \
		Horde_Mail \
		Horde_Mime \
		Horde_Support \
		Horde_Translation \
		Horde_Util

.include <bsd.port.mk>
