# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: tags/RELEASE_10_3_0/databases/pear-MDB2/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	MDB2
DISTVERSION=	2.5.0b5
CATEGORIES=	databases www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PEAR database abstraction layer

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USES=		pear

.include <bsd.port.mk>
