# Created by: Kozlov Sergey <kozlov.sergey.404@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/py-pdfminer/Makefile 374183 2014-12-07 10:01:36Z mva $

PORTNAME=	pdfminer
PORTVERSION=	20140328
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	kozlov.sergey.404@gmail.com
COMMENT=	PDF parser and analyzer

LICENSE=	MIT

USES=		python:2
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
