# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Text-Similarity/Makefile 398939 2015-10-09 18:32:20Z sunpoet $

PORTNAME=	Text-Similarity
PORTVERSION=	0.13
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Measure the similarity of text documents

LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/GPL.txt

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
