# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/R-cran-BH/Makefile 401045 2015-11-08 09:13:29Z tota $

PORTNAME=	BH
DISTVERSION=	1.58.0-1
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Boost C++ Header Files

LICENSE=	BSL

USES=	cran:auto-plist

.include <bsd.port.mk>
