# $FreeBSD: tags/RELEASE_10_3_0/x11/xmag/Makefile 399841 2015-10-20 13:47:13Z kwm $

PORTNAME=	xmag
PORTVERSION=	1.0.6
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X application for screen magnifying

LICENSE=	MIT

XORG_CAT=	app
USE_XORG=	xt xaw

.include <bsd.port.mk>
