# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/pear-Horde_Xml_Wbxml/Makefile 376829 2015-01-12 14:54:44Z mm $

PORTNAME=	Horde_Xml_Wbxml
PORTVERSION=	2.0.2
CATEGORIES=	textproc www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde API for encoding and decoding WBXML documents

USES=	horde
USE_HORDE_RUN=	Horde_Util

.include <bsd.port.mk>
