# Created by: Murilo Opsfelder <mopsfelder@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/www/p5-CGI-Utils/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	CGI-Utils
PORTVERSION=	0.12
PORTREVISION=	1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	mopsfelder@gmail.com
COMMENT=	Utilities for retrieving information through the CGI

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
