# $FreeBSD: tags/RELEASE_10_3_0/net/rubygem-open-uri-cached/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	open-uri-cached
PORTVERSION=	0.0.5
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	OpenURI with transparent disk caching

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
