# Created by: Yen-Ming Lee <leeym@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-accessors/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	accessors
PORTVERSION=	1.01
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:SPURKIS
PKGNAMEPREFIX=	p5-

MAINTAINER=	leeym@FreeBSD.org
COMMENT=	Create accessor methods in caller's package #'

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
