# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-Horde_Stream_Filter/Makefile 376829 2015-01-12 14:54:44Z mm $

PORTNAME=	Horde_Stream_Filter
PORTVERSION=	2.0.3
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Stream filters

USES=	horde

.include <bsd.port.mk>
