# Created by: Joseph Benden <joe@thrallingpenguin.com>
# $FreeBSD: tags/RELEASE_10_3_0/www/rubygem-hashicorp-checkpoint/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	hashicorp-checkpoint
PORTVERSION=	0.1.4
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	joe@thrallingpenguin.com
COMMENT=	Internal HashiCorp service to check version information

LICENSE=	MPL

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
