# $FreeBSD: tags/RELEASE_10_3_0/www/twiki-TWikiUserMappingContrib/Makefile 362252 2014-07-19 11:09:51Z ohauer $

PORTNAME=	TWikiUserMappingContrib
SVNREV=		17569

COMMENT=	Traditional topic-based user mapping and management

.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
