# Created by: vvelox@vvelox.net
# $FreeBSD: tags/RELEASE_10_3_0/graphics/p5-Imager-AverageGray/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Imager-AverageGray
PORTVERSION=	0.0.0
PORTREVISION=	4
CATEGORIES=	graphics perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	vvelox@vvelox.net
COMMENT=	Finds the average gray for a Imager object or image

RUN_DEPENDS=	p5-Imager>=0:${PORTSDIR}/graphics/p5-Imager

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
