# $FreeBSD: tags/RELEASE_10_3_0/devel/pybugz/Makefile 390644 2015-06-26 15:24:20Z koobs $

PORTNAME=	pybugz
PORTVERSION=	0.11.1
CATEGORIES=	devel python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	crees@FreeBSD.org
COMMENT=	Python command-line interface to bugzilla

LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes

USES=		python:3.3+
USE_GITHUB=	yes
USE_PYTHON=	autoplist distutils

GH_ACCOUNT=	williamh

.include <bsd.port.mk>
