# $FreeBSD: releng/10.3/usr.bin/col/tests/Makefile 282339 2015-05-02 12:08:28Z bapt $

TESTSDIR=	${TESTSBASE}/usr.bin/col

ATF_TESTS_SH=	col

FILES=		rlf.in \
		rlf2.in
FILESDIR=	${TESTSDIR}

.include <bsd.test.mk>
