# Created by: Babak Farrokhi <farrokhi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/net-mgmt/rcpd/Makefile 343900 2014-02-12 10:47:13Z miwi $

PORTNAME=	rcpd
PORTVERSION=	1.2
CATEGORIES=	net-mgmt net
MASTER_SITES=	ftp://ftp.shrubbery.net/pub/rcpd/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	RCP server for routers and network devices

GNU_CONFIGURE=	yes

PLIST_FILES=	sbin/rcpd \
		man/man1/rcpd.1.gz

.include <bsd.port.mk>
