# Created by: Muhammad Moinur Rahman <bofh@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py3-vcversioner/Makefile 401983 2015-11-20 00:45:07Z bofh $

PORTNAME=	vcversioner
PORTVERSION=	2.14.0.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Use version control tags to discover version numbers

LICENSE=	ISCL

USES=		python:3
USE_PYTHON=	distutils autoplist
NO_ARCH=	yes

.include <bsd.port.mk>
