# $FreeBSD: tags/RELEASE_10_3_0/textproc/rubygem-creole/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	creole
PORTVERSION=	0.5.0
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Creole-to-HTML converter

LICENSE=	RUBY

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
