# Created by: mat
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Devel-Size/Makefile 383053 2015-04-02 19:21:06Z sunpoet $

PORTNAME=	Devel-Size
PORTVERSION=	0.80
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl extension for finding the memory usage of Perl variables

LICENSE_COMB=	dual
LICENSES=	ART10 GPLv1

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
