# $FreeBSD: tags/RELEASE_10_3_0/archivers/liblzxcomp/files/Makefile.bsd 343484 2014-02-09 12:28:47Z ak $

LIB = 	lzxcomp
SRCS=	lz_nonslide.c lzx_layer.c
INCS=	lzx_compress.h lzx_constants.h

CFLAGS+= -DLZ_ONEBUFFER -DLAZY -DNONSLIDE
LDADD= -lm

SHLIB_MAJOR=	1

LIBDIR=		${PREFIX}/lib
INCLUDEDIR=	${PREFIX}/include

MAN3=	lzxcomp.3
MANDIR=	${PREFIX}/man/man

.include <bsd.lib.mk>
