# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/www/webpy/Makefile 376109 2015-01-03 08:41:20Z mva $

PORTNAME=	webpy
PORTVERSION=	0.37
CATEGORIES=	www python
MASTER_SITES=	http://webpy.org/static/ \
		CHEESESHOP
DISTNAME=	web.py-${PORTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Web Framework For Python

USES=		python
USE_PYTHON=	distutils
PYDISTUTILS_PKGNAME=	web.py

.include <bsd.port.mk>
