# Created by: Toby Allsopp <toby@mi6.gen.nz>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Text-Tabs+Wrap/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Text-Tabs+Wrap
PORTVERSION=	2013.0523
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Line wrapping to form simple paragraphs

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
