# Created by: Jason Bacon <bacon4000@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/papp/Makefile 403636 2015-12-12 23:02:03Z bapt $

PORTNAME=	papp
PORTVERSION=	0.3.1
CATEGORIES=	devel
MASTER_SITES=	http://acadix.biz/Ports/distfiles/

MAINTAINER=	bacon4000@gmail.com
COMMENT=	Assembly Preprocessor

BROKEN=		unfetchable

LICENSE=	BSD2CLAUSE

.include <bsd.port.mk>
