# Created by: Emil J.V. Björsell (Jev)
# $FreeBSD: tags/RELEASE_10_3_0/graphics/barcode/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	barcode
PORTVERSION=	0.98
CATEGORIES=	graphics
MASTER_SITES=	GNU

MAINTAINER=	jev@ecad.org
COMMENT=	A barcode generation library along with a command line frontend

BUILD_DEPENDS=	gawk:${PORTSDIR}/lang/gawk

GNU_CONFIGURE=	yes
INFO=		barcode

.include <bsd.port.mk>
