# Created by: Thinker K.F. Li <thinker@branda.to>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-mez_xml/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	mez_xml
PORTVERSION=	0.4
CATEGORIES=	devel www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Simple template engine for Python

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
