# Created by: Robert Gogolok <gogo@cs.uni-sb.de>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-ruby-prof/Makefile 399584 2015-10-17 18:09:54Z sunpoet $

PORTNAME=	ruby-prof
PORTVERSION=	0.15.8
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Fast profiler for Ruby

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/ruby-prof bin/ruby-prof-check-trace

.include <bsd.port.mk>
