# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Tie-Simple/Makefile 402751 2015-12-01 16:05:15Z sunpoet $

PORTNAME=	Tie-Simple
PORTVERSION=	1.04
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Variable ties made easier: much, much, much easier

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

NO_ARCH=	yes 
USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
