# Created by: James FitzGibbon <jfitz@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Term-ReadKey/Makefile 379667 2015-02-23 10:09:03Z sunpoet $

PORTNAME=	Term-ReadKey
PORTVERSION=	2.32
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	TermReadKey-${PORTVERSION}

MAINTAINER=	demon@FreeBSD.org
COMMENT=	Perl5 module for simple terminal control

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

MAKE_JOBS_UNSAFE=	yes

.include <bsd.port.mk>
