# Created by: Michael Moll <kvedulv at kvedulv.de>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-kafo_parsers/Makefile 405015 2016-01-01 17:05:54Z mmoll $

PORTNAME=	kafo_parsers
PORTVERSION=	0.0.5
PORTREVISION=	1
CATEGORIES=	devel ruby
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Parser for puppet modules

LICENSE=	GPLv3

RUN_DEPENDS=	puppet:${PORTSDIR}/sysutils/puppet

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
