# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Devel-Modlist/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Devel-Modlist
PORTVERSION=	0.801
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl extension to collect module use information

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
