# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: tags/RELEASE_10_3_0/converters/p5-Encode-Detect/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	Encode-Detect
PORTVERSION=	1.01
PORTREVISION=	1
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Encode::Encoding subclass that detects the encoding of data

LICENSE=	MPL

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
