# $FreeBSD: tags/RELEASE_10_3_0/devel/py-lazy-object-proxy/Makefile 404415 2015-12-25 12:13:04Z mva $

PORTNAME=	lazy-object-proxy
PORTVERSION=	1.2.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	mva@FreeBSD.org
COMMENT=	Fast and thorough lazy object proxy

LICENSE=	BSD2CLAUSE

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
