# Created by: Lars Thegler <lars@thegler.dk>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Proc-PID-File/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Proc-PID-File
PORTVERSION=	1.27
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Perl module to manage process id files

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
