# Created by: anarcat
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/worldtools/Makefile 337789 2013-12-27 19:21:50Z bapt $

PORTNAME=	worldtools
PORTVERSION=	1.3.1
PORTREVISION=	1
CATEGORIES=	sysutils
MASTER_SITES=	http://anarcat.ath.cx/software/distfiles/

MAINTAINER=	anarcat@anarcat.ath.cx
COMMENT=	Handy tools for living with make world

USES=		perl5 uidfix shebangfix
SHEBANG_FILES=	whereintheworld
USE_PERL5=	run

MAKE_ARGS=	SHAREDIR=${PREFIX}

.include <bsd.port.mk>
