# $FreeBSD: tags/RELEASE_10_3_0/security/asignify/Makefile 377035 2015-01-14 18:35:31Z az $

PORTNAME=	asignify
PORTVERSION=	1.0
CATEGORIES=	security
MASTER_SITES=	http://highsecure.ru/distfiles/

MAINTAINER=	vsevolod@FreeBSD.org
COMMENT=	Yet another signify tool

LICENSE=	BSD2CLAUSE

USES=		tar:xz libtool

GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes
INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
