# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Iterator-Simple/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Iterator-Simple
PORTVERSION=	0.06
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Simple iterator and utilities

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
