# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-aws-sdk/Makefile 404460 2015-12-25 19:45:06Z sunpoet $

PORTNAME=	aws-sdk
PORTVERSION=	2.2.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	AWS SDK for Ruby

LICENSE=	APACHE20

RUN_DEPENDS=	rubygem-aws-sdk-resources>=${PORTVERSION}:${PORTSDIR}/devel/rubygem-aws-sdk-resources

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
