# Created by: nobu@rd.isac.co.jp
# $FreeBSD: tags/RELEASE_10_3_0/math/ngraph/Makefile 392401 2015-07-18 00:56:35Z sanpei $

PORTNAME=	ngraph
PORTVERSION=	6.3.54
CATEGORIES=	math
MASTER_SITES=	http://www2e.biglobe.ne.jp/~isizaka/bin/ \
		PORTS_JP
DISTNAME=	Ngraph-${PORTVERSION}-src

MAINTAINER=	sanpei@FreeBSD.org
COMMENT=	XY plotting tool for students, scientists, and engineers

LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/gpl.txt

USES=		gmake motif

.include <bsd.port.mk>
