# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: tags/RELEASE_10_3_0/ftp/pear-Net_FTP/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Net_FTP
PORTVERSION=	1.4.0
CATEGORIES=	ftp www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PEAR OO interface to the PHP FTP functions plus some additions

LICENSE=	BSD2CLAUSE

USE_PHP=	ftp
USES=		pear

.include <bsd.port.mk>
