# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/shells/pear-PHP_Shell/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	PHP_Shell
PORTVERSION=	0.3.2
CATEGORIES=	shells www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Interactive PHP Shell

USE_PHP=	pcre tokenizer readline

USES=	pear

.include <bsd.port.mk>
