# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: tags/RELEASE_10_3_0/textproc/pear-Numbers_Roman/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	Numbers_Roman
PORTVERSION=	1.0.2
CATEGORIES=	textproc devel pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR methods for converting to and from Roman Numerals

USES=	pear

.include <bsd.port.mk>
