# Created by: mharo@FreeBSD.org
# $FreeBSD: tags/RELEASE_10_3_0/databases/p5-DWH_File/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	DWH_File
PORTVERSION=	0.24
PORTREVISION=	2
CATEGORIES=	databases perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Store deep and wide hashes in single level tied hash

BUILD_DEPENDS=	p5-URI>=0:${PORTSDIR}/net/p5-URI
RUN_DEPENDS=	p5-URI>=0:${PORTSDIR}/net/p5-URI

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
