# Created by: Gerrit Beine (<gerrit.beine@gmx.de>)
# $FreeBSD: tags/RELEASE_10_3_0/graphics/pear-Image_GraphViz/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Image_GraphViz
PORTVERSION=	1.3.0
CATEGORIES=	graphics www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Interface to AT&T's GraphViz tools

RUN_DEPENDS=	${LOCALBASE}/bin/dot:${PORTSDIR}/graphics/graphviz

USES=	pear

.include <bsd.port.mk>
