# Created by: Yuri Victorovich <yuri@rawbw.com>
# $FreeBSD: tags/RELEASE_10_3_0/math/py-pyvtk/Makefile 404904 2015-12-31 03:24:11Z miwi $

PORTNAME=	pyVTK
PORTVERSION=	0.4.85
CATEGORIES=	math python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	PyVTK-${PORTVERSION}

MAINTAINER=	yuri@rawbw.com
COMMENT=	Tools for manipulating VTK files in Python

LICENSE=	GPLv2

USES=		python
USE_PYTHON=	autoplist distutils
NO_ARCH=	yes

.include <bsd.port.mk>
