# Created by: Zhen REN <bg1tpt@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/mail/pear-Mail_mimeDecode/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Mail_mimeDecode
PORTVERSION=	1.5.5
CATEGORIES=	mail www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Provides a class to decode mime messages

LICENSE=	BSD3CLAUSE

BUILD_DEPENDS=	${PEARDIR}/Mail/mime.php:${PORTSDIR}/mail/pear-Mail_Mime
RUN_DEPENDS=	${PEARDIR}/Mail/mime.php:${PORTSDIR}/mail/pear-Mail_Mime

USES=		pear
NO_ARCH=	yes

.include <bsd.port.mk>
