# Created by: Kurt Jaeger <pi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/converters/p5-Encoding-BER/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Encoding-BER
PORTVERSION=	1.00
PORTREVISION=	1
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:JAW
PKGNAMEPREFIX=	p5-

MAINTAINER=	pi@FreeBSD.org
COMMENT=	Encode/decode data using ASN.1 Basic Encoding Rules (BER)

LICENSE=	ART10

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
