# Created by: Philippe Audeoud <jadawin@tuxaco.net>
# $FreeBSD: tags/RELEASE_10_3_0/net/p5-Net-Proxy/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	Net-Proxy
PORTVERSION=	0.13
PORTREVISION=	1
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	jadawin@FreeBSD.org
COMMENT=	Framework for proxying network connections in many ways

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

MAN1=	connect-tunnel.1 \
	sslh.1

.include <bsd.port.mk>
