# Created by: Satoshi TAOKA
# $FreeBSD: tags/RELEASE_10_3_0/x11/xcoloredit/Makefile 363374 2014-07-29 19:11:51Z adamw $

PORTNAME=	xcoloredit
PORTVERSION=	1.2
PORTREVISION=	2
CATEGORIES=	x11
MASTER_SITES=	XCONTRIB/../R5contrib
DISTNAME=	${PORTNAME}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Find colour values by graphical colour mixing

USES=		imake tar:Z
USE_XORG=	ice sm x11 xaw xext xmu xpm xt

PLIST_FILES=	bin/xcoloredit \
		man/man1/xcoloredit.1.gz

.include <bsd.port.mk>
