# $FreeBSD: releng/10.3/libexec/tests/Makefile 257853 2013-11-08 14:33:41Z jmmv $

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/libexec

.PATH:		${.CURDIR:H:H}/tests
KYUAFILE=	yes

.include <bsd.test.mk>
