# $FreeBSD: tags/RELEASE_10_3_0/security/pear-Horde_Auth/Makefile 393466 2015-08-03 07:06:14Z mm $

PORTNAME=	Horde_Auth
PORTVERSION=	2.1.10
CATEGORIES=	security www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Authentication API

USES=	horde
USE_HORDE_RUN=	Horde_Exception Horde_Util
USE_PHP=	hash

.include <bsd.port.mk>
