# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/archivers/quazip/Makefile 378823 2015-02-11 09:20:18Z nivit $

PORTNAME=	quazip
PORTVERSION=	0.7.1
CATEGORIES=	archivers
MASTER_SITES=	SF

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Qt/C++ wrapper for ZIP/UNZIP package

LICENSE=	LGPL21

USES=		qmake
USE_LDCONFIG=	yes
USE_QT4=	corelib moc_build network_build qtestlib_build

.include <bsd.port.mk>
