# Created by: Shin-ya MURAKAMI <murashin@gfd-dennou.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-slop/Makefile 402523 2015-11-28 09:29:38Z sunpoet $

PORTNAME=	slop
PORTVERSION=	4.2.1
CATEGORIES=	devel ruby
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Simple DSL for gathering options and parsing the command line

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
