# Created by: TAKANO, Yuji
# $FreeBSD: tags/RELEASE_10_3_0/japanese/mozc-el/Makefile 358380 2014-06-19 11:08:10Z sanpei $

PKGNAMESUFFIX=	-el-${EMACS_PORT_NAME}

COMMENT=	Emacs input method for Mozc

MASTERDIR=	${.CURDIR}/../../japanese/mozc-server
PKGMESSAGE=	${.CURDIR}/pkg-message

BUILD_MOZC_LIST=mozc_el

.include "${MASTERDIR}/Makefile"
