# Created by: Peter Pentchev <roam@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Time-Human/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	Time-Human
PORTVERSION=	1.03
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Convert localtime() format to "speaking clock" time

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
