# Created by: William Grzybowski <wg@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/patchelf/Makefile 362024 2014-07-16 03:18:26Z adamw $

PORTNAME=	patchelf
PORTVERSION=	0.6
CATEGORIES=	sysutils
MASTER_SITES=	http://hydra.nixos.org/build/1524660/download/3/

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Utility to modify the dynamic linker

USES=		gmake
GNU_CONFIGURE=	yes

OPTIONS_DEFINE=	DOCS

.include <bsd.port.mk>
