# $FreeBSD: tags/RELEASE_10_3_0/security/rubygem-omniauth-shibboleth/Makefile 390385 2015-06-23 12:22:14Z sunpoet $

PORTNAME=	omniauth-shibboleth
PORTVERSION=	1.2.1
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	OmniAuth Shibboleth strategies for OmniAuth 1.x

LICENSE=	MIT

RUN_DEPENDS=	rubygem-omniauth>=1.0:${PORTSDIR}/security/rubygem-omniauth

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
