# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-UDCode/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	UDCode
PORTVERSION=	1.03
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:MJD
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Does a set of code words form a uniquely decodable code?

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
