# $FreeBSD: tags/RELEASE_10_3_0/print/rubygem-color/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	color
PORTVERSION=	1.7.1
CATEGORIES=	print rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Provides colour space definition and manipulation

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
