# Created by: Kuang-che Wu <kcwu@csie.org>
# $FreeBSD: tags/RELEASE_10_3_0/games/tsito/Makefile 374095 2014-12-06 08:51:44Z amdmi3 $

PORTNAME=	tsito
PORTVERSION=	0.8.4
CATEGORIES=	games
MASTER_SITES=	SF/xiangqi-engine/xiangqi-engine/${PORTNAME}-${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Chinese chess (Xiangqi) program

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

GNU_CONFIGURE=	yes
LIBS+=		-lcompat

.include <bsd.port.mk>
