# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/rubygem-sys-host/Makefile 387306 2015-05-24 18:56:58Z sunpoet $

PORTNAME=	sys-host
PORTVERSION=	0.6.2
CATEGORIES=	sysutils rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Provides hostname, IP address, and other information for a given host

LICENSE=	ART20

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
