# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/R-cran-selectr/Makefile 394031 2015-08-12 19:11:15Z tota $

PORTNAME=	selectr
DISTVERSION=	0.2-3
CATEGORIES=	www
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Translate CSS Selectors to XPath Expressions

LICENSE=	BSD3CLAUSE

RUN_DEPENDS=	R-cran-XML>0:${PORTSDIR}/textproc/R-cran-XML \
		R-cran-stringr>0:${PORTSDIR}/textproc/R-cran-stringr

USES=	cran:auto-plist

.include <bsd.port.mk>
