# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Tie-Hash-Sorted/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Tie-Hash-Sorted
PORTVERSION=	0.10
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Tie::Hash::Sorted - presents hashes in sorted order

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
