# Created by: Sergei Vyshenski <svysh@pn.sinp.msu.ru>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Proc-SafeExec/Makefile 375249 2014-12-22 17:12:26Z feld $

PORTNAME=	Proc-SafeExec
PORTVERSION=	1.5
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	svysh.fbsd@gmail.com
COMMENT=	Convenient utility for executing external commands in various ways

LICENSE=	BSD2CLAUSE GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
