# Created by: Torsten Zuhlsdorff <ports@toco-domains.de>
# $FreeBSD: tags/RELEASE_10_3_0/databases/rubygem-after_commit_queue-rails41/Makefile 402300 2015-11-23 18:27:07Z sunpoet $

PKGNAMESUFFIX=	-rails41

RUN_DEPENDS=	rubygem-activerecord41>=4.1:${PORTSDIR}/databases/rubygem-activerecord41

MASTERDIR=	${.CURDIR}/../rubygem-after_commit_queue

.include "${MASTERDIR}/Makefile"
