# Created by: Oliver Fromme <oliver.fromme@heim3.tu-clausthal.de>
# $FreeBSD: tags/RELEASE_10_3_0/audio/tosha/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	tosha
PORTVERSION=	0.6
PORTREVISION=	1
CATEGORIES=	audio
MASTER_SITES=	LOCAL/markp

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Read CD digital audio and video data via the SCSI bus

LICENSE=	BSD3CLAUSE

.include <bsd.port.mk>
