# Created by: Tsung-Han Yeh <snowfly@yuntech.edu.tw>
# $FreeBSD: tags/RELEASE_10_3_0/security/p5-Cisco-Hash/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Cisco-Hash
PORTVERSION=	0.02
PORTREVISION=	1
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	snowfly@yuntech.edu.tw
COMMENT=	De- and encrypts Cisco type 7 hashes

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
