# $FreeBSD: tags/RELEASE_10_3_0/irc/rubygem-cinch/Makefile 400902 2015-11-06 08:51:53Z sunpoet $

PORTNAME=	cinch
PORTVERSION=	2.3.1
CATEGORIES=	irc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	IRC Bot Building Framework

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
