# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Class-Autouse/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Class-Autouse
PORTVERSION=	2.01
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:ADAMK
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Defer loading of one or more classes

BUILD_DEPENDS=	p5-prefork>=0:${PORTSDIR}/devel/p5-prefork
RUN_DEPENDS=	p5-prefork>=0:${PORTSDIR}/devel/p5-prefork

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
