# $FreeBSD: tags/RELEASE_10_3_0/sysutils/rubygem-fssm/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	fssm
PORTVERSION=	0.2.10
CATEGORIES=	sysutils ruby
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	State tracking and event firing utility

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
