# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: tags/RELEASE_10_3_0/security/p5-Crypt-Rijndael_PP/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Crypt-Rijndael_PP
PORTVERSION=	0.05
PORTREVISION=	1
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl implementation of Rijndael

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
