# Created by: Scott Sanders <scott@jssjr.com>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/rubygem-escape_utils/Makefile 386017 2015-05-10 20:19:26Z sunpoet $

PORTNAME=	escape_utils
PORTVERSION=	1.1.0
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Faster string escaping routines for your web apps

LICENSE=	MIT

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
