# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-PHP_CodeSniffer/Makefile 396493 2015-09-09 13:58:46Z pi $

PORTNAME=	PHP_CodeSniffer
PORTVERSION=	2.3.4
CATEGORIES=	devel www pear

MAINTAINER=	ports@toco-domains.de
COMMENT=	PHP Script Tokenises and Sniffs PHP and JavaScript code

LICENSE=	BSD3CLAUSE

NO_ARCH=	yes
USES=		pear
USE_PHP=	simplexml tokenizer

.include <bsd.port.mk>
