# $FreeBSD: tags/RELEASE_10_3_0/textproc/erlang-edown/Makefile 391483 2015-07-06 22:27:17Z olgeni $

PORTNAME=	edown
PORTVERSION=	0.7
CATEGORIES=	textproc
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	EDoc extension for generating Github-flavored Markdown

USES=		erlang:rebar
USE_GITHUB=	yes
GH_ACCOUNT=	uwiger

ERL_DOCS=	doc/*

.include <bsd.port.mk>
