# $FreeBSD: tags/RELEASE_10_3_0/x11-fonts/xlsfonts/Makefile 399848 2015-10-20 13:58:29Z kwm $

PORTNAME=	xlsfonts
PORTVERSION=	1.0.5
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Server font list displayer for X

XORG_CAT=	app
USE_XORG=	x11

PLIST_FILES=	bin/xlsfonts man/man1/xlsfonts.1.gz

.include <bsd.port.mk>
