# Created by: Carlo Strub
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-testtools/Makefile 404447 2015-12-25 19:01:28Z cs $

PORTNAME=	testtools
PORTVERSION=	0.9.35
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	http://launchpadlibrarian.net/164010578/ \
		http://www.c-s.li/ports/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Extensions to the Python library's unit testing framework

LICENSE=	MIT

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}extras>=0.0.3:${PORTSDIR}/devel/py-extras

USES=		python
USE_PYTHON=	distutils

.include <bsd.port.mk>
