# Created by: Roland van Laar <roland@micite.net>
# $FreeBSD: tags/RELEASE_10_3_0/databases/py-sqlparse/Makefile 399081 2015-10-11 08:56:09Z pi $

PORTNAME=	sqlparse
PORTVERSION=	0.1.16
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Non-validating SQL parser for Python

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
