# Created by: Valentin Nechayev <netch@segfault.kiev.ua>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/gpte/Makefile 367526 2014-09-07 11:49:17Z antoine $

PORTNAME=	gpte
PORTVERSION=	1.0
CATEGORIES=	sysutils
MASTER_SITES=	ftp://segfault.kiev.ua/pub/

MAINTAINER=	netch@segfault.kiev.ua
COMMENT=	Simple command-line GPT partition editor

USES=		uidfix
MAKEFILE=	Makefile.bsd

PLIST_FILES=	bin/gpte \
		man/man8/gpte.8.gz

.include <bsd.port.mk>
