# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Term-ReadPassword/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Term-ReadPassword
PORTVERSION=	0.11
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl module for asking the user for a password

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
