# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Module-Runtime-Conflicts/Makefile 381203 2015-03-13 14:02:09Z sunpoet $

PORTNAME=	Module-Runtime-Conflicts
PORTVERSION=	0.002
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Provide information on conflicts for Module::Runtime

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USE_PERL5=	modbuildtiny
USES=		perl5

.include <bsd.port.mk>
