# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/converters/php5-recode/Makefile 340722 2014-01-22 17:00:46Z mat $

CATEGORIES=	converters

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-recode

.include "${MASTERDIR}/Makefile"
