# Created by: ijliao
# $FreeBSD: tags/RELEASE_10_3_0/astro/p5-Astro-FITS-Header/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Astro-FITS-Header
PORTVERSION=	3.07
PORTREVISION=	1
CATEGORIES=	astro perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Object Orientated interface to FITS HDUs

LICENSE=	GPLv3

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
