# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-pygpx/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	pygpx
PORTVERSION=	0.2
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wenheping@gmail.com
COMMENT=	Python Module For Parsing GPS Exchange Format (GPX) File

PLIST_SUB=	GPX_INFO=${PYDISTUTILS_EGGINFO}

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
