# Created by: Rodrigo Graeff <delphus@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/libytnef/Makefile 366451 2014-08-28 19:53:09Z tijl $

PORTNAME=	libytnef
PORTVERSION=	1.5
PORTREVISION=	3
CATEGORIES=	devel mail
MASTER_SITES=	SF/ytnef/${PORTNAME}/${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Unpack data in MS Outlook TNEF format

GNU_CONFIGURE=	yes
INSTALL_TARGET=	install-strip
USES=		libtool
USE_LDCONFIG=	yes

.include <bsd.port.mk>
