# Created by: Masahiro Teramoto <markun@onohara.to>
# $FreeBSD: tags/RELEASE_10_3_0/net/p5-Net-Growl/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Net-Growl
PORTVERSION=	0.99
PORTREVISION=	1
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	markun@onohara.to
COMMENT=	Growl Notifications over the network

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
