# Created by: Aaron Dalton <aaron@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/ftp/p5-File-Fetch/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	File-Fetch
PORTVERSION=	0.48
PORTREVISION=	1
CATEGORIES=	ftp www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Generic file fetching mechanism

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
