# Created by: James FitzGibbon <jfitz@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/p5-HTML-Stream/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	HTML-Stream
PORTVERSION=	1.60
PORTREVISION=	1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 HTML output stream class, and some markup utilities

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
