# Created by: Gerrit Beine (<gerrit@beine-computer.de>)
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-PHPDoc/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	PHPDoc
PORTVERSION=	0.1.0
CATEGORIES=	devel www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Tool to generate documentation from the source

USES=	pear

.include <bsd.port.mk>
