# Created by: Eugene Ossintsev
# $FreeBSD: tags/RELEASE_10_3_0/lang/ocaml-nox11/Makefile 361857 2014-07-15 03:42:50Z vanilla $

PORTNAME=	ocaml-nox11
CATEGORIES=	lang

MAINTAINER=	michael.grunewald@laposte.net
COMMENT=	Objective Caml compiler and programming environment (no X11)

MASTERDIR=	${.CURDIR}/../ocaml

CONFLICTS=	metaocaml-[0-9]* ocaml-[0-9]* ocaml-notk-[0-9]*

OPTIONS_EXCLUDE=TK X11

SFX=		-nox11

.include "${MASTERDIR}/Makefile"
