# Created by: Christopher Boumenot <boumenot@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Class-Gomor/Makefile 378437 2015-02-05 02:11:32Z vanilla $

PORTNAME=	Class-Gomor
PORTVERSION=	1.03
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	spry@anarchy.in.the.ph
COMMENT=	Class and object builder

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
