# Created by: Zane C. Bowers
# $FreeBSD: tags/RELEASE_10_3_0/x11/p5-X11-Resolution/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	X11-Resolution
PORTVERSION=	0.0.0
PORTREVISION=	1
CATEGORIES=	x11 perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	vvelox@vvelox.net
COMMENT=	Provides a method to get the resolution for a X11 screen

RUN_DEPENDS=	p5-X11-Protocol>=0:${PORTSDIR}/x11/p5-X11-Protocol

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
