# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/math/p5-Number-Uncertainty/Makefile 398532 2015-10-03 17:11:21Z sunpoet $

PORTNAME=	Number-Uncertainty
PORTVERSION=	0.1
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Object-orientated uncertainty object

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

NO_ARCH=	yes
USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
