# Created by: Kimura Fuyuki <fuyuki@hadaly.org>
# $FreeBSD: tags/RELEASE_10_3_0/security/p5-Crypt-CAST5_PP/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Crypt-CAST5_PP
PORTVERSION=	1.04
PORTREVISION=	1
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	CAST5 block cipher in pure Perl

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
