# Created by: joerg@FreeBSD.org
# $FreeBSD: tags/RELEASE_10_3_0/games/xmahjongg/Makefile 344603 2014-02-16 16:17:30Z miwi $

PORTNAME=	xmahjongg
PORTVERSION=	3.7
PORTREVISION=	2
CATEGORIES=	games
MASTER_SITES=	http://www.lcdf.org/xmahjongg/

MAINTAINER=	joerg@FreeBSD.org
COMMENT=	The Chinese game of Mahjongg for X11

USE_XORG=	x11
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
