# Created by: ijliao
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Devel-StackTrace/Makefile 373890 2014-12-04 13:21:00Z culot $

PORTNAME=	Devel-StackTrace
PORTVERSION=	2.00
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Stack trace and stack trace frame objects

LICENSE=	ART20

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
