# $FreeBSD: tags/RELEASE_10_3_0/databases/rubygem-arel5/Makefile 404166 2015-12-21 18:35:13Z sunpoet $

PORTNAME=	arel
PORTVERSION=	5.0.1.20140414130214
PORTEPOCH=	1
CATEGORIES=	databases rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	5

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Relational Algebra for Ruby

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
