# Created by: will
# $FreeBSD: tags/RELEASE_10_3_0/finance/p5-Math-Financial/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Math-Financial
PORTVERSION=	0.76
PORTREVISION=	1
CATEGORIES=	finance math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Perl module containing common functions for loans and annuities

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
