# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/net/php5-ldap/Makefile 364014 2014-08-04 15:03:44Z ale $

CATEGORIES=	net

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-ldap

.include "${MASTERDIR}/Makefile"
