# $FreeBSD: tags/RELEASE_10_3_0/devel/mips-xtoolchain-gcc/Makefile 384399 2015-04-21 01:49:29Z adrian $

PKGNAMEPREFIX=	mips-
PLIST=	${.CURDIR}/pkg-plist

MASTERDIR=	${.CURDIR}/../powerpc64-xtoolchain-gcc

.include "${MASTERDIR}/Makefile"
