# Created by: Joao Carlos Mendes Luis <jonny@jonny.eng.br>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/skill/Makefile 363335 2014-07-29 15:00:12Z adamw $

PORTNAME=	skill
PORTVERSION=	4.1.4
CATEGORIES=	sysutils
MASTER_SITES=	ftp://ftp.flux.utah.edu/pub/skill/ \
		ftp://fast.cs.utah.edu/pub/skill/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	SuperKILL, kill, or renice processes by pid, name, tty, or uid

USES=		tar:tgz

.include <bsd.port.mk>
