# Created by: Rick Elrod <codeblock@eighthbit.net>
# $FreeBSD: tags/RELEASE_10_3_0/graphics/rubygem-imagesize/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	imagesize
PORTVERSION=	0.1.1
CATEGORIES=	graphics rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	RubyGem for finding the size of an image

LICENSE=	BSD2CLAUSE RUBY
LICENSE_COMB=	dual

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
