# $FreeBSD: tags/RELEASE_10_3_0/hungarian/Makefile 341681 2014-01-29 07:10:12Z bapt $
#

    COMMENT = Hungarian language support

    SUBDIR += aspell
    SUBDIR += calligra-l10n
    SUBDIR += hu-phone
    SUBDIR += hu-zipcodes
    SUBDIR += hunspell
    SUBDIR += hyphen
    SUBDIR += jdictionary-eng-hun
    SUBDIR += jdictionary-eng-hun-expr
    SUBDIR += kde4-l10n
    SUBDIR += libreoffice
    SUBDIR += mythes

.include <bsd.port.subdir.mk>
