# $FreeBSD: tags/RELEASE_10_3_0/databases/rubygem-arel-helpers/Makefile 406787 2016-01-20 18:45:53Z antoine $

PORTNAME=	arel-helpers
PORTVERSION=	2.1.1
PORTREVISION=	1
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Helpers to construct database queries with ActiveRecord and Arel

LICENSE=	MIT

RUN_DEPENDS=	rubygem-activerecord>=3.1.0:${PORTSDIR}/databases/rubygem-activerecord

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
