# Created by: Mario Sergio Fujikawa Ferreira <lioux@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/converters/p5-Unicode-UTF8simple/Makefile 385902 2015-05-09 16:16:23Z adamw $

PORTNAME=	Unicode-UTF8simple
PORTVERSION=	1.06
PORTREVISION=	1
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Conversions to/from UTF-8 from/to charactersets

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
