# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-VersionControl_Git/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	VersionControl_Git
PORTVERSION=	0.4.4
CATEGORIES=	devel pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	OO interface to handle Git repository

USES=	pear

.include <bsd.port.mk>
