# Created by: Boris Samorodov <bsam@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/russian/eric6/Makefile 380765 2015-03-08 10:38:19Z bsam $

CATEGORIES=	russian devel python

.include "${.CURDIR}/../../devel/eric6/Makefile.inc"
