# Created by: Travis Campbell <hcoyote@ghostar.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Text-Textile/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Text-Textile
PORTVERSION=	2.12
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	hcoyote@ghostar.org
COMMENT=	Perl-based implementation of the Textile syntax by Dean Allen

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
