# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-gitlab_meta/Makefile 399578 2015-10-17 18:09:25Z sunpoet $

PORTNAME=	gitlab_meta
PORTVERSION=	7.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	GitLab meta gem

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
USES=		cpe

CPE_PRODUCT=	gitlab
CPE_VENDOR=	gitlab

.include <bsd.port.mk>
