# Created by: Ju Pengfei <jupengfei@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Sys-Trace/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	Sys-Trace
PORTVERSION=	0.03
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Interface to system call tracing interfaces

LICENSE=	WTFPL2
LICENSE_NAME=	Do What The Fuck You Want To Public License version 2
LICENSE_FILE=	${WRKSRC}/README
LICENSE_PERMS=	dist-mirror dist-sell pkg-mirror pkg-sell auto-accept

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
