# Created by: Tom Judge <tom@tomjudge.com>
# $FreeBSD: tags/RELEASE_10_3_0/databases/py-MySQLdb55/Makefile 343503 2014-02-09 14:15:28Z rm $

PKGNAMESUFFIX=	55

COMMENT=	Access a MySQL database through Python (Using MySQL 5.5 Client)

WANT_MYSQL_VER=	55
MASTERDIR=	${.CURDIR}/../py-MySQLdb

.include "${MASTERDIR}/Makefile"
