# Created by: chinsan
# $FreeBSD: tags/RELEASE_10_3_0/devel/pecl-uploadprogress/Makefile 402450 2015-11-26 14:39:58Z miwi $

PORTNAME=	uploadprogress
PORTVERSION=	1.0.3
CATEGORIES=	devel pear
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-
DIST_SUBDIR=	PECL

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Provides track progress of a file upload

LICENSE=	PHP301

USES=		tar:tgz
USE_PHP=	yes
USE_PHPEXT=	yes

CONFIGURE_ARGS=	--enable-uploadprogress

.include <bsd.port.mk>
