# Created by: Alex Miller (<asm@asm.kiev.ua>)
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-XML_Util/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	XML_Util
PORTVERSION=	1.3.0
CATEGORIES=	devel www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PEAR XML utility class

LICENSE=	BSD2CLAUSE

USES=		pear

.include <bsd.port.mk>
