# $FreeBSD: tags/RELEASE_10_3_0/devel/elixir-excoveralls/Makefile 402713 2015-12-01 02:18:54Z vanilla $

PORTNAME=	excoveralls
PORTVERSION=	0.4.3
DISTVERSIONPREFIX=	v
CATEGORIES=	devel
PKGNAMEPREFIX=	elixir-

MAINTAINER=	vanilla@FreeBSD.org
COMMENT=	Coverage Reports for Elixir

LICENSE=	APACHE20

MIX_BUILD_DEPS=	devel/elixir-exjsx \
		www/erlang-hackney

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	parroty

.include <bsd.port.mk>
