# Created by: Ryan Steinmetz (<rpsfa@rit.edu>)
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-configuration/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	configuration
PORTVERSION=	1.3.4
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Mechanism to parse ruby configuration files

LICENSE=	BSD2CLAUSE RUBY
LICENSE_COMB=	dual

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
