# Created by: gpalmer
# $FreeBSD: tags/RELEASE_10_3_0/x11/xdtm/Makefile 346436 2014-02-28 07:09:07Z bapt $

PORTNAME=	xdtm
PORTVERSION=	2.5.8
PORTREVISION=	2
CATEGORIES=	x11
MASTER_SITES=	XCONTRIB/applications

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Graphical shell for the X Window System

WRKSRC=		${WRKDIR}/${PORTNAME}

USE_XORG=	xaw
USES=		imake
MAKE_JOBS_UNSAFE=	yes

.include <bsd.port.mk>
