# Created by: matt@bdd.net
# $FreeBSD: tags/RELEASE_10_3_0/x11/xtacy/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	xtacy
PORTVERSION=	1.14
PORTREVISION=	2
CATEGORIES=	x11
MASTER_SITES=	http://www.ultranet.com/~jjohnson/ \
		SUNSITE/apps/graphics/hacks/X
DISTNAME=	${PORTNAME}114

MAINTAINER=	matt@bdd.net
COMMENT=	X11 trippy color-cycling toy

USES=		imake
USE_XORG=	x11 xext
PLIST_FILES=	bin/xtacy man/man1/xtacy.1.gz

WRKSRC=		${WRKDIR}/Xtacy

.include <bsd.port.mk>
