# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/audio/py-mpd/Makefile 371170 2014-10-19 07:33:09Z mva $

PORTNAME=	mpd
PORTVERSION=	0.3.0
PORTREVISION=	1
#PORTEPOCH=	0
CATEGORIES=	audio python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	python-${PORTNAME}-${PORTVERSION}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Python MPD client library

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
