# Created by: jmacd
# $FreeBSD: tags/RELEASE_10_3_0/games/xpilot/Makefile 363371 2014-07-29 18:41:15Z adamw $

PORTNAME=	xpilot
PORTVERSION=	4.5.5
CATEGORIES=	games
MASTER_SITES=	SF/${PORTNAME}game/${PORTNAME}-4/${PORTNAME}-${PORTVERSION}

MAINTAINER=	lme@FreeBSD.org
COMMENT=	Xpilot(client) and xpilots(server)

USE_XORG=	x11 xext
USES=		imake tar:bzip2

.include <bsd.port.mk>
