# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/R-cran-rngtools/Makefile 393888 2015-08-10 19:17:24Z tota $

PORTNAME=	rngtools
PORTVERSION=	1.2.4
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Utility functions for working with Random Number Generators

LICENSE=	GPLv3

RUN_DEPENDS=	R-cran-pkgmaker>=0.20:${PORTSDIR}/devel/R-cran-pkgmaker

USES=	cran:auto-plist

.include <bsd.port.mk>
