# Created by: Thierry Thomas (<thierry@FreeBSD.org>)
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-VFS/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	VFS
PORTVERSION=	0.3.0
CATEGORIES=	devel pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PEAR Virtual File System API

BUILD_DEPENDS=	${PEARDIR}/Log/null.php:${PORTSDIR}/sysutils/pear-Log
RUN_DEPENDS=	${PEARDIR}/Log/null.php:${PORTSDIR}/sysutils/pear-Log

USE_PHP=	gettext
USES=	pear

.include <bsd.port.mk>
