# Created by: CyrilM <cyrilm@tower.pp.ru>
# $FreeBSD: tags/RELEASE_10_3_0/mail/jamlib/Makefile 365343 2014-08-18 19:13:18Z antoine $

PORTNAME=	jamlib
PORTVERSION=	1.4.7
PORTREVISION=	2
CATEGORIES=	mail
MASTER_SITES=	SF

MAINTAINER=	ports@FreeBSD.org
COMMENT=	JAM subroutine library

USES=		libtool
GNU_CONFIGURE=	yes
INSTALL_TARGET=	install-strip
USE_LDCONFIG=	yes

.include <bsd.port.mk>
