# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-DateTime-Cron-Simple/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	DateTime-Cron-Simple
PORTVERSION=	0.2
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Parse a cron entry and check against current time

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
