# $FreeBSD: tags/RELEASE_10_3_0/devel/erlang-bear/Makefile 391483 2015-07-06 22:27:17Z olgeni $

PORTNAME=	bear
PORTVERSION=	0.8.2
CATEGORIES=	devel
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Set of statistics functions for Erlang

LICENSE=	APACHE20

USES=		erlang:rebar
USE_GITHUB=	yes
GH_ACCOUNT=	boundary

.include <bsd.port.mk>
