#
# $FreeBSD: releng/10.3/tools/regression/environ/Makefile.retention 276486 2014-12-31 23:25:37Z ngie $
#
SRCS=	retention.c
PROG=	retention

CFLAGS+=-Wall -I../../../include

CLEANFILES=	*~ ${PROG}.core

MAN=

.include <bsd.prog.mk>

test: ${PROG}
	@./${PROG}
