#
# $FreeBSD: releng/10.3/tools/regression/environ/Makefile.envctl 276486 2014-12-31 23:25:37Z ngie $
#
SRCS=	envctl.c
PROG=	envctl

CFLAGS+=-Wall -I../../../include

CLEANFILES=	${PROG}.core

MAN=

.include <bsd.prog.mk>

test: ${PROG}
	@env -i sh envtest.t
