#!/bin/sh
#
# $FreeBSD: releng/10.3/etc/rc.d/NETWORKING 294680 2016-01-24 19:41:31Z ian $
#

# PROVIDE: NETWORKING NETWORK
# REQUIRE: netif netwait netoptions routing ppp ipfw stf faith
# REQUIRE: defaultroute routed mrouted route6d mroute6d resolv bridge
# REQUIRE: static_arp static_ndp

#	This is a dummy dependency, for services which require networking
#	to be operational before starting.
