# $FreeBSD: tags/RELEASE_10_3_0/x11-drivers/xf86-video-tdfx/Makefile 399179 2015-10-13 07:45:08Z kwm $

PORTNAME=	xf86-video-tdfx
PORTVERSION=	1.4.6
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org tdfx display driver

USE_GL=		gl

XORG_CAT=	driver
USE_XORG=	xf86driproto glproto

.include <bsd.port.mk>
