# Created by: Joe Marcus Clarke <marcus@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/audio/freedesktop-sound-theme/Makefile 382573 2015-03-29 09:07:26Z kwm $

PORTNAME=	freedesktop-sound-theme
PORTVERSION=	0.8
CATEGORIES=	audio gnome
MASTER_SITES=	http://people.freedesktop.org/~mccann/dist/
DISTNAME=	sound-theme-freedesktop-${PORTVERSION}

MAINTAINER=	gnome@FreeBSD.org
COMMENT=	Sound theme based on the FreeDesktop specification

USE_GNOME=	intlhack
USES=		gettext-tools gmake tar:bzip2
GNU_CONFIGURE=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
