# Created by: Timur I. Bakeyev <bat@cpan.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-boolean/Makefile 378581 2015-02-07 10:07:08Z bofh $

PORTNAME=	boolean
PORTVERSION=	0.45
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:INGY
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Boolean support for Perl

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
