# Created by: Pav Lucistnik <pav@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/graphics/libiptcdata/Makefile 363578 2014-07-31 12:39:04Z amdmi3 $

PORTNAME=	libiptcdata
PORTVERSION=	1.0.4
PORTREVISION=	1
CATEGORIES=	graphics
MASTER_SITES=	SF

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Library for manipulating IPTC metadata stored in image files

USES=		pkgconfig iconv libtool pathfix
USE_LDCONFIG=	yes
GNU_CONFIGURE=	yes
CONFIGURE_ARGS=	--disable-nls
INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
