# $FreeBSD: tags/RELEASE_10_3_0/print/cups-image/Makefile 344633 2014-02-16 21:17:15Z bsam $

CATEGORIES=	print

MAINTAINER=	ports@FreeBSD.org

MASTERDIR?=	${.CURDIR}/../cups-base

CUPS_IMAGE=	yes

.sinclude "${.CURDIR}/Makefile.local"
.include "${MASTERDIR}/Makefile"
