# $FreeBSD: tags/RELEASE_10_3_0/mail/p5-MIME-Types/Makefile 401541 2015-11-13 19:13:25Z sunpoet $

PORTNAME=	MIME-Types
PORTVERSION=	2.12
CATEGORIES=	mail perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:MARKOV
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl extension for determining MIME types

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
