# Created by: Charlie & <root@meatwad.mouf.net>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-bacon/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	bacon
PORTVERSION=	1.2.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Bacon is a small RSpec clone

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/bacon

.include <bsd.port.mk>
