# Created by: Zhen REN <bg1tpt@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/math/pear-Math_Combinatorics/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Math_Combinatorics
PORTVERSION=	1.0.0
PORTEPOCH=	1
CATEGORIES=	math pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Package that produces combinations and permutations

USES=	pear

.include <bsd.port.mk>
