# $FreeBSD: tags/RELEASE_10_3_0/multimedia/gstreamer1-plugins-x264/Makefile 397984 2015-09-26 14:36:23Z kwm $

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	Gstreamer x264 plugin

GST_PLUGIN=	x264
DIST=		ugly

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
