# Created by: clsung@dragon2.net
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Object-MultiType/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Object-MultiType
PORTVERSION=	0.05
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl Objects as Hash, Array, and Scalar at the same time

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
