# Created by: Volodymyr Kostyrko <c.kworr@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-termcolor/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	termcolor
PORTVERSION=	1.1.0
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	c.kworr@gmail.com
COMMENT=	ANSII Color formatting for output in terminal

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
