# Created by: Sofian Brabez <sbrabez@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-aspyct/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	aspyct
PORTVERSION=	3.0
CATEGORIES=	devel python
MASTER_SITES=	SF/${PORTNAME}/${PORTNAME}/${PORTVERSION}%20beta%204
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	${PORTNAME:C/a/A/}-${PORTVERSION}_beta_4

MAINTAINER=	sbz@FreeBSD.org
COMMENT=	Python library including an aspect-oriented programming (AOP) engine

LICENSE=	LGPL3

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
