# Created by: Olivier Duchateau <duchateau.olivier@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-speaklater/Makefile 375249 2014-12-22 17:12:26Z feld $

PORTNAME=	speaklater
PORTVERSION=	1.3
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	olivierd@FreeBSD.org
COMMENT=	Lazy string Python module for translations

LICENSE=	BSD3CLAUSE

USES=	python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
