# Created by: chinsan
# $FreeBSD: tags/RELEASE_10_3_0/textproc/vbindiff/Makefile 386097 2015-05-11 18:34:57Z mat $

PORTNAME=	vbindiff
DISTVERSION=	3.0_beta4
CATEGORIES=	textproc
MASTER_SITES=	http://www.cjmweb.net/vbindiff/

MAINTAINER=	cyberbotx@cyberbotx.com
COMMENT=	Visual binary diff, visually compare binary files

GNU_CONFIGURE=	yes

PLIST_FILES=	bin/vbindiff \
		man/man1/vbindiff.1.gz

.include <bsd.port.mk>
