# Created by: Jose Jachuf <jjachuf@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/databases/py-firebirdsql/Makefile 379677 2015-02-23 14:19:53Z culot $

PORTNAME=	firebirdsql
PORTVERSION=	0.9.6
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jjachuf@gmail.com
COMMENT=	Python DBAPI module for FirebirdSQL

LICENSE=	BSD2CLAUSE

# Python3 ready
USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
