# Created by: stas
# $FreeBSD: tags/RELEASE_10_3_0/devel/libinotify/Makefile 397035 2015-09-16 00:58:12Z delphij $

PORTNAME=	libinotify
PORTVERSION=	20150910
CATEGORIES=	devel

MAINTAINER=	delphij@FreeBSD.org
COMMENT=	Kevent based inotify compatible library

LICENSE=	MIT

USE_GITHUB=	yes
GH_ACCOUNT=	dmatveev
GH_PROJECT=	libinotify-kqueue
GH_TAGNAME=	b2873cf

USES=		autoreconf libtool
GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes
INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
