# Created by: William Grzybowski
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-mimeparse/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	mimeparse
PORTVERSION=	0.1.4
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	python-${PORTNAME}-${PORTVERSION}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Basic functions for handling mime-types in Python

USES=		python
USE_PYTHON=	distutils autoplist
PYDISTUTILS_EGGINFO=	python_mimeparse-${PORTVERSION}-py${PYTHON_VER}.egg-info

.include <bsd.port.mk>
