# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-rubygems-test/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	rubygems-test
PORTVERSION=	0.4.3
PORTREVISION=	1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Run automated tests

LICENSE=	MIT

RUN_DEPENDS=	rubygem-rake>=0.8.7:${PORTSDIR}/devel/rubygem-rake

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
