# Created by: Joe Marcus Clarke <marcus@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py3-dbus/Makefile 393429 2015-08-02 15:03:19Z tijl $

PORTREVISION=	1

PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
PKGNAMESUFFIX=

COMMENT=	Python3 bindings for the D-BUS messaging system

SLAVE_PORT=	python3

MASTERDIR=	${.CURDIR}/../../devel/pydbus-common
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
