# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: tags/RELEASE_10_3_0/net/pear-Net_Ping/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Net_Ping
PORTVERSION=	2.4.5
CATEGORIES=	net pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PEAR class to execute ping

USES=	pear

.include <bsd.port.mk>
