# Created by: Alex Miller (<asm@asm.kiev.ua>)
# $FreeBSD: tags/RELEASE_10_3_0/www/pear-HTTP_Header/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	HTTP_Header
PORTVERSION=	1.2.1
CATEGORIES=	www devel pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PEAR OO interface to modify and handle HTTP headers and status codes

BUILD_DEPENDS=	${PEARDIR}/HTTP.php:${PORTSDIR}/www/pear-HTTP
RUN_DEPENDS=	${PEARDIR}/HTTP.php:${PORTSDIR}/www/pear-HTTP

USES=	pear

.include <bsd.port.mk>
