# Created by: Tomoyuki Sakurai <cherry@trombik.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-XML-RSSLite/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	XML-RSSLite
PORTVERSION=	0.15
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Lightweight, relaxed RSS (and XML-ish) parser

USES=		perl5 tar:tgz
USE_PERL5=	configure

.include <bsd.port.mk>
