# Created by: will
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Tie-IxHash/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Tie-IxHash
PORTVERSION=	1.23
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module implementing ordered in-memory associative arrays

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
