# $FreeBSD: tags/RELEASE_10_3_0/www/twiki-BlogAddOn/Makefile 362252 2014-07-19 11:09:51Z ohauer $

PORTNAME=	BlogAddOn
SVNREV=		16623

COMMENT=	Simple blogging application

.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
