# $FreeBSD: tags/RELEASE_10_3_0/textproc/rubygem-hikidoc/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	hikidoc
PORTVERSION=	0.1.0
CATEGORIES=	textproc ruby
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Text-to-HTML conversion tool for web writers

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/hikidoc

.include <bsd.port.mk>
