# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-debug_inspector/Makefile 389387 2015-06-13 13:53:41Z sunpoet $

PORTNAME=	debug_inspector
PORTVERSION=	0.0.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby wrapper for the MRI 2.0 debug_inspector API

LICENSE=	MIT

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
