# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Class-Null/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Class-Null
PORTVERSION=	2.110730
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module which implements the Null Class design pattern

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
