# Created by: Mario Sergio Fujikawa Ferreira <lioux@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/x11-themes/kde-icons-noia/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	noia
PORTVERSION=	1.00
MASTER_SITES=	GENTOO
DISTNAME=	noia-kde-icons-${PORTVERSION}

COMMENT=	KDE Noia complete iconset

USES=		tar:tgz
WRKSRC=		"${WRKDIR}/noia_kde_${PORTVERSION:C/\.//}"
PORT_SHAREDIR=	${PORTNAME}

.include "${.CURDIR}/Makefile.icons"
