# Created by: Dikshie <dikshie@sfc.wide.ad.jp>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Config-Grammar/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Config-Grammar
PORTVERSION=	1.10
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:DSCHWEI
PKGNAMEPREFIX=	p5-

MAINTAINER=	dikshie@sfc.wide.ad.jp
COMMENT=	Grammar-based, user-friendly config parser

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
