# $FreeBSD: tags/RELEASE_10_3_0/graphics/digikam-kde4-doc/Makefile 398832 2015-10-08 15:11:28Z olgeni $

PORTNAME=	digikam-doc
PORTVERSION=	${DIGIKAM_VER}
CATEGORIES=	graphics kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Documentation for digiKam, showFoto, and Kipi-plugins

CONFLICTS_INSTALL=	digikam-2.* kipi-plugins-2.*

WRKSRC=		${WRKDIR}/${DISTNAME}/doc

.include "${.CURDIR}/../digikam-kde4/Makefile.common"
.include <bsd.port.mk>
