# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Fennec-Lite/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Fennec-Lite
PORTVERSION=	0.004
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension for minimalist Fennec, the commonly used bits

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
