# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Sub-Delete/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Sub-Delete
PORTVERSION=	1.00002
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module enabling one to delete subroutines

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
