# Created by: Ditesh Shashikant Gathani <ditesh@gathani.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/pear-Services_SharedBook/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Services_SharedBook
PORTVERSION=	0.2.6
CATEGORIES=	www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PHP wrapper for SharedBook Open API

BUILD_DEPENDS=	${PEARDIR}/HTTP/Client.php:${PORTSDIR}/www/pear-HTTP_Client
RUN_DEPENDS=	${PEARDIR}/HTTP/Client.php:${PORTSDIR}/www/pear-HTTP_Client

USES=	pear

.include <bsd.port.mk>
