# Created by: Christer Edwards <christer.edwards@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-ioflo/Makefile 403457 2015-12-10 14:17:58Z miwi $

PORTNAME=	ioflo
PORTVERSION=	1.4.6
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	christer.edwards@gmail.com
COMMENT=	Automated Reasoning Engine and Flow Based Programming Framework

LICENSE=	APACHE20

USES=		python:2 shebangfix
USE_PYTHON=	autoplist distutils
NO_ARCH=	yes

SHEBANG_FILES=	scripts/ioflo

.include <bsd.port.mk>
