# Created by: Zach Thompson <hideo@lastamericanempire.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Date-Range/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Date-Range
PORTVERSION=	1.41
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Date::Range - work with a range of dates

BUILD_DEPENDS=	p5-Date-Simple>=0.03:${PORTSDIR}/devel/p5-Date-Simple
RUN_DEPENDS=	p5-Date-Simple>=0.03:${PORTSDIR}/devel/p5-Date-Simple

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
