# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-algebrick/Makefile 405015 2016-01-01 17:05:54Z mmoll $

PORTNAME=	algebrick
PORTVERSION=	0.7.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Typed structs based on algebraic type definitions

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
