# $FreeBSD: releng/10.3/release/doc/en_US.ISO8859-1/Makefile 296858 2016-03-14 13:45:59Z gjb $

RELN_ROOT?= ${.CURDIR}/..

SUBDIR = relnotes
SUBDIR+= hardware
SUBDIR+= installation
SUBDIR+= readme
SUBDIR+= errata

COMPAT_SYMLINK = en

LANGCODE=en_US.ISO8859-1
_LANGCODE=en_US.ISO8859-1

.include "${RELN_ROOT}/share/mk/doc.relnotes.mk"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
