# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-timelib/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	timelib
PORTVERSION=	0.2.4
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Parse English textual date descriptions

USES=		python zip
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
