# Created by: Andrei Antoukh <niwi@niwi.be>
# $FreeBSD: tags/RELEASE_10_3_0/databases/py-couchdb/Makefile 371173 2014-10-19 08:50:17Z mva $

PORTNAME=	CouchDB
PORTVERSION=	0.8
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=	python

MAINTAINER=	niwi@niwi.be
COMMENT=	Simple Library to Allow Python Applications to Use CouchDB

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	distutils pythonprefix

.include <bsd.port.mk>
