# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Proc-Queue/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Proc-Queue
PORTVERSION=	1.23
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Proc::Queue - limit the number of child processes running

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
