# Created by: bsam
# $FreeBSD: tags/RELEASE_10_3_0/multimedia/linux-f10-libv4l/Makefile 368845 2014-09-22 10:40:00Z xmj $

PORTNAME=	libv4l
PORTVERSION=	0.6.2
CATEGORIES=	multimedia linux

MAINTAINER=	emulation@FreeBSD.org
COMMENT=	Collection of video4linux support libraries (Fedora 10)

USE_LINUX=	f10
USE_LINUX_RPM=	yes

RPMVERSION=	1.fc10
USE_LDCONFIG=	yes
PLIST_SUB+=	PORTVERSION=${PORTVERSION}

.include <bsd.port.mk>
