# Created by: Jason Heiss <jheiss@aput.biz>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-File-Cat/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	File-Cat
PORTVERSION=	1.2
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl implementation of cat

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
