# Created by: Andrew Pantyukhin <infofarmer@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/xpi-foxmarks/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	foxmarks
PORTVERSION=	2.7.2
PORTREVISION=	1
DISTVERSIONSUFFIX=	-fx
CATEGORIES=	www

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Bookmark synchronizer

XPI_DISTNAME=	foxmarks_bookmark_synchronizer
XPI_ID=		foxmarks@kei.com
XPI_NUM=	2410

.include "${.CURDIR}/../xpi-adblock/Makefile.xpi"
.include <bsd.port.mk>
