# $FreeBSD: releng/10.3/tools/regression/pthread/mutex_isowned_np/Makefile 276486 2014-12-31 23:25:37Z ngie $

PROG=	mutex_isowned_np
MAN=
DPADD=	${LIBPTHREAD}
LDADD=	-lpthread

.include <bsd.prog.mk>
