# Created by: rafan@infor.org
# $FreeBSD: tags/RELEASE_10_3_0/science/libsvm-python/Makefile 377195 2015-01-16 17:28:13Z rafan $

PKGNAMESUFFIX=	-python

MAINTAINER=	ports@FreeBSD.org

MASTERDIR=	${.CURDIR}/../../science/libsvm

PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
