# $FreeBSD: tags/RELEASE_10_3_0/www/twiki-SpreadSheetPlugin/Makefile 362252 2014-07-19 11:09:51Z ohauer $

PORTNAME=	SpreadSheetPlugin
SVNREV=		16417

COMMENT=	Spreadsheet capabilities in topics

.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
