# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pecl-hrtime/Makefile 396250 2015-09-07 07:12:28Z vanilla $

PORTNAME=	hrtime
PORTVERSION=	0.5.1
CATEGORIES=	devel
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-
DIST_SUBDIR=	PECL

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	High resolution timing for PHP

LICENSE=	BSD2CLAUSE

USES=		tar:tgz
USE_PHP=	yes
USE_PHPEXT=	yes

.include <bsd.port.mk>
