# Created by: rpsfa@rit.edu
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-yui-compressor/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	yui-compressor
PORTVERSION=	0.12.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	YUI Compressor for minifying JavaScript and CSS assets

LICENSE=	BSD3CLAUSE MIT MPL
LICENSE_COMB=	dual

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
