# $FreeBSD: tags/RELEASE_10_3_0/x11-drivers/xf86-input-fpit/Makefile 399179 2015-10-13 07:45:08Z kwm $

PORTNAME=	xf86-input-fpit
PORTVERSION=	1.4.0
PORTREVISION=	6
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org fpit input driver

XORG_CAT=	driver
USE_XORG=	xrandr

.include <bsd.port.mk>
