# Created by: Thinker K.F. Li <thinker@branda.to>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pythk/Makefile 379646 2015-02-23 07:47:10Z amdmi3 $

PORTNAME=	pythk
PORTVERSION=	0.2.0
PORTREVISION=	1
CATEGORIES=	devel
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Collection of Python functions

LICENSE=	BSD2CLAUSE

USES=		python:2
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
