# $FreeBSD: tags/RELEASE_10_3_0/devel/sparc64-gcc/Makefile 392874 2015-07-25 11:30:27Z bapt $

PKGNAMEPREFIX=	sparc64-
PLIST=	${.CURDIR}/pkg-plist

MASTERDIR=	${.CURDIR}/../powerpc64-gcc

.include "${MASTERDIR}/Makefile"
