# Created by: Yoshisato YANAGISAWA
# $FreeBSD: tags/RELEASE_10_3_0/security/p5-Crypt-Camellia_PP/Makefile 395270 2015-08-25 14:52:02Z sunpoet $

PORTNAME=	Crypt-Camellia_PP
PORTVERSION=	0.02
PORTREVISION=	1
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Pure Perl Camellia 128-bit block cipher module

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
