# $FreeBSD: tags/RELEASE_10_3_0/devel/py-daemons/Makefile 368332 2014-09-16 15:57:48Z jhale $

PORTNAME=	daemons
PORTVERSION=	0.2.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	fax@nohik.ee
COMMENT=	Resource library for Python developers to create daemon processes

LICENSE=	APACHE20

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
