# $FreeBSD: tags/RELEASE_10_3_0/sysutils/py-ptyprocess/Makefile 390301 2015-06-22 16:48:24Z robak $

PORTNAME=	ptyprocess
PORTVERSION=	0.5
CATEGORIES=	sysutils python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	robak@FreeBSD.org
COMMENT=	Run a subprocess in a pseudo terminal

LICENSE=	ISCL

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
