# Created by: jeffhung
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Class-OOorNO/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Class-OOorNO
PORTVERSION=	0.011
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	jeffhung@mail2000.com.tw
COMMENT=	Perl module that give your module classic AND OO interfaces

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
