# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/misc/rubygem-mime-types/Makefile 402970 2015-12-04 12:35:16Z sunpoet $

PORTNAME=	mime-types
PORTVERSION=	2.99
CATEGORIES=	misc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby gem which provides a mailcap-like MIME Content-Type lookup

LICENSE=	ART20 GPLv2 GPLv3 MIT
LICENSE_COMB=	dual

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
