# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/security/R-cran-digest/Makefile 389316 2015-06-13 03:55:29Z tota $

PORTNAME=	digest
PORTVERSION=	0.6.8
CATEGORIES=	security
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Create cryptographic hash digests of R objects

LICENSE=	GPLv2

USES=	cran:auto-plist

.include <bsd.port.mk>
