# $FreeBSD: tags/RELEASE_10_3_0/audio/p5-Audio-Ecasound/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Audio-Ecasound
PORTVERSION=	1.01
PORTREVISION=	1
CATEGORIES=	audio perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension for ecasound sampler, recorder, fx-processor

BUILD_DEPENDS=	libecasoundc-config:${PORTSDIR}/audio/ecasound

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
