# Created by: Mauricio Herrera Cuadra <mauricio@arareko.net>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Syntax-Highlight-Perl-Improved/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Syntax-Highlight-Perl-Improved
PORTVERSION=	1.01
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:DAVIDCYL/Syntax-Highlight-Perl-Improved-101
PKGNAMEPREFIX=	p5-

MAINTAINER=	mauricio@arareko.net
COMMENT=	Syntax highlighting for Perl code

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
