# Created by: Steven Kreuzer <skreuzer@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/py-python-digitalocean/Makefile 403208 2015-12-07 14:40:32Z skreuzer $

PORTNAME=	python-digitalocean
PORTVERSION=	1.8
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	API to manage digitalocean.com droplets

LICENSE=	GPLv3

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}requests>=2.0.0:${PORTSDIR}/www/py-requests

USES=	python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
