# Created by: Stefan Zehl <sec@42.org>
# $FreeBSD: tags/RELEASE_10_3_0/games/ladder/Makefile 384672 2015-04-24 18:41:36Z amdmi3 $

PORTNAME=	ladder
PORTVERSION=	1.00
PORTREVISION=	2
CATEGORIES=	games
MASTER_SITES=	http://www.srv.net/~kth/ \
		ftp://ftp.42.org/pub/unix/games/ \
		http://mirror.amdmi3.ru/distfiles/
DISTNAME=	${PORTNAME}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	The old "ladder" game

RESTRICTED=	possible copyright problems ?

USES=		tar
NO_WRKSUBDIR=	true

.include <bsd.port.mk>
