# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Params-Classify/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Params-Classify
PORTVERSION=	0.013
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Argument type classification

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
