# Created by: Tom McLaughlin <tmclaugh@sdf.lonestar.org>
# $FreeBSD: tags/RELEASE_10_3_0/x11-themes/gnome-icons-stylish/Makefile 400848 2015-11-05 12:36:25Z mat $

# Port logic gratuitously stolen from x11-themes/kde-icons-noia by
# lioux@.  If it's not defined here and you think it should be, check
# x11-themes/gnome-icons/bsd.gnome-icons.mk for it.

PORTNAME=	stylish
PORTVERSION=	20030129
PORTREVISION=	2
CATEGORIES=	x11-themes gnome
MASTER_SITES=	GNOME/teams/art.gnome.org/archive/themes/icon
DISTNAME=	ICON-Stylish

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Stylish Icons for Gnome

RESTRICTED=	${REASON}

NO_WRKSUBDIR=	yes

.include "${.CURDIR}/../gnome-icons/bsd.gnome-icons.mk"
.include <bsd.port.mk>
