# Created by: Vasiliy Ch <blttll@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/ciso/Makefile 362126 2014-07-17 08:57:51Z olgeni $

PORTNAME=	ciso
PORTVERSION=	1.0.0
PORTREVISION=	2
CATEGORIES=	sysutils
MASTER_SITES=	SF

MAINTAINER=	blttll@gmail.com
COMMENT=	Tool to compress ISO images to CSO format

USES=		dos2unix
PLIST_FILES=	bin/ciso

.include <bsd.port.mk>
