# Created by: Craig Manley
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Scope-Guard/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Scope-Guard
PORTVERSION=	0.20
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:CHOCOLATE
PKGNAMEPREFIX=	p5-

MAINTAINER=	v.a.popov@gmail.com
COMMENT=	Lexically scoped resource management

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
