# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/py-apachelog/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	apachelog
PORTVERSION=	1.1
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	GOOGLE_CODE \
		http://freebsd.unixfreunde.de/sources/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Python access log parser

USES=		python:2
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
