# Created by: Yoshiro MIHIRA <sanpei@yy.cs.keio.ac.jp>
# $FreeBSD: tags/RELEASE_10_3_0/x11-clocks/swisswatch/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	swisswatch
PORTVERSION=	0.06
PORTREVISION=	2
CATEGORIES=	x11-clocks
MASTER_SITES=	PORTS_JP

MAINTAINER=	sanpei@FreeBSD.org
COMMENT=	Swiss railway clock emulation, and a fancy default appearance

USES=		imake tar:Z
USE_XORG=	ice sm x11 xext xmu xt

.include <bsd.port.mk>
