# $FreeBSD: tags/RELEASE_10_3_0/net/wireshark-qt5/Makefile 401779 2015-11-16 17:19:50Z marcus $

MASTERDIR=	${.CURDIR}/../wireshark
COMMENT=	Powerful network analyzer/capture tool (QT package)

CONFLICTS=	wireshark-[0-9]*

OPTIONS_EXCLUDE=	GTK2 GTK3
OPTIONS_DEFAULT=	SNMP ADNS IPV6 GEOIP KRB_BASE QT5

.include "${MASTERDIR}/Makefile"
