# Created by: Nick Sayer <nsayer@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/comms/p5-Device-SerialPort/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Device-SerialPort
PORTVERSION=	1.040000
PORTREVISION=	1
CATEGORIES=	comms perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-${PORTVERSION:C/0+$//}

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 module for simple serial port control

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
