# Created by: Ion-Mihai "IOnut" Tetcu <itetcu@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/mail/squirrelmail-check_quota-plugin/Makefile 366415 2014-08-28 15:16:49Z adamw $

PORTNAME=	check-quota
PORTVERSION=	2.2
PORTREVISION=	3
CATEGORIES=	mail www
DISTNAME=	${PORTNAME:S/-/_/}-${PORTVERSION}-1.4.0

MAINTAINER=	itetcu@FreeBSD.org
COMMENT=	Check/display users' mail quota (filesystem, IMAP-based, and cPanel)

USE_SM_COMPAT=	YES

SQUIRREL_PLUGIN_NAME=	${PORTNAME:S/-/_/}

.include "${.CURDIR}/../squirrelmail/bsd.squirrelmail.mk"
.include <bsd.port.mk>
