# Created by: Yen-Ming Lee <leeym@cae.ce.ntu.edu.tw>
# $FreeBSD: tags/RELEASE_10_3_0/security/p5-Digest-SHA1/Makefile 376708 2015-01-10 14:19:12Z wen $

PORTNAME=	Digest-SHA1
PORTVERSION=	2.13
PORTREVISION=	1
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl interface to the SHA-1 Algorithm

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
