# Created by: Maxim Sobolev <sobomax@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/net/p5-Net-TCLink/Makefile 377064 2015-01-15 09:05:37Z tijl $

PORTNAME=	Net-TCLink
PORTVERSION=	3.4
PORTREVISION=	2
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	Net_TCLink.pm-${PORTVERSION}

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Module to for connecting to the TrustCommerce payment gateway

LICENSE=	LGPL21

USES=		perl5
USE_OPENSSL=	yes
USE_PERL5=	configure

.include <bsd.port.mk>
