# $FreeBSD: tags/RELEASE_10_3_0/devel/R-cran-randomForest/Makefile 367888 2014-09-10 20:50:31Z gerald $

PORTNAME=	randomForest
DISTVERSION=	4.6-7
PORTREVISION=	6
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Classification based on a forest of trees using random inputs

RUN_DEPENDS=	R-cran-RColorBrewer>=1.0.5_6:${PORTSDIR}/graphics/R-cran-RColorBrewer

USES=	cran:auto-plist

.include <bsd.port.mk>
