# Created by: otaviof@gmail.com
# $FreeBSD: tags/RELEASE_10_3_0/www/p5-Apache-Htgroup/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Apache-Htgroup
PORTVERSION=	1.23
PORTREVISION=	1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	otaviof@gmail.com
COMMENT=	Manage Apache authentication group files

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
