# Created by: Mark Pulford <mark@kyne.com.au>
# $FreeBSD: tags/RELEASE_10_3_0/net/nc/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	nc
PORTVERSION=	1.0.1
PORTREVISION=	1
CATEGORIES=	net
MASTER_SITES=	SUNSITE/utils/file
DISTNAME=	ncat-${PORTVERSION}

MAINTAINER=	lx@redundancy.redundancy.org
COMMENT=	Network aware cat

GNU_CONFIGURE=	yes

PLIST_FILES=	bin/ncat \
		man/man1/ncat.1.gz

.include <bsd.port.mk>
