# Created by: Gabor Kovesdan
# $FreeBSD: tags/RELEASE_10_3_0/security/p5-Digest-Hashcash/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Digest-Hashcash
PORTVERSION=	0.04
PORTREVISION=	1
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:ADAMBACK
PKGNAMEPREFIX=	p5-

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Perl extension for Hashcash hash algorithm

USES=		perl5 tar:tgz
USE_PERL5=	configure

.include <bsd.port.mk>
