# Created by: tdb
# $FreeBSD: tags/RELEASE_10_3_0/devel/libmowgli2/Makefile 386691 2015-05-18 17:07:45Z mat $

PORTNAME=	libmowgli2
PORTVERSION=	2.0.0
DISTVERSIONPREFIX=	libmowgli-
PORTREVISION=	1
CATEGORIES=	devel

MAINTAINER=	tdb@FreeBSD.org
COMMENT=	Development framework for C

USE_GITHUB=	yes
GH_ACCOUNT=	atheme
GH_PROJECT=	libmowgli-2

GNU_CONFIGURE=	yes
USES=		gmake pathfix
PATHFIX_MAKEFILEIN=	Makefile
USE_LDCONFIG=	yes
USE_OPENSSL=	yes

.include <bsd.port.mk>
