# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-XML-Code/Makefile 386075 2015-05-11 12:04:18Z mat $

PORTNAME=	XML-Code
PORTVERSION=	0.4
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Module for converting XML hash structures into plain text

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
