# $FreeBSD: releng/10.3/share/tests/Makefile 258299 2013-11-18 12:57:46Z jmmv $

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/share

.PATH:		${.CURDIR:H:H}/tests
KYUAFILE=	yes

.include <bsd.test.mk>
