# Created by: Michael Lyngbøl <lyngbol@wheel.dk>
# $FreeBSD: tags/RELEASE_10_3_0/net-mgmt/p5-Telnet-Cisco/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Net-Telnet-Cisco
PORTVERSION=	1.10
PORTREVISION=	2
CATEGORIES=	net-mgmt perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lyngbol@wheel.dk
COMMENT=	Perl5 module to telnet to Cisco routers

RUN_DEPENDS=	p5-Net-Telnet>=3.02:${PORTSDIR}/net/p5-Net-Telnet \
		p5-Term-ReadKey>=2:${PORTSDIR}/devel/p5-Term-ReadKey

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
