# Created by: Bill Fumerola <billf@mu.org>
# $FreeBSD: tags/RELEASE_10_3_0/net/tshark-lite/Makefile 401821 2015-11-17 17:35:31Z marcus $

LITE=		yes

MASTERDIR=	${.CURDIR}/../tshark
COMMENT=	Powerful network analyzer/capture tool (lite package)

.include "${MASTERDIR}/Makefile"
