# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/astro/p5-GPS-OID/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	GPS-OID
PORTVERSION=	0.07
PORTREVISION=	1
CATEGORIES=	astro perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Package for GPS PRN - Object ID conversions

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
