# Created by: Ryan Steinmetz <rpsfa@rit.edu>
# $FreeBSD: tags/RELEASE_10_3_0/net/isc-dhcp43-client/Makefile 349269 2014-03-26 17:27:24Z garga $

COMMENT=	The ISC Dynamic Host Configuration Protocol client

SUBSYS=		client
MASTERDIR=	${.CURDIR}/../isc-dhcp43-server

.include "${MASTERDIR}/Makefile"
