# Created by: Stefan Zehl <sec@42.org>
# $FreeBSD: tags/RELEASE_10_3_0/audio/shorten/Makefile 348028 2014-03-13 04:38:59Z eadler $

PORTNAME=	shorten
PORTVERSION=	3.6.1
CATEGORIES=	audio archivers
MASTER_SITES=	http://www.etree.org/shnutils/shorten/dist/src/

MAINTAINER=	sec@42.org
COMMENT=	Fast and optionally lossless compression for waveform files

RESTRICTED=	May not be sold.  May not be distributed if modified

GNU_CONFIGURE=	yes

PLIST_FILES=	bin/shorten \
		man/man1/shorten.1.gz

.include <bsd.port.mk>
