# Created by: Veniamin Gvozdikov <vg@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/x11-themes/cursor-chameleon-darkskyblue/Makefile 359870 2014-06-30 15:46:54Z vg $

PORTNAME=	chameleon
PORTVERSION=	0.5
CATEGORIES=	x11-themes
MASTER_SITES=	LOCAL/vg
PKGNAMEPREFIX=	cursor-
PKGNAMESUFFIX=	-darkskyblue
DISTNAME=	Chameleon-DarkSkyBlue-${PORTVERSION}

MAINTAINER=	vg@FreeBSD.org
COMMENT=	Chameleon Xcursors theme

LICENSE=	GPLv2

THEME=		DarkSkyBlue

.include "${.CURDIR}/../cursor-chameleon-white/files/Makefile.common"
.include <bsd.port.mk>
