# $FreeBSD: tags/RELEASE_10_3_0/www/elixir-html_entities/Makefile 392299 2015-07-16 15:36:10Z olgeni $

PORTNAME=	html_entities
PORTVERSION=	0.2.0
DISTVERSIONPREFIX=	v
CATEGORIES=	www
PKGNAMEPREFIX=	elixir-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Elixir module for decoding HTML entities

LICENSE=	MIT

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	martinsvalin

MIX_REWRITE=	yes

.include <bsd.port.mk>
