# Created by: Wen heping <wenheping@gmail.com>)
# $FreeBSD: tags/RELEASE_10_3_0/www/pear-Services_Facebook/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Services_Facebook
PORTVERSION=	0.2.14
CATEGORIES=	www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PHP interface to Facebook's API

BUILD_DEPENDS=	${PEARDIR}/Validate.php:${PORTSDIR}/devel/pear-Validate
RUN_DEPENDS=	${PEARDIR}/Validate.php:${PORTSDIR}/devel/pear-Validate

USES=	pear
USE_PHP=	curl

.include <bsd.port.mk>
