# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Text-VisualWidth/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Text-VisualWidth
PORTVERSION=	0.02
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension for trimming text by terminal columns

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
