# Created by: Steven Kreuzer <skreuzer@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/finance/py-ystockquote/Makefile 377524 2015-01-20 14:45:20Z skreuzer $

PORTNAME=	ystockquote
PORTVERSION=	0.2.4
CATEGORIES=	finance python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Python module to retrieve stock quote data from Yahoo Finance

LICENSE=	LGPL21

USES=	python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
