# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/math/p5-Math-Matrix/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Math-Matrix
PORTVERSION=	0.8
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Math::Matrix - multiply and invert matrices

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
