# $FreeBSD: tags/RELEASE_10_3_0/www/rubygem-jquery-ui-rails-rails4/Makefile 390860 2015-06-28 17:58:10Z sunpoet $

PORTNAME=	jquery-ui-rails
PORTVERSION=	5.0.5
CATEGORIES=	www rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	-rails4

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Packaged JavaScript, CSS and image files of jQuery UI for Rails

LICENSE=	MIT

RUN_DEPENDS=	rubygem-railties4>=4.1.4:${PORTSDIR}/www/rubygem-railties4

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
