# Created by: andy@fud.org.nz
# $FreeBSD: tags/RELEASE_10_3_0/security/pamtester/Makefile 362126 2014-07-17 08:57:51Z olgeni $

PORTNAME=	pamtester
PORTVERSION=	0.1.2
CATEGORIES=	security
MASTER_SITES=	SF

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Command line pam authentication tester

GNU_CONFIGURE=	yes
CPPFLAGS+=	${CFLAGS}
USES=	gmake

PLIST_FILES=	bin/pamtester \
		man/man1/pamtester.1.gz

.include <bsd.port.mk>
