# Created by: Marc Fournier <scrappy@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/converters/p5-Convert-ASN1/Makefile 381151 2015-03-12 23:00:02Z adamw $

PORTNAME=	Convert-ASN1
PORTVERSION=	0.27
PORTREVISION=	2
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 module to encode and decode ASN.1 data structures

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
