# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/net-mgmt/php56-snmp/Makefile 367268 2014-09-04 14:24:25Z ale $

CATEGORIES=	net-mgmt

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-snmp

.include "${MASTERDIR}/Makefile"
