# Created by: tobez
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-File-ReadBackwards/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	File-ReadBackwards
PORTVERSION=	1.05
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	File::ReadBackwards -- read a file backwards by lines

TEST_DEPENDS=	p5-Test-Simple>=0.88:${PORTSDIR}/devel/p5-Test-Simple

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
