# Created by: milki <milki@rescomp.berkeley.edu>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-SQL-Tokenizer/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	SQL-Tokenizer
PORTVERSION=	0.24
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:IZUT
PKGNAMEPREFIX=	p5-

MAINTAINER=	milki@FreeBSD.org
COMMENT=	Simple regular expressions based SQL tokenizer

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
