# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: tags/RELEASE_10_3_0/www/tidy-lib/Makefile 349767 2014-03-31 16:02:09Z rene $

PORTNAME=	tidy
CATEGORIES=	www
PKGNAMESUFFIX=	-lib

MAINTAINER=	thierry@FreeBSD.org
COMMENT=	Utility to clean up and pretty print HTML/XHTML/XML (with shared lib)

MASTERDIR=	${.CURDIR}/../../www/tidy-devel

WITH_SHLIB=	yes

.include "${MASTERDIR}/Makefile"
