# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Text-Context-EitherSide/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Text-Context-EitherSide
PORTVERSION=	1.4
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Text::Context::EitherSide - Get n words either side of search keywords

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
