# Created by: Muhammad Moinur Rahman <bofh@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/py3-chardet/Makefile 401991 2015-11-20 08:20:02Z bofh $

PORTNAME=	chardet
PORTVERSION=	2.3.0
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Universal encoding detector for Python 3

LICENSE=	LGPL21
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python:3
USE_PYTHON=	autoplist distutils
NO_ARCH=	yes

.include <bsd.port.mk>
