# Created by: ijliao
# $FreeBSD: tags/RELEASE_10_3_0/misc/p5-Chatbot-Eliza/Makefile 400649 2015-11-02 10:29:58Z culot $

PORTNAME=	Chatbot-Eliza
PORTVERSION=	1.06
CATEGORIES=	misc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Clone of the classic Eliza program

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
