# $FreeBSD: tags/RELEASE_10_3_0/databases/postgresql92-pgtcl/Makefile 355673 2014-05-29 08:12:51Z antoine $

PKGNAMESUFFIX=	-postgresql92

CONFLICTS=	pgtcl-[0-9]* pgtcl-postgresql9[0134]-[0-9]*

PGTCL_SLAVE=	9.2
MASTERDIR=	${.CURDIR}/../pgtcl

.include "${MASTERDIR}/Makefile"
