# $FreeBSD: tags/RELEASE_10_3_0/x11/bitmap/Makefile 384234 2015-04-18 15:34:36Z kwm $

PORTNAME=	bitmap
PORTVERSION=	1.0.8
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Bitmap editor and converter utilities for X

XORG_CAT=	app
USE_XORG=	x11 xaw xbitmaps xmu xproto

.include <bsd.port.mk>
