# Created by: Mikolaj Golub <trociny@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/databases/rubygem-leo_manager_client/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	leo_manager_client
PORTVERSION=	0.4.13
CATEGORIES=	databases
MASTER_SITES=	RG

MAINTAINER=	trociny@FreeBSD.org
COMMENT=	LeoFS-Manager client library for Ruby

LICENSE=	APACHE20

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
