# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Object-Import/Makefile 376152 2015-01-03 18:50:15Z pi $

PORTNAME=	Object-Import
PORTVERSION=	1.004
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	pi@FreeBSD.org
COMMENT=	Import methods of an object as functions to a package

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
