# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/math/R-cran-memisc/Makefile 389324 2015-06-13 06:57:28Z tota $

PORTNAME=	memisc
DISTVERSION=	0.97
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Provides an infrastructure for the management of survey data

LICENSE=	GPLv2

USES=	cran:auto-plist

.include <bsd.port.mk>
