# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/graphics/php55-exif/Makefile 340722 2014-01-22 17:00:46Z mat $

CATEGORIES=	graphics

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-exif

.include "${MASTERDIR}/Makefile"
