# Created by: Sulev-Madis Silber <madis555@hot.ee>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Number-Bytes-Human/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Number-Bytes-Human
PORTVERSION=	0.07
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	madis555@hot.ee
COMMENT=	Convert byte count to human readable format

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
