# Created by: Melvyn Sopacua <melvyn@magemana.nl>
# $FreeBSD: tags/RELEASE_10_3_0/www/py-django-datetime-widget/Makefile 371154 2014-10-18 19:01:59Z rm $

PORTNAME=	django-datetime-widget
PORTVERSION=	0.6
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	melvyn@magemana.nl
COMMENT=	Simple and clean widget for DateTimeField

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}django>0:${PORTSDIR}/www/py-django

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
