# Created by: Dejan Lesjak <lesi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/x11-fonts/libfontenc/Makefile 399849 2015-10-20 13:58:56Z kwm $

PORTNAME=	libfontenc
PORTVERSION=	1.1.3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	The fontenc Library

XORG_CAT=	lib
USE_XORG=	xproto

.include <bsd.port.mk>
