# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/net/arp-scan/Makefile 383816 2015-04-11 17:04:23Z johans $

PORTNAME=	arp-scan
PORTVERSION=	1.9
CATEGORIES=	net
MASTER_SITES=	http://www.nta-monitor.com/files/${PORTNAME}/

MAINTAINER=	johans@FreeBSD.org
COMMENT=	ARP scanning and fingerprinting tool

LICENSE=	GPLv3

GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes

.include <bsd.port.mk>
