# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-stomp/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	stomp
PORTVERSION=	1.3.4
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Streaming Text Orientated Messaging Protocol gem

LICENSE=	APACHE20

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=		bin/catstomp bin/stompcat

.include <bsd.port.mk>
