# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/pear-File_Gettext/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	File_Gettext
PORTVERSION=	0.4.2
CATEGORIES=	sysutils devel pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PEAR GNU Gettext file parser

USES=	pear
USE_PHP=	yes

.include <bsd.port.mk>
