# Created by: Gerrit Beine (<tux@pinguru.net>)
# $FreeBSD: tags/RELEASE_10_3_0/net/pear-Net_Server/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Net_Server
PORTVERSION=	1.0.3
CATEGORIES=	net pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Generic server class

USES=	pear
USE_PHP=	sockets pcntl

.include <bsd.port.mk>
