# Created by: dom@happygiraffe.net
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Time-Object/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	Time-Object
PORTVERSION=	1.00
PORTREVISION=	2
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Perl OO interface to time and dates

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
