# $FreeBSD: tags/RELEASE_10_3_0/x11/fstobdf/Makefile 384234 2015-04-18 15:34:36Z kwm $

PORTNAME=	fstobdf
PORTVERSION=	1.0.6
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Generate BDF font from X font server

XORG_CAT=	app
USE_XORG=	x11 libfs

PLIST_FILES=	bin/fstobdf man/man1/fstobdf.1.gz

.include <bsd.port.mk>
