# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-deep_merge/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	deep_merge
PORTVERSION=	1.0.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	robak@FreeBSD.org
COMMENT=	Recursive hash merger

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
