# $FreeBSD: tags/RELEASE_10_3_0/net/packetdrill/files/Makefile 340722 2014-01-22 17:00:46Z mat $

SUBDIR=	libpd packetdrill checksum_test packet_parser_test packet_to_string_test

.include <bsd.subdir.mk>
