# Created by: Veniamin Gvozdikov <vg@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/libpo6/Makefile 377507 2015-01-20 11:57:41Z vg $

PORTNAME=	libpo6
PORTVERSION=	0.5.2
CATEGORIES=	devel
MASTER_SITES=	http://hyperdex.org/src/

MAINTAINER=	vg@FreeBSD.org
COMMENT=	POSIX wrappers for C++

LICENSE=	BSD3CLAUSE

GNU_CONFIGURE=	yes
USES=	gmake pathfix

.include <bsd.port.mk>
