# Created by: mat@FreeBSD.org
# $FreeBSD: tags/RELEASE_10_3_0/net/rubygem-epp-client-secdns/Makefile 380380 2015-03-03 15:58:06Z mat $

PORTNAME=	epp-client-secdns
PORTVERSION=	0.13.1
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	mat@FreeBSD.org
COMMENT=	SecDNS EPP client library

LICENSE=	MIT

RUN_DEPENDS=	rubygem-builder>=2.1.2:${PORTSDIR}/devel/rubygem-builder \
		rubygem-nokogiri14>=1.4:${PORTSDIR}/textproc/rubygem-nokogiri14

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
