# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-PHP_Parser/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	PHP_Parser
PORTVERSION=	0.2.2
CATEGORIES=	devel www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PHP Grammar Parser

USES=	pear

.include <bsd.port.mk>
