# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/www/py-pywebdav/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	PyWebDAV
PORTVERSION=	0.9.8
PORTREVISION=	1
CATEGORIES=	www net python
MASTER_SITES=	GOOGLE_CODE CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	WebDAV Library and Server for Python

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
