# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Net-Snort-Parser/Makefile 388088 2015-05-31 13:37:20Z amdmi3 $

PORTNAME=	Net-Snort-Parser
PORTVERSION=	1.41
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	https://projects.honeynet.org/svn/honeywall/honeywall/trunk/rpm-devel/perl-${PORTNAME}/ \
    		http://mirrors.rit.edu/zi/
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl modules for parsing Snort configuration files

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
