# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/security/php5-mcrypt/Makefile 389655 2015-06-14 20:23:09Z ale $

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-mcrypt

.include "${MASTERDIR}/Makefile"
