# Created by: Jon Nistor <nistor@snickers.org>
# $FreeBSD: tags/RELEASE_10_3_0/databases/p5-DBIx-Sequence/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	DBIx-Sequence
PORTVERSION=	1.5
PORTREVISION=	1
CATEGORIES=	databases perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	nistor@snickers.org
COMMENT=	DBIx::Sequence - A simple SQL92 ID generator

BUILD_DEPENDS=	p5-DBI>=0:${PORTSDIR}/databases/p5-DBI
RUN_DEPENDS=	p5-DBI>=0:${PORTSDIR}/databases/p5-DBI

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
