# Created by: Joseph Benden <joe@thrallingpenguin.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-nori/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	nori
PORTVERSION=	2.6.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	joe@thrallingpenguin.com
COMMENT=	Library for converting XML to Hash syntax

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
