# $FreeBSD: releng/10.3/usr.bin/gzip/tests/Makefile 272788 2014-10-09 02:24:34Z ngie $

TESTSRC=	${.CURDIR}/../../../contrib/netbsd-tests/usr.bin/gzip
.PATH: ${TESTSRC}

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/usr.bin/gzip
ATF_TESTS_SH=	gzip_test
ATF_TESTS_SH_SRC_gzip_test=	t_gzip.sh

.include <bsd.test.mk>
