# $FreeBSD: tags/RELEASE_10_3_0/x11/iceauth/Makefile 384234 2015-04-18 15:34:36Z kwm $

PORTNAME=	iceauth
PORTVERSION=	1.0.7
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	ICE authority file utility for X

LICENSE=	MIT

XORG_CAT=	app
USE_XORG=	xproto ice

PLIST_FILES=	bin/iceauth man/man1/iceauth.1.gz

.include <bsd.port.mk>
