# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/graphics/frei0r-plugins-gavl/Makefile 355000 2014-05-24 08:46:13Z miwi $
MASTERDIR=	${.CURDIR}/../frei0r

BUILDING_FREI0R_GAVL=	yes

.include "${MASTERDIR}/Makefile"
