# Created by: Dejan Lesjak <lesi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/x11-fonts/fontsproto/Makefile 399179 2015-10-13 07:45:08Z kwm $

PORTNAME=	fontsproto
PORTVERSION=	2.1.3
PORTEPOCH=	1
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Fonts extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
