# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/pear-File_MARC/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	File_MARC
PORTVERSION=	1.1.2
CATEGORIES=	textproc pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Parse, modify, and create MARC records

USES=	pear

.include <bsd.port.mk>
