# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Text-HikiDoc/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Text-HikiDoc
PORTVERSION=	1.021
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Pure Perl implementation of 'HikiDoc'

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
