# Created by: Vadim Belman <vab@lflat.vas.mobilix.dk>
# $FreeBSD: tags/RELEASE_10_3_0/net/p5-Net-SSH/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Net-SSH
PORTVERSION=	0.09
PORTREVISION=	1
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 module to access and use ssh protocol

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
