# Created by: James FitzGibbon <jfitz@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/finance/p5-Business-CreditCard/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Business-CreditCard
PORTVERSION=	0.32
PORTREVISION=	1
CATEGORIES=	finance perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl5 module to validate/generate credit card checksums/names

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
