# Created by: winter@jurai.net
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/setquota/Makefile 367585 2014-09-07 17:38:21Z antoine $

PORTNAME=	setquota
PORTVERSION=	0.1
CATEGORIES=	sysutils
MASTER_SITES=	ftp://ftp.jurai.net/users/winter/

MAINTAINER=	winter@jurai.net
COMMENT=	Command line quota tools

WRKSRC=		${WRKDIR}/setquota/
USES=		uidfix

.include <bsd.port.mk>
