# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-Horde_Exception/Makefile 393466 2015-08-03 07:06:14Z mm $

PORTNAME=	Horde_Exception
PORTVERSION=	2.0.6
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Exception Handler

USES=	horde
USE_HORDE_RUN=	Horde_Translation

.include <bsd.port.mk>
