# $FreeBSD: tags/RELEASE_10_3_0/textproc/rubygem-ltsv/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	ltsv
PORTVERSION=	0.1.0
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Parser / Dumper for LTSV

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
