# Created by: Aaron Dalton <aaron@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Parse-Flex/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	Parse-Flex
PORTVERSION=	0.12
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	The Fastest Lexer in the West

LICENSE=	GPLv3

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
