# Created by: Marc Fonvieille <blackend@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/misc/freebsd-doc-es/Makefile 354559 2014-05-19 16:43:45Z blackend $

CATEGORIES=	misc docs spanish
PKGNAMEPREFIX=	es-

MAINTAINER=	doceng@FreeBSD.org
COMMENT=	Spanish translation of the FreeBSD Documentation Project

MASTERDIR=	${.CURDIR}/../freebsd-doc-en
PLIST=		${.CURDIR}/pkg-plist

DOCLANG=	es_ES.ISO8859-1

.include "${MASTERDIR}/Makefile"
