# Created by: Ying-Chieh Liao <ijliao@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/libavl/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	libavl
PORTVERSION=	1.4.0
CATEGORIES=	devel
MASTER_SITES=	GNU/avl
DISTNAME=	avl-${PORTVERSION}

MAINTAINER=	rodrigo@FreeBSD.org
COMMENT=	Library for balanced binary trees

GNU_CONFIGURE=	yes

INFO=		avl

.include <bsd.port.mk>
