# $FreeBSD: tags/RELEASE_10_3_0/misc/erlang-mimerl/Makefile 403967 2015-12-18 14:46:08Z olgeni $

PORTNAME=	mimerl
PORTVERSION=	1.1.0
CATEGORIES=	misc
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Erlang library to handle mimetypes

LICENSE=	MIT

USES=		erlang:rebar3
USE_GITHUB=	yes
GH_ACCOUNT=	benoitc

.include <bsd.port.mk>
