# $FreeBSD: tags/RELEASE_10_3_0/devel/py-serpent/Makefile 394186 2015-08-13 19:33:02Z rm $

PORTNAME=	serpent
PORTVERSION=	1.11
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	rm@FreeBSD.org
COMMENT=	Simple serialization library based on ast.literal_eval

LICENSE=	MIT

NO_ARCH=	yes
USES=		dos2unix python
USE_PYTHON=	autoplist concurrent distutils

.include <bsd.port.mk>
