# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-TeX-Hyphen/Makefile 389592 2015-06-14 05:29:23Z kuriyama $

PORTNAME=	TeX-Hyphen
PORTVERSION=	1.16
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Hyphenate words using TeX's patterns

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	YES

.include <bsd.port.mk>
