# Created by: Wen Heping<wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/www/pear-HTTP_WebDAV_Client/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	HTTP_WebDAV_Client
PORTVERSION=	1.0.2
CATEGORIES=	www devel pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	WebDAV Stream Wrapper Class

BUILD_DEPENDS=	${PEARDIR}/HTTP/Request.php:${PORTSDIR}/www/pear-HTTP_Request
RUN_DEPENDS:=	${PEARDIR}/HTTP/Request.php:${PORTSDIR}/www/pear-HTTP_Request

USES=	pear

.include <bsd.port.mk>
