# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Test-Time/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Test-Time
PORTVERSION=	0.04
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension to override time()/sleep() core functions for testing

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
