# $FreeBSD: tags/RELEASE_10_3_0/lang/gcc6-aux/Makefile.common 403127 2015-12-06 16:04:22Z marino $

.include "Makefile.version"

LIB_DEPENDS=		libgmp.so:${PORTSDIR}/math/gmp
LIB_DEPENDS+=		libmpfr.so:${PORTSDIR}/math/mpfr
LIB_DEPENDS+=		libmpc.so:${PORTSDIR}/math/mpc

ONLY_FOR_ARCHS= 	i386 amd64

GNU_CONFIGURE=		yes
USES=			gmake libtool perl5 tar:bzip2
USE_PERL5=		build
ALL_TARGET=		default
