# Created by: Julien Laffaye <kimelto@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-gflags/Makefile 399684 2015-10-19 14:50:52Z amdmi3 $

PORTNAME=	gflags
PORTVERSION=	2.0
PORTREVISION=	2
CATEGORIES=	devel python
MASTER_SITES=	GOOGLE_CODE
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	python-gflags-${PORTVERSION}

MAINTAINER=	jlaffaye@FreeBSD.org
COMMENT=	Commandline flags module for Python

LICENSE=	BSD3CLAUSE

USES=		python:2 shebangfix
USE_PYTHON=	autoplist distutils

SHEBANG_FILES=	gflags2man.py

PROJECTHOST=	python-gflags

.include <bsd.port.mk>
