# Created by: Frederic Culot <culot@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/p5-HTTP-Date/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	HTTP-Date
PORTVERSION=	6.02
PORTREVISION=	1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Conversion routines for the HTTP protocol date formats

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

CONFLICTS=	p5-libwww-5*

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
