# Created by: Choe, Cheng-Dae
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-configobj/Makefile 397982 2015-09-26 14:27:12Z nivit $

PORTNAME=	configobj
PORTVERSION=	5.0.6
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Simple but powerful config file reader and writer

LICENSE=	BSD3CLAUSE

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}six>0:${PORTSDIR}/devel/py-six

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
