# $FreeBSD: tags/RELEASE_10_3_0/devel/gstreamer1-plugins-soup/Makefile 351947 2014-04-23 14:22:47Z tijl $

PORTREVISION=	0
CATEGORIES=	devel

COMMENT=	Gstreamer soup http src plugin

GST_PLUGIN=	soup
DIST=		good

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
