# Created by: Dmitry Sivachenko <demon@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/py-pygtail/Makefile 404623 2015-12-28 12:00:39Z demon $

PORTNAME=	pygtail
PORTVERSION=	0.6.1
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	demon@FreeBSD.org
COMMENT=	Python module which reads log file lines that have not been read

USES=		python
USE_PYTHON=	autoplist concurrent distutils

.include <bsd.port.mk>
