# $FreeBSD: tags/RELEASE_10_3_0/converters/p5-Convert-Base32/Makefile 393071 2015-07-28 13:06:56Z pi $

PORTNAME=	Convert-Base32
PORTVERSION=	0.06
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	pi@FreeBSD.org
COMMENT=	Encoding and decoding of base32 strings

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
