# Created by: Wen Heping<wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/www/pear-HTTP_WebDAV_Server/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	HTTP_WebDAV_Server
PORTVERSION=	1.0.0.r4
CATEGORIES=	www devel pear
DISTNAME=	${PORTNAME}-1.0.0RC4

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	WebDAV Server Baseclass

USES=	pear

.include <bsd.port.mk>
