# Created by: TAKAHASHI Kaoru <kaoru@kaisei.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/p5-Acme-Monta/Makefile 386075 2015-05-11 12:04:18Z mat $

PORTNAME=	Acme-Monta
PORTVERSION=	0.01
PORTREVISION=	1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Monta Method reproduced in web

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
