# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-mocha/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	mocha
PORTVERSION=	0.14.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Library for mocking and stubbing syntax like JMock and SchMock

LICENSE=	MIT

RUN_DEPENDS=	rubygem-metaclass>=0:${PORTSDIR}/devel/rubygem-metaclass

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
