# $FreeBSD: tags/RELEASE_10_3_0/x11-themes/qtcurve-kde4/Makefile 386718 2015-05-18 21:26:50Z makc $

PORTNAME=	qtcurve
PORTREVISION=	0

COMMENT=	QtCurve KDE 4 widget style and window decoration

QTCURVE_SLAVE=	kde4

MASTERDIR=	${.CURDIR}/../qtcurve

.include "${MASTERDIR}/Makefile"
