# $FreeBSD: tags/RELEASE_10_3_0/textproc/makepatch/Makefile 393565 2015-08-05 04:35:34Z amdmi3 $

PORTNAME=	makepatch
PORTVERSION=	2.05
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:JV

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Perl scripts to assist in the generation and application of patches

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
