# $FreeBSD: tags/RELEASE_10_3_0/science/py-pyteomics.biolccc/Makefile 371453 2014-10-24 16:50:42Z mva $

PORTNAME=	pyteomics.biolccc
PORTVERSION=	1.5.0
CATEGORIES=	science python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	makc@FreeBSD.org
COMMENT=	Python bindings for BioLCCC

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
