# Created by: Mykola Dzham <i@levsha.me>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/py-drmaa/Makefile 374505 2014-12-11 00:40:16Z feld $

PORTNAME=	drmaa
PORTVERSION=	0.4b3
PORTREVISION=	1
CATEGORIES=	sysutils python
MASTER_SITES=	GOOGLE_CODE
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	i@levsha.me
COMMENT=	Interact with DRMAA-compliant distributed resource management systems

LICENSE=	BSD3CLAUSE
PROJECTHOST=	drmaa-python

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
