# Created by: Dirk Froemberg <dirk@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/french/php_doc/Makefile 353996 2014-05-13 21:13:31Z edwin $

CATEGORIES=	french lang
PKGNAMEPREFIX=
PHP_LANG=	fr
MASTERDIR=	${.CURDIR}/../../lang/php_doc

.include "${MASTERDIR}/Makefile"
