# Created by: Kozlov Sergey <kozlov.sergey.404@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/print/py-preppy/Makefile 396733 2015-09-12 07:33:37Z wen $

PORTNAME=	preppy
PORTVERSION=	2.3.4
CATEGORIES=	print python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	kozlov.sergey.404@gmail.com
COMMENT=	ReportLab's templating system

LICENSE=	BSD3CLAUSE

NO_ARCH=	yes

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
