# Created by: Dejan Lesjak <lesi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/x11/xbitmaps/Makefile 351411 2014-04-16 18:28:47Z zeising $

PORTNAME=	xbitmaps
PORTVERSION=	1.1.1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org bitmaps data

LICENSE=	MIT

USES=		pathfix

XORG_CAT=	data

.include <bsd.port.mk>
