# Created by: Gvozdikov Veniamin <g.veniamin@googlemail.com>
# $FreeBSD: tags/RELEASE_10_3_0/russian/stardict-computer/Makefile 363399 2014-07-29 21:43:17Z adamw $

PORTNAME=	stardict-computer
PORTVERSION=	2.4.2
CATEGORIES=	russian
MASTER_SITES=	http://abloz.com/huzheng/stardict-dic/ru/
DISTNAME=	${PORTNAME}-ru-${PORTVERSION}

MAINTAINER=	vg@FreeBSD.org
COMMENT=	English-Russian Computer dictionary

USES=	tar:bzip2

.include "${.CURDIR}/../stardict-mueller7/files/Makefile.common"
.include <bsd.port.mk>
