# $FreeBSD: tags/RELEASE_10_3_0/www/gstreamer1-plugins-neon/Makefile 351947 2014-04-23 14:22:47Z tijl $

PORTREVISION=	0
CATEGORIES=	www

COMMENT=	Gstreamer neon http source plugin

GST_PLUGIN=	neon
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
