# $FreeBSD: tags/RELEASE_10_3_0/devel/py-Products.ExternalEditor/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	Products.ExternalEditor
PORTVERSION=	1.1.0
PORTREVISION=	1
CATEGORIES=	devel python zope
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=	zope

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Zope external editor

LICENSE=	ZPL21

USES=		python zip
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
