# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-ref/Makefile 391758 2015-07-11 15:28:36Z sunpoet $

PORTNAME=	ref
PORTVERSION=	2.0.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Library with refs across runtimes (MRI, REE, YARV, ...)

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
