# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-setuptools-git/Makefile 381743 2015-03-20 15:46:03Z pawel $

PORTNAME=	setuptools-git
PORTVERSION=	1.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Setuptools plugin for git

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
