# Created by: Justin Stanford <jus@security.za.net>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-File-Remove/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	File-Remove
PORTVERSION=	1.52
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:ADAMK
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 module to easily removes files and directories

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
