# Created by: Kimo <kimor79@yahoo.com>
# $FreeBSD: tags/RELEASE_10_3_0/databases/rubygem-mysql2/Makefile 395377 2015-08-26 16:34:41Z sunpoet $

PORTNAME=	mysql2
PORTVERSION=	0.3.20
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Simple, fast MySQL library for Ruby, binding to libmysql

LICENSE=	MIT

USE_MYSQL=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
