# Created by: Stefan Esser <se@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/archivers/unshield/Makefile 404969 2016-01-01 06:35:45Z sunpoet $

PORTNAME=	unshield
PORTVERSION=	0.6
PORTREVISION=	7
CATEGORIES=	archivers
MASTER_SITES=	SF/synce/Unshield/${PORTVERSION}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Extract data from InstallShield CAB files

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

GNU_CONFIGURE=	yes
INSTALL_TARGET=	install-strip
USE_LDCONFIG=	yes
USES=		libtool pathfix

.include <bsd.port.mk>
