# Created by: Ryan Steinmetz (<rpsfa@rit.edu>)
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-little-plugger/Makefile 395586 2015-08-30 03:56:46Z sunpoet $

PORTNAME=	little-plugger
PORTVERSION=	1.1.4
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Mechanism to parse ruby little-plugger files

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
