# Created by: arensb@ooblick.com
# $FreeBSD: tags/RELEASE_10_3_0/mail/gensig/Makefile 361099 2014-07-07 15:31:01Z olgeni $

PORTNAME=	gensig
PORTVERSION=	2.3
PORTREVISION=	1
CATEGORIES=	mail
MASTER_SITES=	http://www.geekthing.com/~robf/ware/gensig/ \
		http://www.ooblick.com/software/gensig/

MAINTAINER=	arensb+freebsd-ports@ooblick.com
COMMENT=	Random .signature generator

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
