# Created by: KOMATSU Shinichiro <koma2@jiro.c.u-tokyo.ac.jp>
# $FreeBSD: tags/RELEASE_10_3_0/japanese/skk-jisyo-cdb/Makefile 354313 2014-05-17 11:08:08Z pawel $

MAINTAINER=	ports@FreeBSD.org
COMMENT=	CDB jisyo (dictionary) files for the SKK Japanese-input software

WITH_SKKJISYO_CDB=	yes

MASTERDIR=	${.CURDIR}/../skk-jisyo

DESCR=		${.CURDIR}/pkg-descr

.include "${MASTERDIR}/Makefile"
