# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: tags/RELEASE_10_3_0/misc/p5-Tie-DxHash/Makefile 381221 2015-03-13 17:29:58Z adamw $

PORTNAME=	Tie-DxHash
PORTVERSION=	1.05
PORTREVISION=	2
CATEGORIES=	misc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module implementing ordered hashes with duplicate keys

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
