# Created by: stas
# $FreeBSD: tags/RELEASE_10_3_0/devel/boehm-gc-redirect/Makefile 398832 2015-10-08 15:11:28Z olgeni $

PORTREVISION=	1

COMMENT=	Garbage collection and memory leak detection for C and C++ with malloc redirection

LICENSE=	MIT

MASTERDIR=	${.CURDIR}/../boehm-gc
DESCR=		${.CURDIR}/pkg-descr

GC_VARIANT=	redirect

.include "${MASTERDIR}/Makefile"
