# $FreeBSD: tags/RELEASE_10_3_0/www/twiki-ClassicSkin/Makefile 362252 2014-07-19 11:09:51Z ohauer $

PORTNAME=	ClassicSkin
SVNREV=		17365

COMMENT=	The Classic TWiki skin

.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
