# Created by: Steve Wills <steve@mouf.net>
# $FreeBSD: tags/RELEASE_10_3_0/math/p5-Number-Fraction/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Number-Fraction
PORTVERSION=	2.00
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:DAVECROSS
PKGNAMEPREFIX=	p5-

MAINTAINER=	swills@FreeBSD.org
COMMENT=	Perl extension to model fractions

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
