# $FreeBSD: tags/RELEASE_10_3_0/dns/p5-Net-DNS-Match/Makefile 376686 2015-01-10 10:36:44Z bofh $

PORTNAME=	Net-DNS-Match
PORTVERSION=	0.05
PORTREVISION=	1
CATEGORIES=	dns perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Test domains against another list of FQDNs

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
