# Created by: "Choe, Cheng-Dae" <whitekid@netian.com>
# $FreeBSD: tags/RELEASE_10_3_0/www/py-clientform/Makefile 371116 2014-10-18 11:47:24Z rm $

PORTNAME=	clientform
PORTVERSION=	0.2.10
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	http://wwwsearch.sourceforge.net/ClientForm/src/ \
		CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	ClientForm-${PORTVERSION}

MAINTAINER=	lwhsu@FreeBSD.org
COMMENT=	Client-side HTTP Form for Python

USES=		python:2
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
