# Created by: Loic Pefferkorn <loic-freebsd@loicp.eu>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-clio/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	clio
PORTVERSION=	0.3.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	loic-freebsd@loicp.eu
COMMENT=	Make easier commandline parsing and console output

LICENSE=	GPLv3

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
