# $FreeBSD: tags/RELEASE_10_3_0/devel/erlang-ssl_verify_hostname/Makefile 403683 2015-12-13 18:26:36Z olgeni $

PORTNAME=	ssl_verify_hostname
PORTVERSION=	1.0.6
CATEGORIES=	devel
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Erlang library for certificate hostname validation

LICENSE=	MIT

USES=		erlang:rebar
USE_GITHUB=	yes
GH_ACCOUNT=	deadtrickster
GH_PROJECT=	ssl_verify_hostname.erl

.include <bsd.port.mk>
