# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: tags/RELEASE_10_3_0/net-im/p5-Net-AOLIM/Makefile 388077 2015-05-31 13:20:55Z amdmi3 $

PORTNAME=	Net-AOLIM
PORTVERSION=	1.61
PORTREVISION=	2
CATEGORIES=	net-im perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl OO interface to the AOL Instant Messenger TOC client protocol

USES=		perl5 shebangfix
SHEBANG_FILES=	example.pl
USE_PERL5=	configure
WRKSRC=		${WRKDIR}/${PORTNAME}
NO_ARCH=	yes

.include <bsd.port.mk>
