# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/databases/php55-mssql/Makefile 340722 2014-01-22 17:00:46Z mat $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-mssql

.include "${MASTERDIR}/Makefile"
