# $FreeBSD: releng/10.3/usr.sbin/bsdconfig/mouse/Makefile 279611 2015-03-05 00:34:33Z dteske $

NO_OBJ=

SUBDIR= include

FILESDIR=	${LIBEXECDIR}/bsdconfig/110.mouse
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	disable enable flags mouse port type

.include <bsd.prog.mk>
