# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Object-Declare/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Object-Declare
PORTVERSION=	0.22
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Declarative object constructor

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
