# Created by: Leif Pedersen <pedersen@meridian-enviro.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Parse-PerlConfig/Makefile 395264 2015-08-25 14:51:36Z sunpoet $

PORTNAME=	Parse-PerlConfig
PORTVERSION=	0.05
PORTREVISION=	3
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 module to use perl scripts as config files

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
