# Created by: oly@world.std.com
# $FreeBSD: tags/RELEASE_10_3_0/print/lout/Makefile 372719 2014-11-18 13:49:58Z danilo $

PORTNAME=	lout
PORTVERSION=	3.40
PORTREVISION=	1
CATEGORIES=	print
MASTER_SITES=	SAVANNAH

MAINTAINER=	danilo@FreeBSD.org
COMMENT=	LaTeX like document creation system with PostScript/PDF output

LICENSE=	GPLv3 # (or later)

OPTIONS_DEFINE=	DOCS

USES=	gmake
MAKEFILE=	makefile
ALL_TARGET=	lout prg2lout
INSTALL_TARGET=	install installman installdoc

.include <bsd.port.mk>
