# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/pear-Horde_Kolab_Format/Makefile 369674 2014-09-30 22:14:59Z bapt $

PORTNAME=	Horde_Kolab_Format
PORTVERSION=	2.0.2
CATEGORIES=	textproc www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde library for reading/writing Kolab data formats

USES=	horde
USE_PHP=	dom
USE_HORDE_RUN=	Horde_Exception

.include <bsd.port.mk>
