# $FreeBSD: tags/RELEASE_10_3_0/www/rubygem-net-http-persistent25/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	net-http-persistent
PKGNAMESUFFIX=	25
PORTVERSION=	2.5.2
CATEGORIES=	www net rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Manages persistent connections using Net::HTTP

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PORTSCOUT=	limit:^2\.5

.include <bsd.port.mk>
