# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/net/py-uritemplate/Makefile 380378 2015-03-03 15:41:26Z nivit $

PORTNAME=	uritemplate
PORTVERSION=	0.6
#PORTREVISION=	0
CATEGORIES=	net
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Python implementation of URI Template

LICENSE=	APACHE20

USE_PYTHON=	autoplist distutils
USES=	python

.include <bsd.port.mk>
