# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: tags/RELEASE_10_3_0/www/xpi-uBlock_origin/Makefile 403873 2015-12-16 20:12:10Z thierry $

PORTNAME=	ublock_origin
PORTVERSION=	1.4.0
DISTVERSIONSUFFIX=	-an+sm+tb+fx
CATEGORIES=	www

MAINTAINER=	thierry@FreeBSD.org
COMMENT=	Efficient blocker for Firefox, fast and lean

LICENSE=	GPLv3

XPI_NUM=	607454
XPI_ID=		uBlock0@raymondhill.net

NO_ARCH=	yes

.include "../xpi-adblock/Makefile.xpi"
.include <bsd.port.mk>
