# Created by: Lars Thegler <lars@thegler.dk>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-CPAN-DistnameInfo/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	CPAN-DistnameInfo
PORTVERSION=	0.12
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Extract distribution name and version from a CPAN filename

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
