# Created by: Anish Mistry (<amistry@am-productions.biz>)
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-Validate_Finance/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Validate_Finance
PORTVERSION=	0.5.6
CATEGORIES=	devel www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PEAR Finance Validation class

BUILD_DEPENDS=	pear-Validate>=0.5.0:${PORTSDIR}/devel/pear-Validate
RUN_DEPENDS=	pear-Validate>=0.5.0:${PORTSDIR}/devel/pear-Validate

USES=	pear

.include <bsd.port.mk>
