# Created by: lth@FreeBSD.org
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Text-FixEOL/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	Text-FixEOL
PORTVERSION=	1.06
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Canonicalizes text to a specified EOL/EOF convention

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
