# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/pear-Horde_Feed/Makefile 376829 2015-01-12 14:54:44Z mm $

PORTNAME=	Horde_Feed
PORTVERSION=	2.0.3
CATEGORIES=	www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Feed libraries

USES=	horde
USE_PHP=	dom
USE_HORDE_RUN=	Horde_Exception \
		Horde_Http \
		Horde_Xml_Element

.include <bsd.port.mk>
