# $FreeBSD: tags/RELEASE_10_3_0/portuguese/Makefile 380766 2015-03-08 10:39:13Z bsam $
#

    COMMENT = Portuguese language support

    SUBDIR += aspell-pt_BR
    SUBDIR += aspell-pt_PT
    SUBDIR += calligra-l10n
    SUBDIR += calligra-l10n-pt_BR
    SUBDIR += eric6
    SUBDIR += gimp-help-pt_BR
    SUBDIR += hunspell
    SUBDIR += hyphen
    SUBDIR += irpf-pt_BR
    SUBDIR += kde4-l10n
    SUBDIR += kde4-l10n-pt_BR
    SUBDIR += libreoffice
    SUBDIR += libreoffice-pt_BR
    SUBDIR += mythes
    SUBDIR += php_doc-br
    SUBDIR += webalizer-pt_BR
    SUBDIR += webalizer-pt_PT

.include <bsd.port.subdir.mk>
