# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/math/p5-Math-String/Makefile 381221 2015-03-13 17:29:58Z adamw $

PORTNAME=	Math-String
PORTVERSION=	1.28
PORTREVISION=	2
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module to calculate with strings as if they were big integers

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
