# Created by: Florian Smeets <flo@smeets.im>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/pecl-proctitle/Makefile 362126 2014-07-17 08:57:51Z olgeni $

PORTNAME=	proctitle
PORTVERSION=	0.1.2
CATEGORIES=	sysutils pear
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-
EXTRACT_SUFX=	.tgz
DIST_SUBDIR=	PECL

MAINTAINER=	flo@FreeBSD.org
COMMENT=	PECL extension that allows changing the current process' name

USE_PHP=	yes
USE_PHPEXT=	yes

.include <bsd.port.mk>
