# Created by: Satoshi TAOKA <taoka@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/chinese/FreeWnn-server/Makefile 357139 2014-06-09 11:21:52Z olgeni $

CATEGORIES=	chinese
PKGNAMESUFFIX=	-server

COMMENT=	Japanese/Chinese/Korean input method (Chinese server)

MASTERDIR=	${.CURDIR}/../../japanese/FreeWnn-server
PKGDIR=		${.CURDIR}

OPTIONS_DEFAULT=CWNN SERVER

.include "${MASTERDIR}/Makefile"
