# Created by: Sergey Skvortsov <skv@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-XML-Filter-SAXT/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	XML-Filter-SAXT
PORTVERSION=	0.01
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Replicates SAX events to several SAX event handlers

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
