# Created by: Monzyne, W. <wamonzyne@hotmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/mdcp/Makefile 362126 2014-07-17 08:57:51Z olgeni $

PORTNAME=	mdcp
PORTVERSION=	0.1.2.2
CATEGORIES=	sysutils
MASTER_SITES=	SF/${PORTNAME}/${PORTNAME}/shine

MAINTAINER=	wamonzyne@hotmail.com
COMMENT=	Fastest utility for copy from a disk device for many

GNU_CONFIGURE=	yes
USES=		gmake

PLIST_FILES=	sbin/mdcp man/man1/mdcp.1.gz

.include <bsd.port.mk>
