# Created by: Erwin Lansing <erwin@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Locale-Maketext-Fuzzy/Makefile 381151 2015-03-12 23:00:02Z adamw $

PORTNAME=	Locale-Maketext-Fuzzy
PORTVERSION=	0.11
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Maketext from already interpolated strings

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
