# Created by: Kevin Golding <ports@caomhin.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/py-django-app-plugins/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	django-app-plugins
PORTVERSION=	0.1.1
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	GOOGLE_CODE
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@caomhin.org
COMMENT=	Reusable django application for writing pluggable reusable django applications

RUN_DEPENDS=	${PYTHON_SITELIBDIR}/django/bin/django-admin.py:${PORTSDIR}/www/py-django

USES=		python:2
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
