# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/math/R-cran-ChangeAnomalyDetection/Makefile 367888 2014-09-10 20:50:31Z gerald $

PORTNAME=	ChangeAnomalyDetection
PORTVERSION=	0.1.0
PORTREVISION=	5
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Change Anomaly Detection

LICENSE=	BSD

RUN_DEPENDS=	R-cran-TTR>0:${PORTSDIR}/finance/R-cran-TTR \
		R-cran-forecast>0:${PORTSDIR}/math/R-cran-forecast

USES=	cran:auto-plist

.include <bsd.port.mk>
