# Created by: Stephen Roznowski <sjr1@flash.net>
# $FreeBSD: tags/RELEASE_10_3_0/mail/xmail/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	xmail
PORTVERSION=	1.6
PORTREVISION=	2
CATEGORIES=	mail
MASTER_SITES=	XCONTRIB/applications
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	sjroz@verizon.net
COMMENT=	X-based interface to the Berkeley mail program

USES=		imake
USE_XORG=	xbitmaps xaw

.include <bsd.port.mk>
