# Created by: Lars Erik Gullerud <lerik@nolink.net>
# $FreeBSD: tags/RELEASE_10_3_0/net/py-radix/Makefile 371449 2014-10-24 16:21:26Z mva $

PORTNAME=	radix
PORTVERSION=	0.5
PORTREVISION=	1
CATEGORIES=	net python
MASTER_SITES=	http://www2.mindrot.org/files/py-radix/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	py-${PORTNAME}-${PORTVERSION}

MAINTAINER=	lerik@nolink.net
COMMENT=	Python radix-tree implementation

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
