# Created by: msciciel
# $FreeBSD: tags/RELEASE_10_3_0/net/dosdetector/Makefile 341916 2014-01-31 06:48:40Z miwi $

# The port will be at version 0.0 (based on dated CVS snapshots)
# until the release of DosDetector 0.1

PORTNAME=	dosdetector
PORTVERSION=	20060621
PORTREVISION=	2
CATEGORIES=	net
MASTER_SITES=	http://darkzone.ma.cx/resources/unix/dosdetector/

MAINTAINER=	msciciel@dark-zone.eu
COMMENT=	Detect suspicious network traffic

HAS_CONFIGURE=	yes
USE_AUTOTOOLS=	autoheader

PLIST_FILES=	bin/dosdetector \
		man/man1/dosdetector.1.gz

.include <bsd.port.mk>
