# Created by: jnlin@csie.nctu.edu.tw
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Tie-ShareLite/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Tie-ShareLite
PORTVERSION=	0.03
PORTREVISION=	2
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	jnlin@csie.nctu.edu.tw
COMMENT=	Tied hash interface to IPC::ShareLite

RUN_DEPENDS=	p5-IPC-ShareLite>=0:${PORTSDIR}/devel/p5-IPC-ShareLite

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
