# Created by: Edwin Groothuis
# $FreeBSD: tags/RELEASE_10_3_0/deskutils/hebcal/Makefile 359259 2014-06-25 16:30:03Z bapt $

PORTNAME=	hebcal
PORTVERSION=	3.7
CATEGORIES=	deskutils
MASTER_SITES=	SF/${PORTNAME}/${PORTNAME}-c/${PORTVERSION}/

MAINTAINER=	edwin@mavetju.org
COMMENT=	Hebrew Calendar calculator

USES=		makeinfo
HAS_CONFIGURE=	yes

PLIST_FILES=	bin/hebcal \
		man/man1/hebcal.1.gz

INFO=		hebcal

.include <bsd.port.mk>
