# Created by: Pawel Pekala <pawel@freebsd.org>
# $FreeBSD: tags/RELEASE_10_3_0/mail/claws-mail-libravatar/Makefile 357321 2014-06-10 15:08:10Z pawel $

PORTNAME=	libravatar
PORTREVISION=	0

COMMENT=	Avatar display plugin for Claws Mail

CLAWS_PLUGINS_BUILD=	libravatar

.include "../claws-mail/Makefile.claws"
.include <bsd.port.mk>
