# Created by: Mun-Kyo Seo <munggo@pmy.lv>
# $FreeBSD: tags/RELEASE_10_3_0/multimedia/mmsrip/Makefile 342437 2014-02-03 13:39:17Z miwi $

PORTNAME=	mmsrip
PORTVERSION=	0.7.0
CATEGORIES=	multimedia
MASTER_SITES=	http://www.sourcefiles.org/Multimedia/Tools/Network/ \
		http://nbenoit.tuxfamily.org/projects/mmsrip/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	MMS ripper - a client for the proprietary protocol mms://

LICENSE=	GPLv2 # (or later)

GNU_CONFIGURE=	yes

PLIST_FILES=	bin/mmsrip \
		man/man1/mmsrip.1.gz

.include <bsd.port.mk>
