# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-Horde_Tree/Makefile 385085 2015-05-01 07:11:54Z mm $

PORTNAME=	Horde_Tree
PORTVERSION=	2.0.4
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Tree API

USES=	horde
USE_HORDE_RUN=	Horde_Exception \
		Horde_Url \
		Horde_Util

.include <bsd.port.mk>
