# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-File-NFSLock/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	File-NFSLock
PORTVERSION=	1.21
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	File::NFSLock - perl module to do NFS (or not) locking

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
