# Created by: Jerry Eriksson <jerry@freebsd.se>
# $FreeBSD: tags/RELEASE_10_3_0/audio/rexima/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	rexima
PORTVERSION=	1.4
CATEGORIES=	audio
MASTER_SITES=	SUNSITE/apps/sound/mixers

MAINTAINER=	jerry@freebsd.se
COMMENT=	ncurses-based console mixer

LICENSE=	GPLv2

PLIST_FILES=	bin/rexima man/man1/rexima.1.gz

.include <bsd.port.mk>
