# Created by: Wen Heping<wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/net/pear-Net_Nmap/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Net_Nmap
PORTVERSION=	1.0.5
CATEGORIES=	net pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Simple Wrapper Class for the Nmap Utility

LICENSE=	LGPL3

BUILD_DEPENDS=	${PEARDIR}/XML/Parser.php:${PORTSDIR}/devel/pear-XML_Parser
RUN_DEPENDS:=	${PEARDIR}/XML/Parser.php:${PORTSDIR}/devel/pear-XML_Parser

USES=	pear

.include <bsd.port.mk>
