# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/multimedia/gstreamer-plugins-vdpau/Makefile 393429 2015-08-02 15:03:19Z tijl $

PORTREVISION=	3
CATEGORIES=	multimedia

COMMENT=	Gstreamer nvidia vdpau plugin

GST_PLUGIN=	vdpau

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
