# Created by: ijliao
# $FreeBSD: tags/RELEASE_10_3_0/www/rubygem-acts_as_taggable/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	acts_as_taggable
PORTVERSION=	2.0.2
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Add tagging capabilities to your ActiveRecord objects

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
