# Created by: SimaMoto,RyoTa <liangtai.s4@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/chinese/gimp-help-zh_CN/Makefile 342129 2014-02-01 12:49:26Z makc $

CATEGORIES=	chinese graphics

MAINTAINER=	liangtai.s16@gmail.com
COMMENT=	The GIMP User Manual in Simplified Chinese

LICENSE=	GFDL

MASTERDIR=	${.CURDIR}/../../misc/gimp-help-en

DOCLANG=	zh_CN

.include "${MASTERDIR}/Makefile"
