# Created by: Stephon Chen <stephon@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-IO-Stty/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	IO-Stty
PORTVERSION=	0.03
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Change and print terminal line settings

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
