# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Text-NeatTemplate/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Text-NeatTemplate
PORTVERSION=	0.10.01
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-${PORTVERSION:R}${PORTVERSION:E}

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Fast, middleweight template engine

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
