# $FreeBSD: tags/RELEASE_10_3_0/www/py-cssmin/Makefile 371186 2014-10-19 15:36:36Z rm $

PORTNAME=	cssmin
PORTVERSION=	0.2.0
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Python port of the YUI CSS compression algorithm

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
