# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Pragmatic/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Pragmatic
PORTVERSION=	1.7
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:BINKLEY
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Adds pragmata to Exporter

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
