# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/dns/pear-Net_DNS2/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Net_DNS2
PORTVERSION=	1.4.1
CATEGORIES=	dns net pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PHP5 Resolver library used to communicate with a DNS server

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		pear

.include <bsd.port.mk>
