# Created by: Pedro F. Giffuni <giffunip@asme.org>
# $FreeBSD: tags/RELEASE_10_3_0/lang/mawk/Makefile 385905 2015-05-09 19:21:49Z johans $

PORTNAME=	mawk
DISTVERSION=	1.3.4-20150503
CATEGORIES=	lang
MASTER_SITES=	ftp://invisible-island.net/${PORTNAME}/

MAINTAINER=	johans@FreeBSD.org
COMMENT=	Interpreter for the AWK Programming Language

LICENSE=	GPLv2

GNU_CONFIGURE=	yes
USES=		tar:tgz

PLIST_FILES=	bin/mawk \
		man/man1/mawk.1.gz

.include <bsd.port.mk>
