# Created by: Groovis <groovis@groovis.net>
# $FreeBSD: tags/RELEASE_10_3_0/www/p5-HTML-Macro/Makefile 395274 2015-08-25 14:52:20Z sunpoet $

PORTNAME=	HTML-Macro
PORTVERSION=	1.30
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Process HTML templates with loops, conditionals, macros and more

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

NO_ARCH=	yes
USE_PERL5=	configure
USES=		perl5 tar:tgz
WRKSRC=		${WRKDIR}/${PORTNAME}

.include <bsd.port.mk>
