# $FreeBSD: tags/RELEASE_10_3_0/textproc/rubygem-jsmin/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	jsmin
PORTVERSION=	1.0.1
PORTREVISION=	1
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby implementation of Douglas Crockford's JSMin JavaScript minifier

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
