# Created by: ijliao
# $FreeBSD: tags/RELEASE_10_3_0/net/rfbproxy/Makefile 363399 2014-07-29 21:43:17Z adamw $

PORTNAME=	rfbproxy
PORTVERSION=	1.1.1
CATEGORIES=	net
MASTER_SITES=	SF

MAINTAINER=	pphillips@experts-exchange.com
COMMENT=	Simple tool for recording VNC sessions

GNU_CONFIGURE=	yes

USES=	tar:bzip2

PLIST_FILES=	bin/rfbproxy \
		man/man1/rfbproxy.1.gz


.include <bsd.port.mk>
