# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: tags/RELEASE_10_3_0/cad/gmsh-occ/Makefile 383542 2015-04-07 21:20:24Z thierry $

PORTNAME=	gmsh
CATEGORIES=	cad
PKGNAMESUFFIX=	-occ

MAINTAINER=	thierry@FreeBSD.org
COMMENT=	Automatic 3D finite element mesh generator with OpenCascade support

MASTERDIR=	${.CURDIR}/../../cad/gmsh

WITH_OCC=	yes

.include "${MASTERDIR}/Makefile"
