# $FreeBSD: tags/RELEASE_10_3_0/devel/py-jellyfish/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	jellyfish
PORTVERSION=	0.3.1
CATEGORIES=	devel
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	bdrewery@FreeBSD.org
COMMENT=	Library for doing approximate and phonetic matching of strings

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
