# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/multimedia/gstreamer-plugins-xvid/Makefile 352119 2014-04-25 12:46:45Z bapt $
#    $MCom: ports/multimedia/gstreamer-plugins-xvid/Makefile,v 1.5 2008/03/19 14:05:37 ahze Exp $

PORTREVISION=	1
CATEGORIES=	multimedia

COMMENT=	Gstreamer xvid plugin

GST_PLUGIN=	xvid

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
