# Created by: ricci@cs.utah.edu
# $FreeBSD: tags/RELEASE_10_3_0/x11-wm/ion/Makefile 364347 2014-08-08 08:42:44Z olgeni $

PORTNAME=	ion
PORTVERSION=	20020207
PORTREVISION=	3
CATEGORIES=	x11-wm
MASTER_SITES=	http://modeemi.fi/~tuomov/dl/archives/

MAINTAINER=	ricci@cs.utah.edu
COMMENT=	Window manager with a text-editorish, keyboard friendly interface

CONFLICTS=	ion-2-*

USE_XORG=	x11
USES=		gmake

.include <bsd.port.mk>
