# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-mutter/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	mutter
PORTVERSION=	0.5.3
#PORTREVISION=	0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	This Ruby gem is a tiny command-line interface library

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
