# Created by: ijliao
# $FreeBSD: tags/RELEASE_10_3_0/graphics/graphopt/Makefile 368108 2014-09-13 15:11:27Z tijl $

PORTNAME=	graphopt
PORTVERSION=	0.4.1
PORTREVISION=	7
CATEGORIES=	graphics
MASTER_SITES=	SF/${PORTNAME}/${PORTNAME}/v${PORTVERSION}
EXTRACT_SUFX=	.tgz

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Graph layout optimizer

LICENSE=	GPLv2 # (or later)

USE_GNOME=	gtk12
GNU_CONFIGURE=	yes

DESKTOP_ENTRIES="GraphOpt" "" "" "${PORTNAME}" "Graphics;GTK;" ""

.include <bsd.port.mk>
