# Created by: Bruce M Simpson <bms@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/x11-fonts/gfe/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	gfe
PORTVERSION=	0.0.4
PORTREVISION=	6
CATEGORIES=	x11-fonts
MASTER_SITES=	SUNSITE/X11/fonts

MAINTAINER=	ports@FreeBSD.org
COMMENT=	GTK+-based .bdf font editor for X

GNU_CONFIGURE=	yes
PLIST_FILES=	bin/gfe

USE_GNOME=	gtk12
USE_XORG=	xpm

.include <bsd.port.mk>
