# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-App-CLI/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	App-CLI
PORTVERSION=	0.313
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	App::CLI - Dispatcher module for command line interface programs

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
