# Created by: Robert Gogolok <gogo@cs.uni-sb.de>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/rubygem-bundler/Makefile 404168 2015-12-21 18:35:22Z sunpoet $

PORTNAME=	bundler
PORTVERSION=	1.11.2
CATEGORIES=	sysutils rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Tool that manages gem dependencies for ruby applications

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/bundle bin/bundler

.include <bsd.port.mk>
