# Created by: Evan Sarmiento <bsdports@wayfair.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-bson/Makefile 402959 2015-12-04 12:34:30Z sunpoet $

PORTNAME=	bson
PORTVERSION=	3.2.6
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Full featured BSON specification implementation in Ruby

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
