# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/R-cran-foreach/Makefile 401880 2015-11-18 16:33:15Z tota $

PORTNAME=	foreach
PORTVERSION=	1.4.3
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Foreach looping construct for R

LICENSE=	APACHE20

RUN_DEPENDS=	R-cran-iterators>=1.0.0:${PORTSDIR}/devel/R-cran-iterators

USES=	cran:auto-plist

.include <bsd.port.mk>
