# Created by: Oleg A. Mamontov <oleg@mamontov.net>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Module-List/Makefile 379666 2015-02-23 10:08:58Z sunpoet $

PORTNAME=	Module-List
PORTVERSION=	0.003
PORTREVISION=	2
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	oleg@mamontov.net
COMMENT=	Module 'directory' listing

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
