# Created by: TERAMOTO Masahiro <markun@onohara.to>
# $FreeBSD: tags/RELEASE_10_3_0/net/p5-Net-Rendezvous-Publish/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Net-Rendezvous-Publish
PORTVERSION=	0.04
PORTREVISION=	2
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	markun@onohara.to
COMMENT=	Publish Rendezvous services

BUILD_DEPENDS=	p5-Class-Accessor-Lvalue>=0:${PORTSDIR}/devel/p5-Class-Accessor-Lvalue
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
