# $FreeBSD: tags/RELEASE_10_3_0/www/rubygem-browser/Makefile 395277 2015-08-25 14:52:39Z sunpoet $

PORTNAME=	browser
PORTVERSION=	1.0.1
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Web browser detection for Ruby

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
