# $FreeBSD: tags/RELEASE_10_3_0/security/pear-Auth_HTTP/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Auth_HTTP
PORTVERSION=	2.1.8
CATEGORIES=	security www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PEAR HTTP authentication

USES=	pear

.include <bsd.port.mk>
