# Created by: Zane C, Bowers <vvelox@vvelox.net>
# $FreeBSD: tags/RELEASE_10_3_0/ports-mgmt/p5-FreeBSD-Ports-INDEXhash/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	FreeBSD-Ports-INDEXhash
PORTVERSION=	1.2.2
PORTREVISION=	1
CATEGORIES=	ports-mgmt sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	vvelox@vvelox.net
COMMENT=	Make a hash out of the index file for the ports tree

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
