# Created by: Ditesh Shashikant Gathani <ditesh@gathani.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-Validate_AU/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Validate_AU
PORTVERSION=	0.1.4
PORTREVISION=	1
CATEGORIES=	devel www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PEAR data validation class for Australia

USES=	pear

.include <bsd.port.mk>
