# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-libyajl2/Makefile 364841 2014-08-14 11:09:24Z robak $

PORTNAME=	libyajl2
PORTVERSION=	1.0.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	renchap@cocoa-x.com
COMMENT=	Vendored copy of libyajl2

LICENSE=	APACHE20

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
