# Created by: will
# $FreeBSD: tags/RELEASE_10_3_0/security/p5-Crypt-UnixCrypt/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Crypt-UnixCrypt
PORTVERSION=	1.0
PORTREVISION=	1
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Perl module implementing crypt(3) function

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
