# $FreeBSD: tags/RELEASE_10_3_0/misc/typetrainer/Makefile 371289 2014-10-20 17:59:37Z mva $

PORTNAME=	typetrainer
PORTVERSION=	0.5.2
PORTREVISION=	2
CATEGORIES=	misc python
MASTER_SITES=	CHEESESHOP

MAINTAINER=	rm@FreeBSD.org
COMMENT=	Typing tutor trainer

LICENSE=	MIT

USE_GNOME=	pygtk2
USES=		python:2
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
