# Created by: Corey Smith
# $FreeBSD: tags/RELEASE_10_3_0/net/py-suds/Makefile 367298 2014-09-04 18:25:30Z sunpoet $

PORTNAME=	suds
PORTVERSION=	0.4
PORTREVISION=	1
CATEGORIES=	net python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	corsmith@gmail.com
COMMENT=	SOAP implementation

LICENSE=	LGPL3

USES=		python:2
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
