# Created by: Jaap Akkerhuis <jaap@NLnetLabs.nl>
# $FreeBSD: tags/RELEASE_10_3_0/dns/p5-DNS-Ldns/Makefile 352683 2014-04-30 15:16:34Z mat $

MASTERDIR=	${.CURDIR}/../../dns/ldns

BUILD_P5PERL=yes

PLIST=	${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
