# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/rubygem-rtlit/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	rtlit
PORTVERSION=	0.0.5
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	CSS left-to-right to right-to-left converter

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/rtlit

.include <bsd.port.mk>
