# Created by: Aaron H. K. Diep <ahkdiep@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-ctags/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	ctags
PORTVERSION=	1.0.5
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	python-ctags-${PORTVERSION}

MAINTAINER=	ahkdiep@gmail.com
COMMENT=	Python bindings for ctags index file

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
