# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/databases/pear-Horde_Imsp/Makefile 369674 2014-09-30 22:14:59Z bapt $

PORTNAME=	Horde_Imsp
PORTVERSION=	2.0.5
CATEGORIES=	databases www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde IMSP API

USES=	horde
USE_HORDE_RUN=	Horde_Translation

.include <bsd.port.mk>
