# Created by: Roman Neuhauser (<neuhauser@bellavista.cz>)
# $FreeBSD: tags/RELEASE_10_3_0/net/pear-Net_URL/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Net_URL
PORTVERSION=	1.0.15
CATEGORIES=	net www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Easy parsing of URLs

USES=	pear

.include <bsd.port.mk>
