# Created by: Yen-Ming Lee <leeym@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/misc/p5-Business-ISBN-Data/Makefile 376721 2015-01-10 18:35:26Z leeym $

PORTNAME=	Business-ISBN-Data
PORTVERSION=	20140910.002
CATEGORIES=	misc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	leeym@FreeBSD.org
COMMENT=	Data pack for Business::ISBN

BUILD_DEPENDS=	p5-ExtUtils-MakeMaker>=6.65:${PORTSDIR}/devel/p5-ExtUtils-MakeMaker

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
