# Created by: asami
# $FreeBSD: tags/RELEASE_10_3_0/x11-wm/piewm/Makefile 342440 2014-02-03 13:40:25Z miwi $

PORTNAME=	piewm
PORTVERSION=	1.04
PORTREVISION=	4
CATEGORIES=	x11-wm
MASTER_SITES=	http://www.crynwr.com/piewm/

MAINTAINER=	david@catwhisker.org
COMMENT=	tvtwm with pie (circular) menus

USES=		imake
DISABLE_SIZE=	yes
USE_XORG=	xbitmaps xpm xmu

CFLAGS+=	-Wno-return-type

.include <bsd.port.mk>
