# Created by: Pawel Worach
# $FreeBSD: tags/RELEASE_10_3_0/x11-fonts/font-screen-cyrillic/Makefile 381876 2015-03-21 23:05:19Z bapt $

PORTNAME=	font-screen-cyrillic
PORTVERSION=	1.0.4
PORTREVISION=	3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org Screen Cyrillic font

XORG_CAT=	font

.include <bsd.port.mk>
