# Created by: Murray Nesbitt <freebsd@nesbitt.ca>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/flasher/Makefile 359398 2014-06-26 16:51:42Z vanilla $

PORTNAME=	flasher
PORTVERSION=	1.3
CATEGORIES=	sysutils
MASTER_SITES=	http://www.unixporting.com/downloads/flasher/

MAINTAINER=	freebsd@nesbitt.ca
COMMENT=	Monitors log or mail files for writes, and flashes a keyboard LED

PLIST_FILES=	sbin/flasher man/man1/flasher.1.gz

.include <bsd.port.mk>
