# Created by: Travis Campbell <hcoyote@ghostar.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Class-Observable/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Class-Observable
PORTVERSION=	1.04
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	hcoyote@ghostar.org
COMMENT=	Allow other classes and objects to respond to events in yours

BUILD_DEPENDS=	p5-Class-ISA>=0:${PORTSDIR}/devel/p5-Class-ISA
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
