# Created by: Frerich Raabe <frerich.raabe@gmx.de>
# $FreeBSD: tags/RELEASE_10_3_0/devel/bnf/Makefile 359257 2014-06-25 16:10:36Z bapt $

PORTNAME=	bnf
PORTVERSION=	1.6.10
CATEGORIES=	devel
MASTER_SITES=	SAVANNAH

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Generate C parser given a grammar in BNF notation

LICENSE=	GPLv2

USES=		makeinfo
GNU_CONFIGURE=	yes

INFO=		bnf
PLIST_FILES=	bin/bnf

.include <bsd.port.mk>
