# Created by: Xin LI <delphij@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/net/openldap24-sasl-client/Makefile 342258 2014-02-02 09:51:17Z miwi $

CLIENT_ONLY=		sasl

MASTERDIR=		${.CURDIR}/../openldap24-server

.include "${MASTERDIR}/Makefile"
