# Created by: Emanuel Haupt <ehaupt@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Package-Generator/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Package-Generator
PORTVERSION=	1.106
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ehaupt@FreeBSD.org
COMMENT=	This module lets you quickly and easily construct new packages

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
