# Created by: Josh Carroll <josh.carroll@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/net-mgmt/wdiag/Makefile 358588 2014-06-20 15:16:37Z vanilla $

PORTNAME=	wdiag
PORTVERSION=	0.10.2
CATEGORIES=	net-mgmt
MASTER_SITES=	SF
EXTRACT_SUFX=	.tgz

MAINTAINER=	josh.carroll@gmail.com
COMMENT=	Utility to collect DSL line stats from Westell DSL modems

WRKSRC=		${WRKDIR}/${PORTNAME}/src

.include <bsd.port.mk>
