# Created by: ijliao
# $FreeBSD: tags/RELEASE_10_3_0/textproc/py-empy/Makefile 374183 2014-12-07 10:01:36Z mva $

PORTNAME=	empy
PORTVERSION=	3.3
CATEGORIES=	textproc python
MASTER_SITES=	http://www.alcyone.com/software/empy/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Powerful and robust templating system for Python

USES=		python:2
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
