# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/x11/libXfixes/Makefile 384234 2015-04-18 15:34:36Z kwm $

PORTNAME=	libXfixes
PORTVERSION=	5.0.1
PORTREVISION=	3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Fixes extension library

LICENSE=	MIT

XORG_CAT=	lib
USE_XORG=	x11 fixesproto:both xproto:both xextproto
USES+=	cpe
CPE_PRODUCT=	libxfixes
CPE_VENDOR=	x

.include <bsd.port.mk>
