# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: tags/RELEASE_10_3_0/math/p5-Statistics-OLS/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Statistics-OLS
PORTVERSION=	0.07
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl module to perform ordinary least squares and other bivariate statistics

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
