# Created by: wen@FreeBSD.org
# $FreeBSD: tags/RELEASE_10_3_0/net-im/pecl-stomp/Makefile 402450 2015-11-26 14:39:58Z miwi $

PORTNAME=	stomp
PORTVERSION=	1.0.8
CATEGORIES=	net-im pear
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PECL extension of stomp client

LICENSE=	PHP301

USES=		tar:tgz
USE_PHP=	yes
USE_PHPIZE=	yes
USE_PHPEXT=	yes

.include <bsd.port.mk>
