# Created by: krion
# $FreeBSD: tags/RELEASE_10_3_0/mail/exim-sqlite/Makefile 362543 2014-07-22 14:05:43Z vsevolod $

PKGNAMESUFFIX=	-sqlite
MASTERDIR=	${.CURDIR}/../exim

OPTIONS_SLAVE=	SQLITE

.include "${MASTERDIR}/Makefile"
