# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/rubygem-addressable/Makefile 403413 2015-12-09 14:28:20Z sunpoet $

PORTNAME=	addressable
PORTVERSION=	2.4.0
CATEGORIES=	www devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Replacement for the URI implementation

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
