# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-fast-stemmer/Makefile 387998 2015-05-30 23:08:48Z sunpoet $

PORTNAME=	fast-stemmer
PORTVERSION=	1.0.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Fast Porter stemmer based on a C version of algorithm

LICENSE=	MIT

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
