# $FreeBSD: tags/RELEASE_10_3_0/devel/elixir-msgpax/Makefile 396556 2015-09-10 09:15:55Z olgeni $

PORTNAME=	msgpax
PORTVERSION=	0.8.1
DISTVERSIONPREFIX=	v
CATEGORIES=	devel
PKGNAMEPREFIX=	elixir-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	MessagePack implementation for Elixir

LICENSE=	ISCL

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	lexmag

.include <bsd.port.mk>
