# Created by: Zhen REN <bg1tpt@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/www/pear-Services_Digg/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Services_Digg
PORTVERSION=	0.4.7
PORTREVISION=	1
CATEGORIES=	www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PHP interface to Digg's API

USES=	pear
USE_PHP=	curl

.include <bsd.port.mk>
