# Created by: TAKAHASHI Kaoru <kaoru@kaisei.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-String-CamelCase/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	String-CamelCase
PORTVERSION=	0.02
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Perl module for camelcase, de-camelcase

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
