# Created by: Jose Jachuf <jjachuf@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-rope/Makefile 379836 2015-02-24 20:03:07Z culot $

PORTNAME=	rope
PORTVERSION=	0.10.2
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	jjachuf@gmail.com
COMMENT=	Python refactoring library

LICENSE=	GPLv2

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
