# $FreeBSD: tags/RELEASE_10_3_0/russian/stardict-bars/Makefile 353800 2014-05-12 10:53:41Z makc $

PORTNAME=	stardict-bars
PORTVERSION=	2.4.2
CATEGORIES=	russian
MASTER_SITES=	http://abloz.com/huzheng/stardict-dic/ru/
DISTNAME=	stardict-en-ru-bars-${PORTVERSION}

MAINTAINER=	makc@FreeBSD.org
COMMENT=	New Comprehensive English-Russian dictionary

USES=		tar:bzip2

.include "${.CURDIR}/../stardict-mueller7/files/Makefile.common"
.include <bsd.port.mk>
