# Created by: Alex Miller (<asm@asm.kiev.ua>)
# $FreeBSD: tags/RELEASE_10_3_0/www/pear-HTTP/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	HTTP
PORTVERSION=	1.4.1
CATEGORIES=	www devel pear

MAINTAINER=	ports@FreeBSD.org
COMMENT=	PEAR miscellaneous HTTP utilities

USES=	pear

.include <bsd.port.mk>
