# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/pear-Horde_JavascriptMinify/Makefile 377058 2015-01-14 23:47:44Z mm $

PORTNAME=	Horde_JavascriptMinify
PORTVERSION=	1.1.2
CATEGORIES=	textproc www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Javascript Minification

USES=	horde

.include <bsd.port.mk>
