# Created by: Jean-Yves Lefort <jylefort@brutele.be>
# $FreeBSD: tags/RELEASE_10_3_0/security/pinentry-gtk2/Makefile 382076 2015-03-24 09:48:40Z makc $

PORTNAME=	pinentry
PORTREVISION=	0

COMMENT=	GTK+ 2.0 version of the GnuPG password dialog

PINENTRY_GUI=	gtk2

MASTERDIR=	${.CURDIR}/../pinentry

.include "${MASTERDIR}/Makefile"
