# Created by: Satoshi TAOKA <taoka@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/chinese/FreeWnn-lib/Makefile 357139 2014-06-09 11:21:52Z olgeni $

CATEGORIES=	chinese
PKGNAMESUFFIX=	-lib

COMMENT=	Japanese/Chinese/Korean input method (Chinese client libraries)

MASTERDIR=	${.CURDIR}/../../japanese/FreeWnn-lib
PKGDIR=		${.CURDIR}

OPTIONS_DEFAULT=CWNN LIB

.include "${MASTERDIR}/Makefile"
