# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-File-Spec-Native/Makefile 389561 2015-06-14 03:06:18Z kuriyama $

PORTNAME=	File-Spec-Native
PORTVERSION=	1.004
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension for native OS implementation of File::Spec

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	YES

.include <bsd.port.mk>
