# Created by: Scott Lambert <lambert@lambertfam.org>
# $FreeBSD: tags/RELEASE_10_3_0/mail/squirrelmail-abook_import_export-plugin/Makefile 366415 2014-08-28 15:16:49Z adamw $

PORTNAME=	abook_import_export
PORTVERSION=	1.1
PORTREVISION=	2
CATEGORIES=	mail www
DISTNAME=	${PORTNAME:S/-/_/}-${PORTVERSION}-1.4.4
DIST_SUBDIR=	squirrelmail

MAINTAINER=	lambert@lambertfam.org
COMMENT=	Allows for the importing of addressbooks from a CSV (comma separated values) file

SQUIRREL_PLUGIN_NAME=	${PORTNAME:S/-/_/}

.include "${.CURDIR}/../squirrelmail/bsd.squirrelmail.mk"
.include <bsd.port.mk>
