# $FreeBSD: tags/RELEASE_10_3_0/databases/rubygem-arel6/Makefile 394126 2015-08-13 17:35:24Z sunpoet $

PORTNAME=	arel
PORTVERSION=	6.0.3
CATEGORIES=	databases rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	6

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Relational Algebra for Ruby

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
