# Created by: Nicklas Johnson <freebsd@spatula.net>
# $FreeBSD: tags/RELEASE_10_3_0/games/speak/Makefile 357272 2014-06-10 06:31:31Z danfe $

PORTNAME=	speak
PORTVERSION=	1.2
CATEGORIES=	games
MASTER_SITES=	http://www.spatula.net/software/speak/

MAINTAINER=	freebsd@spatula.net
COMMENT=	Generates random middle-management synergy speak

CONFLICTS=	espeak-1.[0-9]*

.include <bsd.port.mk>
