# $FreeBSD: tags/RELEASE_10_3_0/devel/py-argh/Makefile 377963 2015-01-26 23:14:46Z nivit $

PORTNAME=	argh
PORTVERSION=	0.26.1
PORTREVISION=	0
CATEGORIES=	devel
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Simple (Python) argparse wrapper

LICENSE=	LGPL3

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
