# Created by: George Hartzell <hartzell@fruitfly.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Text-Shellwords/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	Text-Shellwords
PORTVERSION=	1.08
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	This is a thin wrapper around the shellwords.pl package

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
