# Created by: Brandon S. Allbery KF8NH <allbery@ece.cmu.edu>
# $FreeBSD: tags/RELEASE_10_3_0/comms/birda/Makefile 383791 2015-04-11 11:41:01Z marino $

PORTNAME=	birda
PORTVERSION=	1.3
CATEGORIES=	comms
MASTER_SITES=	ftp://ftp.netbsd.org/pub/pkgsrc/distfiles/

MAINTAINER=	mjl@luckie.org.nz
COMMENT=	Bohlin's IrDA utilities, ported from NetBSD's pkgsrc

USES=		uidfix

.include <bsd.port.mk>
