# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-dirspec/Makefile 378158 2015-01-30 15:32:36Z nivit $

PORTNAME=	dirspec
PORTVERSION=	13.10
PORTREVISION=	0
CATEGORIES=	devel
MASTER_SITES=	https://launchpadlibrarian.net/152764618/ \
		http://nivit.altervista.org/FreeBSD/ports/distfiles/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	XDG Base and User directories implementation

LICENSE=	GPLv3

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
