# Created by: Steven Kreuzer <skreuzer@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/R-cran-pystr/Makefile 392100 2015-07-14 21:26:45Z skreuzer $

PORTNAME=	pystr
DISTVERSION=	1.0.0
CATEGORIES=	textproc
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	String operations the Python way

USES=	cran:auto-plist

.include <bsd.port.mk>
