# $FreeBSD: tags/RELEASE_10_3_0/x11-drivers/xf86-video-sunffb/Makefile 399179 2015-10-13 07:45:08Z kwm $

PORTNAME=	xf86-video-sunffb
PORTVERSION=	1.2.2
PORTREVISION=	6
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org sunffb display driver

USE_GL=		gl

XORG_CAT=	driver
USE_XORG=	xf86driproto xextproto glproto
ONLY_FOR_ARCHS=	sparc64

.include <bsd.port.mk>
