# Created by: Yoshiro MIHIRA <sanpei@jp.FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/japanese/ngraph-fonts/Makefile 398016 2015-09-26 21:15:00Z antoine $

PORTNAME=	ngraph-fonts
PORTVERSION=	1.0
PORTREVISION=	3
CATEGORIES=	japanese math x11-fonts

MAINTAINER=	sanpei@FreeBSD.org
COMMENT=	Japanese Font Setup for math/ngraph

RUN_DEPENDS= \
	${LOCALBASE}/share/kanji/kanji18.pcf.gz:${PORTSDIR}/japanese/font-kanji18 \
	${LOCALBASE}/share/kanji/kanji26.pcf.gz:${PORTSDIR}/japanese/font-kanji26

USES=		metaport

.include <bsd.port.mk>
