# Created by: Johann Visagie <wjv@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/mail/exim-doc-pdf/Makefile 360749 2014-07-05 14:39:18Z vsevolod $

DOCFORMAT=	pdf
MASTERDIR=	${.CURDIR}/../exim-doc-html

.include "${MASTERDIR}/Makefile"
