# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/net/pear-Horde_Socket_Client/Makefile 381067 2015-03-12 09:17:40Z mm $

PORTNAME=	Horde_Socket_Client
PORTVERSION=	2.0.0
CATEGORIES=	net www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Socket Client

USES=	horde
USE_HORDE_RUN=	Horde_Exception

.include <bsd.port.mk>
