# $FreeBSD: tags/RELEASE_10_3_0/devel/git-gui/Makefile 398132 2015-09-28 18:33:46Z garga $

PKGNAMESUFFIX=	-gui

COMMENT=	Distributed source code management tool (GUI enabled)

MASTERDIR=	${.CURDIR}/../git

DESCR=		${.CURDIR}/pkg-descr

OPTIONS_SLAVE=	GUI

CONFLICTS_INSTALL=	git-[0-9]* git-lite-[0-9]* git-subversion-[0-9]*

DISTINFO_FILE=	${MASTERDIR}/distinfo

.include "${MASTERDIR}/Makefile"
