# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-dotenv-deployment/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	dotenv-deployment
PORTVERSION=	0.0.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Deployment concerns for dotenv

LICENSE=	MIT

DEPRECATED=	Deprecated by upstream in latest version (0.3.0)

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=yes

.include <bsd.port.mk>
