# Created by: Oliver Lehmann <oliver@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/security/courier-authlib-base/Makefile 396348 2015-09-07 21:29:19Z madpilot $

PORTREVISION=	2
PKGNAMESUFFIX=	-base

COMMENT=	Courier authentication library base
CATEGORIES=	security mail

MASTERDIR=	${.CURDIR}/../../security/courier-authlib

USE_LDCONFIG=	${PREFIX}/lib/${PORTNAME}

.include "${MASTERDIR}/Makefile"
