# Created by: Mirko Zinn <mail@derzinn.de>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-anyjson/Makefile 375249 2014-12-22 17:12:26Z feld $

PORTNAME=	anyjson
PORTVERSION=	0.3.3
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	mail@derzinn.de
COMMENT=	JSON library wrapper for Python

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
