# Created by: Simon Barner <barner@gmx.de>
# $FreeBSD: tags/RELEASE_10_3_0/audio/p5-Audio-WMA/Makefile 385807 2015-05-08 17:47:38Z adamw $

PORTNAME=	Audio-WMA
PORTVERSION=	1.3
PORTREVISION=	1
CATEGORIES=	audio perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Fetch info from WMA audio files

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
