# Created by: peter.schuller@infidyne.com
# $FreeBSD: tags/RELEASE_10_3_0/textproc/rubygem-liquid2/Makefile 400532 2015-10-30 11:26:38Z sunpoet $

PORTNAME=	liquid
PORTVERSION=	2.6.3
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	2

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Library for rendering safe templates

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
