# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: tags/RELEASE_10_3_0/german/alt-aspell/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	alt-aspell
DISTVERSION=	6-de-alt-2.1-1
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	german textproc
MASTER_SITES=	GNU/aspell/dict/de-alt

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell German Old Spelling (Deutsch - alte Rechtschreibung) dictionary

DICT=	 	de

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
