# Created by: Alexandre Biancalana <ale@biancalanas.net>
# $FreeBSD: tags/RELEASE_10_3_0/net-mgmt/p5-Net-IPAddress/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Net-IPAddress
PORTVERSION=	1.10
PORTREVISION=	1
CATEGORIES=	net-mgmt perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:SARENNER
PKGNAMEPREFIX=	p5-

MAINTAINER=	ale@biancalanas.net
COMMENT=	Perl functions used to manipulate IP addresses, masks and FQDN's

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
