# $FreeBSD: tags/RELEASE_10_3_0/www/py-webassets/Makefile 366526 2014-08-29 16:25:24Z wg $

PORTNAME=	webassets
PORTVERSION=	0.10.1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Media asset management for Python

LICENSE=	BSD2CLAUSE

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
