# Created by: ijliao
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Text-Greeking/Makefile 374045 2014-12-05 15:37:35Z jadawin $

PORTNAME=	Text-Greeking
PORTVERSION=	0.14
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Generate meaningless text that creates the illusion of the document

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
