# Created by: Mark Pulford <mark@kyne.com.au>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/xin/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	xin
PORTVERSION=	1.0.0
PORTREVISION=	1
CATEGORIES=	sysutils
MASTER_SITES=	SUNSITE/utils/file

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Splits standard input and pipes into a command

GNU_CONFIGURE=	yes
PLIST_FILES=	bin/xin man/man1/xin.1.gz

.include <bsd.port.mk>
