# Created by: Aaron Dalton <aaron@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/math/p5-Math-Geometry-Planar-GPC/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	Math-Geometry-Planar-GPC
PORTVERSION=	1.04
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Perl wrapper for Alan Murta's gpc library

LICENSE=	ART10

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
