# Created by: jhay
# $FreeBSD: tags/RELEASE_10_3_0/net/p5-Net-SMPP/Makefile 402155 2015-11-21 13:21:14Z culot $

PORTNAME=	Net-SMPP
PORTVERSION=	1.19
PORTREVISION=	2
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Net::SMPP - pure Perl implementation of SMPP 3.4 over TCP

USES=		perl5 shebangfix
SHEBANG_FILES=	*.pl
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
