# $FreeBSD: tags/RELEASE_10_3_0/mail/p5-Parse-MIME/Makefile 395087 2015-08-23 11:55:18Z kuriyama $

PORTNAME=	Parse-MIME
PORTVERSION=	1.003
CATEGORIES=	mail perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension to parse mime-types

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	YES

.include <bsd.port.mk>
