# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-jsonlib2/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	jsonlib2
PORTVERSION=	1.5.2
PORTREVSION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	JSON Serializer/Deserializer for Python

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
