# Created by: peter.schuller@infidyne.com
# $FreeBSD: tags/RELEASE_10_3_0/textproc/rubygem-liquid/Makefile 400359 2015-10-27 22:49:57Z mmoll $

PORTNAME=	liquid
PORTVERSION=	3.0.6
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Library for rendering safe templates

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
