# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: tags/RELEASE_10_3_0/www/google-sitemapgen/Makefile 376109 2015-01-03 08:41:20Z mva $

PORTNAME=	google-sitemapgen
PORTVERSION=	1.5
CATEGORIES=	www devel
MASTER_SITES=	GOOGLE_CODE
DISTNAME=	sitemap_gen_${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Script to analyze web server and generate Google Sitemap files

PROJECTHOST=	sitemap-generators

NO_WRKSUBDIR=

USES=		python
USE_PYTHON=	distutils
PYDISTUTILS_PKGNAME=	sitemap_gen

.include <bsd.port.mk>
