# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/x11/libxkbui/Makefile 384234 2015-04-18 15:34:36Z kwm $

PORTNAME=	libxkbui
PORTVERSION=	1.0.2
PORTREVISION=	4
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	The xkbui library

XORG_CAT=	lib
USE_XORG=	x11 xt xkbfile kbproto:both
.include <bsd.port.mk>
