# Created by: Thomas Zander <riggs@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-validictory/Makefile 402086 2015-11-20 14:42:18Z rm $

PORTNAME=	validictory
PORTVERSION=	1.0.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	python@FreeBSD.org
COMMENT=	General purpose Python data validator

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

NO_ARCH=	yes
USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
