# Created by: Joseph Benden <joe@thrallingpenguin.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-wdm/Makefile 375249 2014-12-22 17:12:26Z feld $

PORTNAME=	wdm
PORTVERSION=	0.1.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	joe@thrallingpenguin.com
COMMENT=	Library for monitoring directories for changes

LICENSE=	MIT

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
