# Created by: Jason Burgess <dev@fenux.net>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Text-Chomp/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Text-Chomp
PORTVERSION=	0.02
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Module implementing a portable chomp

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
