# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/audio/gstreamer-plugins-twolame/Makefile 352119 2014-04-25 12:46:45Z bapt $

PORTREVISION=	1
CATEGORIES=	audio

COMMENT=	Gstreamer High-quality free MP2 encoder plugin

GST_PLUGIN=	twolame

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
