# Created by: john@zoner.org
# $FreeBSD: tags/RELEASE_10_3_0/textproc/py-pyx12/Makefile 374183 2014-12-07 10:01:36Z mva $

PORTNAME=	pyx12
PORTVERSION=	2.1.1
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Validate and convert HIPAA X12 documents

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
