# $FreeBSD: tags/RELEASE_10_3_0/databases/py-mysql-connector-python/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=		mysql-connector-python
PORTVERSION=		1.2.3
CATEGORIES=		databases python
MASTER_SITES=		MYSQL/Connector-Python
PKGNAMEPREFIX=		${PYTHON_PKGNAMEPREFIX}

MAINTAINER=		bofh@FreeBSD.org
COMMENT=		MySQL driver written in Python

LICENSE=		GPLv2

PORTSCOUT=		limit:^1\.
USES=			python
USE_PYTHON=		distutils autoplist

.include <bsd.port.mk>
