# Created by: Evan Sarmiento <bsdports@wayfair.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-bson1/Makefile 402960 2015-12-04 12:34:34Z sunpoet $

PORTNAME=	bson
PORTVERSION=	1.12.5
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	1

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Full featured BSON specification implementation in Ruby

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PORTSCOUT=	limit:^1\.

.include <bsd.port.mk>
