# Created by: Fabian Keil <fk@fabiankeil.de>
# $FreeBSD: tags/RELEASE_10_3_0/net-mgmt/vidalia/Makefile 389284 2015-06-12 16:22:33Z jbeich $

PORTNAME=	vidalia
PORTVERSION=	0.2.21
CATEGORIES=	net-mgmt security
MASTER_SITES=	TOR/vidalia

MAINTAINER=	fk@fabiankeil.de
COMMENT=	Graphical Tor controller based on Qt 4.x

USES=		cmake
INSTALLS_ICONS=	yes
USE_QT4=	gui moc_build qmake_build rcc_build uic_build network xml linguist_build

.include <bsd.port.mk>
