# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/math/p5-Math-Gradient/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Math-Gradient
PORTVERSION=	0.04
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Calculating gradients for color transitions and the like

USES=		perl5 tar:tgz
USE_PERL5=	configure

.include <bsd.port.mk>
