# Created by: Maxim Ignatenko
# $FreeBSD: tags/RELEASE_10_3_0/irc/irc2dc/Makefile 363399 2014-07-29 21:43:17Z adamw $

PORTNAME=	irc2dc
PORTVERSION=	0.1
CATEGORIES=	irc net-p2p
MASTER_SITES=	SF

MAINTAINER=	gelraen.ua@gmail.com
COMMENT=	Provides intercommunication between DC++ hub and IRC channel

USES=	tar:bzip2
HAS_CONFIGURE=	yes

USE_RC_SUBR=	irc2dc

PLIST_FILES=	bin/irc2dc \
		etc/irc2dc.conf.dist

.include <bsd.port.mk>
