# Created by: Anes Mukhametov <anes@anes.su>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Class-Mixin/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Class-Mixin
PORTVERSION=	1.00
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	anes@anes.su
COMMENT=	API for aliasing methods to/from other classes

USES=	perl5
USE_PERL5=	configure

.include <bsd.port.mk>
