# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/R-cran-proto/Makefile 367888 2014-09-10 20:50:31Z gerald $

PORTNAME=	proto
DISTVERSION=	0.3-10
PORTREVISION=	7
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Prototype object-based programming

LICENSE=	GPLv2

USES=	cran:auto-plist

.include <bsd.port.mk>
