# Created by: Fukang Chen <loader@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-glob2/Makefile 396502 2015-09-09 14:14:40Z loader $

PORTNAME=	glob2
PORTVERSION=	0.4.1
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	loader@FreeBSD.org
COMMENT=	Glob that captures patterns and supports recursive wildcards

LICENSE=	BSD2CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
