# Created by: Edwin Mons
# $FreeBSD: tags/RELEASE_10_3_0/games/trojka/Makefile 359017 2014-06-23 23:00:51Z jhale $

PORTNAME=	trojka
PORTVERSION=	1.0
CATEGORIES=	games
MASTER_SITES=	ftp://ftp.funet.fi/pub/unix/games/
DISTNAME=	${PORTNAME}

MAINTAINER=	e@ik.nu
COMMENT=	Game of skill

LICENSE=	TROJKA
LICENSE_NAME=	Trojka Copyright
LICENSE_PERMS=	dist-mirror dist-sell pkg-mirror pkg-sell auto-accept
LICENSE_FILE=	${WRKSRC}/COPYRIGHT

SUB_FILES=	pkg-message

.include <bsd.port.mk>
