# $FreeBSD: tags/RELEASE_10_3_0/print/ghostscript7-base/files/Makefile.lx5000 386312 2015-05-14 10:15:04Z mat $
# LX5000 - additional driver for Lexmark 5000/Z51/Z82
# http://homepage.powerup.com.au/~pbwest/lexmark/lexmark.html

MASTER_SITES+=	LOCAL/pav:lx5000
DISTFILES+=	gdevlx50.c:lx5000
EXTRADEVMKFILE+=	${FILESDIR}/lx5000.contrib.mak

post-extract-lx5000:
	${INSTALL_DATA} ${DISTDIR}/${DIST_SUBDIR}/gdevlx50.c ${WRKSRC}/src

post-extract: post-extract-lx5000
