# $FreeBSD: tags/RELEASE_10_3_0/print/ghostscript7-base/files/Makefile.cdj880 340722 2014-01-22 17:00:46Z mat $
# for HP DeskJet 812C/815C/832C/880C/882C/895C
# http://www.gelhaus.net/hp880c/

MASTER_SITES+=	http://www.gelhaus.net/hp880c/1.4beta/:cdj880
DISTFILES+=	gdevcd8.tar.gz:cdj880
EXTRADEVMKFILE+=	${FILESDIR}/cdj850.contrib.mak

post-extract-cdj880:
	${TAR} -C ${WRKSRC}/src -xzf ${DISTDIR}/${DIST_SUBDIR}/gdevcd8.tar.gz

post-extract: post-extract-cdj880
