# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/mail/claws-mail-bsfilter/Makefile 336489 2013-12-14 22:02:10Z pawel $

PORTNAME=	bsfilter
PORTREVISION=	0

COMMENT=	Spam filtering, bsfilter based plugin for Claws Mail

RUN_DEPENDS=	bsfilter:${PORTSDIR}/mail/bsfilter

CLAWS_PLUGINS_BUILD=	bsfilter

.include "../claws-mail/Makefile.claws"
.include <bsd.port.mk>
