# Created by: Dmitry Sivachenko <dima@Chg.RU>
# $FreeBSD: tags/RELEASE_10_3_0/www/p5-HTML-TableLayout/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	HTML-TableLayout
PORTVERSION=	1.001008
PORTREVISION=	1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	demon@FreeBSD.org
COMMENT=	Layout manager for CGI-based web applications

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
