# Created by: Andrew Pantyukhin <infofarmer@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/xpi-xmpp4moz/Makefile 372709 2014-11-18 09:37:31Z bapt $

PORTNAME=	xmpp4moz
PORTVERSION=	0.5.2.2007113019
DISTVERSIONSUFFIX=	-fx+tb+fl
CATEGORIES=	www

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Support for XMPP

XPI_ID=		xmpp4moz@hyperstruct.net
XPI_NUM=	3632

.include "${.CURDIR}/../xpi-adblock/Makefile.xpi"
.include <bsd.port.mk>
