# $FreeBSD: releng/10.3/cddl/usr.bin/tests/Makefile 264741 2014-04-21 21:39:25Z jmmv $

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/cddl/usr.bin

.PATH:		${.CURDIR:H:H:H}/tests
KYUAFILE=	yes

.include <bsd.test.mk>
