# Created by: Anders Nordby <anders@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/misc/p5-Norge/Makefile 386075 2015-05-11 12:04:18Z mat $

PORTNAME=	Norge
PORTVERSION=	1.08
PORTREVISION=	1
CATEGORIES=	misc textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Misc. Norwegian methods for Perl, conversion/dates/numbers etc.

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
