# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Exporter-Easy/Makefile 401303 2015-11-11 23:03:19Z adamw $

PORTNAME=	Exporter-Easy
PORTVERSION=	0.18
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Takes the drudgery out of Exporting symbols

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
