# Created by: Peter Schuller <peter.schuller@infidyne.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-boto/Makefile 394189 2015-08-13 19:49:42Z rm $

PORTNAME=	boto
PORTVERSION=	2.38.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	rm@FreeBSD.org
COMMENT=	Python interface to Amazon Web Services

LICENSE=	MIT

NO_ARCH=	yes
USES=		python
USE_PYTHON=	autoplist distutils

CONFLICTS=	p5-Net-Amazon-Route53-[0-9]*

.include <bsd.port.mk>
