# $FreeBSD: tags/RELEASE_10_3_0/devel/erlang-getopt/Makefile 391483 2015-07-06 22:27:17Z olgeni $

PORTNAME=	getopt
PORTVERSION=	0.8.2
DISTVERSIONPREFIX=	v
CATEGORIES=	devel
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Command line parsing library for Erlang

LICENSE=	BSD3CLAUSE

USES=		erlang:rebar
USE_GITHUB=	yes
GH_ACCOUNT=	jcomellas

.include <bsd.port.mk>
