# $FreeBSD: tags/RELEASE_10_3_0/audio/py-al/Makefile 383412 2015-04-06 08:01:38Z mva $

PORTNAME=	al
PORTVERSION=	0.1.0
CATEGORIES=	audio python
MASTER_SITES=	http://bitbucket.org/marcusva/py-al/downloads/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	PyAL-${PORTVERSION}

MAINTAINER=	mva@FreeBSD.org
COMMENT=	PyAL is a binding of OpenAL for Python

LICENSE=	ZLIB

USES=		openal:al python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
