# Created by: Bill Ross <bross@nas.nasa.gov>
# $FreeBSD: tags/RELEASE_10_3_0/devel/avltree/Makefile 400076 2015-10-24 00:43:46Z bapt $

PORTNAME=	avltree
PORTVERSION=	1.1
PORTREVISION=	1
CATEGORIES=	devel
MASTER_SITES=	http://www.gtlib.gatech.edu/pub/FreeBSD/distfiles/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	In-memory index w/ binary and string keys and key counts

BROKEN=		Does not fetch
MAKE_ARGS=	PREFIX=${STAGEDIR}${PREFIX}

.include <bsd.port.mk>
