# Created by: Alex Kapranoff <kapr@crosswinds.net>
# $FreeBSD: tags/RELEASE_10_3_0/www/p5-HTML-Clean/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	HTML-Clean
PORTVERSION=	0.8
PORTREVISION=	1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Cleans up HTML code for web browsers, not humans

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
