# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/audio/gstreamer-plugins-mad/Makefile 374303 2014-12-08 16:48:38Z tijl $
#   $MCom: ports/audio/gstreamer-plugins-mad/Makefile,v 1.5 2008/03/19 14:05:30 ahze Exp $

PORTREVISION=	3
CATEGORIES=	audio

COMMENT=	Gstreamer mp3 decoder plugin

GST_PLUGIN=	mad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
