# Created by: will
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Algorithm-Permute/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Algorithm-Permute
PORTVERSION=	0.12
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl interface to handy and fast permutation

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
