# Created by: Shin-ya MURAKAMI <murashin@gfd-dennou.org>
# $FreeBSD: tags/RELEASE_10_3_0/math/rubygem-numru-misc/Makefile 356622 2014-06-05 09:31:38Z miwi $

PORTNAME=	numru-misc
PORTVERSION=	0.1.1
CATEGORIES=	math rubygems
MASTER_SITES=	RG

MAINTAINER=	murashin@gfd-dennou.org
COMMENT=	Miscellaneous functions and classes to help Ruby programming

RUN_DEPENDS=	rubygem-narray>0:${PORTSDIR}/math/rubygem-narray \
		rubygem-narray_miss>0:${PORTSDIR}/math/rubygem-narray_miss

USE_RUBY=	yes
USE_RAKE=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
