# $FreeBSD: tags/RELEASE_10_3_0/www/py-requests-toolbelt/Makefile 369542 2014-09-29 18:32:12Z wg $

PORTNAME=	requests-toolbelt
PORTVERSION=	0.3.1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Utility belt for advanced users of python-requests

LICENSE=	APACHE20

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}requests>0:${PORTSDIR}/www/py-requests

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
