# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/pear-I18Nv2/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	I18Nv2
PORTVERSION=	0.11.4
CATEGORIES=	sysutils devel pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PEAR Internationalization

USES=	pear
USE_PHP=	iconv

.include <bsd.port.mk>
