# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/gstreamer-plugins-soup/Makefile 352119 2014-04-25 12:46:45Z bapt $
#   $MCom: ports/devel/gstreamer-plugins-soup/Makefile,v 1.3 2008/03/19 14:05:33 ahze Exp $

PORTREVISION=	1
CATEGORIES=	devel

COMMENT=	Gstreamer soup http src plugin

GST_PLUGIN=	soup

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
