# Created by: Yen-Ming Lee <leeym@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/net/jumpgate/Makefile 356729 2014-06-06 01:34:31Z vanilla $

PORTNAME=	jumpgate
PORTVERSION=	0.7
CATEGORIES=	net
MASTER_SITES=	http://jumpgate.sourceforge.net/

MAINTAINER=	leeym@FreeBSD.org
COMMENT=	TCP connection forwarder

GNU_CONFIGURE=	yes

PLIST_FILES=	man/man8/jumpgate.8.gz sbin/jumpgate

.include <bsd.port.mk>
