# Created by: Ed Schouten <ed@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/cloudabi-binutils-aarch64/Makefile 399906 2015-10-21 12:28:21Z ed $

PKGNAMEPREFIX=	cloudabi-
PKGNAMESUFFIX=	-aarch64

MAINTAINER=	ed@FreeBSD.org
COMMENT=	GNU Binutils for CloudABI cross-development

MASTERDIR=	${.CURDIR}/../binutils
PATCHDIR=	${.CURDIR}/files
PLIST=		${.CURDIR}/pkg-plist

BUTARGET=	aarch64-unknown-cloudabi

.include "${MASTERDIR}/Makefile"
