# Created by: will
# $FreeBSD: tags/RELEASE_10_3_0/archivers/p5-Archive-Zip/Makefile 403138 2015-12-06 17:52:10Z sunpoet $

PORTNAME=	Archive-Zip
PORTVERSION=	1.55
CATEGORIES=	archivers perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Create, manipulate, read, and write Zip archive files

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-Test-MockModule>=0:${PORTSDIR}/devel/p5-Test-MockModule

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
