# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-PHP_Compat/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	PHP_Compat
PORTVERSION=	1.5.0
CATEGORIES=	devel www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Provides missing functionality for older versions of PHP

PORTSCOUT=	skipv:1.6.0a1,1.6.0a2
USES=	pear

.include <bsd.port.mk>
