# Created by: Adam Weinberger <adamw@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Brannigan/Makefile 378972 2015-02-14 17:26:55Z adamw $

PORTNAME=	Brannigan
PORTVERSION=	1.1
CATEGORIES=	devel www perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:IDOPEREL
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Comprehensive, flexible system for validating and parsing input

LICENSE=	GPLv1 ART20
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
