# Created by: Fabiano Sidler <fabianosidler@swissonline.ch>
# $FreeBSD: tags/RELEASE_10_3_0/print/py-fpdf/Makefile 400480 2015-10-29 21:35:01Z pawel $

PORTNAME=	fpdf
PORTVERSION=	1.7.2
CATEGORIES=	print python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	fabianosidler@swissonline.ch
COMMENT=	Simple PDF generation for Python

LICENSE=	LGPL3

USES=		python
USE_PYTHON=	autoplist distutils
NO_ARCH=	yes

.include <bsd.port.mk>
