# Created by: Olivier Duchateau <duchateau.olivier@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/www/py-flask-uploads/Makefile 404016 2015-12-19 14:10:22Z olivierd $

PORTNAME=	Flask-Uploads
PORTVERSION=	0.2.0
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	python@FreeBSD.org
COMMENT=	Flexible and efficient upload handling for Flask

LICENSE=	MIT

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}Flask>=0.10:${PORTSDIR}/www/py-flask

USES=	python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
