# Created by: Igor Vinokurov <igor@zynaps.ru>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-AppConfig/Makefile 388694 2015-06-07 13:06:24Z lth $

PORTNAME=	AppConfig
PORTVERSION=	1.71
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Perl module for reading configuration files

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
