# Created by: Tsung-Han Yeh <snowfly@yuntech.edu.tw>
# $FreeBSD: tags/RELEASE_10_3_0/net-im/p5-Net-NetSend/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Net-NetSend
PORTVERSION=	0.12
PORTREVISION=	1
CATEGORIES=	net-im perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	snowfly@yuntech.edu.tw
COMMENT=	Perl extension for sending Windows Popup Messages

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
