# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-XML-Tiny/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	XML-Tiny
PORTVERSION=	2.06
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Simple lightweight parser for a subset of XML

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
