# Created by: Johannes Meixner <xmj@chaot.net>
# $FreeBSD: tags/RELEASE_10_3_0/dns/linux-c6-libasyncns/Makefile 393817 2015-08-09 19:14:13Z netchild $

PORTNAME=	libasyncns
PORTVERSION=	0.8
PORTREVISION=	2
CATEGORIES=	dns devel linux

MAINTAINER=	emulation@FreeBSD.org
COMMENT=	C library for executing DNS queries asynchronously (Linux CentOS ${LINUX_DIST_VER})

USE_LINUX=	c6
USE_LINUX_RPM=	yes
RPMVERSION=	1.1.el6
USE_LDCONFIG=	yes

.include <bsd.port.mk>
