# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/gstreamer-plugins-gio/Makefile 352119 2014-04-25 12:46:45Z bapt $
#   $MCom: ports/devel/gstreamer-plugins-gio/Makefile,v 1.1 2008/03/21 04:14:18 ahze Exp $

PORTREVISION=	1
CATEGORIES=	devel

COMMENT=	Gstreamer gio (Glib I/O) plugin

GST_PLUGIN=	gio

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
