# Created by: Eric van Gyzen <vangyzen@stat.duke.edu>
# $FreeBSD: tags/RELEASE_10_3_0/math/libRmath/Makefile 350209 2014-04-05 10:30:21Z antoine $

PORTNAME=	libRmath

COMMENT=	The standalone math library from R

DESCR=	${.CURDIR}/pkg-descr
LIBRMATH_SLAVEPORT=	yes
MASTERDIR=	${.CURDIR}/../R
PLIST=	${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
