# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Text-ParseWords/Makefile 381105 2015-03-12 15:23:52Z sunpoet $

PORTNAME=	Text-ParseWords
PORTVERSION=	3.30
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Parse text into an array of tokens or array of arrays

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
