# $FreeBSD: tags/RELEASE_10_3_0/security/rubygem-six/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	six
PORTVERSION=	0.2.0
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Very simple authorization gem

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
