# $FreeBSD: tags/RELEASE_10_3_0/x11/xorg-docs/Makefile 399834 2015-10-20 13:42:37Z kwm $

PORTNAME=	xorg-docs
PORTVERSION=	1.7.1
PORTEPOCH=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.org documentation files

CONFIGURE_ARGS+=	--without-xmlto --without-fop --disable-specs

XORG_CAT=	doc

.include <bsd.port.mk>
