# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/converters/R-cran-RJSONIO/Makefile 368802 2014-09-22 05:20:09Z tota $

PORTNAME=	RJSONIO
DISTVERSION=	1.3-0
CATEGORIES=	converters
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Serialize R objects to JSON, JavaScript Object Notation

LICENSE=	BSD3CLAUSE

USES=	cran:auto-plist

.include <bsd.port.mk>
