# Created by: chinsan
# $FreeBSD: tags/RELEASE_10_3_0/net/pear-Net_Whois/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Net_Whois
PORTVERSION=	1.0.5
CATEGORIES=	net pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Tool to query internet domain name services

USES=	pear

RUN_DEPENDS=	${PEARDIR}/Net/Socket.php:${PORTSDIR}/net/pear-Net_Socket

.include <bsd.port.mk>
