# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-nagioscheck/Makefile 368384 2014-09-17 15:27:06Z zi $

PORTNAME=	nagioscheck
PORTVERSION=	0.1.6
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	python@FreeBSD.org
COMMENT=	Class library for writing Nagios plugins

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
