# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/rubygem-webrobots/Makefile 391473 2015-07-06 18:05:37Z sunpoet $

PORTNAME=	webrobots
PORTVERSION=	0.1.1
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Write robots.txt compliant web robots in Ruby

LICENSE=	BSD2CLAUSE

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
