# $FreeBSD: tags/RELEASE_10_3_0/japanese/p5-Encode-JP-Emoji/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Encode-JP-Emoji
PORTVERSION=	0.60
PORTREVISION=	1
CATEGORIES=	japanese perl5
MASTER_SITES=	CPAN

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension for Emoji encodings and cross-mapping tables

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.pre.mk>

PKGNAMEPREFIX:=	${PKGNAMEPREFIX}p5-

.include <bsd.port.post.mk>
