# Created by: Boris Lytochkin <lytboris@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/net/rubygem-ipaddress/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	ipaddress
PORTVERSION=	0.8.0
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	IP address manipulation library for rubygems

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
