# Created by: Andrew Pantyukhin <infofarmer@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/xpi-tabletools/Makefile 401096 2015-11-09 12:59:03Z antoine $

PORTNAME=	tabletools
PORTVERSION=	0.2.6
DISTVERSION=	0.27
DISTVERSIONSUFFIX=	-fx
CATEGORIES=	www

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Sort any HTML data table

BROKEN=		unfetchable

XPI_NUM=	2637
XPI_ID=		{7C7F5C11-4ACD-4CDB-9293-2E3F46654E2A}

.include "${.CURDIR}/../xpi-adblock/Makefile.xpi"
.include <bsd.port.mk>
