# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/hs-safe/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	safe
PORTVERSION=	0.3.9
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Library for safe (exception free) functions

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
