# Created by: Bill Swingle <unfurl@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/p5-Compress-LeadingBlankSpaces/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	Compress-LeadingBlankSpaces
PORTVERSION=	0.06
PORTREVISION=	1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Perl class to compress leading blank spaces in web content

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
