# $FreeBSD: tags/RELEASE_10_3_0/www/twiki-TipsContrib/Makefile 362252 2014-07-19 11:09:51Z ohauer $

PORTNAME=	TipsContrib
SVNREV=		16417

COMMENT=	Tip-of-the-day rotating display

TWDEP=	SpreadSheetPlugin>=0

.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
