# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/security/rubygem-ruby-rc4/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	ruby-rc4
PORTVERSION=	0.1.5
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Pure Ruby implementation of the RC4 algorithm

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
