# Created by: Don Croyle <croyle@gelemna.org>
# $FreeBSD: tags/RELEASE_10_3_0/lang/emacs-lisp-intro/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	emacs-lisp-intro
PORTVERSION=	2.04
CATEGORIES=	lang elisp
MASTER_SITES=	GNU/emacs

MAINTAINER=	amakawa@jp.FreeBSD.org
COMMENT=	Introduction to Emacs Lisp programming

GNU_CONFIGURE=	yes
INFO=		emacs-lisp-intro

.include <bsd.port.mk>
