# Created by: Chad Castleberry AKA ritalin
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/rename/Makefile 402160 2015-11-21 14:00:50Z pi $

PORTNAME=	rename
PORTVERSION=	1.3
PORTREVISION=	1
CATEGORIES=	sysutils
MASTER_SITES=	http://rename.sourceforge.net/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Rename multiple files using regular expressions

GNU_CONFIGURE=	yes
USES=		gmake

PLIST_FILES=	bin/${PORTNAME} man/man1/${PORTNAME}.1.gz

.include <bsd.port.mk>
