# Created by: Pawel Pekala <c0rn@o2.pl>
# $FreeBSD: tags/RELEASE_10_3_0/mail/claws-mail-att_remover/Makefile 329440 2013-10-05 11:25:29Z pawel $

PORTNAME=	att_remover
PORTREVISION=	0

COMMENT=	Attachments removing plugin for Claws Mail

CLAWS_PLUGINS_BUILD=	att_remover

.include "../claws-mail/Makefile.claws"
.include <bsd.port.mk>
