# Created by: ichiro@ichiro.org
# $FreeBSD: tags/RELEASE_10_3_0/japanese/gd/Makefile 360810 2014-07-05 19:27:03Z olgeni $

CATEGORIES=	japanese

MAINTAINER=	ichiro@ichiro.org
COMMENT=	Graphics library for fast image creation with Japanese support

MASTERDIR=	${.CURDIR}/../../graphics/gd

CPPFLAGS+=	-DJISX0208

.include "${MASTERDIR}/Makefile"
