# $FreeBSD: tags/RELEASE_10_3_0/devel/geany-plugin-git-changebar/Makefile 395656 2015-08-31 08:57:38Z makc $

PORTNAME=	geany-plugin-git-changebar
PORTVERSION=	${GEANY_VER}
CATEGORIES=	devel

MAINTAINER=	makc@FreeBSD.org
COMMENT=	Geany plugin: ${${GEANY_PLUGIN}_DESC}

LIB_DEPENDS=	libgit2.so:${PORTSDIR}/devel/libgit2

.include "${.CURDIR}/../geany-plugins/files/Makefile.common"
.include <bsd.port.mk>
