# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/x11/libXdamage/Makefile 384234 2015-04-18 15:34:36Z kwm $

PORTNAME=	libXdamage
PORTVERSION=	1.1.4
PORTREVISION=	3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Damage extension library

XORG_CAT=	lib
USE_XORG=	x11 damageproto:both xfixes fixesproto xextproto xproto:both

.include <bsd.port.mk>
