# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/multimedia/gstreamer-plugins-annodex/Makefile 352119 2014-04-25 12:46:45Z bapt $
#    $MCom: ports/multimedia/gstreamer-plugins-annodex/Makefile,v 1.1 2006/07/06 19:48:44 ahze Exp $

PORTREVISION=	1
CATEGORIES=	multimedia

COMMENT=	Gstreamer annodex CMML plugin

GST_PLUGIN=	annodex

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
