# Created by: Lars Thegler <lth@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Test-Object/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Test-Object
PORTVERSION=	0.07
PORTREVISION=	2
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:ADAMK
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Thoroughly testing objects via registered handlers

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
