# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-tgMochiKit/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	tgMochiKit
PORTVERSION=	1.4.2
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	MochiKit packaged as TurboGears widgets

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
