# $FreeBSD: tags/RELEASE_10_3_0/comms/libmodbus/Makefile 368942 2014-09-22 14:28:15Z bsam $

PORTNAME=	libmodbus
PORTVERSION=	3.1.1
PORTREVISION=	1
CATEGORIES=	comms
MASTER_SITES=	http://libmodbus.org/site_media/build/

MAINTAINER=	bsam@FreeBSD.org
COMMENT=	Modbus library

LICENSE=	LGPL21

GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes
USES=		gmake libtool pathfix
INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
