# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/audio/gstreamer-plugins-shout2/Makefile 353022 2014-05-05 14:51:06Z sunpoet $
#   $MCom: ports/audio/gstreamer-plugins-shout2/Makefile,v 1.3 2008/03/19 14:05:31 ahze Exp $

PORTREVISION=	2
CATEGORIES=	audio

COMMENT=	Gstreamer icecast plugin

GST_PLUGIN=	shout2

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
