# Created by: Anders Nordby <anders@fix.no>
# $FreeBSD: tags/RELEASE_10_3_0/net/p5-Net-ParseWhois/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	Net-ParseWhois
PORTVERSION=	0.70
PORTREVISION=	1
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-${PORTVERSION:C/0$//}

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Extendable perl5 module for parsing whois information

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
