# $FreeBSD: tags/RELEASE_10_3_0/sysutils/rubygem-fluent-plugin-config-expander/Makefile 350511 2014-04-07 15:56:51Z bapt $

PORTNAME=	fluent-plugin-config-expander
PORTVERSION=	0.1.3
CATEGORIES=	sysutils rubygems
MASTER_SITES=	RG

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Fluent plugin which provides directives for loop extraction

RUN_DEPENDS=	\
	rubygem-fluentd>0:${PORTSDIR}/sysutils/rubygem-fluentd

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
