# Created by: Tsung-Han Yeh <snowfly@yuntech.edu.tw>
# $FreeBSD: tags/RELEASE_10_3_0/graphics/p5-Image-MetaData-JPEG/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Image-MetaData-JPEG
PORTVERSION=	0.153
PORTREVISION=	1
CATEGORIES=	graphics perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	snowfly@yuntech.edu.tw
COMMENT=	Perl extension for showing/modifying JPEG (meta)data]

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
