# Created by: Oliver Eikemeier <eik@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/mail/exim-sa-exim/Makefile 362543 2014-07-22 14:05:43Z vsevolod $

PKGNAMESUFFIX=	-sa-exim
MASTERDIR=	${.CURDIR}/../exim

PORTVERSION?=	${EXIM_VERSION}+${SA_EXIM_VERSION}

OPTIONS_SLAVE=	SA_EXIM

.include "${MASTERDIR}/Makefile"
