# $FreeBSD: tags/RELEASE_10_3_0/multimedia/gstreamer1-plugins-resindvd/Makefile 397984 2015-09-26 14:36:23Z kwm $

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	Gstreamer resindvd plugin

GST_PLUGIN=	resindvd
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
