# Created by: Steven Kreuzer
# $FreeBSD: tags/RELEASE_10_3_0/security/rubygem-ezcrypto/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	ezcrypto
PORTVERSION=	0.7.2
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Wrapper for the poorly documented OpenSSL ruby library

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
