# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/biology/python-nexus/Makefile 403479 2015-12-11 00:59:39Z wen $

PORTNAME=	python-nexus
PORTVERSION=	1.32
CATEGORIES=	biology python
MASTER_SITES=	CHEESESHOP

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Generic nexus file format reader for python

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
