# $FreeBSD: tags/RELEASE_10_3_0/sysutils/ezjail/Makefile 402477 2015-11-27 07:52:55Z miwi $

PORTNAME=	ezjail
PORTVERSION=	3.4.2
CATEGORIES=	sysutils
MASTER_SITES=	http://erdgeist.org/arts/software/ezjail/

MAINTAINER=	erdgeist@erdgeist.org
COMMENT=	Framework to easily create, manipulate, and run FreeBSD jails

USES=		tar:bzip2

MAKE_ENV=	DESTDIR=${STAGEDIR}

.include <bsd.port.mk>
