# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/rubygem-erubis/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	erubis
PORTVERSION=	2.7.0
PORTREVISION=	1
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Fast, secure, and extensible implementation of eRuby

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/erubis

.include <bsd.port.mk>
