# Created by: Cory R. King <coryking@mozimedia.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Digest-TransformPath/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Digest-TransformPath
PORTVERSION=	1.00
PORTREVISION=	2
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	coryking@mozimedia.com
COMMENT=	Implements the TransformPath concept

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
