# Created by: Thorsten Greiner <thorsten.greiner@web.de>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Lingua-Stem-Snowball-Se/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Lingua-Stem-Snowball-Se
PORTVERSION=	1.2
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:ASKSH
PKGNAMEPREFIX=	p5-
DISTNAME=	Snowball-Swedish-${PORTVERSION}

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Stemmer for Swedish

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
