# Created by: Peter Avalos <pavalos@theshell.com>
# $FreeBSD: tags/RELEASE_10_3_0/www/p5-HTML-Widgets-SelectLayers/Makefile 387008 2015-05-22 10:22:06Z amdmi3 $

PORTNAME=	HTML-Widgets-SelectLayers
PORTVERSION=	0.07
PORTREVISION=	2
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Implements an HTML widget with multiple layers

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5 shebangfix
SHEBANG_FILES=	homepage.pl
USE_PERL5=	configure

.include <bsd.port.mk>
