# Created by: chinsan
# $FreeBSD: tags/RELEASE_10_3_0/misc/p5-Array-FileReader/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Array-FileReader
PORTVERSION=	0.03
PORTREVISION=	2
CATEGORIES=	misc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Lazily tie files to arrays for reading

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
