# Created by: Emanuel Haupt <ehaupt@critical.ch>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Sort-Array/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Sort-Array
DISTVERSION=	0.26
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ehaupt@FreeBSD.org
COMMENT=	Powerful array sorting Perl interface

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
