# Created by: Dennis Herrmann <dhn@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/rubygem-termcolor/Makefile 389366 2015-06-13 13:51:45Z sunpoet $

PORTNAME=	termcolor
PORTVERSION=	1.2.2
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Library for ANSII color formatting like HTML for output in terminal

LICENSE=	MIT

RUN_DEPENDS=	rubygem-highline>=1.5.0:${PORTSDIR}/devel/rubygem-highline

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
