# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/pear-Horde_Text_Filter_Csstidy/Makefile 369674 2014-09-30 22:14:59Z bapt $

PORTNAME=	Horde_Text_Filter_Csstidy
PORTVERSION=	2.0.1
CATEGORIES=	textproc www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Text Filter CSS optimization class

USES=	horde
USE_HORDE_RUN=	Horde_Text_Filter
USE_PHP=	ctype

.include <bsd.port.mk>
