# Created by: Alexander Logvinov <ports@logvinov.com>
# $FreeBSD: tags/RELEASE_10_3_0/graphics/rubygem-railroad/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	railroad
PORTVERSION=	0.5.0
CATEGORIES=	graphics devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Class diagrams generator for Ruby on Rails applications

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/railroad

.include <bsd.port.mk>
