# Created by: Muhammad Moinur Rahman <bofh@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Test-API/Makefile 382907 2015-04-01 12:00:15Z bofh $

PORTNAME=	Test-API
PORTVERSION=	0.005
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:DAGOLDEN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Test a list of subroutines provided by a module

LICENSE=	APACHE20

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
