# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/php56-sysvmsg/Makefile 367268 2014-09-04 14:24:25Z ale $

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-sysvmsg

.include "${MASTERDIR}/Makefile"
