# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/gstreamer-plugins-sdl/Makefile 374303 2014-12-08 16:48:38Z tijl $
#   $MCom: ports/devel/gstreamer-plugins-sdl/Makefile,v 1.5 2008/03/19 14:05:33 ahze Exp $

PORTREVISION=	3
CATEGORIES=	devel

COMMENT=	Gstreamer SDL plugin

GST_PLUGIN=	sdl

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
