# Created by: joerg
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/manck/Makefile 367869 2014-09-10 16:08:51Z antoine $

PORTNAME=	manck
PORTVERSION=	1.2
PORTREVISION=	1
CATEGORIES=	sysutils
MASTER_SITES=	http://wolfram.schneider.org/src/

MAINTAINER=	wosch@FreeBSD.org
COMMENT=	Manual page consistency checker

USES=		perl5 shebangfix uidfix
USE_PERL5=	run
SHEBANG_FILES=	manck.pl

.include <bsd.port.mk>
