# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-repoze.lru/Makefile 373790 2014-12-02 22:40:56Z bapt $

PORTNAME=	repoze.lru
PORTVERSION=	0.6
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Tiny LRU cache implementation and decorator

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
