# Created by: Kirill P. Spitsin <tn@0x746e.org.ua>
# $FreeBSD: tags/RELEASE_10_3_0/www/py-meld3/Makefile 376109 2015-01-03 08:41:20Z mva $

PORTNAME=	meld3
PORTVERSION=	0.6.8
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	tn@0x746e.org.ua
COMMENT=	HTML/XML templating system for Python

USES=		python:2
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
