# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/misc/rubygem-iesd/Makefile 391473 2015-07-06 18:05:37Z sunpoet $

PORTNAME=	iesd
PORTVERSION=	1.2.2
CATEGORIES=	misc rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Modify Extensions, Kextcache and Packages on InstallESD

LICENSE=	BSD2CLAUSE

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/iesd

.include <bsd.port.mk>
