# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/gstreamer-plugins-gnomevfs/Makefile 352119 2014-04-25 12:46:45Z bapt $
#   $MCom: ports/devel/gstreamer-plugins-gnomevfs/Makefile,v 1.6 2008/03/21 04:01:31 ahze Exp $

PORTREVISION=	1
CATEGORIES=	devel

COMMENT=	Gstreamer gnomevfs plugin

GST_PLUGIN=	gnomevfs

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
