# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/misc/py-YABT/Makefile 371289 2014-10-20 17:59:37Z mva $

PORTNAME=	YABT
PORTVERSION=	2.0.2
PORTREVISION=	1
CATEGORIES=	misc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	General Purpose Braille Translation System

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
