# $FreeBSD: tags/RELEASE_10_3_0/security/rubygem-metasploit-payloads/Makefile 387176 2015-05-23 16:32:23Z antoine $

PORTNAME=	metasploit-payloads
PORTVERSION=	0.0.3
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	antoine@FreeBSD.org
COMMENT=	Compiled binaries for Metasploit's Meterpreter

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PORTSCOUT=	ignore:1

.include <bsd.port.mk>
