# Created by: jesusr
# $FreeBSD: tags/RELEASE_10_3_0/net/sipsak/Makefile 382727 2015-03-30 20:56:34Z bapt $

PORTNAME=	sipsak
PORTVERSION=	0.9.6
DISTFILES=	sipsak-0.9.6-1.tar.gz
CATEGORIES=	net
MASTER_SITES=	BERLIOS

MAINTAINER=	jesusr@FreeBSD.org
COMMENT=	Small command line tool for SIP testing

USE_CSTD=	gnu89
GNU_CONFIGURE=	yes

PLIST_FILES=	bin/sipsak \
		man/man1/sipsak.1.gz

.include <bsd.port.mk>
