# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Logfile-Rotate/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Logfile-Rotate
PORTVERSION=	1.04
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module to rotate logfiles

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
