# $FreeBSD: tags/RELEASE_10_3_0/java/openjdk8-jre/Makefile 372338 2014-11-09 05:23:31Z glewis $

PKGNAMESUFFIX=	${JDK_MAJOR_VERSION}-jre

COMMENT=	Java Runtime Environment ${JDK_MAJOR_VERSION}

BUILD_JRE=	yes
MASTERDIR=	${.CURDIR}/../openjdk8

.include "${MASTERDIR}/Makefile"
