# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-devise-async-rails4/Makefile 394133 2015-08-13 17:35:58Z sunpoet $

PKGNAMESUFFIX=	-rails4

RUN_DEPENDS=    rubygem-devise-rails4>=3.2:${PORTSDIR}/devel/rubygem-devise-rails4

MASTERDIR=	${.CURDIR}/../rubygem-devise-async

.include "${MASTERDIR}/Makefile"
