# $FreeBSD: tags/RELEASE_10_3_0/net/libnids-libnet11/Makefile 347607 2014-03-09 14:38:16Z miwi $

PKGNAMESUFFIX=	-libnet11

COMMENT=	Network monitoring library with TCP/IP reassembly using libnet11

MASTERDIR=	${.CURDIR}/../libnids

DESCR=		${.CURDIR}/pkg-descr

WITH_LIBNET11=	yes

CONFLICTS?=	libnids-[0-9]*

DISTINFO_FILE=	${MASTERDIR}/distinfo

.include "${MASTERDIR}/Makefile"
