# $FreeBSD: tags/RELEASE_10_3_0/devel/gitinspector/Makefile 377097 2015-01-15 15:51:37Z rpaulo $

PORTNAME=	gitinspector
PORTVERSION=	0.3.2
CATEGORIES=	devel python
MASTER_SITES=	GOOGLE_CODE
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	rpaulo@FreeBSD.org
COMMENT=	Statistical analysis tool for git repositories

LICENSE=	GPLv3

WRKSRC=		${WRKDIR}/${PORTNAME}-${PORTVERSION}

USES=		zip python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
