# $FreeBSD: tags/RELEASE_10_3_0/audio/festvox-cmu_us_rms_arctic/Makefile 402853 2015-12-02 21:09:41Z pi $

VOICE=	cmu_us_rms_arctic

COMMENT=	CMU US English male voice for festival

MASTERDIR=	${.CURDIR}/../festvox-cmu_us_slt_arctic

.include "${MASTERDIR}/Makefile"
