# Created by: Zane C, Bowers <vvelox@vvelox.net>
# $FreeBSD: tags/RELEASE_10_3_0/net/p5-Net-LDAP-Makepath/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Net-LDAP-Makepath
PORTVERSION=	1.0.1
PORTREVISION=	2
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:VVELOX
PKGNAMEPREFIX=	p5-

MAINTAINER=	vvelox@vvelox.net
COMMENT=	Provides a method for creating paths in LDAP simply

RUN_DEPENDS=	 p5-perl-ldap>=0:${PORTSDIR}/net/p5-perl-ldap

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
