# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/rubygem-net-http-digest_auth/Makefile 391473 2015-07-06 18:05:37Z sunpoet $

PORTNAME=	net-http-digest_auth
PORTVERSION=	1.4
CATEGORIES=	www net rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Implementation of RFC 2617 - Digest Access Authentication

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
