# Created by: milki <milki@rescomp.berkeley.edu>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-edavis10-object_daddy/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	edavis10-object_daddy
PORTVERSION=	0.4.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	milki@FreeBSD.org
COMMENT=	Object Daddy assists in automating testing

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
