# $FreeBSD: tags/RELEASE_10_3_0/www/twiki-MailerContrib/Makefile 362252 2014-07-19 11:09:51Z ohauer $

PORTNAME=	MailerContrib
SVNREV=		17641

COMMENT=	E-mail notification of changes

RUN_DEPENDS=	p5-URI>=1.35:${PORTSDIR}/net/p5-URI

.include "${.CURDIR}/../twiki/bsd.twiki.mk"
.include <bsd.port.mk>
