# Created by: Alexey Dokuchaev <danfe@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/x11-themes/gtk-aluminumalloy-toxic-theme/Makefile 347726 2014-03-10 09:17:29Z danfe $

PORTREVISION=	5

FLAVOR=		toxic

MASTERDIR=	${.CURDIR}/../gtk-aluminumalloy-volcanic-theme

DISTINFO_FILE=	${.CURDIR}/../gtk-aluminumalloy-toxic-theme/distinfo
PLIST=		${.CURDIR}/../gtk-aluminumalloy-toxic-theme/pkg-plist

.include "${MASTERDIR}/Makefile"
