# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-IO-FDPass/Makefile 394928 2015-08-21 07:37:29Z kuriyama $

PORTNAME=	IO-FDPass
PORTVERSION=	1.1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension to pass a file descriptor over a socket

BUILD_DEPENDS=	p5-Canary-Stability>0:${PORTSDIR}/devel/p5-Canary-Stability

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
