# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/py-uliweb/Makefile 402263 2015-11-23 07:32:23Z wen $

PORTNAME=	uliweb
PORTVERSION=	0.4.1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	Uliweb-${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Easy python web framework

LICENSE=	BSD2CLAUSE

USES=		dos2unix python:2
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
