# Created by: Foxfair Hu <foxfair@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/math/p5-Math-Round/Makefile 398531 2015-10-03 17:11:16Z sunpoet $

PORTNAME=	Math-Round
PORTVERSION=	0.07
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Perl extension for rounding numbers

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

NO_ARCH=	yes
USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
