# $FreeBSD: tags/RELEASE_10_3_0/x11/xman/Makefile 399833 2015-10-20 13:42:00Z kwm $

PORTNAME=	xman
PORTVERSION=	1.1.4
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Manual page display program for X

LICENSE=	MIT

XORG_CAT=	app
USE_XORG=	xt xaw xp xprintutil

.include <bsd.port.mk>
