# $FreeBSD: tags/RELEASE_10_3_0/devel/websocketpp/Makefile 385521 2015-05-06 15:16:53Z mat $

PORTNAME=	websocketpp
PORTVERSION=	0.4.0
CATEGORIES=	devel

MAINTAINER=	arved@FreeBSD.org
COMMENT=	Header only implementation of the WebSocket protocol

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

USE_GITHUB=	yes
GH_ACCOUNT=	zaphoyd
USES=		cmake

.include <bsd.port.mk>
