# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/math/R-cran-bdsmatrix/Makefile 367888 2014-09-10 20:50:31Z gerald $

PORTNAME=	bdsmatrix
DISTVERSION=	1.3-2
PORTREVISION=	1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Routines for Block Diagonal Symmetric matrices

LICENSE=	LGPL20

USES=	cran:auto-plist

.include <bsd.port.mk>
