# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/audio/gstreamer-plugins-wavpack/Makefile 374303 2014-12-08 16:48:38Z tijl $
#   $MCom: ports/audio/gstreamer-plugins-wavpack/Makefile,v 1.3 2008/03/19 14:05:33 ahze Exp $

PORTREVISION=	2
CATEGORIES=	audio

GST_PLUGIN=	wavpack

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
