# Created by: Andrey Lykhin <lan31@inbox.ru>
# $FreeBSD: tags/RELEASE_10_3_0/comms/bfhist/Makefile 344548 2014-02-16 12:16:37Z ehaupt $

PORTNAME=	bfhist
PORTVERSION=	0.4
CATEGORIES=	comms
MASTER_SITES=	http://lan31.narod.ru/bfhist/files/ \
		http://lan31.hotbox.ru/bfhist/files/

MAINTAINER=	lan31@inbox.ru
COMMENT=	Statistics generator for BinkleyForce FTN mailer

PLIST_FILES=	bin/bfhist

.include <bsd.port.mk>
