# Created by: TAKAHASHI Kaoru <kaoru@kaisei.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Tie-Array-Pack/Makefile 386075 2015-05-11 12:04:18Z mat $

PORTNAME=	Tie-Array-Pack
PORTVERSION=	0.02
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Array implemented as a packed string

USES=		perl5
USE_PERL5=	configure


.include <bsd.port.mk>
