# $FreeBSD: tags/RELEASE_10_3_0/databases/pear-Horde_Memcache/Makefile 369674 2014-09-30 22:14:59Z bapt $

PORTNAME=	Horde_Memcache
PORTVERSION=	2.0.3
CATEGORIES=	databases www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Memcache API

USES=	horde
USE_PHP=	memcache hash
USE_HORDE_RUN=	Horde_Exception

.include <bsd.port.mk>
