# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: tags/RELEASE_10_3_0/www/rubygem-typhoeus/Makefile 397291 2015-09-18 18:00:39Z sunpoet $

PORTNAME=	typhoeus
PORTVERSION=	0.8.0
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Parallel HTTP request library

LICENSE=	MIT

RUN_DEPENDS=	rubygem-ethon>=0.7.4:${PORTSDIR}/www/rubygem-ethon

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
