# Created by: Will Stacey <will@at.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/mod_authz_unixgroup24/Makefile 371519 2014-10-26 18:17:17Z ohauer $

PORTNAME=	mod_authz_unixgroup
PORTVERSION=	1.1.0
CATEGORIES=	www
MASTER_SITES=	http://mod-auth-external.googlecode.com/files/
DIST_SUBDIR=	apache2

MAINTAINER=	apache@FreeBSD.org
COMMENT=	UNIX group access control module for Apache 2.4

LICENSE=	APACHE20

PORTSCOUT=	limit:^1\.1\.

USE_APACHE=	24
AP_FAST_BUILD=	yes
AP_GENPLIST=	yes
SHORTMODNAME=	authz_unixgroup

.include <bsd.port.mk>
