# Created by: Michael Moll <kvedulv at kvedulv.de>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-byebug/Makefile 402521 2015-11-28 09:29:29Z sunpoet $

PORTNAME=	byebug
PORTVERSION=	8.2.1
CATEGORIES=	devel ruby
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby 2 debugger

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/byebug

.include <bsd.port.mk>
