# Created by: Yen-Ming Lee <leeym@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Test-Debugger/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Test-Debugger
PORTVERSION=	0.14
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	leeym@FreeBSD.org
COMMENT=	Create Test Scripts which Generate Log Files

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
