# Created by: Tom McLaughlin <tmclaugh@sdf.lonestar.org>
# $FreeBSD: tags/RELEASE_10_3_0/ftp/tnftp/Makefile 398731 2015-10-07 00:26:51Z danilo $

PORTNAME=	tnftp
PORTVERSION=	20151004
CATEGORIES=	ftp ipv6
MASTER_SITES=	ftp://ftp.netbsd.org/pub/NetBSD/misc/tnftp/

MAINTAINER=	danilo@FreeBSD.org
COMMENT=	Enhanced ftp client from NetBSD

GNU_CONFIGURE=	yes
USE_OPENSSL=	yes

PLIST_FILES=	bin/tnftp man/man1/tnftp.1.gz

.include <bsd.port.mk>
