# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/rubygem-css_parser/Makefile 397644 2015-09-23 20:13:37Z sunpoet $

PORTNAME=	css_parser
PORTVERSION=	1.3.7
CATEGORIES=	textproc www rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Set of classes for parsing CSS in Ruby

LICENSE=	MIT

RUN_DEPENDS=	rubygem-addressable>=0:${PORTSDIR}/www/rubygem-addressable

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
