# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Lingua-Conjunction/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Lingua-Conjunction
PORTVERSION=	2.00
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Convert Perl lists into linguistic conjunctions

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
