# Created by: Brad Walker <tha_walka@hotmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/audio/rubygem-ruby-mp3info/Makefile 394791 2015-08-19 15:15:02Z sunpoet $

PORTNAME=	ruby-mp3info
PORTVERSION=	0.8
CATEGORIES=	audio rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby library to access information on mp3 files

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
