# $FreeBSD: releng/10.3/libexec/hyperv/Makefile 291819 2015-12-04 19:16:56Z bdrewery $

.PATH:		${.CURDIR}/../../contrib/hyperv/tools/scripts

BINDIR=		${LIBEXECDIR}/hyperv

SCRIPTS=	hv_set_ifconfig hv_get_dns_info hv_get_dhcp_info
NO_OBJ=

.include <bsd.prog.mk>
