# Created by: Dmitry Sivachenko <demon@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Module-Versions-Report/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Module-Versions-Report
PORTVERSION=	1.06
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Report versions of all modules in memory

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
