# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-icalendar/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	icalendar
PORTVERSION=	2.3.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Library for working with iCalendar files

LICENSE=	BSD2CLAUSE GPLv2 RUBY
LICENSE_COMB=	dual

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
