# Created by: Steven Enderle <enderle@mdn.de>
# $FreeBSD: tags/RELEASE_10_3_0/misc/bestfit/Makefile 376401 2015-01-06 09:39:03Z ehaupt $

PORTNAME=	bestfit
PORTVERSION=	0.2.0
CATEGORIES=	misc
MASTER_SITES=	LOCAL/ehaupt

MAINTAINER=	ehaupt@FreeBSD.org
COMMENT=	Optimally choose files to be put on a CD (or other media)

LICENSE=	GPLv2

GNU_CONFIGURE=	yes

PLIST_FILES=	bin/bestfit man/man1/bestfit.1.gz

.include <bsd.port.mk>
