# Created by: Jason Portwood <jason@iac.net>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-OLE-Storage_Lite/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	OLE-Storage_Lite
PORTVERSION=	0.19
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module for OLE document interface

BUILD_DEPENDS=	p5-IO-stringy>=0:${PORTSDIR}/devel/p5-IO-stringy
RUN_DEPENDS:=	${BUILD_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
