# $FreeBSD: tags/RELEASE_10_3_0/databases/py-pypuppetdb/Makefile 388238 2015-06-01 16:15:33Z allanjude $

PORTNAME=	pypuppetdb
PORTVERSION=	0.1.1
DISTVERSIONPREFIX=	v
CATEGORIES=	databases python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	allanjude@FreeBSD.org
COMMENT=	Library to work with PuppetDB's REST API

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes
GH_ACCOUNT=	puppet-community

USES=	python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
