# Created by: will
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-String-RexxParse/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	String-RexxParse
PORTVERSION=	1.10
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Perl module that provides an interface to REXX parsing routines

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
