# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/net/gstreamer-plugins-libmms/Makefile 352119 2014-04-25 12:46:45Z bapt $
#   $MCom: ports/net/gstreamer-plugins-libmms/Makefile,v 1.3 2008/03/19 14:05:38 ahze Exp $

PORTREVISION=	1
CATEGORIES=	net

COMMENT=	Gstreamer mms:// and mmsh:// plugin

GST_PLUGIN=	libmms

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
