# Created by: Pawel Worach
# $FreeBSD: tags/RELEASE_10_3_0/x11-fonts/font-arabic-misc/Makefile 381876 2015-03-21 23:05:19Z bapt $

PORTNAME=	font-arabic-misc
PORTVERSION=	1.0.3
PORTREVISION=	3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org miscellaneous Arabic fonts

XORG_CAT=	font

.include <bsd.port.mk>
