# Created by: Andrew Romero <melanhit@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/xorg-sgml-doctools/Makefile 355336 2014-05-26 13:21:43Z miwi $

PORTNAME=	xorg-sgml-doctools
PORTVERSION=	1.11
CATEGORIES=	textproc x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Stylesheets and entities for X.Org documentation

XORG_CAT=       doc

USES=		pathfix gmake

.include <bsd.port.mk>
