# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/net/py-speedtest-cli/Makefile 404066 2015-12-20 17:12:11Z nivit $

PORTNAME=	speedtest-cli
PORTVERSION=	0.3.4
CATEGORIES=	net python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Command line interface for testing internet bandwidth

LICENSE=	APACHE20

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
