# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Class-Accessor/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Class-Accessor
PORTVERSION=	0.34
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Automated accessor generation

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
