# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-memoizable/Makefile 391473 2015-07-06 18:05:37Z sunpoet $

PORTNAME=	memoizable
PORTVERSION=	0.4.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Memoize method return values

LICENSE=	MIT

RUN_DEPENDS=	rubygem-thread_safe>=0.3.1:${PORTSDIR}/devel/rubygem-thread_safe

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
