# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: tags/RELEASE_10_3_0/mail/rubygem-pony/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	pony
PORTVERSION=	1.11
CATEGORIES=	mail rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Express way to send mail from Ruby

LICENSE=	MIT

RUN_DEPENDS=	rubygem-mail>=2.0:${PORTSDIR}/mail/rubygem-mail

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
