# Created by: Jeremy Chadwick <yoshi@parodius.com>
# $FreeBSD: tags/RELEASE_10_3_0/games/nethack33-nox11/Makefile 359731 2014-06-29 06:39:53Z glewis $

MASTERDIR=	${.CURDIR}/../nethack33

MAINTAINER=	glewis@FreeBSD.org

PKGNAMESUFFIX=	-nox11

.include "${MASTERDIR}/Makefile"
