# Created by: Aaron Dalton <aaron@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/p5-Filesys-Statvfs/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Filesys-Statvfs
PORTVERSION=	0.82
PORTREVISION=	1
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	pirzyk@FreeBSD.org
COMMENT=	Perl extension for statvfs() and fstatvfs()

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
