# Created by: Jun Kuriyama <kuriyama@opt.phys.waseda.ac.jp>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-File-Sync/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	File-Sync
PORTVERSION=	0.11
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl5 module interface to the UNIX sync(2) and POSIX.1b fsync(2)

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
