# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-Horde_Constraint/Makefile 376829 2015-01-12 14:54:44Z mm $

PORTNAME=	Horde_Constraint
PORTVERSION=	2.0.2
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Constraint library

USES=	horde

.include <bsd.port.mk>
