# Created by: Mij <mij@bitchx.it>
# $FreeBSD: tags/RELEASE_10_3_0/security/sshguard-null/Makefile 392923 2015-07-26 15:04:34Z feld $

PKGNAMESUFFIX=	-null

COMMENT=	Protect hosts from brute force attacks against ssh and other services

CONFLICTS=	sshguard-1.* sshguard-ipfilter-1.* sshguard-ipfw-1.* sshguard-pf-1.*

SSHGUARDFW=	null
MASTERDIR=	${.CURDIR}/../sshguard

.include "${MASTERDIR}/Makefile"
