# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/graphics/shared-color-profiles/Makefile 372768 2014-11-19 11:49:04Z kwm $
#   $MCom: ports/trunk/graphics/shared-color-profiles/Makefile 18965 2013-12-20 11:02:42Z kwm $

PORTNAME=	shared-color-profiles
PORTVERSION=	0.1.5
CATEGORIES=	graphics
MASTER_SITES=	http://people.freedesktop.org/~hughsient/releases/

MAINTAINER=	gnome@FreeBSD.org
COMMENT=	Color profiles from contributors for color calibration

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
