# Created by: Jin-Shan Tseng <tjs@cdpa.nsysu.edu.tw>
# $FreeBSD: tags/RELEASE_10_3_0/net/p5-Socket-Multicast6/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Socket-Multicast6
PORTVERSION=	0.04
PORTREVISION=	1
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Constructors and constants for IPv4/IPv6 multicast socket operations

RUN_DEPENDS=	p5-Socket6>=0.19:${PORTSDIR}/net/p5-Socket6

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
