# Created by: Shinsuke Matsui <smatsui@karashi.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-HTML-Entities-ImodePictogram/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	HTML-Entities-ImodePictogram
PORTVERSION=	0.06
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	smatsui@karashi.org
COMMENT=	HTML::Entities::ImodePictogram - encode / decode i-mode pictogram

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
