# $FreeBSD: tags/RELEASE_10_3_0/devel/erlang-pooler/Makefile 399645 2015-10-19 08:38:42Z olgeni $

PORTNAME=	pooler
PORTVERSION=	1.5.0
CATEGORIES=	devel
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	OTP process pool application

LICENSE=	APACHE20

USES=		erlang:rebar
USE_GITHUB=	yes
GH_ACCOUNT=	seth

.include <bsd.port.mk>
