# Created by: joerg
# $FreeBSD: tags/RELEASE_10_3_0/emulators/cpmtools/Makefile 398225 2015-09-30 17:42:52Z amdmi3 $

PORTNAME=	cpmtools
PORTVERSION=	1.1
PORTREVISION=	1
CATEGORIES=	emulators
MASTER_SITES=	LOCAL/joerg
DISTNAME=	cpm-${PORTVERSION}

MAINTAINER=	joerg@FreeBSD.org
COMMENT=	Utility to transfer files from/to CP/M (R) diskettes

WRKSRC=		${WRKDIR}/cpm

CFLAGS+=	-Wno-return-type

.include <bsd.port.mk>
