# $FreeBSD: tags/RELEASE_10_3_0/www/p5-PSGI/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	PSGI
PORTVERSION=	1.102
PORTREVISION=	1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:MIYAGAWA
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Pod documentation for Perl Web Server Gateway Interface Specification

USES=	perl5
USE_PERL5=	configure

.include <bsd.port.mk>
