# Created by: Michael Nottebrock <lofi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/security/pinentry-curses/Makefile 382076 2015-03-24 09:48:40Z makc $

PORTNAME=	pinentry
PORTREVISION=	0

COMMENT=	Curses version of the GnuPG password dialog

PINENTRY_GUI=	curses

MASTERDIR=	${.CURDIR}/../pinentry

.include "${MASTERDIR}/Makefile"
