# $FreeBSD: tags/RELEASE_10_3_0/astro/p5-Astro/Makefile 384893 2015-04-28 11:58:47Z mat $

PORTNAME=	Astro
PORTVERSION=	0.78
CATEGORIES=	astro perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Collection of useful astronomical routines in Perl

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
