# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-UNIVERSAL-require/Makefile 389579 2015-06-14 04:35:08Z kuriyama $

PORTNAME=	UNIVERSAL-require
PORTVERSION=	0.18
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl module to require() from a variable

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	YES

.include <bsd.port.mk>
