# $FreeBSD: tags/RELEASE_10_3_0/x11-drivers/xf86-video-r128/Makefile 399179 2015-10-13 07:45:08Z kwm $

PORTNAME=	xf86-video-r128
PORTVERSION=	6.10.0
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org r128 display driver

USE_GL=		gl
XORG_CAT=	driver
USE_XORG=	glproto xf86driproto xf86miscproto xineramaproto

.include <bsd.port.mk>
