# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/mod_realdoc/Makefile 385665 2015-05-07 20:24:15Z mat $

PORTNAME=	mod_realdoc
PORTVERSION=	20130701
CATEGORIES=	www
MASTER_SITES=	http://freebsd.cs.nctu.edu.tw/~gslin/files/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Apache module to support atomic deploys

AP_FAST_BUILD=	yes
AP_GENPLIST=	yes
GH_ACCOUNT=	etsy
GH_TAGNAME=	4925acc
USE_APACHE=	22+
USE_GITHUB=	yes

.include <bsd.port.mk>
