# Created by: Jin-Shan Tseng <tjs@cdpa.nsysu.edu.tw>
# $FreeBSD: tags/RELEASE_10_3_0/math/p5-Data-Float/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Data-Float
PORTVERSION=	0.012
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:ZEFRAM
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Details of the floating point data type

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
