# Created by: Florent Thoumie <flz@xbsd.org>
# $FreeBSD: tags/RELEASE_10_3_0/security/p5-Crypt-SmbHash/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	Crypt-SmbHash
PORTVERSION=	0.12
PORTREVISION=	1
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Perl module implementing lanman and nt md4 hash functions

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
