# $FreeBSD: tags/RELEASE_10_3_0/vietnamese/Makefile 373618 2014-11-29 14:33:15Z rene $
#

    COMMENT = Vietnamese support

    SUBDIR += aspell
    SUBDIR += hunspell
    SUBDIR += kde4-l10n
    SUBDIR += libreoffice
    SUBDIR += libviet
    SUBDIR += unicode-uhoai
    SUBDIR += urwvn
    SUBDIR += vietunicode-hannom
    SUBDIR += vietunicode-trichlor
    SUBDIR += vietunicode-web1
    SUBDIR += vis2u
    SUBDIR += vn7to8
    SUBDIR += vnconvert
    SUBDIR += vnless
    SUBDIR += vnpstext
    SUBDIR += vnroff
    SUBDIR += x-unikey

.include <bsd.port.subdir.mk>
