# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/mail/php55-imap/Makefile 340722 2014-01-22 17:00:46Z mat $

CATEGORIES=	mail

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-imap

.include "${MASTERDIR}/Makefile"
