# $FreeBSD: tags/RELEASE_10_3_0/x11/gstreamer1-plugins-ximagesrc/Makefile 351947 2014-04-23 14:22:47Z tijl $

PORTREVISION=	0
CATEGORIES=	x11
PKGNAMESUFFIX=	1-plugins-ximagesrc

COMMENT=	Gstreamer X source plugin

GST_PLUGIN=	x
DIST=		good

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
