# Created by: Philip Paeps <philip@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-DateTime-Calendar-Discordian/Makefile 398341 2015-10-01 15:59:07Z sunpoet $

PORTNAME=	DateTime-Calendar-Discordian
PORTVERSION=	1.0
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	philip@FreeBSD.org
COMMENT=	Perl extension for the Discordian Calendar

RUN_DEPENDS=	p5-DateTime>=0:${PORTSDIR}/devel/p5-DateTime \
		p5-DateTime-Locale>=0:${PORTSDIR}/devel/p5-DateTime-Locale \
		p5-Params-Validate>=0:${PORTSDIR}/devel/p5-Params-Validate

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
