# $FreeBSD: tags/RELEASE_10_3_0/x11/x11perf/Makefile 399844 2015-10-20 13:49:18Z kwm $

PORTNAME=	x11perf
PORTVERSION=	1.6.0
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X11 server performance test program

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

XORG_CAT=	app
USE_XORG=	x11 xmuu xrender xft xext
USES=		cpe
CPE_VENDOR=	xfree86

.include <bsd.port.mk>
