# Created by: Dikshie <dikshie@sfc.wide.ad.jp>
# $FreeBSD: tags/RELEASE_10_3_0/www/p5-Mojo-Server-FastCGI/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Mojo-Server-FastCGI
PORTVERSION=	0.41
PORTREVISION=	1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:ARPI
PKGNAMEPREFIX=	p5-

MAINTAINER=	dikshie@sfc.wide.ad.jp
COMMENT=	Mojo Server FastCGI

LICENSE=	ART20

RUN_DEPENDS=	p5-Mojolicious>=3.21:${PORTSDIR}/www/p5-Mojolicious

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
