# $FreeBSD: tags/RELEASE_10_3_0/devel/amd64-xtoolchain-gcc/Makefile 373620 2014-11-29 14:46:30Z bapt $

PKGNAMEPREFIX=	amd64-
PLIST=	${.CURDIR}/pkg-plist

MASTERDIR=	${.CURDIR}/../powerpc64-xtoolchain-gcc

.include "${MASTERDIR}/Makefile"
