# Created by: Joe Horn <joehorn@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/net/p5-Geo-IP-PurePerl/Makefile 401648 2015-11-15 03:02:19Z sunpoet $

PORTNAME=	Geo-IP-PurePerl
PORTVERSION=	1.25
PORTREVISION=	1
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Look up country by IP Address

LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/COPYING

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
