# $FreeBSD: tags/RELEASE_10_3_0/sysutils/phybs/Makefile 401777 2015-11-16 16:39:13Z des $

PORTNAME=	phybs
PORTVERSION=	20140717
CATEGORIES=	sysutils
MASTER_SITES=	LOCAL/des

MAINTAINER=	des@FreeBSD.org
COMMENT=	Disk benchmarking utility

LICENSE=	BSD2CLAUSE

PLIST_FILES=	bin/phybs man/man1/phybs.1.gz

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
