# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-PHP_ArrayOf/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	PHP_ArrayOf
PORTVERSION=	0.2.1
CATEGORIES=	devel www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Abstract class package to create arrays of specific element types

USES=	pear

.include <bsd.port.mk>
