# $FreeBSD: tags/RELEASE_10_3_0/multimedia/gstreamer1-plugins-openh264/Makefile 397984 2015-09-26 14:36:23Z kwm $

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	Gstreamer (openh264) plugin

GST_PLUGIN=	openh264
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
