# Created by: Lars Thegler <lth@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-IO-CaptureOutput/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	IO-CaptureOutput
PORTVERSION=	1.11.02
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-${PORTVERSION:R}${PORTVERSION:E}

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Capture STDOUT/STDERR from subprocesses and XS/C modules

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
