# Created by: Aaron Dalton <aaron@daltons.ca>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Data-Table/Makefile 389484 2015-06-13 20:00:29Z sunpoet $

PORTNAME=	Data-Table
PORTVERSION=	1.72
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Data type related to database tables, HTML table displays, etc

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

NO_ARCH=	yes
USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
