# Created by: Yoichi Asai <yatt@msc.biglobe.ne.jp>
# $FreeBSD: tags/RELEASE_10_3_0/audio/timidity++-gtk/Makefile 356603 2014-06-05 07:31:00Z miwi $

PKGNAMESUFFIX=	-gtk

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Gtk interface for TiMidity++

MASTERDIR=	${.CURDIR}/../../audio/timidity++

PLIST_FILES=	bin/${LINK} ${TIMID_LIBDIR}/if_gtk.so

.include "${MASTERDIR}/Makefile"
