# Created by: Eric Freeman <freebsdports@chillibear.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-deprecated2/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	deprecated
PORTVERSION=	2.0.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	2

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Version 2 of this library intended to aid working with deprecated code

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PORTSCOUT=	limit:^2\.[0-9]*

.include <bsd.port.mk>
