# Created by: Dmitry Sivachenko <demon@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-MARC-Record/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	MARC-Record
PORTVERSION=	2.0.6
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	demon@FreeBSD.org
COMMENT=	The core class for representing a single MARC record

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
