# Created by: Alexandre Biancalana <ale@biancalanas.net>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-String-HexConvert/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	String-HexConvert
PORTVERSION=	0.01
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:AHERNIT
PKGNAMEPREFIX=	p5-

MAINTAINER=	ale@biancalanas.net
COMMENT=	String::HexConver - Converts ascii strings to hex and reverse

WRKSRC=	${WRKDIR}/${PORTNAME}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
