# Created by: Anton Berezin
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-File-CountLines/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	File-CountLines
PORTVERSION=	0.0.3
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-v${PORTVERSION}

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Efficiently count the number of line breaks in a file

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
