# Created by: Yoichi Asai <yatt@msc.biglobe.ne.jp>
# $FreeBSD: tags/RELEASE_10_3_0/audio/timidity++-xskin/Makefile 356603 2014-06-05 07:31:00Z miwi $

PKGNAMESUFFIX=	-xskin

MAINTAINER=	ports@FreeBSD.org
COMMENT=	X11AMP skin interface for TiMidity++

OPTIONS_DEFINE=	DOCS

MASTERDIR=	${.CURDIR}/../../audio/timidity++

.include "${MASTERDIR}/Makefile"
