# $FreeBSD: tags/RELEASE_10_3_0/net/pjsip-extsrtp/Makefile 385557 2015-05-06 20:10:09Z madpilot $

PKGNAMESUFFIX=	-extsrtp

CONFLICTS=	pjsip-[0-9]*

OPTIONS_SLAVE=	EXTSRTP
MASTERDIR=	${.CURDIR}/../pjsip

.include "${MASTERDIR}/Makefile"
