# Created by: Gerrit Beine <gerrit.beine@gmx.de>
# $FreeBSD: tags/RELEASE_10_3_0/mail/squirrelmail-wetteronline-plugin/Makefile 366415 2014-08-28 15:16:49Z adamw $

PORTNAME=	wetteronline
PORTVERSION=	0.1
PORTREVISION=	3
CATEGORIES=	mail www

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Plugin for the weather in Germany

USE_SM_COMPAT=	yes

.include "${.CURDIR}/../squirrelmail/bsd.squirrelmail.mk"
.include <bsd.port.mk>
