# Created by: wenheping <wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/net/pear-URI_Template/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	URI_Template
PORTVERSION=	0.3.3
CATEGORIES=	net pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Parser for URI Templates

USES=	pear

.include <bsd.port.mk>
