# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/R-cran-stringi/Makefile 402262 2015-11-23 07:02:04Z tota $

PORTNAME=	stringi
DISTVERSION=	1.0-1
CATEGORIES=	textproc
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Character String Processing Facilities

LICENSE=	BSD3CLAUSE

LIB_DEPENDS=	libicui18n.so:${PORTSDIR}/devel/icu

USES=	cran:auto-plist pkgconfig:build

.include <bsd.port.mk>
