# $FreeBSD: tags/RELEASE_10_3_0/news/husky-areafix/Makefile 397523 2015-09-21 22:09:08Z bdrewery $

PORTNAME=	husky-areafix

COMMENT=	Husky FTN areafix library

LIB_DEPENDS=	libfidoconfig.so:${PORTSDIR}/news/husky-fidoconf

USE_LDCONFIG=	yes

MASTERDIR=	${.CURDIR}/../husky
COMPONENT_SUBDIR=	areafix

.include "${MASTERDIR}/Makefile"
