# $FreeBSD: releng/10.3/usr.sbin/bsdconfig/startup/include/Makefile 279611 2015-03-05 00:34:33Z dteske $

NO_OBJ=

FILESDIR=	${LIBEXECDIR}/bsdconfig/140.startup/include
FILES=		messages.subr

.include <bsd.prog.mk>
