# Created by: Craig Leres <leres@ee.lbl.gov>
# $FreeBSD: tags/RELEASE_10_3_0/security/create-cert/Makefile 374458 2014-12-10 14:04:23Z feld $

PORTNAME=	create-cert
PORTVERSION=	2.5
CATEGORIES=	security
MASTER_SITES=	ftp://ee.lbl.gov/

MAINTAINER=	leres@ee.lbl.gov
COMMENT=	Create openssl client key and certificates

LICENSE=	BSD3CLAUSE

PLIST_FILES=	sbin/create-cert \
		man/man8/create-cert.8.gz

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
