# Created by: Stas Timokhin <stast@bsdportal.ru>
# $FreeBSD: tags/RELEASE_10_3_0/audio/dumb-allegro/Makefile 394778 2015-08-19 13:29:59Z mat $

OPTIONS_SLAVE=	ALLEGRO
MASTERDIR=	${.CURDIR}/../dumb
PKGNAMESUFFIX=	-allegro

.include "${MASTERDIR}/Makefile"
