# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Class-Loader/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Class-Loader
PORTVERSION=	2.03
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Load modules and create objects on demand

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
