# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/archivers/php56-zlib/Makefile 367268 2014-09-04 14:24:25Z ale $

CATEGORIES=	archivers

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-zlib

.include "${MASTERDIR}/Makefile"
