# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-tilt1/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	tilt
PORTVERSION=	1.4.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	1

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Generic interface to multiple Ruby template engines

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PORTSCOUT=	limit:^1\.

.include <bsd.port.mk>
