# Created by: Cy Schubert <cy@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/zetaback/Makefile 396346 2015-09-07 20:46:17Z amdmi3 $

PORTNAME=	zetaback
PORTVERSION=	1.0.7
CATEGORIES=	sysutils
MASTER_SITES=	http://mirrors.omniti.com/zetaback/

MAINTAINER=	cy@FreeBSD.org
COMMENT=	Zetaback ZFS backup and recovery management system

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		autoreconf perl5
USE_PERL5=	run
GNU_CONFIGURE=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
