# Created by: Neil Booth
# $FreeBSD: tags/RELEASE_10_3_0/security/py-slowaes/Makefile 371453 2014-10-24 16:50:42Z mva $

PORTNAME=	slowaes
DISTVERSION=	0.1a1
PORTREVISION=	1
CATEGORIES=	security python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	kyuupichan@gmail.com
COMMENT=	Implementation of AES in pure Python

LICENSE=	APACHE20

USES=		python:2
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
