# Created by: Ilia Chipitsine <ilia@jane.cgu.chel.su>
# $FreeBSD: tags/RELEASE_10_3_0/converters/p5-Unicode-String/Makefile 381151 2015-03-12 23:00:02Z adamw $

PORTNAME=	Unicode-String
PORTVERSION=	2.09
PORTREVISION=	1
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 modules to handle various Unicode issues

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
