# Created by: Denis Podolskiy <bytestore@yandex.ru>
# $FreeBSD: tags/RELEASE_10_3_0/graphics/libjpeg-turbo/Makefile 388256 2015-06-01 19:13:39Z antoine $

PKGNAMEPREFIX=	lib

COMMENT=	SIMD-accelerated JPEG codec library, provides libTurboJPEG

MASTERDIR=	${.CURDIR:H}/jpeg-turbo
SLAVE_PORT=	yes
OPTIONS_EXCLUDE=DOCS EXAMPLES

.include "${MASTERDIR}/Makefile"
