# Created by: Boris Samorodov <bsam@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/tr-eric6/Makefile 394769 2015-08-19 08:52:05Z bsam $

CATEGORIES=	devel python
I18N_LANG=	tr
PKGNAMEPREFIX=	${I18N_LANG}-

.include "${.CURDIR}/../../devel/eric6/Makefile.inc"
