# Created by: Yuri Victorovich <yuri@rawbw.com>
# $FreeBSD: tags/RELEASE_10_3_0/databases/py-oursql/Makefile 400870 2015-11-05 21:11:50Z pawel $

PORTNAME=	oursql
PORTVERSION=	0.9.3.1
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	yuri@rawbw.com
COMMENT=	MySQL bindings for python

LICENSE=	BSD2CLAUSE

USES=		python
USE_MYSQL=	client
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
