# Created by: SimaMoto,RyoTa <liangtai.s4@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/misc/gimp-help-es/Makefile 344828 2014-02-17 22:36:02Z thierry $

CATEGORIES=	misc graphics spanish

MAINTAINER=	liangtai.s16@gmail.com
COMMENT=	The GIMP User Manual in Spanish

LICENSE=	GFDL

MASTERDIR=	${.CURDIR}/../gimp-help-en

DOCLANG=	es

.include "${MASTERDIR}/Makefile"
