# Created by: Sofian Brabez <sbrabez@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/security/py-PF/Makefile 387528 2015-05-27 00:09:55Z amdmi3 $

PORTNAME=	PF
PORTVERSION=	0.0.8
CATEGORIES=	security python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	sbz@FreeBSD.org
COMMENT=	Pure-Python module for managing OpenBSD Packet Filter

LICENSE=	BSD3CLAUSE

USE_GITHUB=	yes
USES=		python:2
USE_PYTHON=	distutils autoplist

GH_ACCOUNT=	dotpy
GH_PROJECT=	py-${PORTNAME:tl}

SUB_FILES=	pkg-message

.include <bsd.port.mk>
