# Created by: Kevin Lo <kevlo@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Regexp-Subst-Parallel/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Regexp-Subst-Parallel
PORTVERSION=	0.11
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kevlo@FreeBSD.org
COMMENT=	Perform multiple substitutions on a string in parallel

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
