# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/R-cran-R2HTML/Makefile 371935 2014-10-31 20:28:03Z thierry $

PORTNAME=	R2HTML
PORTVERSION=	2.3.1
CATEGORIES=	textproc
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	thierry@FreeBSD.org
COMMENT=	HTML exportation for R objects

LICENSE=	GPLv2

USES=	cran:auto-plist

.include <bsd.port.mk>
