# Created by: Roman Bogorodskiy <novel@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/conky-awesome/Makefile 341879 2014-01-30 19:45:17Z pawel $

PKGNAMESUFFIX=	-awesome

MAINTAINER=	ntarmos@ceid.upatras.gr
COMMENT=	Advanced, highly configurable system monitor (configured for x11-wm/awesome)

MASTERDIR=	${.CURDIR}/../conky
DESCR=		${.CURDIR}/pkg-descr

CONFLICTS=	conky-[0-9]*

OPTIONS_EXCLUDE=	X11
OPTIONS_GROUP=
OPTIONS_DEFAULT=

.include "${MASTERDIR}/Makefile"
