# Created by: Matt Peterson <matt@peterson.org>
# $FreeBSD: tags/RELEASE_10_3_0/x11/deskmenu/Makefile 396866 2015-09-13 22:02:56Z bapt $

PORTNAME=	deskmenu
PORTVERSION=	1.3.0
PORTREVISION=	5
CATEGORIES=	x11
MASTER_SITES=	http://matt.peterson.org/FreeBSD/ports/ \
		http://gd.tuwien.ac.at/opsys/linux/gentoo/distfiles/

MAINTAINER=	matt@peterson.org
COMMENT=	X11 application launcher

BROKEN=		Does not fetch
PLIST_FILES=	bin/deskmenu
USES=		gmake
USE_GNOME=	gtk12
USE_CSTD=	gnu89

.include <bsd.port.mk>
