# Created by: Jim Riggs <ports@christianserving.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/libestr/Makefile 359286 2014-06-25 19:26:47Z amdmi3 $

PORTNAME=	libestr
PORTVERSION=	0.1.9
PORTREVISION=	1
CATEGORIES=	devel
MASTER_SITES=	http://libestr.adiscon.com/files/download/

MAINTAINER=	brd@FreeBSD.org
COMMENT=	Library for some string essentials

USES=		libtool
USE_LDCONFIG=	yes
GNU_CONFIGURE=	yes
CONFIGURE_ARGS=	--prefix="${PREFIX}" \
		--disable-testbench

.include <bsd.port.mk>
