# Created by: Kris Moore <kmoore@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/audio/py3-pylast/Makefile 376731 2015-01-10 23:15:27Z demon $

PORTNAME=	pylast
PORTVERSION=	0.5.11
PORTREVISION=	1
CATEGORIES=	audio python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	kmoore@FreeBSD.org
COMMENT=	Python3 interface to Last.fm

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		python:3
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
