# $FreeBSD: tags/RELEASE_10_3_0/mail/rainloop-community/Makefile 391428 2015-07-06 17:24:09Z pi $

PORTNAME=	rainloop
PKGNAMESUFFIX=	-community

COMMENT=	Modern and interactive webmail - community edition

LICENSE=	AGPLv3

MASTERDIR=	${.CURDIR}/../rainloop
DISTINFO_FILE=	${.CURDIR}/distinfo
PLIST=		${.CURDIR}/pkg-plist

CONFLICTS_INSTALL=	rainloop-[0-9]*

.include "${MASTERDIR}/Makefile"
