# Created by: chinsan
# $FreeBSD: tags/RELEASE_10_3_0/math/p5-Math-NumberCruncher/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Math-NumberCruncher
PORTVERSION=	5.00
PORTREVISION=	2
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Collection of useful math-related functions

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
