# Created by: William Grzybowski <wg@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/py-tmdb3/Makefile 401605 2015-11-14 21:26:48Z wg $

PORTNAME=	tmdb3
PORTVERSION=	0.7.2
CATEGORIES=	www devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	TheMovieDB.org APIv3 interface

USES=		python:2
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
