# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/pear-Horde_Http/Makefile 384516 2015-04-22 19:58:46Z mm $

PORTNAME=	Horde_Http
PORTVERSION=	2.1.5
CATEGORIES=	www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde HTTP libraries

USES=	horde
USE_HORDE_RUN=	Horde_Exception \
		Horde_Support

.include <bsd.port.mk>
