# Created by: David Phillips <david@acz.org>
# $FreeBSD: tags/RELEASE_10_3_0/databases/pydbx/Makefile 371173 2014-10-19 08:50:17Z mva $

PORTNAME=	pydbx
PORTVERSION=	0.14
CATEGORIES=	databases python
MASTER_SITES=	http://david.acz.org/pydbx/ \
		http://ftp.giga.net.tw/OS/FreeBSD/distfiles/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	david@acz.org
COMMENT=	Simple SQL database abstraction layer for Python

USES=		python
USE_PYTHON=	distutils

.include <bsd.port.mk>
