# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/security/rubygem-bcrypt/Makefile 402578 2015-11-29 07:00:31Z sunpoet $

PORTNAME=	bcrypt
PORTVERSION=	3.1.10
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	OpenBSD bcrypt password hashing algorithm

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
