# Created by: Thierry Thomas (<thierry@pompo.net>)
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/pear-File/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	File
PORTVERSION=	1.4.1
PORTEPOCH=	2
CATEGORIES=	sysutils www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PEAR common file and directory routines

USES=		pear
USE_PHP=	pcre

.include <bsd.port.mk>
