# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/net/pear-Horde_Scribe/Makefile 369674 2014-09-30 22:14:59Z bapt $

PORTNAME=	Horde_Scribe
PORTVERSION=	2.0.1
CATEGORIES=	net www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Scribe client

USES=	horde
USE_HORDE_RUN=	Horde_Thrift

.include <bsd.port.mk>
