# $FreeBSD: tags/RELEASE_10_3_0/devel/cmake-modules-webos/Makefile 385521 2015-05-06 15:16:53Z mat $

PORTNAME=	cmake-modules-webos
DISTVERSION=	1.0b
CATEGORIES=	devel

MAINTAINER=	penzin.dev@gmail.com
COMMENT=	CMake modules needed to build WebOS components

LICENSE=	APACHE20

USE_GITHUB=	yes
GH_ACCOUNT=	FreeWebOS
GH_TAGNAME=	submissions/19

USES=		cmake:outsource
INSTALL_TARGET=	install

.include <bsd.port.mk>
