# Created by: Yarema <yds@CoolRat.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/sysconftool/Makefile 390231 2015-06-21 14:07:03Z bapt $

PORTNAME=	sysconftool
PORTVERSION=	0.17
CATEGORIES=	devel
MASTER_SITES=	SF/courier/${PORTNAME}/${PORTVERSION}

MAINTAINER=	garga@FreeBSD.org
COMMENT=	Helps to install application configuration files

LICENSE=	GPLv3

USES=		autoreconf perl5 tar:bzip2
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
