# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/x11/libXxf86dga/Makefile 384234 2015-04-18 15:34:36Z kwm $

PORTNAME=	libXxf86dga
PORTVERSION=	1.1.4
PORTREVISION=	3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X DGA Extension

LICENSE=	MIT

XORG_CAT=	lib
USE_XORG=	xproto x11 xextproto xext xf86dgaproto:both
USES+=	cpe
CPE_PRODUCT=	libxxf86dga
CPE_VENDOR=	x

.include <bsd.port.mk>
