# Created by: stas
# $FreeBSD: tags/RELEASE_10_3_0/devel/boehm-gc-threaded/Makefile 369894 2014-10-03 12:52:34Z tijl $

PORTREVISION=	1

COMMENT=	Garbage collection and memory leak detection for C and C++ with threading support

LICENSE=	MIT

MASTERDIR=	${.CURDIR}/../boehm-gc
DESCR=		${.CURDIR}/pkg-descr

GC_VARIANT=	threaded

.include "${MASTERDIR}/Makefile"
