# Created by: Steven Kreuzer <skreuzer@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/R-cran-chron/Makefile 367888 2014-09-10 20:50:31Z gerald $

PORTNAME=	chron
DISTVERSION=	2.3-43
PORTREVISION=	7
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	R package for creating objects which can handle dates and times

LICENSE=	GPLv2

USES=	cran:auto-plist

.include <bsd.port.mk>
