# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-ruby-fogbugz/Makefile 402303 2015-11-23 18:28:03Z sunpoet $

PORTNAME=	ruby-fogbugz
PORTVERSION=	0.2.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@michael-fausten.de
COMMENT=	Simple Ruby wrapper for the Fogbugz XML API

LICENSE=	MIT

RUN_DEPENDS=	rubygem-crack>=0.4:${PORTSDIR}/devel/rubygem-crack

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
