# Created by: Palle Girgensohn <girgen@pingpong.net>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Cache-Simple-TimedExpiry/Makefile 375378 2014-12-24 00:14:11Z bofh $

PORTNAME=	Cache-Simple-TimedExpiry
PORTVERSION=	0.27
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Lightweight cache with timed expiration

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
