# Created by: Kubilay Kocak <koobs@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/py-django-mezzanine-filebrowser/Makefile 378712 2015-02-09 04:19:14Z koobs $

PORTNAME=	django-mezzanine-filebrowser
PORTVERSION=	0.3.5
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	filebrowser_safe-${PORTVERSION}

MAINTAINER=	koobs@FreeBSD.org
COMMENT=	Fork of django-filebrowser for Mezzanine CMS

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		gettext python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
