# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-XML-DoubleEncodedEntities/Makefile 382006 2015-03-23 14:29:10Z sunpoet $

PORTNAME=	XML-DoubleEncodedEntities
PORTVERSION=	1.1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Unbreak XML with Doubly-Encoded Entities

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
