# $FreeBSD: tags/RELEASE_10_3_0/net/p5-Geo-IPfree/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Geo-IPfree
PORTVERSION=	1.131650
PORTREVISION=	1
CATEGORIES=	net perl5 geography
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Look up country from an IP Address

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
