# Created by: David O'Brien <obrien@cs.ucdavis.edu>
# $FreeBSD: tags/RELEASE_10_3_0/print/mp-a4/Makefile 363130 2014-07-28 11:05:17Z marino $

PAPERSIZE=	a4
MASTERDIR=	${.CURDIR}/../mp-letter

.include "${MASTERDIR}/Makefile"
