# Created by: Anes Mukhametov <anes@anes.su>
# $FreeBSD: tags/RELEASE_10_3_0/net/p5-Net-CIDR-Set/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Net-CIDR-Set
PORTVERSION=	0.13
PORTREVISION=	1
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	anes@anes.su
COMMENT=	Manipulate sets of IP addresses

LICENSE=	GPLv2 ART20
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
