# Created by: Jose Alonso Cardenas Marquez <acm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/emulators/mupen64plus-video-rice/Makefile 389666 2015-06-15 03:27:50Z acm $

PORTREVISION=	0
PKGNAMESUFFIX=	-video-rice

COMMENT=	The rice graphics plugin for Mupen64plus

USE_GL=		yes

MASTERDIR=	${.CURDIR}/../mupen64plus-core

OPTIONS_DEFINE=	#

.include "${MASTERDIR}/Makefile"
