# Created by: Oleg Mamontov <oleg@mamontov.net>
# $FreeBSD: tags/RELEASE_10_3_0/www/p5-WWW-Mechanize-Meta/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	WWW-Mechanize-Meta
PORTVERSION=	0.07
PORTREVISION=	1
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	oleg@mamontov.net
COMMENT=	Adds HEAD tag parsing to WWW::Mechanize

RUN_DEPENDS=	p5-WWW-Mechanize>=1.20:${PORTSDIR}/www/p5-WWW-Mechanize
BUILD_DEPENDS:=	${RUN_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
