# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: tags/RELEASE_10_3_0/math/p5-Statistics-LTU/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Statistics-LTU
PORTVERSION=	2.8
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl implementation of Linear Threshold Units

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
