# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/security/pear-Horde_Secret/Makefile 399990 2015-10-22 16:00:30Z mm $

PORTNAME=	Horde_Secret
PORTVERSION=	2.0.5
CATEGORIES=	security www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Secret Encryption API

USES=	horde
USE_HORDE_RUN=	Horde_Crypt_Blowfish \
		Horde_Exception \
		Horde_Support

USE_PHP=	hash

.include <bsd.port.mk>
