# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-Horde_Date_Parser/Makefile 385085 2015-05-01 07:11:54Z mm $

PORTNAME=	Horde_Date_Parser
PORTVERSION=	2.0.4
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Date Parser

USES=	horde
USE_HORDE_RUN=	Horde_Date \
		Horde_Support

.include <bsd.port.mk>
