# Created by: Yen-Ming Lee <leeym@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-IPC-Shareable/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	IPC-Shareable
PORTVERSION=	0.61
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	leeym@FreeBSD.org
COMMENT=	Share Perl variables between processes

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
