# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/pear-Services_W3C_HTMLValidator/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Services_W3C_HTMLValidator
PORTVERSION=	1.0.0
PORTEPOCH=	1
CATEGORIES=	www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Object Oriented Interface to the W3C HTML Validator service

BUILD_DEPENDS=	${PEARDIR}/HTTP/Request2.php:${PORTSDIR}/www/pear-HTTP_Request2
RUN_DEPENDS=	${PEARDIR}/HTTP/Request2.php:${PORTSDIR}/www/pear-HTTP_Request2

USES=		pear

.include <bsd.port.mk>
