# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Text-vFile-asData/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Text-vFile-asData
PORTVERSION=	0.08
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Parse vFile formatted files into data structures

RUN_DEPENDS=	p5-Class-Accessor-Chained>0:${PORTSDIR}/devel/p5-Class-Accessor-Chained
BUILD_DEPENDS:=	${RUN_DEPENDS}

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
