# Created by: Neil Darlow <neil@darlow.co.uk>
# $FreeBSD: tags/RELEASE_10_3_0/mail/squirrelmail-password_forget-plugin/Makefile 366415 2014-08-28 15:16:49Z adamw $

PORTNAME=	password_forget
PORTVERSION=	2.2
PORTREVISION=	2
CATEGORIES=	mail www
DISTNAME=	${SQUIRREL_PLUGIN_NAME}-${PORTVERSION}-1.0.1

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Prevent reuse of login details by browsers at public terminals

USE_SM_COMPAT=	yes

.include "${.CURDIR}/../squirrelmail/bsd.squirrelmail.mk"
.include <bsd.port.mk>
