# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-Date_Holidays_Austria/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Date_Holidays_Austria
PORTVERSION=	0.1.6
CATEGORIES=	devel www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Driver based class to calculate holidays in Austria

LICENSE=	PHP301

BUILD_DEPENDS=	${PEARDIR}/Date/Holidays.php:${PORTSDIR}/devel/pear-Date_Holidays
RUN_DEPENDS=	${PEARDIR}/Date/Holidays.php:${PORTSDIR}/devel/pear-Date_Holidays

USES=		pear
NO_ARCH=	yes

.include <bsd.port.mk>
