# Created by: james@cs.uwm.edu
# $FreeBSD: tags/RELEASE_10_3_0/multimedia/spigot/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	spigot
PORTVERSION=	1.7
CATEGORIES=	multimedia
MASTER_SITES=	LOCAL/fenner
DISTFILES=	${PORTNAME}.${PORTVERSION}${EXTRACT_SUFX}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Video spigot for Windows library

# binary package
NO_BUILD=	yes
NO_WRKSUBDIR=	yes
ONLY_FOR_ARCHS=	i386

.include <bsd.port.mk>
