# Created by: Andrey Polyakov <andrey.polyakov@unix.net>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-ydbf/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	ydbf
PORTVERSION=	0.0.1
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP/source/Y/YDbf/
DISTNAME=	YDbf-0.0.1dev-20080514

MAINTAINER=	andrey.polyakov@unix.net
COMMENT=	Yelded DBF reader/writer for Python

LICENSE=	GPLv2

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
