# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-grizzled/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	grizzled
PORTVERSION=	0.9.4
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	The Grizzled Python Utility Library

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
