# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/hs-MemoTrie/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	MemoTrie
PORTVERSION=	0.6.2
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Trie-based memo functions

LICENSE=	BSD3CLAUSE

USE_CABAL=	void

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
