# Created by: Gabor Kovesdan
# $FreeBSD: tags/RELEASE_10_3_0/security/p5-Crypt-Enigma/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Crypt-Enigma
PORTVERSION=	1.4
PORTREVISION=	1
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Perl extension for the Enigma cipher

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
