# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-blockenspiel/Makefile 387109 2015-05-23 07:14:54Z sunpoet $

PORTNAME=	blockenspiel
PORTVERSION=	0.4.5
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Library designed to make it easy to implement DSL blocks in Ruby

LICENSE=	BSD3CLAUSE

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
