# Created by: clsung@dragon2.net
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Class-ParmList/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Class-ParmList
PORTVERSION=	1.05
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Module for processing named parameter lists for method calls

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
