# $FreeBSD: tags/RELEASE_10_3_0/dns/pear-Horde_Idna/Makefile 385085 2015-05-01 07:11:54Z mm $
PORTNAME=	Horde_Idna
PORTVERSION=	1.0.3
CATEGORIES=	dns www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde IDNA backend normalization package

USES=	horde
USE_PHP=	dom

USE_HORDE_RUN=	Horde_Exception

.include <bsd.port.mk>
