# Created by: Ulrich Spoerlein <uspoerlein@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-stream/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	stream
PORTVERSION=	0.5
PORTREVISION=	2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Interface for external iterators

LICENSE=	BSD2CLAUSE RUBY
LICENSE_COMB=	dual

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
