# Created by: Jean-Yves Lefort <jylefort@brutele.be>
# $FreeBSD: tags/RELEASE_10_3_0/games/xpilot-ng-client/Makefile 374303 2014-12-08 16:48:38Z tijl $

PORTREVISION=	4
PKGNAMESUFFIX=	-client

COMMENT=	Enhanced version of XPilot (client program)

MASTERDIR=	${.CURDIR}/../xpilot-ng-server

.include "${MASTERDIR}/Makefile"
