# Created by: Koichiro IWAO <meta+ports@vmeta.jp>
# $FreeBSD: tags/RELEASE_10_3_0/japanese/uim-mozc/Makefile 396515 2015-09-09 14:58:07Z hrs $

PKGNAMEPREFIX=	ja-uim-

COMMENT=	Mozc engine for uim

MASTERDIR=	${.CURDIR}/../../japanese/mozc-server
FILESDIR=	${.CURDIR}/files
DATADIR=	${PREFIX}/share/uim
SUB_FILES=	pkg-message
PKGMESSAGE=	${WRKDIR}/pkg-message

BUILD_MOZC_LIST=uim_mozc

.include "${MASTERDIR}/Makefile"
