# Created by: Sylvio Cesar <sylvio@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-PEAR_PackageFileManager_Plugins/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	PEAR_PackageFileManager_Plugins
PORTVERSION=	1.0.2
CATEGORIES=	devel www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	The plugins for PEAR_PackageFileManager

BUILD_DEPENDS=	${PEARDIR}/XML/Serializer.php:${PORTSDIR}/devel/pear-XML_Serializer
RUN_DEPENDS=	${PEARDIR}/XML/Serializer.php:${PORTSDIR}/devel/pear-XML_Serializer

LICENSE=	BSD2CLAUSE

USES=	pear

.include <bsd.port.mk>
