# Created by: Gerrit Beine <gerrit.beine@gmx.de>
# $FreeBSD: tags/RELEASE_10_3_0/mail/squirrelmail-qmailadmin_login-plugin/Makefile 366415 2014-08-28 15:16:49Z adamw $

PORTNAME=	qmailadmin_login
PORTVERSION=	1.1
PORTREVISION=	4
CATEGORIES=	mail www
DISTNAME=	${PORTNAME}-${PORTVERSION}-1.4.3

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Using the QmailAdmin cgi interface from SquirrelMail

RUN_DEPENDS=	${PREFIX}/www/cgi-bin.default/qmailadmin/qmailadmin:${PORTSDIR}/mail/qmailadmin

USE_GENERIC_PKGMESSAGE=	yes

.include "${.CURDIR}/../squirrelmail/bsd.squirrelmail.mk"
.include <bsd.port.mk>
