# Created by: ijliao
# $FreeBSD: tags/RELEASE_10_3_0/devel/inilib/Makefile 367307 2014-09-04 19:26:24Z antoine $

PORTNAME=	inilib
PORTVERSION=	1.0.7b3
CATEGORIES=	devel
MASTER_SITES=	SF/${PORTNAME}/${PORTNAME}/1.0.7

MAINTAINER=	ports@FreeBSD.org
COMMENT=	C++ lib which provides a method of saving the "state" of a program

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
