# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-constant-defer/Makefile 384782 2015-04-26 12:28:06Z sunpoet $

PORTNAME=	constant-defer
PORTVERSION=	6
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Constant subs with deferred value calculation

LICENSE=	GPLv3

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
