# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/science/R-cran-bayesm/Makefile 367888 2014-09-10 20:50:31Z gerald $

PORTNAME=	bayesm
PORTVERSION=	2.2.5
PORTREVISION=	2
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${PORTVERSION:C/\./-/g:C/-/./1}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Bayesian Inference for Marketing/Micro-econometrics

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USES=		cran:auto-plist

.include <bsd.port.mk>
