# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/net/py-simplesoap/Makefile 395888 2015-09-02 17:04:27Z sunpoet $

PORTNAME=	simplesoap
PORTVERSION=	1.10
PORTREVISION=	1
CATEGORIES=	net www python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Python Simple SOAP Library

LICENSE=	LGPL3

NO_ARCH=	yes
USE_PYTHON=	autoplist concurrent distutils
USES=		python

GH_ACCOUNT=	py${PORTNAME}
GH_PROJECT=	py${PORTNAME}
USE_GITHUB=	yes

.include <bsd.port.mk>
