# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/audio/gstreamer-plugins-sidplay/Makefile 352119 2014-04-25 12:46:45Z bapt $
#   $MCom: ports/audio/gstreamer-plugins-sidplay/Makefile,v 1.5 2008/03/19 14:05:31 ahze Exp $

PORTREVISION=	1
CATEGORIES=	audio

COMMENT=	Gstreamer Commodore SID decoder plugin

GST_PLUGIN=	sidplay

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
