# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Sys-Sig/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Sys-Sig
PORTVERSION=	0.05
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Return signal constants for this host

LICENSE=	GPLv2

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
