# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Devel-SmallProf/Makefile 381151 2015-03-12 23:00:02Z adamw $

PORTNAME=	Devel-SmallProf
PORTVERSION=	2.02
PORTREVISION=	2
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Per-line Perl profiler

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
