# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/net/pear-Horde_Ldap/Makefile 373688 2014-11-30 20:50:59Z mm $

PORTNAME=	Horde_Ldap
PORTVERSION=	2.2.0
CATEGORIES=	net www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde LDAP libraries

USES=	horde
USE_PHP=	ldap
USE_HORDE_RUN=	Horde_Exception \
		Horde_Util

.include <bsd.port.mk>
