# Created by: chinsan <chinsan.tw@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/p5-BSD-Sysctl/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	BSD-Sysctl
PORTVERSION=	0.11
PORTREVISION=	1
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	david@landgren.net
COMMENT=	Fetch sysctl values from BSD-like systems

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
