# $FreeBSD: tags/RELEASE_10_3_0/devel/py-collective.monkeypatcher/Makefile 405764 2016-01-11 05:23:46Z rm $

PORTNAME=	collective.monkeypatcher
PORTVERSION=	1.1.1
CATEGORIES=	devel python zope
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=	zope

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Applying monkey patches on startup using ZCML configuration

LICENSE=	ZPL21

USES=		python zip
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
