# Created by: Naram Qashat <cyberbotx@cyberbotx.com>
# $FreeBSD: tags/RELEASE_10_3_0/graphics/libspiro/Makefile 391480 2015-07-06 21:20:56Z amdmi3 $

PORTNAME=	libspiro
DISTVERSION=	0.5.20150702
PORTEPOCH=	1
CATEGORIES=	graphics

MAINTAINER=	cyberbotx@cyberbotx.com
COMMENT=	Library to convert clothoid splines into Bezier splines

LICENSE=	GPLv3 # or later
LICENSE_FILE=	${WRKSRC}/COPYING

USE_GITHUB=	yes
GH_ACCOUNT=	fontforge

USES=		gmake libtool autoreconf
GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes
INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
