# $FreeBSD: tags/RELEASE_10_3_0/print/indexinfo/Makefile 399977 2015-10-22 13:36:58Z bapt $

PORTNAME=	indexinfo
PORTVERSION=	0.2.4
CATEGORIES=	print ports-mgmt

MAINTAINER=	bapt@FreeBSD.org
COMMENT=	Utility to regenerate the GNU info page index

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/COPYING

USE_GITHUB=	yes
GH_ACCOUNT=	bapt
INSTALL_TARGET=	install-strip
PLIST_FILES=	bin/indexinfo

.include <bsd.port.mk>
