# Created by: Christoph Kick
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-ffi/Makefile 391101 2015-07-01 17:46:36Z sunpoet $

PORTNAME=	ffi
PORTVERSION=	1.9.10
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Extension for dynamic libraries & binding functions

LICENSE=	BSD3CLAUSE

LIB_DEPENDS=	libffi.so:${PORTSDIR}/devel/libffi

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
