# Created by: Li-Wen Hsu <lwhsu@lwhsu.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/py-httplib2/Makefile 390510 2015-06-24 18:03:05Z sunpoet $

PORTNAME=	httplib2
PORTVERSION=	0.9.1
DISTVERSIONPREFIX=	v
CATEGORIES=	www python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	lwhsu@FreeBSD.org
COMMENT=	Comprehensive HTTP client library

LICENSE=	MIT

NO_ARCH=	yes
USE_PYTHON=	autoplist distutils
USES=		python

USE_GITHUB=	yes
GH_ACCOUNT=	jcgregorio

.include <bsd.port.mk>
