# $FreeBSD: tags/RELEASE_10_3_0/devel/elixir-combine/Makefile 402789 2015-12-01 21:32:12Z olgeni $

PORTNAME=	combine
PORTVERSION=	0.6.0
CATEGORIES=	devel
PKGNAMEPREFIX=	elixir-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Parser combinator library for Elixir

LICENSE=	MIT

USES=		elixir
USE_GITHUB=	yes
GH_ACCOUNT=	bitwalker

MIX_REWRITE=	yes

.include <bsd.port.mk>
