# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-String-Strip/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	String-Strip
PORTVERSION=	1.02
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl extension for fast, commonly used, string operations

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
