# Created by: ntarmos@ceid.upatras.gr
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/battmond/Makefile 362126 2014-07-17 08:57:51Z olgeni $

PORTNAME=	battmond
PORTVERSION=	0.3
CATEGORIES=	sysutils
MASTER_SITES=	http://ntarmos.dyndns.org/Software/FreeBSD/

MAINTAINER=	ntarmos@cs.uoi.gr
COMMENT=	Daemon monitoring the battery level of ACPI-enabled laptops

PLIST_FILES=	sbin/battmond \
		etc/rc.d/battmond \
		man/man1/battmond.1.gz

.include <bsd.port.mk>
