# Created by: Andrey Chernov <ache@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Cache-LRU/Makefile 399786 2015-10-19 20:22:42Z sunpoet $

PORTNAME=	Cache-LRU
PORTVERSION=	0.04
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:KAZUHO
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Simple, fast implementation of an in-memory LRU cache

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-Test-Requires>=0:${PORTSDIR}/devel/p5-Test-Requires

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
