# Created by: ijliao
# $FreeBSD: tags/RELEASE_10_3_0/misc/py-pexpect/Makefile 371289 2014-10-20 17:59:37Z mva $

PORTNAME=	pexpect
PORTVERSION=	3.3
CATEGORIES=	misc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Pure Python Expect-like module

LICENSE=	ISCL

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
