# Created by: Mike Meyer <mwm@mired.org>
# $FreeBSD: tags/RELEASE_10_3_0/x11-toolkits/py-xlib/Makefile 371203 2014-10-19 18:16:15Z mva $

PORTNAME=	xlib
PORTVERSION=	0.14
PORTREVISION=	1
CATEGORIES=	x11-toolkits python
MASTER_SITES=	SF/python-${PORTNAME}/python-${PORTNAME}/${PORTVERSION}
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	python-xlib-${PORTVERSION}

MAINTAINER=	mwm@mired.org
COMMENT=	X11 library for Python

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
