# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/multimedia/gstreamer-plugins-dvd/Makefile 374303 2014-12-08 16:48:38Z tijl $
#   $MCom: ports/multimedia/gstreamer-plugins-dvd/Makefile,v 1.7 2008/03/19 14:05:36 ahze Exp $

PORTREVISION=	4
CATEGORIES=	multimedia

COMMENT=	Gstreamer dvd plugin set

GST_PLUGIN=	dvd

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
