# Created by: Johannes Meixner <xmj@chaot.net>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-tapi/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	tapi
PORTVERSION=	0.1.7
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	Tapi-${PORTVERSION}

MAINTAINER=	xmj@chaot.net
COMMENT=	Framework for testing APIs

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
