# $FreeBSD: tags/RELEASE_10_3_0/russian/stardict-mueller7/Makefile 353800 2014-05-12 10:53:41Z makc $

PORTNAME=	stardict-mueller7
PORTVERSION=	2.4.2
CATEGORIES=	russian
MASTER_SITES=	http://abloz.com/huzheng/stardict-dic/ru/

MAINTAINER=	makc@FreeBSD.org
COMMENT=	Mueller English-Russian dictionary

USES=		tar:bzip2

.include "${.CURDIR}/../stardict-mueller7/files/Makefile.common"
.include <bsd.port.mk>
