# $FreeBSD: tags/RELEASE_10_3_0/security/rubygem-bcrypt-ruby/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	bcrypt-ruby
PORTVERSION=	3.1.5
PORTREVISION=	1
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Sophisticated and secure hash algorithm for passwords

LICENSE=	MIT

RUN_DEPENDS=	rubygem-bcrypt>=3.1.3:${PORTSDIR}/security/rubygem-bcrypt

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
