# $FreeBSD: tags/RELEASE_10_3_0/devel/py-termstyle/Makefile 401509 2015-11-13 13:07:59Z wg $

PORTNAME=	termstyle
PORTVERSION=	0.1.10
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	python-${PORTNAME}-${PORTVERSION}

MAINTAINER=	wg@FreeBSD.org
COMMENT=	Dirt-simple terminal-colour library for python

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
