# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/py-zope.i18nmessageid/Makefile 374183 2014-12-07 10:01:36Z mva $

PORTNAME=	zope.i18nmessageid
PORTVERSION=	3.6.1
PORTREVISION=	1
CATEGORIES=	textproc www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=	zope

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Message Identifiers for internationalization

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
