# $FreeBSD: tags/RELEASE_10_3_0/archivers/rubygem-archive-tar-minitar/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	archive-tar-minitar
PORTVERSION=	0.5.2
CATEGORIES=	archivers rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Library and command-line utility for tar archives

LICENSE=	GPLv2 GPLv3 RUBY
LICENSE_COMB=	dual

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/minitar

.include <bsd.port.mk>
