# $FreeBSD: tags/RELEASE_10_3_0/databases/qt5-sqldrivers-sqlite3/Makefile 372179 2014-11-05 09:39:21Z rakuco $

PORTNAME=	sqlite3

DB=		SQLite
DB_DESC=	SQLite 3

USE_SQLITE=	3
CONFIGURE_ARGS=	-system-sqlite

.include "${.CURDIR:H:H}/devel/qt5/Makefile.sqldrivers"
