# $FreeBSD: tags/RELEASE_10_3_0/editors/calligra-l10n-ca_valencia/Makefile 404140 2015-12-21 18:10:32Z rakuco $

PORTNAME=	calligra-l10n
PORTVERSION=	${CALLIGRA_VERSION}
CATEGORIES=	editors kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Valencian (southern Catalan) messages and documentation for Calligra

CALLIGRA_L10N=	ca@valencia

.include "${.CURDIR}/../../editors/calligra-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
