# Created by: Johannes Meixner <xmj@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-rails-deprecated_sanitizer/Makefile 389419 2015-06-13 13:56:07Z sunpoet $

PORTNAME=	rails-deprecated_sanitizer
PORTVERSION=	1.0.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Deprecated sanitizer API extracted from Action View

LICENSE=	MIT

RUN_DEPENDS=	rubygem-activesupport4>=4.2.1:${PORTSDIR}/devel/rubygem-activesupport4

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
