# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Date-EzDate/Makefile 376289 2015-01-05 09:50:57Z tobez $

PORTNAME=	Date-EzDate
PORTVERSION=	1.16
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Date and time manipulation made easy

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
