# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Data-Capture/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Data-Capture
PORTVERSION=	0.27
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
#MASTER_SITE_SUBDIR=	CPAN:CLKAO
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl6 Capture objects

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
