# $FreeBSD: tags/RELEASE_10_3_0/devel/qca-qt5/Makefile 400930 2015-11-06 12:56:36Z makc $

PKGNAMESUFFIX=	-qt5

COMMENT=	Cross-platform crypto API for Qt 5

PLIST=		${PKGDIR}/pkg-plist.qt5

MASTERDIR=	${.CURDIR}/../qca
.include "${MASTERDIR}/Makefile"
