# $FreeBSD: tags/RELEASE_10_3_0/www/py-plonetheme.classic/Makefile 405764 2016-01-11 05:23:46Z rm $

PORTNAME=	plonetheme.classic
PORTVERSION=	1.3.3
CATEGORIES=	www python zope
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=	zope

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Classic Plone 3 default theme

LICENSE=	GPLv2

NO_ARCH=	yes
USES=		python zip
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
