# $FreeBSD: tags/RELEASE_10_3_0/ukrainian/Makefile 341681 2014-01-29 07:10:12Z bapt $
#

    COMMENT = Ukrainian support

    SUBDIR += aspell
    SUBDIR += calligra-l10n
    SUBDIR += emacs-koi8u
    SUBDIR += gd
    SUBDIR += hunspell
    SUBDIR += hyphen
    SUBDIR += kde4-l10n
    SUBDIR += libreoffice
    SUBDIR += monacofonts
    SUBDIR += mythes
    SUBDIR += webalizer

.include <bsd.port.subdir.mk>
