# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/pear-Horde_Template/Makefile 376829 2015-01-12 14:54:44Z mm $

PORTNAME=	Horde_Template
PORTVERSION=	2.0.2
CATEGORIES=	www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Template System

USES=	horde

.include <bsd.port.mk>
