# Created by: marius@alchemy.franken.de
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/gcdmaster/Makefile 375280 2014-12-22 22:39:18Z bapt $

PORTNAME=	gcdmaster
PORTREVISION=	7

COMMENT=	GNOME frontend for cdrdao

MASTERDIR=	${.CURDIR}/../cdrdao
DESCR=		${.CURDIR}/pkg-descr
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
