# $FreeBSD: tags/RELEASE_10_3_0/java/openjdk7-jre/Makefile 394508 2015-08-17 14:20:40Z mat $

PKGNAMESUFFIX=	-jre

MAINTAINER=	java@FreeBSD.org
COMMENT=	Java Runtime Environment ${JDK_MAJOR_VERSION}

BUILD_JRE=	yes
MASTERDIR=	${.CURDIR}/../openjdk7

.include "${MASTERDIR}/Makefile"
