# Created by: Zhihao Yuan <lichray@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/chinese/fcitx-table-extra/Makefile 382798 2015-03-31 07:08:00Z delphij $

PORTNAME=	fcitx-table-extra
PORTVERSION=	0.3.7
CATEGORIES=	chinese
MASTER_SITES=	http://download.fcitx-im.org/${PORTNAME}/
DIST_SUBDIR=	fcitx

MAINTAINER=	lichray@gmail.com
COMMENT=	Table-based input methods for Fcitx

LICENSE=	GPLv2

LIB_DEPENDS=	libfcitx-config.so:${PORTSDIR}/chinese/fcitx

USES=		tar:xz cmake gettext
INSTALLS_ICONS=	yes
STRIP=

.include <bsd.port.mk>
