# $FreeBSD: tags/RELEASE_10_3_0/emulators/py-gns3-converter/Makefile 392943 2015-07-26 19:19:36Z pi $

PORTNAME=	gns3-converter
PORTVERSION=	1.2.3
CATEGORIES=	emulators
MASTER_SITES=	CHEESESHOP

MAINTAINER=	pi@FreeBSD.org
COMMENT=	Convert old GNS3 (<=0.8.7) topologies to newer versions

LICENSE=	GPLv3

USES=		python:3
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
