# Created by: Joe Marcus Clarke <marcus@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/print/pdflib-perl/Makefile 348628 2014-03-19 15:53:04Z ale $

PKGNAMESUFFIX=	-perl

MAINTAINER=	ale@FreeBSD.org

MASTERDIR=	${.CURDIR}/../pdflib

OPTIONS_DEFAULT=PERL

.include "${MASTERDIR}/Makefile"
