# Created by: mat
# $FreeBSD: tags/RELEASE_10_3_0/dns/p5-DNS-ZoneParse/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	DNS-ZoneParse
PORTVERSION=	1.10
PORTREVISION=	2
CATEGORIES=	dns textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Parse and manipulate DNS Zone Files

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
