# Created by: Robert Gogolok <gogo@cs.uni-sb.de>
# $FreeBSD: tags/RELEASE_10_3_0/www/rubygem-haml/Makefile 394162 2015-08-13 17:38:20Z sunpoet $

PORTNAME=	haml
PORTVERSION=	4.0.7
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Markup language to describe HTML

LICENSE=	MIT

RUN_DEPENDS=	rubygem-tilt>=0:${PORTSDIR}/devel/rubygem-tilt

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/haml

.include <bsd.port.mk>
