# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-apipie-params/Makefile 405015 2016-01-01 17:05:54Z mmoll $

PORTNAME=	apipie-params
PORTVERSION=	0.0.4
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	DSL for describing data structures with json-schema bindings

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE

NO_ARCH=	yes

USE_RAKE=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
