# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-mwlib.ext/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	mwlib.ext
PORTVERSION=	0.13.2
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Provide Dependencies for mwlib

USES=		python zip
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
