# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/py-translationstring/Makefile 377007 2015-01-14 10:29:56Z bofh $

PORTNAME=	translationstring
PORTVERSION=	1.3
CATEGORIES=	textproc www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Utility library for i18n relied on by various Repoze packages

LICENSE=	BSDMV
LICENSE_NAME=	BSD Modification Variant
LICENSE_FILE=	${WRKSRC}/LICENSE.txt
LICENSE_PERMS=	dist-mirror dist-sell pkg-mirror pkg-sell auto-accept

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
