# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-Horde_Token/Makefile 399990 2015-10-22 16:00:30Z mm $

PORTNAME=	Horde_Token
PORTVERSION=	2.0.7
CATEGORIES=	devel www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde Token API

USES=	horde
USE_HORDE_RUN=	Horde_Exception \
		Horde_Translation \
		Horde_Url \
		Horde_Util
USE_PHP=	hash

.include <bsd.port.mk>
