# Created by: Douglas Thrift <douglas@douglasthrift.net>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-fs/Makefile 401890 2015-11-18 20:01:36Z rm $

PORTNAME=	fs
PORTVERSION=	0.5.4
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	douglas@douglasthrift.net
COMMENT=	Python filesystem abstraction

LICENSE=	ISCL

NO_ARCH=	yes
USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
