# Created by: tiger@whitetigersd.com
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Algorithm-LCS/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Algorithm-LCS
PORTVERSION=	1.04
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:JOESUF
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Fast (XS) implementation of the Longest Common Subsequence Algorithm

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
