# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/xpi-gdata_provider/Makefile 374737 2014-12-15 11:13:39Z ale $

PORTNAME=	gdata_provider
PORTVERSION=	1.0.3
DISTVERSIONSUFFIX=	-tb+sm
CATEGORIES=	www deskutils

MAINTAINER=	ale@FreeBSD.org
COMMENT=	Allows bidirectional access to Google Calendar

XPI_DISTNAME=	provider_for_google_calendar
XPI_NUM=	4631
XPI_ID=		{a62ef8ec-5fdc-40c2-873c-223b8a6925cc}

.include "../xpi-adblock/Makefile.xpi"
.include <bsd.port.mk>
