# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/archivers/php55-zip/Makefile 340722 2014-01-22 17:00:46Z mat $

CATEGORIES=	archivers

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-zip

.include "${MASTERDIR}/Makefile"
