# Created by: Mikle Davidkin <skylord@vt.net.ru>
# $FreeBSD: tags/RELEASE_10_3_0/net-p2p/verlihub-plugins-iplog/Makefile 367657 2014-09-08 17:04:04Z tijl $

PORTNAME=	iplog
PORTVERSION=	1.1
PORTREVISION=	4
CATEGORIES=	net-p2p
MASTER_SITES=	SF/verlihub/VH_IPLog/${DISTVERSION}

MAINTAINER=	me@skylord.ru

PLUGIN_DESC=	IPLog

.include "../verlihub-plugins/Makefile.plugins"
.include <bsd.port.mk>
