# Created by: Andrew Stevenson <andrew@ugh.net.au>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/wait_on/Makefile 348299 2014-03-15 08:55:13Z rene $

PORTNAME=	wait_on
PORTVERSION=	1.1
CATEGORIES=	sysutils
MASTER_SITES=	http://weboutsourcing.cz/freebsd/ports/sysutils/wait_on/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Enable shell scripts to monitor directories for new files

USES=		uidfix
WRKSRC=		${WRKDIR}/wait_on

PLIST_FILES=	bin/wait_on man/man1/wait_on.1.gz

.include <bsd.port.mk>
