# Created by: chinsan
# $FreeBSD: tags/RELEASE_10_3_0/graphics/p5-Image-Pngslimmer/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Image-Pngslimmer
PORTVERSION=	0.30
PORTREVISION=	2
CATEGORIES=	graphics perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Slims (dynamically created) PNGs

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
