# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-cloudfiles/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	cloudfiles
PORTVERSION=	1.5.0.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby version of the Rackspace Cloud Files API

LICENSE=	MIT

RUN_DEPENDS=	rubygem-json>=0:${PORTSDIR}/devel/rubygem-json

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
