# Created by: Aaron Dalton <aaron@daltons.ca>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Tree-Binary/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Tree-Binary
PORTVERSION=	1.06
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Object Oriented Binary Tree for Perl

LICENSE=	ART20

TEST_DEPENDS=	p5-Test-Exception>=0:${PORTSDIR}/devel/p5-Test-Exception

USES=		perl5 tar:tgz
USE_PERL5=	configure

.include <bsd.port.mk>
