# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/mail/pear-Horde_ListHeaders/Makefile 385085 2015-05-01 07:11:54Z mm $

PORTNAME=	Horde_ListHeaders
PORTVERSION=	1.2.2
CATEGORIES=	mail www pear

MAINTAINER=	horde@FreeBSD.org
COMMENT=	Horde List Headers Parsing Library

USES=	horde
USE_HORDE_RUN=	Horde_Mail

.include <bsd.port.mk>
