# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/rubygem-ya2yaml/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	ya2yaml
PORTVERSION=	0.31
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Yet another YAML converter, includes complete UTF8 support

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
