# Created by: bz
# $FreeBSD: tags/RELEASE_10_3_0/security/clamav-milter/Makefile 354254 2014-05-16 18:46:48Z garga $

PKGNAMESUFFIX=	-milter

OPTIONS_SET+=	MILTER

MASTERDIR=	${.CURDIR}/../clamav
PKGNAMESUFFIX=	-milter

CONFLICTS=	clamav-[0-9]*

.include "${MASTERDIR}/Makefile"
