# Created by: Ion-Mihai "IOnut" Tetcu <itetcu@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/mail/squirrelmail-user_special_mailboxes-plugin/Makefile 366415 2014-08-28 15:16:49Z adamw $

PORTNAME=	user_special_mailboxes
PORTVERSION=	0.1
PORTREVISION=	3
CATEGORIES=	mail www
DISTNAME=	${PORTNAME:S/-/_/}.${PORTVERSION}-1.4

MAINTAINER=	itetcu@FreeBSD.org
COMMENT=	Lets define folders to be displayed at the top of the folders list

USE_SM_COMPAT=	yes

SQUIRREL_PLUGIN_NAME=	${PORTNAME:S/-/_/}

.include "${.CURDIR}/../squirrelmail/bsd.squirrelmail.mk"
.include <bsd.port.mk>
