# $FreeBSD: tags/RELEASE_10_3_0/devel/erlang-gen_smtp/Makefile 391483 2015-07-06 22:27:17Z olgeni $

PORTNAME=	gen_smtp
PORTVERSION=	0.9.0
CATEGORIES=	devel
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Extensible SMTP server and client for Erlang

LICENSE=	BSD2CLAUSE

USES=		erlang:rebar
USE_GITHUB=	yes
GH_ACCOUNT=	Vagabond

.include <bsd.port.mk>
