# Created by: Jose Alonso Cardenas Marquez <acm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/emulators/mupen64plus-input-sdl/Makefile 389666 2015-06-15 03:27:50Z acm $

PORTREVISION=	0
PKGNAMESUFFIX=	-input-sdl

COMMENT=	Input plugin for Mupen64plus

MASTERDIR=	${.CURDIR}/../mupen64plus-core

OPTION_DEFINE=	#

.include "${MASTERDIR}/Makefile"
