# Created by: Steve Wills <swills@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-fastri/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	fastri
PORTVERSION=	0.3.1.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Fast RDoc documentation browser for ruby

LICENSE=	GPLv2 RUBY
LICENSE_COMB=	dual

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/fastri-server bin/fri bin/qri bin/ri-emacs

.include <bsd.port.mk>
