# Created by: Jonathan Weiss (<jw@innerewut.de>)
# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-rake/Makefile 399582 2015-10-17 18:09:44Z sunpoet $

PORTNAME=	rake
PORTVERSION=	10.4.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Ruby Make

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/rake

.include <bsd.port.mk>
