# Created by: ijliao
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-resourcepackage/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	resourcepackage
PORTVERSION=	1.0.0
CATEGORIES=	devel python
MASTER_SITES=	SF/${PORTNAME}/${PORTNAME}/${PORTVERSION}%20%28final%29
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	ResourcePackage-${PORTVERSION}

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Automated resource-as-package embedding mechanism

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
