# Created by: Jose Alonso Cardenas Marquez <acm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/emulators/mupen64plus-rsp-hle/Makefile 364872 2014-08-14 22:05:53Z marino $

PKGNAMESUFFIX=	-rsp-hle

COMMENT=	RSP plugin for Mupen64plus

MASTERDIR=	${.CURDIR}/../mupen64plus-core

OPTIONS_DEFINE=	#

.include "${MASTERDIR}/Makefile"
