# Created by: Gabor Kovesdan
# $FreeBSD: tags/RELEASE_10_3_0/security/p5-Crypt-GPG/Makefile 378694 2015-02-08 22:21:47Z ashish $

PORTNAME=	Crypt-GPG
PORTVERSION=	1.64
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ashish@FreeBSD.org
COMMENT=	Perl extension for GnuPG

RUN_DEPENDS=	p5-IPC-Run>=0:${PORTSDIR}/devel/p5-IPC-Run \
		p5-TimeDate>=1.20:${PORTSDIR}/devel/p5-TimeDate

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
