# Created by: Thomas Abthorpe <thomas@goodking.ca>
# $FreeBSD: tags/RELEASE_10_3_0/mail/squirrelmail-pupdate-plugin/Makefile 366415 2014-08-28 15:16:49Z adamw $

PORTNAME=	pupdate
PORTVERSION=	0.7
PORTREVISION=	4
CATEGORIES=	mail www
DISTNAME=	${PORTNAME}.${PORTVERSION}-1.4.2

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Checks for plugin updates by parsing the SM site

LICENSE=	GPLv2

USE_GENERIC_PKGMESSAGE=	yes

.include "${.CURDIR}/../squirrelmail/bsd.squirrelmail.mk"
.include <bsd.port.mk>
