# Created by: chinsan
# $FreeBSD: tags/RELEASE_10_3_0/math/p5-Statistics-Forecast/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	Statistics-Forecast
PORTVERSION=	0.3
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Calculates a future value

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
