# $FreeBSD: tags/RELEASE_10_3_0/devel/py-wrapt/Makefile 404416 2015-12-25 12:14:37Z mva $

PORTNAME=	wrapt
PORTVERSION=	1.10.6
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	mva@FreeBSD.org
COMMENT=	Decorators, wrappers and monkey patching

LICENSE=	BSD2CLAUSE

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
