# Created by: Jyun-Yan You <jyyou@cs.nctu.edu.tw>
# $FreeBSD: tags/RELEASE_10_3_0/net/rubygem-net-ldap/Makefile 403563 2015-12-11 22:09:37Z mmoll $

PORTNAME=	net-ldap
PORTVERSION=	0.12.1
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Pure Ruby LDAP support library with most client features

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/License.rdoc

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
