# $FreeBSD: tags/RELEASE_10_3_0/x11-toolkits/gstreamer1-plugins-pango/Makefile 397984 2015-09-26 14:36:23Z kwm $

PORTREVISION=	0
CATEGORIES=	x11-toolkits

COMMENT=	Gstreamer pango textoverlay plugin

GST_PLUGIN=	pango
DIST=		base

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
