# Created by: Thierry Thomas <thierry@pompo.net>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/nn-aspell/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	${DICT}-aspell
DISTVERSION=	-nn-0.50.1-1
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	textproc

MAINTAINER=	office@FreeBSD.org
COMMENT=	Aspell Norwegian Nynorsk dictionary

DICT=	 	nn

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
