# Created by: fjoe@FreeBSD.org
# $FreeBSD: tags/RELEASE_10_3_0/x11-toolkits/wxgtk28-common/Makefile 347864 2014-03-11 07:13:06Z miwi $

MAINTAINER=	fjoe@FreeBSD.org
COMMENT=	The wxWidgets GUI toolkit (common files)

WXGTK_FLAVOR=	gtk2-common
MASTERDIR=	${.CURDIR}/../wxgtk28

.include "${MASTERDIR}/Makefile"
