# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-B-Size2/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	B-Size2
PORTVERSION=	2.07
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension to measure size of Perl OPs and SVs

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
