# Created by: Dominic Fandrey
# $FreeBSD: tags/RELEASE_10_3_0/games/openarena-server/Makefile 394508 2015-08-17 14:20:40Z mat $

PORTNAME=	openarena
PKGNAMESUFFIX=	-server

MAINTAINER=	kamikaze@bsdforen.de
COMMENT=	OpenArena dedicated server

MASTERDIR=	${.CURDIR}/../${PORTNAME}

IOQ3=		SERVER

.include "${MASTERDIR}/Makefile"
