# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/www/pear-Services_Blogging/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Services_Blogging
PORTVERSION=	0.2.4
CATEGORIES=	www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PHP interface to Blog

BUILD_DEPENDS=	${PEARDIR}/XML/RPC.php:${PORTSDIR}/net/pear-XML_RPC
RUN_DEPENDS=	${PEARDIR}/XML/RPC.php:${PORTSDIR}/net/pear-XML_RPC

USES=	pear

.include <bsd.port.mk>
