# Created by: jfreund
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/cdeploy/Makefile 356796 2014-06-06 14:47:28Z vanilla $

PORTNAME=	cdeploy
PORTVERSION=	0.2.1
CATEGORIES=	sysutils
MASTER_SITES=	SF/root-tools/cdeploy/0.2

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Deploy a set of configuration files to a target file system

USES=		tar:bzip2

PLIST_FILES=	man/man1/cdeploy.1.gz sbin/cdeploy

.include <bsd.port.mk>
