# Created by: Sergey Skvortsov <skv@protey.ru>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Shell-Parser/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Shell-Parser
PORTVERSION=	0.04
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Simple shell script parser

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
