# $FreeBSD: tags/RELEASE_10_3_0/devel/erlang-gproc/Makefile 391484 2015-07-06 22:34:11Z olgeni $

PORTNAME=	gproc
PORTVERSION=	0.5
PORTREVISION=	1
CATEGORIES=	devel
PKGNAMEPREFIX=	erlang-

MAINTAINER=	olgeni@FreeBSD.org
COMMENT=	Process dictionary for Erlang

LICENSE=	EPLICENCE
LICENSE_NAME=	Erlang Public License
LICENSE_FILE=	${WRKSRC}/LICENSE
LICENSE_PERMS=	dist-mirror dist-sell pkg-mirror pkg-sell auto-accept

USES=		erlang:rebar
USE_GITHUB=	yes
GH_ACCOUNT=	uwiger

ERL_DOCS=	doc/*

.include <bsd.port.mk>
