# Created by: Sergey V. Dyatko <sergey.dyatko@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-interface/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	interface
PORTVERSION=	0.03
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:SWALTERS
PKGNAMEPREFIX=	p5-

MAINTAINER=	sergey.dyatko@gmail.com
COMMENT=	Simple compile time interface checking for OO Perl

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
