# Created by: aturetta@commit.it
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Module-Refresh/Makefile 399249 2015-10-14 11:04:10Z culot $

PORTNAME=	Module-Refresh
PORTVERSION=	0.17
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	culot@FreeBSD.org
COMMENT=	Refresh %INC files when updated on disk

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-Path-Class>=0:${PORTSDIR}/devel/p5-Path-Class

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
