# Created by: Anton Berezin <tobez@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/converters/p5-Encode-DoubleEncodedUTF8/Makefile 386312 2015-05-14 10:15:04Z mat $

PORTNAME=	Encode-DoubleEncodedUTF8
PORTVERSION=	0.05
PORTREVISION=	1
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Fix double encoded UTF-8 bytes to the correct ones

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
