# $FreeBSD: tags/RELEASE_10_3_0/x11/xmh/Makefile 399840 2015-10-20 13:46:06Z kwm $

PORTNAME=	xmh
PORTVERSION=	1.0.3
CATEGORIES=	x11 mail

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Send and read mail with an X interface to MH

RUN_DEPENDS+=	repl:${PORTSDIR}/mail/nmh

XORG_CAT=	app
USE_XORG=	xaw xmu xt xbitmaps

.include <bsd.port.mk>
