# Created by: Cheng-Lung Sung <clsung@dragon2.net>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-OOTools/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	OOTools
PORTVERSION=	2.30
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:SKNPP
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-${PORTVERSION:S/0$//}

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl module collection to easily create constructors methods

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
