# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-Pager/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Pager
PORTVERSION=	2.4.9
CATEGORIES=	devel www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PEAR data paging class

USES=	pear

.include <bsd.port.mk>
