# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Module-Versions/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Module-Versions
PORTVERSION=	0.02
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kuriyama@FreeBSD.org
COMMENT=	Perl extension to handle versions of loaded modules

USES=		perl5 zip
USE_PERL5=	configure

.include <bsd.port.mk>
