# Created by: Udo Schweigert <udo.schweigert@siemens.com>
# $FreeBSD: tags/RELEASE_10_3_0/mail/mutt-lite/Makefile 342475 2014-02-03 22:39:05Z thierry $

# Just to get a mutt-devel-lite pkg on pkg cluster
MASTERDIR=	${.CURDIR}/../mutt

COMMENT=	The Mongrel of Mail User Agents (development version, lite package)

CONFLICTS=	ja-mutt-[0-9]* ja-mutt-devel-[0-9]* mutt-[0-9]* mutt-devel-[0-9]* mutt-lite-1.4* zh-mutt-devel-[0-9]*

MUTT_LITE=	yes

.include "${MASTERDIR}/Makefile"
