# Created by: Boris Samorodov <bsam@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/german/eric4/Makefile 367888 2014-09-10 20:50:31Z gerald $

PORTREVISION=	1
CATEGORIES=	german devel python

I18N_LANG=	de

.include "${.CURDIR}/../../devel/eric4/Makefile.inc"
