# Created by: ofsen@enderunix.org
# $FreeBSD: tags/RELEASE_10_3_0/mail/isoqlog/Makefile 350261 2014-04-05 20:03:34Z danilo $

PORTNAME=	isoqlog
PORTVERSION=	2.2.1
PORTREVISION=	1
CATEGORIES=	mail
MASTER_SITES=	http://www.enderunix.org/isoqlog/ \
		http://www.trunix.org/projeler/isoqlog/ \
		http://www.acikkod.org/softwares/

MAINTAINER=	dbaio@bsd.com.br
COMMENT=	Qmail, postfix, sendmail, exim MTA log analysis program

LICENSE=	BSD3CLAUSE

GNU_CONFIGURE=	yes
USES=	gmake

OPTIONS_DEFINE=	DOCS

SUB_FILES=	pkg-message

.include <bsd.port.mk>
