# Created by: Greg Larkin <glarkin@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-VersionControl_SVN/Makefile 377871 2015-01-25 09:15:46Z bofh $

PORTNAME=	VersionControl_SVN
PORTVERSION=	0.5.2
CATEGORIES=	devel pear

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Wrapper interface for the Subversion command-line client

LICENSE=	BSD2CLAUSE

BUILD_DEPENDS=	pear-XML_Parser>=1.3.4:${PORTSDIR}/devel/pear-XML_Parser
RUN_DEPENDS=	pear-XML_Parser>=1.3.4:${PORTSDIR}/devel/pear-XML_Parser

USE_PHP=	yes
USES=	pear

.include <bsd.port.mk>
