# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pecl-uopz/Makefile 385363 2015-05-04 02:15:17Z vanilla $

PORTNAME=	uopz
PORTVERSION=	2.0.7
CATEGORIES=	devel
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-
DIST_SUBDIR=	PECL

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	User Operations for PHP Zend engine

LICENSE=	PHP301

USE_PHP=	yes
USE_PHPEXT=	yes
USES=		tar:tgz
IGNORE_WITH_PHP=	53

.include <bsd.port.mk>
