# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: tags/RELEASE_10_3_0/databases/p5-AsciiDB-TagFile/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	AsciiDB-TagFile
PORTVERSION=	1.06
PORTREVISION=	1
CATEGORIES=	databases perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl tie class for a simple ASCII database

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
