# Created by: Seamus Venasse <svenasse@polaris.ca>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/p5-Text-Repository/Makefile 386075 2015-05-11 12:04:18Z mat $

PORTNAME=	Text-Repository
PORTVERSION=	1.04
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Simple way to manage text without mixing it with Perl

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
