# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/rubygem-tinymce-rails/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	tinymce-rails
PORTVERSION=	4.1.0
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	zi@FreeBSD.org
COMMENT=	Seamlessly integrates TinyMCE into the Rails asset pipeline

LICENSE=	MIT

RUN_DEPENDS=	rubygem-railties>=3.1.1:${PORTSDIR}/www/rubygem-railties

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
