# Created by: Lars Thegler <lth@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-IO-Capture/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	IO-Capture
PORTVERSION=	0.05
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	lth@FreeBSD.org
COMMENT=	Abstract Base Class to build modules to capture output

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
