# Created by: Alexey Dokuchaev <danfe@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/x11/nvidia-driver-304/Makefile 397773 2015-09-24 22:09:54Z jkim $

DISTVERSION=	304.128
# Explicitly set PORTREVISION as it can be overridden by the master port
PORTREVISION=	0

MASTERDIR=	${.CURDIR}/../nvidia-driver
PKGNAMESUFFIX=	-304

.include "${MASTERDIR}/Makefile"
