# Created by: hrs
# $FreeBSD: tags/RELEASE_10_3_0/print/papersize-default-letter/Makefile 347878 2014-03-11 13:05:46Z hrs $

MASTERDIR=	${.CURDIR}/../../print/papersize-default-a4
DEFAULTPAPERSIZE=	letter

.include "${MASTERDIR}/Makefile"
