# Created by: Alex Kapranoff <kapr@crosswinds.net>
# $FreeBSD: tags/RELEASE_10_3_0/russian/p5-Lingua-RU-Charset/Makefile 386075 2015-05-11 12:04:18Z mat $

PORTNAME=	Lingua-RU-Charset
PORTVERSION=	0.02
PORTREVISION=	1
CATEGORIES=	russian perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl extension for detecting and converting Russian character sets

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
