# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/R-cran-XML/Makefile 391231 2015-07-03 11:26:45Z tota $

PORTNAME=	XML
DISTVERSION=	3.98-1.3
CATEGORIES=	textproc
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Tools for parsing and generating XML

LICENSE=	BSD2CLAUSE

USES=	cran:auto-plist
USE_GNOME=	libxml2

.include <bsd.port.mk>
