# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/net/pear-Net_URL_Mapper/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Net_URL_Mapper
PORTVERSION=	0.9.1
CATEGORIES=	net www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Simple and flexible way to build nice URLs for web applications

USES=	pear

.include <bsd.port.mk>
