# Created by: TERAMOTO Masahiro <markun@onohara.to>
# $FreeBSD: tags/RELEASE_10_3_0/www/rubygem-simple-rss/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	simple-rss
PORTVERSION=	1.3.1
CATEGORIES=	www textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	markun@onohara.to
COMMENT=	Simple, flexible, extensible, and liberal RSS and Atom reader for Ruby

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
