# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/rubygem-redcarpet/Makefile 398349 2015-10-01 15:59:47Z sunpoet $

PORTNAME=	redcarpet
PORTVERSION=	3.3.3
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Fast, safe and extensible Markdown to (X)HTML parser

LICENSE=	MIT

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/redcarpet

.include <bsd.port.mk>
