# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Test-TempDir-Tiny/Makefile 380610 2015-03-06 16:33:39Z sunpoet $

PORTNAME=	Test-TempDir-Tiny
PORTVERSION=	0.004
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Temporary directories that stick around when tests fail

LICENSE=	APACHE20

USE_PERL5=	configure
USES=		perl5

.include <bsd.port.mk>
