# Created by: Miguel Mendez <flynn@energyhq.es.eu.org>
# $FreeBSD: tags/RELEASE_10_3_0/mail/addresses/Makefile 397315 2015-09-19 10:33:34Z theraven $

PORTNAME=	addresses
PORTVERSION=	0.4.8
PORTREVISION=	3
CATEGORIES=	mail gnustep
MASTER_SITES=	SAVANNAH/gap
DISTNAME=	Addresses-${PORTVERSION}

MAINTAINER=	theraven@FreeBSD.org
COMMENT=	Versatile addressbook for GNUstep

LICENSE=	LGPL21

USES=		gnustep
USE_GNUSTEP=	back build
USE_LDCONFIG=	${GNUSTEP_LOCAL_LIBRARIES}

.include <bsd.port.mk>
