# Created by: Valery Komarov <komarov@valerka.net>
# $FreeBSD: tags/RELEASE_10_3_0/devel/php5-msgpack/Makefile 386811 2015-05-19 21:25:59Z mat $

PORTNAME=	msgpack
PORTVERSION=	2012.05.05
CATEGORIES=	devel
PKGNAMEPREFIX=	php5-

MAINTAINER=	komarov@valerka.net
COMMENT=	PHP extension for interfacing with MessagePack

USE_GITHUB=	yes
GH_TAGNAME=	980a652
WRKSRC_SUBDIR=	php

USE_PHP=	session
USE_PHP_BUILD=	yes
USE_PHPIZE=	yes
USE_PHPEXT=	yes
PHP_MODNAME=	msgpack

.include <bsd.port.mk>
