# Created by: Douglas Thrift <douglas@douglasthrift.net>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/rubygem-yard-chef/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	yard-chef
PORTVERSION=	1.0.0
CATEGORIES=	textproc devel rubygems
MASTER_SITES=	RG

MAINTAINER=	douglas@douglasthrift.net
COMMENT=	YARD plugin for Chef

LICENSE=	MIT

RUN_DEPENDS=	rubygem-yard>=0.8:${PORTSDIR}/textproc/rubygem-yard

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
