# Created by: Mario Sergio Fujikawa Ferreira <lioux@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/x11-themes/kde-icons-lime-rade8/Makefile 377648 2015-01-22 06:07:26Z vanilla $

PORTNAME=	lime-rade8
PORTVERSION=	3.1
MASTER_SITES=	SF/graphitekde/graphitekde/Lime-RAD.E8-${PORTVERSION}/
DISTNAME=	Lime-RAD.E8-${PORTVERSION}

COMMENT=	KDE Mac OS X like iconset, most from rad-e8 design

USES=		tar:bzip2
WRKSRC=		${WRKDIR}/Lime-RAD.E8-${PORTVERSION}

.include "${.CURDIR}/../kde-icons-noia/Makefile.icons"
