# $FreeBSD: tags/RELEASE_10_3_0/mail/rubygem-email_reply_parser/Makefile 402308 2015-11-23 18:31:26Z sunpoet $

PORTNAME=	email_reply_parser
PORTVERSION=	0.5.8
CATEGORIES=	mail rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@michael-fausten.de
COMMENT=	Library to parse plain text email content

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
