# Created by: Thierry Thomas (<thierry@pompo.net>)
# $FreeBSD: tags/RELEASE_10_3_0/mail/pear-Mail_Mime/Makefile 396890 2015-09-14 11:37:20Z bofh $

PORTNAME=	Mail_Mime
PORTVERSION=	1.10.0
PORTEPOCH=	2
CATEGORIES=	mail www pear

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	PEAR classes to create and decode MIME messages

LICENSE=	BSD3CLAUSE

USES=		pear
NO_ARCH=	yes

.include <bsd.port.mk>
