# Created by: Ederson de Moura <ederbs@ederbs.org>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/upsdaemon/Makefile 359781 2014-06-29 16:06:33Z vanilla $

PORTNAME=	upsdaemon
PORTVERSION=	1.0
CATEGORIES=	sysutils
MASTER_SITES=	http://www.ederbs.org/pub/ \
		ftp://ederbs.org/pub/

MAINTAINER=	freebsduser@paradisegreen.co.uk
COMMENT=	Simple APC UPS Daemon

LICENSE=	BSD2CLAUSE

USE_RC_SUBR=	upsdaemon

.include <bsd.port.mk>
