# Created by: Mikhail T. <michael@fun-box.ru>
# $FreeBSD: tags/RELEASE_10_3_0/www/rubygem-davclient/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	davclient
PORTVERSION=	0.0.8
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Command line WebDAV client and Ruby library

LICENSE=	GPLv2

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/dav

.include <bsd.port.mk>
