# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-paint/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	paint
PORTVERSION=	1.0.0
CATEGORIES=	devel
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Terminal painter

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
