# Created by: Thomas Bartelmess <thomas@bartelmess.io>
# $FreeBSD: tags/RELEASE_10_3_0/devel/go-hashicorp-logutils/Makefile 385521 2015-05-06 15:16:53Z mat $

PORTNAME=	go-hachicorp-logutils
PORTVERSION=	0.1
CATEGORIES=	devel

MAINTAINER=	thomas@bartelmess.io
COMMENT=	Utilities for slightly better logging in Go (Golang)

LICENSE=	BSD2CLAUSE

USE_GITHUB=	yes
GH_ACCOUNT=	hashicorp
GH_PROJECT=	logutils
GH_TAGNAME=	8e0820f

GO_PKGNAME=	github.com/hashicorp/logutils

.include <bsd.port.pre.mk>
.include "${PORTSDIR}/lang/go/files/bsd.go.mk"
.include <bsd.port.post.mk>
