# $FreeBSD: tags/RELEASE_10_3_0/databases/py-psycogreen/Makefile 385589 2015-05-07 01:21:18Z wen $

PORTNAME=	psycogreen
PORTVERSION=	1.0
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	loic.blot@unix-experience.fr
COMMENT=	Python library to enable psycopg2 to work with coroutine libraries

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
