# $FreeBSD: tags/RELEASE_10_3_0/devel/py-stdnum/Makefile 403184 2015-12-07 06:14:19Z pi $

PORTNAME=	stdnum
PORTVERSION=	1.2
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	python-${PORTNAME}-${PORTVERSION}

MAINTAINER=	pi@FreeBSD.org
COMMENT=	Python module to handle standardized numbers and codes

LICENSE=	LGPL21

# Python3 ready
USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
