# Created by: Nick Withers (nick@nickwithers.com)
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/downtime/Makefile 362126 2014-07-17 08:57:51Z olgeni $

PORTNAME=	downtime
PORTVERSION=	0.4.0
PORTREVISION=	2
CATEGORIES=	sysutils
MASTER_SITES=	http://www.nickwithers.com/downtime/

MAINTAINER=	nick@nickwithers.com
COMMENT=	GTK-based shutdown manager using shutdown(8)

USES=		desktop-file-utils pkgconfig shared-mime-info
USE_GNOME=	gtk20

.include <bsd.port.mk>
