# Created by: Wes Peters <wes@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/obliterate/Makefile 367570 2014-09-07 16:32:49Z antoine $

PORTNAME=	obliterate
PORTVERSION=	0.5
CATEGORIES=	sysutils
MASTER_SITES=	LOCAL/wes

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Securely delete file[s]

USES=		uidfix

PLIST_FILES=	bin/obliterate man/man8/${PORTNAME}.8.gz

.include <bsd.port.mk>
