# Created by: Anton Berezin <tobez@tobez.org>
# $FreeBSD: tags/RELEASE_10_3_0/math/p5-Statistics-Distributions/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Statistics-Distributions
PORTVERSION=	1.02
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tobez@FreeBSD.org
COMMENT=	Perl module that calculates critical values of common statistical distributions

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
