# $FreeBSD: tags/RELEASE_10_3_0/devel/rubygem-rake-compiler/Makefile 391169 2015-07-02 16:01:06Z pgollucci $

PORTNAME=	rake-compiler
PORTVERSION=	0.9.5
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Build and package Ruby extensions (C, Java) using Rake

LICENSE=	MIT

NO_ARCH=	yes

USE_RUBY=	yes
USE_RAKE=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/rake-compiler

.include <bsd.port.mk>
