# Created by: mat
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-Data-Dump/Makefile 390902 2015-06-29 13:50:38Z sunpoet $

PORTNAME=	Data-Dump
PORTVERSION=	1.23
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Pretty printing of data structures

LICENSE=	ART10 GPLv1
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
