# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/php56-pspell/Makefile 384787 2015-04-26 12:33:09Z ale $

CATEGORIES=	textproc

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-pspell

.include "${MASTERDIR}/Makefile"
