# Created by: Adam Weinberger <adamw@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/p5-File-Tail-Multi/Makefile 378972 2015-02-14 17:26:55Z adamw $

PORTNAME=	File-Tail-Multi
PORTVERSION=	0.1
PORTREVISION=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:ATRIPPS
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Stateful tail of multiple files

LICENSE=	GPLv1 ART10
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
