# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/pear-Net_Gearman/Makefile 390421 2015-06-23 16:04:55Z amdmi3 $

PORTNAME=	Net_Gearman
PORTVERSION=	0.2.3
PORTREVISION=	3
CATEGORIES=	devel pear

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	Gearman client libraray for PHP

LICENSE=	BSD2CLAUSE

BUILD_DEPENDS=	${LOCALBASE}/share/pear/PEAR.php:${PORTSDIR}/devel/pear
RUN_DEPENDS=	${LOCALBASE}/share/pear/PEAR.php:${PORTSDIR}/devel/pear

USE_PHP=	json mbstring sockets
USES=		pear

.include <bsd.port.mk>
