# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/x11/libXv/Makefile 384234 2015-04-18 15:34:36Z kwm $

PORTNAME=	libXv
PORTVERSION=	1.0.10
PORTREVISION=	3
PORTEPOCH=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Video Extension library

LICENSE=	MIT

XORG_CAT=	lib
USE_XORG=	x11 xext xextproto videoproto:both xproto:both
USES+=	cpe
CPE_PRODUCT=	libxv
CPE_VENDOR=	x

.include <bsd.port.mk>
