# Created by: Antonio Carlos Venancio Junior (<antonio@inf.ufsc.br>)
# $FreeBSD: tags/RELEASE_10_3_0/databases/pear-DBA/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	DBA
PORTVERSION=	1.1.1
CATEGORIES=	databases www pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Berkely-style database abstraction class

USES=		pear

.include <bsd.port.mk>
