# $FreeBSD: tags/RELEASE_10_3_0/x11/beforelight/Makefile 364347 2014-08-08 08:42:44Z olgeni $

PORTNAME=	beforelight
PORTVERSION=	1.0.5
PORTREVISION=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Sample screen saver for X

XORG_CAT=	app
USE_XORG=	x11 xscrnsaver xt xaw7 xt

.include <bsd.port.mk>
