# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/textproc/R-cran-stringr/Makefile 385406 2015-05-04 14:02:12Z tota $

PORTNAME=	stringr
PORTVERSION=	1.0.0
CATEGORIES=	textproc
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Make it easier to work with strings

LICENSE=	GPLv2

RUN_DEPENDS=	R-cran-stringi>=0.4.1:${PORTSDIR}/textproc/R-cran-stringi \
		R-cran-magrittr>0:${PORTSDIR}/devel/R-cran-magrittr

USES=	cran:auto-plist

.include <bsd.port.mk>
