# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/devel/py-qserve/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	qserve
PORTVERSION=	0.2.8
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Job queue server

USES=		python zip
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
