# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/gstreamer-plugins-cdio/Makefile 352119 2014-04-25 12:46:45Z bapt $

CATEGORIES=	sysutils
PORTREVISION=	1

COMMENT=	Gstreamer compact disc input and control library

GST_PLUGIN=	cdio

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
