# Created by: ache
# $FreeBSD: tags/RELEASE_10_3_0/security/p5-Digest-MD5/Makefile 376924 2015-01-13 12:45:04Z tobez $

PORTNAME=	Digest-MD5
PORTVERSION=	2.54
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	perl@FreeBSD.org
COMMENT=	Perl5 interface to the MD5 algorithm

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
