# $FreeBSD: tags/RELEASE_10_3_0/portuguese/php_doc-br/Makefile 353996 2014-05-13 21:13:31Z edwin $

CATEGORIES=	portuguese lang
PKGNAMEPREFIX=

PHP_LANG=	br
MASTERDIR=	${.CURDIR}/../../lang/php_doc

.include "${MASTERDIR}/Makefile"
