# Created by: joris
# $FreeBSD: tags/RELEASE_10_3_0/net-mgmt/p5-SNMP-Trapinfo/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	SNMP-Trapinfo
PORTVERSION=	1.02
PORTREVISION=	1
CATEGORIES=	net-mgmt perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	joris.dedieu@gmail.com
COMMENT=	Process an SNMP trap with perl

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
