# Created by: Ryan Steinmetz <zi@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/databases/rubygem-mysql/Makefile 387665 2015-05-27 17:54:37Z sunpoet $

PORTNAME=	mysql
PORTVERSION=	2.9.1
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	MySQL API module for Ruby

LICENSE=	GPLv2 RUBY
LICENSE_COMB=	dual

USE_MYSQL=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
