# Created by: Zhen REN <bg1tpt@gmail.com>
# $FreeBSD: tags/RELEASE_10_3_0/net/pear-Net_MAC/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Net_MAC
PORTVERSION=	0.1.5
PORTREVISION=	1
CATEGORIES=	net pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PEAR class that validates and formats MAC addresses

USES=	pear

.include <bsd.port.mk>
