# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/security/pear-Net_Portscan/Makefile 402439 2015-11-26 12:04:00Z miwi $

PORTNAME=	Net_Portscan
PORTVERSION=	1.0.3
CATEGORIES=	security pear

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Provides an API for scanning ports

USES=	pear

.include <bsd.port.mk>
