# $FreeBSD: tags/RELEASE_10_3_0/devel/py-zope.cachedescriptors/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	zope.cachedescriptors
PORTVERSION=	3.5.1
PORTREVISION=	1
CATEGORIES=	devel python zope
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DIST_SUBDIR=	zope

MAINTAINER=	zope@FreeBSD.org
COMMENT=	Method and property caching decorators

LICENSE=	ZPL21

USES=		python zip
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
