# Created by: tundra
# $FreeBSD: tags/RELEASE_10_3_0/sysutils/abck/Makefile 393196 2015-07-29 22:09:53Z antoine $

PORTNAME=	abck
PORTVERSION=	2.2
PORTREVISION=	1
CATEGORIES=	sysutils
MASTER_SITES=	http://www.tundraware.com/Software/abck/

MAINTAINER=	tundra@tundraware.com
COMMENT=	Manage intrusion attempts recorded in the system log

USES=		python shebangfix
SHEBANG_FILES=	abck
python_OLD_CMD=	/usr/local/bin/python

.include <bsd.port.mk>
