# Created by: Li-Wen Hsu <lwhsu@FreeBSD.org>
# $FreeBSD: tags/RELEASE_10_3_0/www/py-dotcloud.cli/Makefile 376109 2015-01-03 08:41:20Z mva $

PORTNAME=	dotcloud.cli
PORTVERSION=	0.4.8
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	lwhsu@FreeBSD.org
COMMENT=	dotCloud command-line interface client

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
